# syntax=dhi.io/build:2-helm3

name: Cilium Helm chart 1.18.x
image: dhi.io/cilium-chart
variant: helm
tags:
  - 1.18.14
platforms:
  - linux/amd64
dates:
  release: "2025-07-29"
vars:
  BUSYBOX_REFERENCE: dhi/busybox:1.38.0-alpine3.24@sha256:59ec745ef4b2e553eafea215cf9550f545daf68edf151bdb88a2abbe392da132
  CHART_COMMIT_SHA: 0a5b4195ff0bfc4d5d6e707a24f57e1047166ab4
  CHART_HELM_NAME: cilium-chart
  CILIUM_CERTGEN_REFERENCE: dhi/cilium-certgen:0.4.11-debian13@sha256:33a6e36f7d0cdd98f7a47b0ab04ae195a6dec054f134c698b5159ff331b662ff
  CILIUM_CLUSTERMESH_APISERVER_REFERENCE: dhi/cilium-clustermesh-apiserver:1.18.14-debian13@sha256:86502c4aeb01ed451f87ade203e67afc356f5dae5555b457eae34a2421fe9ff4
  CILIUM_ENVOY_REFERENCE: dhi/cilium-envoy:1.18.14-debian13-compat@sha256:18ddcce6aea362b63b39007285d5cf1c045768bae1e88d9e0f5d6d0ef444f6b6
  CILIUM_OPERATOR_REFERENCE: dhi/cilium-operator:1.18.14-debian13@sha256:b0ac9a3c6a8bc74984c033e618f8fb84980bb7e6979171014968ca467d6f01c6
  CILIUM_REFERENCE: dhi/cilium:1.18.14-debian13@sha256:52adbb3d6f6ea9c64bfaa87a5698f655c2ac5188b534fe36485358754e127c1d
  CILIUM_STARTUP_SCRIPT_REFERENCE: dhi/cilium-startup-script:0.20261002-debian13@sha256:f43eaff07a8c08d5faafbaf9ddc77adf74c98ec44038bf76a78d357f9e3a7d5e
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_VERSION: 4.1.4-2
  HUBBLE_RELAY_REFERENCE: dhi/hubble-relay:1.18.14-debian13@sha256:c262c460efcf409e432a9faca95e3644285f133689f33fd1c03598ec73fcdb25
  HUBBLE_UI_BACKEND_REFERENCE: dhi/hubble-ui-backend:0.13.6-debian13@sha256:25e613be665b6ad7d8e713ffb397449c2acf931d68ea1d1b9c5ed25ae1a9af5d
  HUBBLE_UI_REFERENCE: dhi/hubble-ui:0.13.6-debian13@sha256:ee060a92b95e554ee78d889674427bf9b2dad804fe9ae4c13bfffb7850d45571
  SEMVER_MAJOR_MINOR_VERSION: "1.18"
  SEMVER_MAJOR_VERSION: "1"
  SEMVER_VERSION: 1.18.14
  SPIRE_AGENT_REFERENCE: dhi/spire-agent:1.15.3-debian13@sha256:c2d4250bd0132c81fb034911340a5c5c4ca9485092ae4497e40cf50e6f0906e2
  SPIRE_SERVER_REFERENCE: dhi/spire-server:1.15.3-debian13@sha256:590aac4969dea05ad09c97ae139ec90f6332abbd156ccced4d7dc1b9dd2b7994
  VERSION: 1.18.14
  ZTUNNEL_REFERENCE: dhi/ztunnel:1.31.1-debian13@sha256:ad3b8cd0bc169965591576f4574caecd05a51063add8678a817c990ee18a9a4f
contents:
  repositories:
    - deb [signed-by=/usr/share/keyrings/dhi-deb-main.gpg] http://dhi.io/deb/debian/main trixie main
  keyring:
    - https://dhi.io/keyring/dhi-deb-gpg.D46852F6925E9F71.key
  builds:
    - name: cilium-chart
      work-dir: ${source.dir}/helm-charts/install/kubernetes/cilium
      contents:
        packages:
          - bash
          - coreutils
          - yq-go
          - helm=4.1.4-2
          - patch
        files:
          - url: git+https://github.com/cilium/cilium.git#v1.18.14
            checksum: 0a5b4195ff0bfc4d5d6e707a24f57e1047166ab4
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          with:
            chart:
              appRef: cilium
              description: Docker Hardened Images Helm chart for Cilium
              images:
                - name: cilium
                  ref: dhi/cilium:1.18.14-debian13@sha256:52adbb3d6f6ea9c64bfaa87a5698f655c2ac5188b534fe36485358754e127c1d
                - name: cilium-operator
                  ref: dhi/cilium-operator:1.18.14-debian13@sha256:b0ac9a3c6a8bc74984c033e618f8fb84980bb7e6979171014968ca467d6f01c6
                - name: hubble-relay
                  ref: dhi/hubble-relay:1.18.14-debian13@sha256:c262c460efcf409e432a9faca95e3644285f133689f33fd1c03598ec73fcdb25
                - name: hubble-ui
                  ref: dhi/hubble-ui:0.13.6-debian13@sha256:ee060a92b95e554ee78d889674427bf9b2dad804fe9ae4c13bfffb7850d45571
                - name: hubble-ui-backend
                  ref: dhi/hubble-ui-backend:0.13.6-debian13@sha256:25e613be665b6ad7d8e713ffb397449c2acf931d68ea1d1b9c5ed25ae1a9af5d
                - name: cilium-envoy
                  ref: dhi/cilium-envoy:1.18.14-debian13-compat@sha256:18ddcce6aea362b63b39007285d5cf1c045768bae1e88d9e0f5d6d0ef444f6b6
                - name: cilium-certgen
                  ref: dhi/cilium-certgen:0.4.11-debian13@sha256:33a6e36f7d0cdd98f7a47b0ab04ae195a6dec054f134c698b5159ff331b662ff
                - name: cilium-clustermesh-apiserver
                  ref: dhi/cilium-clustermesh-apiserver:1.18.14-debian13@sha256:86502c4aeb01ed451f87ade203e67afc356f5dae5555b457eae34a2421fe9ff4
                - name: cilium-startup-script
                  ref: dhi/cilium-startup-script:0.20261002-debian13@sha256:f43eaff07a8c08d5faafbaf9ddc77adf74c98ec44038bf76a78d357f9e3a7d5e
                - name: ztunnel
                  ref: dhi/ztunnel:1.31.1-debian13@sha256:ad3b8cd0bc169965591576f4574caecd05a51063add8678a817c990ee18a9a4f
                - name: spire-agent
                  ref: dhi/spire-agent:1.15.3-debian13@sha256:c2d4250bd0132c81fb034911340a5c5c4ca9485092ae4497e40cf50e6f0906e2
                - name: spire-server
                  ref: dhi/spire-server:1.15.3-debian13@sha256:590aac4969dea05ad09c97ae139ec90f6332abbd156ccced4d7dc1b9dd2b7994
                - name: busybox
                  ref: dhi/busybox:1.38.0-alpine3.24@sha256:59ec745ef4b2e553eafea215cf9550f545daf68edf151bdb88a2abbe392da132
              name: cilium-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/cilium/cilium
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: patch spire agent daemonset
          uses: patch@v1
          work-dir: ${source.dir}/helm-charts/install/kubernetes/cilium
          with:
            options: -p1
            patch: ${source.dir}/spire-agent-daemonset-chown.patch
        - name: remove ztunnel values (pre-1.19)
          uses: yq/patch@v1
          work-dir: ${source.dir}/helm-charts/install/kubernetes/cilium
          with:
            file: values.yaml
            patches:
              - del(.encryption.ztunnel)
        - name: remove dnsproxy image override (pre-1.19)
          uses: yq/patch@v1
          work-dir: ${source.dir}/helm-charts/install/kubernetes/cilium
          with:
            file: values.yaml
            patches:
              - del(.dnsproxy.image)
        - name: lint
          uses: helm/cmd@v1
          with:
            chart: .
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: .
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/cilium/config
        - type: file
          path: ${source.dir}/spire-agent-daemonset-chown.patch
          uid: 0
          gid: 0
          source: chart/cilium/patches/spire-agent-daemonset-chown.patch
