# syntax=dhi.io/build:2-helm3

name: Cilium Helm chart 1.20.x
image: dhi.io/cilium-chart
variant: helm
tags:
  - 1.20.2
platforms:
  - linux/amd64
dates:
  release: "2026-07-29"
vars:
  BUSYBOX_REFERENCE: dhi/busybox:1.38.0-alpine3.24@sha256:59ec745ef4b2e553eafea215cf9550f545daf68edf151bdb88a2abbe392da132
  CHART_COMMIT_SHA: e0dc92bd6dac33d7ba3b5eace82a0448bbb13aac
  CHART_HELM_NAME: cilium-chart
  CILIUM_CERTGEN_REFERENCE: dhi/cilium-certgen:0.4.11-debian13@sha256:33ff45f0eba1b51264255434c063d4c898aaa0ed9b4c2ceac830fac41a2479ce
  CILIUM_CLUSTERMESH_APISERVER_REFERENCE: dhi/cilium-clustermesh-apiserver:1.20.2-debian13@sha256:fa640f0ceb145e1b8379d814b5c555b9872afb529459e88ac135d429a63936f6
  CILIUM_DNSPROXY_REFERENCE: dhi/cilium-dnsproxy:1.20.2-debian13@sha256:f4839c1c11ad4510fa1f51eddc13bf89ea232517862c8a1d2580b2384149e87a
  CILIUM_ENVOY_REFERENCE: dhi/cilium-envoy:1.20.2-debian13-compat@sha256:7afa7f3eb64f6ab17492297065fd746ac4b1325de551994d4e435738a0cde518
  CILIUM_OPERATOR_REFERENCE: dhi/cilium-operator:1.20.2-debian13@sha256:2a46c971bed53f4025dd22e4292789a0933b6b026db4bb1f599317e6926c1d9b
  CILIUM_REFERENCE: dhi/cilium:1.20.2-debian13@sha256:d217a994986e3d4ef18dc8601c8ab56479f59300f9160e8e31c09959f7e987f9
  CILIUM_STARTUP_SCRIPT_REFERENCE: dhi/cilium-startup-script:0.20260701-debian13@sha256:092f36664d410f85819c834b8939df9c91c20ee43b5590065607db6377edf375
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_VERSION: 4.1.4-2
  HUBBLE_RELAY_REFERENCE: dhi/hubble-relay:1.20.2-debian13@sha256:d841ab520b288499c12fb3985f6365f19dbffde3d25cbca3d773e203c7ed2e7d
  HUBBLE_UI_BACKEND_REFERENCE: dhi/hubble-ui-backend:0.13.6-debian13@sha256:66230a52d0e7961286ae25f8e6b4fdce0acaacb2ceaa1156f27feab5517454aa
  HUBBLE_UI_REFERENCE: dhi/hubble-ui:0.13.6-debian13@sha256:573d3379d6b92bced0b5f635e35cc7e2ca03b8477ed13ea499de61324636a402
  SEMVER_MAJOR_MINOR_VERSION: "1.20"
  SEMVER_MAJOR_VERSION: "1"
  SEMVER_VERSION: 1.20.2
  SPIRE_AGENT_REFERENCE: dhi/spire-agent:1.15.3-debian13@sha256:e7e491bc0a7d1bc2216a28ca8511088792bfb9d623d7cef5275c2b8e181e6411
  SPIRE_SERVER_REFERENCE: dhi/spire-server:1.15.3-debian13@sha256:86d980074d5cda5800f509209b2c7b4cdbc3328c96a961e4cac09fc32a557583
  VERSION: 1.20.2
  ZTUNNEL_REFERENCE: dhi/ztunnel:1.31.1-debian13@sha256:ae837f9c1e859b02b28afb692a40737c89680d21b5f441f1720b765cdc43cb6d
contents:
  repositories:
    - deb [signed-by=/usr/share/keyrings/dhi-deb-main.gpg] http://dhi.io/deb/debian/main trixie main
  keyring:
    - https://dhi.io/keyring/dhi-deb-gpg.D46852F6925E9F71.key
  builds:
    - name: cilium-chart
      work-dir: ${source.dir}/helm-charts/install/kubernetes/cilium
      contents:
        packages:
          - bash
          - coreutils
          - yq-go
          - helm=4.1.4-2
          - patch
        files:
          - url: git+https://github.com/cilium/cilium.git#v1.20.2
            checksum: e0dc92bd6dac33d7ba3b5eace82a0448bbb13aac
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          with:
            chart:
              appRef: cilium
              description: Docker Hardened Images Helm chart for Cilium
              images:
                - name: cilium
                  ref: dhi/cilium:1.20.2-debian13@sha256:d217a994986e3d4ef18dc8601c8ab56479f59300f9160e8e31c09959f7e987f9
                - name: cilium-operator
                  ref: dhi/cilium-operator:1.20.2-debian13@sha256:2a46c971bed53f4025dd22e4292789a0933b6b026db4bb1f599317e6926c1d9b
                - name: hubble-relay
                  ref: dhi/hubble-relay:1.20.2-debian13@sha256:d841ab520b288499c12fb3985f6365f19dbffde3d25cbca3d773e203c7ed2e7d
                - name: hubble-ui
                  ref: dhi/hubble-ui:0.13.6-debian13@sha256:573d3379d6b92bced0b5f635e35cc7e2ca03b8477ed13ea499de61324636a402
                - name: hubble-ui-backend
                  ref: dhi/hubble-ui-backend:0.13.6-debian13@sha256:66230a52d0e7961286ae25f8e6b4fdce0acaacb2ceaa1156f27feab5517454aa
                - name: cilium-envoy
                  ref: dhi/cilium-envoy:1.20.2-debian13-compat@sha256:7afa7f3eb64f6ab17492297065fd746ac4b1325de551994d4e435738a0cde518
                - name: cilium-certgen
                  ref: dhi/cilium-certgen:0.4.11-debian13@sha256:33ff45f0eba1b51264255434c063d4c898aaa0ed9b4c2ceac830fac41a2479ce
                - name: cilium-clustermesh-apiserver
                  ref: dhi/cilium-clustermesh-apiserver:1.20.2-debian13@sha256:fa640f0ceb145e1b8379d814b5c555b9872afb529459e88ac135d429a63936f6
                - name: cilium-startup-script
                  ref: dhi/cilium-startup-script:0.20260701-debian13@sha256:092f36664d410f85819c834b8939df9c91c20ee43b5590065607db6377edf375
                - name: cilium-dnsproxy
                  ref: dhi/cilium-dnsproxy:1.20.2-debian13@sha256:f4839c1c11ad4510fa1f51eddc13bf89ea232517862c8a1d2580b2384149e87a
                - name: ztunnel
                  ref: dhi/ztunnel:1.31.1-debian13@sha256:ae837f9c1e859b02b28afb692a40737c89680d21b5f441f1720b765cdc43cb6d
                - name: spire-agent
                  ref: dhi/spire-agent:1.15.3-debian13@sha256:e7e491bc0a7d1bc2216a28ca8511088792bfb9d623d7cef5275c2b8e181e6411
                - name: spire-server
                  ref: dhi/spire-server:1.15.3-debian13@sha256:86d980074d5cda5800f509209b2c7b4cdbc3328c96a961e4cac09fc32a557583
                - name: busybox
                  ref: dhi/busybox:1.38.0-alpine3.24@sha256:59ec745ef4b2e553eafea215cf9550f545daf68edf151bdb88a2abbe392da132
              name: cilium-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/cilium/cilium
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: patch spire agent daemonset
          uses: patch@v1
          work-dir: ${source.dir}/helm-charts/install/kubernetes/cilium
          with:
            options: -p1
            patch: ${source.dir}/spire-agent-daemonset-chown.patch
        - name: lint
          uses: helm/cmd@v1
          with:
            chart: .
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: .
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/cilium/config
        - type: file
          path: ${source.dir}/spire-agent-daemonset-chown.patch
          uid: 0
          gid: 0
          source: chart/cilium/patches/spire-agent-daemonset-chown.patch
