# syntax=dhi.io/build:2-helm3

name: Prometheus Helm chart 28.x
image: dhi.io/prometheus-chart
variant: helm
tags:
  - 28.16.0
platforms:
  - linux/amd64
vars:
  ALERTMANAGER_CHART_REFERENCE: dhi/alertmanager-chart:1.36.0@sha256:f62198e72b0713371d96f3398b63bcf6d3af9d53c06b04ed9ba32cabf85b94a0
  CHART_COMMIT_SHA: 97de013b787ae602d8c24e12f6a82c9bb716927e
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.20.2-debian13-dev@sha256:0e82c726efb7039ffa0875ffb88632189d0082a77f0ee94efa3a048992db3c71
  KUBE_STATE_METRICS_CHART_REFERENCE: dhi/kube-state-metrics-chart:7.3.0@sha256:432cc6404093ce1860cde36940d8a861e53db1f02778eaf395cd894f765acb2e
  NODE_EXPORTER_CHART_REFERENCE: dhi/node-exporter-chart:4.55.0@sha256:02c03bf85f640a6e23e87b19d563630f1b0ff39dccaaa74d4e5094de82c800cb
  PROMETHEUS_CONFIG_RELOADER_REFERENCE: dhi/prometheus-config-reloader:0.91.0-debian13@sha256:c93345a02add512cd5c54d0ffadf907578ac03099781e50b9ebaee4a54183807
  PROMETHEUS_REFERENCE: dhi/prometheus:3.11.3-debian13@sha256:b882ddf87061148bda421c5a0f16187ea9cc12500177514573341a4721e886ab
  PUSHGATEWAY_CHART_REFERENCE: dhi/pushgateway-chart:3.6.0@sha256:757949437e616a5101d9d1e9c0f8bc09a42a6d105face58732115e62afdd2f58
  SEMVER_MAJOR_MINOR_VERSION: "28.16"
  SEMVER_MAJOR_VERSION: "28"
  SEMVER_VERSION: 28.16.0
  VERSION: 28.16.0
contents:
  builds:
    - name: prometheus-chart
      uses: dhi.io/helm:3.20.2-debian13-dev@sha256:0e82c726efb7039ffa0875ffb88632189d0082a77f0ee94efa3a048992db3c71
      contents:
        files:
          - url: git+https://github.com/prometheus-community/helm-charts.git#prometheus-28.16.0
            checksum: 97de013b787ae602d8c24e12f6a82c9bb716927e
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/prometheus
          with:
            chart:
              appRef: prometheus
              dependencies:
                - alias: alertmanager
                  condition: alertmanager.enabled
                  name: alertmanager
                  ref: dhi/alertmanager-chart:1.36.0@sha256:f62198e72b0713371d96f3398b63bcf6d3af9d53c06b04ed9ba32cabf85b94a0
                - alias: kube-state-metrics
                  condition: kube-state-metrics.enabled
                  name: kube-state-metrics
                  ref: dhi/kube-state-metrics-chart:7.3.0@sha256:432cc6404093ce1860cde36940d8a861e53db1f02778eaf395cd894f765acb2e
                - alias: prometheus-node-exporter
                  condition: prometheus-node-exporter.enabled
                  name: prometheus-node-exporter
                  ref: dhi/node-exporter-chart:4.55.0@sha256:02c03bf85f640a6e23e87b19d563630f1b0ff39dccaaa74d4e5094de82c800cb
                - alias: prometheus-pushgateway
                  condition: prometheus-pushgateway.enabled
                  name: prometheus-pushgateway
                  ref: dhi/pushgateway-chart:3.6.0@sha256:757949437e616a5101d9d1e9c0f8bc09a42a6d105face58732115e62afdd2f58
              description: Docker Hardened Images Helm chart for Prometheus
              images:
                - name: prometheus
                  ref: dhi/prometheus:3.11.3-debian13@sha256:b882ddf87061148bda421c5a0f16187ea9cc12500177514573341a4721e886ab
                - name: prometheus-config-reloader
                  ref: dhi/prometheus-config-reloader:0.91.0-debian13@sha256:c93345a02add512cd5c54d0ffadf907578ac03099781e50b9ebaee4a54183807
              name: prometheus-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/prometheus-community/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/prometheus
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: helm login
          uses: helm/login@v1
          with:
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          privileged: true
          with:
            chart: prometheus
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: prometheus
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: prometheus
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/prometheus/config
