# syntax=dhi.io/build:2-helm3

name: Prometheus Helm chart 28.x
image: dhi.io/prometheus-chart
variant: helm
tags:
  - 28.16.0
platforms:
  - linux/amd64
vars:
  ALERTMANAGER_CHART_REFERENCE: dhi/alertmanager-chart:1.39.1@sha256:601e20f3638443e4daf84bc978e6445f8b17496feffe27ac657effc34ea34fc0
  CHART_COMMIT_SHA: 97de013b787ae602d8c24e12f6a82c9bb716927e
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.21.1-debian13-dev@sha256:210cf8f74216e3b27dc70a0cec01194863ce8b319fe089d97e6e10d8a020b666
  KUBE_STATE_METRICS_CHART_REFERENCE: dhi/kube-state-metrics-chart:7.5.1@sha256:1ed013b1e1f16583f030e13562eb014d8d30ef9388ba562c849a33714302ca2e
  NODE_EXPORTER_CHART_REFERENCE: dhi/node-exporter-chart:4.55.0@sha256:3e0ed61169ebda634c8ff20df5984c981ba35cf6fd6ef3b5cde9ec210a0ce6fe
  PROMETHEUS_CONFIG_RELOADER_REFERENCE: dhi/prometheus-config-reloader:0.91.0-debian13@sha256:4fb15111521a2ffaee9069ea9d90a2f3eee3e70887629a3f7b31feccb002b890
  PROMETHEUS_REFERENCE: dhi/prometheus:3.12.0-debian13@sha256:2fc4fd884ee9bcbe3190d8721de6e36216eb72e01e8bf60a61990acaae5f8710
  PUSHGATEWAY_CHART_REFERENCE: dhi/pushgateway-chart:3.6.1@sha256:955df1719857cb4d80580acc9fd6928d883bb1b16b4d6e8d2cdb83a8538567dc
  SEMVER_MAJOR_MINOR_VERSION: "28.16"
  SEMVER_MAJOR_VERSION: "28"
  SEMVER_VERSION: 28.16.0
  VERSION: 28.16.0
contents:
  builds:
    - name: prometheus-chart
      uses: dhi.io/helm:3.21.1-debian13-dev@sha256:210cf8f74216e3b27dc70a0cec01194863ce8b319fe089d97e6e10d8a020b666
      contents:
        files:
          - url: git+https://github.com/prometheus-community/helm-charts.git#prometheus-28.16.0
            checksum: 97de013b787ae602d8c24e12f6a82c9bb716927e
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/prometheus
          with:
            chart:
              appRef: prometheus
              dependencies:
                - alias: alertmanager
                  condition: alertmanager.enabled
                  name: alertmanager
                  ref: dhi/alertmanager-chart:1.39.1@sha256:601e20f3638443e4daf84bc978e6445f8b17496feffe27ac657effc34ea34fc0
                - alias: kube-state-metrics
                  condition: kube-state-metrics.enabled
                  name: kube-state-metrics
                  ref: dhi/kube-state-metrics-chart:7.5.1@sha256:1ed013b1e1f16583f030e13562eb014d8d30ef9388ba562c849a33714302ca2e
                - alias: prometheus-node-exporter
                  condition: prometheus-node-exporter.enabled
                  name: prometheus-node-exporter
                  ref: dhi/node-exporter-chart:4.55.0@sha256:3e0ed61169ebda634c8ff20df5984c981ba35cf6fd6ef3b5cde9ec210a0ce6fe
                - alias: prometheus-pushgateway
                  condition: prometheus-pushgateway.enabled
                  name: prometheus-pushgateway
                  ref: dhi/pushgateway-chart:3.6.1@sha256:955df1719857cb4d80580acc9fd6928d883bb1b16b4d6e8d2cdb83a8538567dc
              description: Docker Hardened Images Helm chart for Prometheus
              images:
                - name: prometheus
                  ref: dhi/prometheus:3.12.0-debian13@sha256:2fc4fd884ee9bcbe3190d8721de6e36216eb72e01e8bf60a61990acaae5f8710
                - name: prometheus-config-reloader
                  ref: dhi/prometheus-config-reloader:0.91.0-debian13@sha256:4fb15111521a2ffaee9069ea9d90a2f3eee3e70887629a3f7b31feccb002b890
              name: prometheus-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/prometheus-community/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/prometheus
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: helm login
          uses: helm/login@v1
          with:
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          privileged: true
          with:
            chart: prometheus
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: prometheus
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: prometheus
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/prometheus/config
