# syntax=dhi.io/build:2-helm3

name: Prometheus Helm chart 28.x
image: dhi.io/prometheus-chart
variant: helm
tags:
  - 28.13.0
platforms:
  - linux/amd64
vars:
  ALERTMANAGER_CHART_REFERENCE: dhi/alertmanager-chart:1.33.1@sha256:79abd38044cbcd7e24d837b7ac4818296f5cb543b6c0c86fc7271ba88a637937
  CHART_COMMIT_SHA: f738b5d4d5a325223701e4d5ba30d95c46e10bb9
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.20.1-debian13-dev@sha256:a2c1b2e1c9d947d8feabde6c5ae3d2f9b1f0883a4d6cd01d49ccb0e509465920
  KUBE_STATE_METRICS_CHART_REFERENCE: dhi/kube-state-metrics-chart:7.2.1@sha256:451d7845fb3eb7ece70f0c1bca87d67526485b864955575de4f8a75ec55cd88b
  NODE_EXPORTER_CHART_REFERENCE: dhi/node-exporter-chart:4.52.1@sha256:8f7305db96494836c71d9f191793e5cc94d03ed5b632e7211d8a0508889449af
  PROMETHEUS_CONFIG_RELOADER_REFERENCE: dhi/prometheus-config-reloader:0.89.0-debian13@sha256:8a257ae1451e837c1e923791e2fe56a24b25f64a02513b7da1bb9739a6ade345
  PROMETHEUS_REFERENCE: dhi/prometheus:3.10.0-debian13@sha256:6dd203f18fa37b68b2e0ef84213bfadde0984993f5835a5373cd4bc47ef84275
  PUSHGATEWAY_CHART_REFERENCE: dhi/pushgateway-chart:3.6.0@sha256:9da8e12c50c746c6e8f90fb72151dded7cb60a6d541048a2d439edbb7cac6689
  SEMVER_MAJOR_MINOR_VERSION: "28.13"
  SEMVER_MAJOR_VERSION: "28"
  SEMVER_VERSION: 28.13.0
  VERSION: 28.13.0
contents:
  builds:
    - name: prometheus-chart
      uses: dhi.io/helm:3.20.1-debian13-dev@sha256:a2c1b2e1c9d947d8feabde6c5ae3d2f9b1f0883a4d6cd01d49ccb0e509465920
      contents:
        files:
          - url: git+https://github.com/prometheus-community/helm-charts.git#prometheus-28.13.0
            checksum: f738b5d4d5a325223701e4d5ba30d95c46e10bb9
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/prometheus
          with:
            chart:
              appRef: prometheus
              dependencies:
                - alias: alertmanager
                  condition: alertmanager.enabled
                  name: alertmanager
                  ref: dhi/alertmanager-chart:1.33.1@sha256:79abd38044cbcd7e24d837b7ac4818296f5cb543b6c0c86fc7271ba88a637937
                - alias: kube-state-metrics
                  condition: kube-state-metrics.enabled
                  name: kube-state-metrics
                  ref: dhi/kube-state-metrics-chart:7.2.1@sha256:451d7845fb3eb7ece70f0c1bca87d67526485b864955575de4f8a75ec55cd88b
                - alias: prometheus-node-exporter
                  condition: prometheus-node-exporter.enabled
                  name: prometheus-node-exporter
                  ref: dhi/node-exporter-chart:4.52.1@sha256:8f7305db96494836c71d9f191793e5cc94d03ed5b632e7211d8a0508889449af
                - alias: prometheus-pushgateway
                  condition: prometheus-pushgateway.enabled
                  name: prometheus-pushgateway
                  ref: dhi/pushgateway-chart:3.6.0@sha256:9da8e12c50c746c6e8f90fb72151dded7cb60a6d541048a2d439edbb7cac6689
              description: Docker Hardened Images Helm chart for Prometheus
              images:
                - name: prometheus
                  ref: dhi/prometheus:3.10.0-debian13@sha256:6dd203f18fa37b68b2e0ef84213bfadde0984993f5835a5373cd4bc47ef84275
                - name: prometheus-config-reloader
                  ref: dhi/prometheus-config-reloader:0.89.0-debian13@sha256:8a257ae1451e837c1e923791e2fe56a24b25f64a02513b7da1bb9739a6ade345
              name: prometheus-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/prometheus-community/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/prometheus
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: helm login
          uses: helm/login@v1
          with:
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          privileged: true
          with:
            chart: prometheus
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: prometheus
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: prometheus
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/prometheus/config
