# syntax=dhi.io/build:2-helm3

name: VictoriaMetrics Alerts Helm chart 0.x
image: dhi.io/victoriametrics-alert-chart
variant: helm
tags:
  - 0.39.0
platforms:
  - linux/amd64
vars:
  ALERTMANAGER_REFERENCE: dhi/alertmanager:0.32.1-debian13@sha256:45bf99ff5a5c81a4cfa5b4511c71662c8044c12ed73dbb3297ec052f52a7c2b3
  CHART_COMMIT_SHA: 287e9d4c6122a9d14866905764bb682dd1ad8b19
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.20.2-debian13-dev@sha256:bf8a03f405f8a317925ae232b32a1d29943a57b019dabfb0b7d0e624f558baf2
  SEMVER_MAJOR_MINOR_VERSION: "0.39"
  SEMVER_MAJOR_VERSION: "0"
  SEMVER_VERSION: 0.39.0
  VERSION: 0.39.0
  VMALERT_REFERENCE: dhi/victoriametrics-vmalert:1.142.0-debian13@sha256:fc6ef41e8f58e217eb70fa64e7900c4affb6612dfb6fbfede9575ba3bbd73377
contents:
  builds:
    - name: victoriametrics-alert-chart
      uses: dhi.io/helm:3.20.2-debian13-dev@sha256:bf8a03f405f8a317925ae232b32a1d29943a57b019dabfb0b7d0e624f558baf2
      contents:
        files:
          - url: git+https://github.com/VictoriaMetrics/helm-charts.git#victoria-metrics-alert-0.39.0
            checksum: 287e9d4c6122a9d14866905764bb682dd1ad8b19
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/victoria-metrics-alert
          with:
            chart:
              appRef: victoriametrics-vmalert
              description: Docker Hardened Images Helm chart for VictoriaMetrics Alert
              images:
                - name: victoriametrics-vmalert
                  ref: dhi/victoriametrics-vmalert:1.142.0-debian13@sha256:fc6ef41e8f58e217eb70fa64e7900c4affb6612dfb6fbfede9575ba3bbd73377
                - name: alertmanager
                  ref: dhi/alertmanager:0.32.1-debian13@sha256:45bf99ff5a5c81a4cfa5b4511c71662c8044c12ed73dbb3297ec052f52a7c2b3
              name: victoriametrics-alert-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/VictoriaMetrics/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/victoria-metrics-alert
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          privileged: true
          with:
            chart: ${source.dir}/helm-charts/charts/victoria-metrics-alert
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: victoria-metrics-alert
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: ${source.dir}/helm-charts/charts/victoria-metrics-alert
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/victoriametrics-alert/config
