# syntax=dhi.io/build:2-helm3

name: VictoriaMetrics Alerts Helm chart 0.x
image: dhi.io/victoriametrics-alert-chart
variant: helm
tags:
  - 0.39.0
platforms:
  - linux/amd64
vars:
  ALERTMANAGER_REFERENCE: dhi/alertmanager:0.32.1-debian13@sha256:1d035893d2530a46e3001424b61b3c9dde262f137f4870d95c4cc4155f4064a8
  CHART_COMMIT_SHA: 287e9d4c6122a9d14866905764bb682dd1ad8b19
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.20.2-debian13-dev@sha256:f9dd4a356298b0769dc4c2f718b9f564b631ddf37c19e061d61af9081bc7da13
  SEMVER_MAJOR_MINOR_VERSION: "0.39"
  SEMVER_MAJOR_VERSION: "0"
  SEMVER_VERSION: 0.39.0
  VERSION: 0.39.0
  VMALERT_REFERENCE: dhi/victoriametrics-vmalert:1.142.0-debian13@sha256:ce4025ab00044a6d4afa6001c804b8ec075266c8a4683854acf8242aacd9364f
contents:
  builds:
    - name: victoriametrics-alert-chart
      uses: dhi.io/helm:3.20.2-debian13-dev@sha256:f9dd4a356298b0769dc4c2f718b9f564b631ddf37c19e061d61af9081bc7da13
      contents:
        files:
          - url: git+https://github.com/VictoriaMetrics/helm-charts.git#victoria-metrics-alert-0.39.0
            checksum: 287e9d4c6122a9d14866905764bb682dd1ad8b19
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/victoria-metrics-alert
          with:
            chart:
              appRef: victoriametrics-vmalert
              description: Docker Hardened Images Helm chart for VictoriaMetrics Alert
              images:
                - name: victoriametrics-vmalert
                  ref: dhi/victoriametrics-vmalert:1.142.0-debian13@sha256:ce4025ab00044a6d4afa6001c804b8ec075266c8a4683854acf8242aacd9364f
                - name: alertmanager
                  ref: dhi/alertmanager:0.32.1-debian13@sha256:1d035893d2530a46e3001424b61b3c9dde262f137f4870d95c4cc4155f4064a8
              name: victoriametrics-alert-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/VictoriaMetrics/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/victoria-metrics-alert
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          privileged: true
          with:
            chart: ${source.dir}/helm-charts/charts/victoria-metrics-alert
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: victoria-metrics-alert
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: ${source.dir}/helm-charts/charts/victoria-metrics-alert
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/victoriametrics-alert/config
