# syntax=dhi.io/build:2-helm3

name: Envoy AI Gateway CRDs Helm chart 0.x
image: dhi.io/envoy-ai-gateway-crds-chart
variant: helm
tags:
  - 0.7.0
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: f2d59a6a4f26680e53f03531ece28eadd70f5320
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.21.0-debian13-dev@sha256:462393863790e8d4b174f63f0da50798da095a059d4fab7692ae4fb7a58e99d3
  SEMVER_MAJOR_MINOR_VERSION: "0.7"
  SEMVER_MAJOR_VERSION: "0"
  SEMVER_VERSION: 0.7.0
  VERSION: 0.7.0
contents:
  builds:
    - name: envoy-ai-gateway-crds-chart
      uses: dhi/helm:3.21.0-debian13-dev@sha256:462393863790e8d4b174f63f0da50798da095a059d4fab7692ae4fb7a58e99d3
      contents:
        files:
          - url: git+https://github.com/envoyproxy/ai-gateway.git#v0.7.0
            checksum: f2d59a6a4f26680e53f03531ece28eadd70f5320
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/manifests/charts/ai-gateway-crds-helm
          with:
            chart:
              appRef: envoy-ai-gateway-crds
              description: Docker Hardened Images Helm chart for Envoy AI Gateway CRDs
              images: []
              name: envoy-ai-gateway-crds-chart
              sourceUrl: https://github.com/envoyproxy/ai-gateway
            cmd: prepare
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/manifests/charts
          with:
            chart: ai-gateway-crds-helm
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/manifests/charts
          with:
            chart: ai-gateway-crds-helm
