# syntax=dhi.io/build:2-alpine3.24

image: dhi.io/pkg-prometheus-statsd-exporter
variant: runtime
tags:
  - 0.30.0-alpine3.24
  - 0.30.0-r1-alpine3.24
platforms:
  - linux/amd64
  - linux/arm64
vars:
  COMMIT_SHA: 4a7feb4d0ec9f1061b9e2f548810dd6efc6a294a
  GOLANG_MAJOR_MINOR_VERSION: "1.26"
  GOLANG_VERSION: 1.26.7-r0
  PACKAGE_NAME: prometheus-statsd-exporter
  REL: "1"
  SEMVER_MAJOR_MINOR_VERSION: "0.30"
  SEMVER_MAJOR_VERSION: "0"
  SEMVER_VERSION: 0.30.0
  VERSION: 0.30.0
contents:
  repositories:
    - https://dhi.io/apk/alpine/v3.24/main
    - https://dhi.io/apk/alpine/v3.23/main
    - https://dl-cdn.alpinelinux.org/alpine/v3.24/main
    - https://dl-cdn.alpinelinux.org/alpine/v3.24/community
  keyring:
    - https://dhi.io/keyring/dhi-apk@docker-0F81AD7700D99184.rsa.pub
  packages:
    - alpine-baselayout-data
  builds:
    - name: prometheus-statsd-exporter
      work-dir: /go/src/github.com/prometheus/statsd_exporter
      contents:
        packages:
          - busybox
          - bash
          - ca-certificates-bundle
          - golang-1.26=1.26.7-r0
          - golang-1.26-oci-config=1.26.7-r0
        files:
          - url: git+https://github.com/prometheus/statsd_exporter.git#v0.30.0
            checksum: 4a7feb4d0ec9f1061b9e2f548810dd6efc6a294a
            path: /go/src/github.com/prometheus/statsd_exporter
            spdx:
              name: statsd_exporter
              version: 0.30.0
              packages:
                - name: statsd_exporter
                  purl: pkg:golang/github.com/prometheus/statsd_exporter@0.30.0
                  license: Apache-2.0
            uid: 0
            gid: 0
      pipeline:
        - name: update go dependencies
          uses: go/bump@v1
          with:
            deps:
              - golang.org/x/crypto@v0.55.0
              - golang.org/x/net@v0.57.0
              - golang.org/x/text@v0.41.0
            download: true
            tidy: true
        - uses: go/hermetic@v1
        - name: build
          uses: go/build@v1
          with:
            fips: false
            ldflags:
              - -X github.com/prometheus/common/version.Version=0.30.0
              - -X github.com/prometheus/common/version.Revision=4a7feb4d0ec9f1061b9e2f548810dd6efc6a294a
              - -X github.com/prometheus/common/version.GoVersion=$(go env GOVERSION)
              - -X github.com/prometheus/common/version.GoOS=$(go env GOOS)
              - -X github.com/prometheus/common/version.GoArch=$(go env GOARCH)
              - -X github.com/prometheus/common/version.Branch=main
              - -X github.com/prometheus/common/version.BuildUser=ci@docker-build
              - -X github.com/prometheus/common/version.BuildDate=$(date -u -d @${SOURCE_DATE_EPOCH} +'%F-%T')
            output: ${target.dir}/usr/bin/statsd_exporter
            packages: .
        - name: build dev
          uses: go/build@v1
          with:
            fips: false
            ldflags:
              - -X github.com/prometheus/common/version.Version=0.30.0
              - -X github.com/prometheus/common/version.Revision=4a7feb4d0ec9f1061b9e2f548810dd6efc6a294a
              - -X github.com/prometheus/common/version.GoVersion=$(go env GOVERSION)
              - -X github.com/prometheus/common/version.GoOS=$(go env GOOS)
              - -X github.com/prometheus/common/version.GoArch=$(go env GOARCH)
              - -X github.com/prometheus/common/version.Branch=main
              - -X github.com/prometheus/common/version.BuildUser=ci@docker-build
              - -X github.com/prometheus/common/version.BuildDate=$(date -u -d @${SOURCE_DATE_EPOCH} +'%F-%T')
            output: ${target.dir}/usr/bin/statsd_exporter-dev
            packages: .
            strip: false
        - uses: dhi/build-pkg:0
          with:
            description: Prometheus StatsD Exporter
            files:
              - usr/bin/statsd_exporter
            license: Apache-2.0
            name: prometheus-statsd-exporter
            rel: 1
            subpackages:
              - files:
                  - path: usr/bin/statsd_exporter
                    source: usr/bin/statsd_exporter-dev
                name: prometheus-statsd-exporter-dev
            url: https://github.com/prometheus/statsd_exporter
            version: 0.30.0
os-release:
  name: Docker Hardened Images (Alpine)
  id: alpine
  version-id: "3.24"
  pretty-name: Docker Hardened Images/Alpine Linux v3.24
  home-url: https://docker.com/products/hardened-images/
  bug-report-url: https://docker.com/support/
