# syntax=dhi.io/build:2-helm3

name: Tailscale Operator Helm chart 1.x
image: dhi.io/tailscale-operator-chart
variant: helm
tags:
  - 1.100.0
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: c811bb19bf3b0c89061ac7b7a073f6cd23b504d0
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.21.2-debian13-dev@sha256:e30b522f3f39307b7710b304f082f76d7b8fc0d0140bfc44bdf2892c5411519f
  SEMVER_MAJOR_MINOR_VERSION: "1.100"
  SEMVER_MAJOR_VERSION: "1"
  SEMVER_VERSION: 1.100.0
  TAILSCALE_OPERATOR_REFERENCE: dhi/tailscale-operator:1.100.0-debian13@sha256:cf6401b741f53a42788d37b8dcd6435bae01d85a1a2c1bb6f50e5bce7323eb3e
  TAILSCALE_REFERENCE: dhi/tailscale:1.100.0-debian13@sha256:001ae0b00759b4243c4c36aab766868c5aae27c21697f57c6d292f5e7aafe164
  VERSION: 1.100.0
contents:
  builds:
    - name: tailscale-operator-chart
      uses: dhi.io/helm:3.21.2-debian13-dev@sha256:e30b522f3f39307b7710b304f082f76d7b8fc0d0140bfc44bdf2892c5411519f
      work-dir: ${source.dir}/tailscale/cmd/k8s-operator/deploy/chart
      contents:
        files:
          - url: git+https://github.com/tailscale/tailscale.git#v1.100.0
            checksum: c811bb19bf3b0c89061ac7b7a073f6cd23b504d0
            path: ${source.dir}/tailscale
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          with:
            chart:
              appRef: tailscale-operator
              description: Docker Hardened Images Helm chart for Tailscale Operator
              images:
                - name: tailscale-operator
                  ref: dhi/tailscale-operator:1.100.0-debian13@sha256:cf6401b741f53a42788d37b8dcd6435bae01d85a1a2c1bb6f50e5bce7323eb3e
                - name: tailscale
                  ref: dhi/tailscale:1.100.0-debian13@sha256:001ae0b00759b4243c4c36aab766868c5aae27c21697f57c6d292f5e7aafe164
              name: tailscale-operator-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/tailscale/tailscale
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          with:
            chart: .
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: .
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/tailscale-operator/config
