metadata:
  display-name: Agentgateway CRDs Helm chart
  short-description: Installs the Gateway API and Agentgateway Custom Resource Definitions required by the Agentgateway controller.
  featured: false
  home-url: https://github.com/agentgateway/agentgateway/tree/main/controller/install/helm/agentgateway-crds
  categories:
    - networking
