# syntax=dhi.io/build:2-helm3

name: Velero Helm chart 11.x
image: dhi.io/velero-chart
variant: helm
tags:
  - 11.3.2
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: b07a5226f3e4b25b8d44ea2266dac680bf8b5c2a
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.20.2-debian13-dev@sha256:f9dd4a356298b0769dc4c2f718b9f564b631ddf37c19e061d61af9081bc7da13
  KUBECTL_REFERENCE: dhi/kubectl:1.35.4-debian13-compat@sha256:a6fba268172cc48d640ee539341f44bc289c4efb5db140c7b00b30ac57923f5c
  SEMVER_MAJOR_MINOR_VERSION: "11.3"
  SEMVER_MAJOR_VERSION: "11"
  SEMVER_VERSION: 11.3.2
  VELERO_REFERENCE: dhi/velero:1.18.0-debian13@sha256:66cf0ecae82a80fb5f3c0dd5ac018bdfdbd97db9063a889a459a56c09f70dce1
  VERSION: 11.3.2
contents:
  builds:
    - name: velero
      uses: dhi.io/helm:3.20.2-debian13-dev@sha256:f9dd4a356298b0769dc4c2f718b9f564b631ddf37c19e061d61af9081bc7da13
      contents:
        files:
          - url: git+https://github.com/vmware-tanzu/helm-charts.git#velero-11.3.2
            checksum: b07a5226f3e4b25b8d44ea2266dac680bf8b5c2a
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/velero
          with:
            chart:
              appRef: velero
              description: Docker Hardened Images Helm chart for Velero
              images:
                - name: velero
                  ref: dhi/velero:1.18.0-debian13@sha256:66cf0ecae82a80fb5f3c0dd5ac018bdfdbd97db9063a889a459a56c09f70dce1
                - name: kubectl
                  ref: dhi/kubectl:1.35.4-debian13-compat@sha256:a6fba268172cc48d640ee539341f44bc289c4efb5db140c7b00b30ac57923f5c
              name: velero-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/vmware-tanzu/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/velero
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            process-templates: true
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          with:
            chart: ${source.dir}/helm-charts/charts/velero
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: velero
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: ${source.dir}/helm-charts/charts/velero
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/velero/config
