# syntax=dhi.io/build:2-helm3

name: Velero Helm chart 12.x
image: dhi.io/velero-chart
variant: helm
tags:
  - 12.0.3
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: 39efb90d063ff715a458fa3940954e00d5cd3a24
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.21.2-debian13-dev@sha256:fc6fdd4be364fc8d33537d170a24eccb64b6c087c17f81ce2f31029301909d91
  KUBECTL_REFERENCE: dhi/kubectl:1.35.6-debian13-compat@sha256:8bab4d118d059615deae9d75dda860a3069353a3f4b4fab0b1b4c0b917729c57
  SEMVER_MAJOR_MINOR_VERSION: "12.0"
  SEMVER_MAJOR_VERSION: "12"
  SEMVER_VERSION: 12.0.3
  VELERO_REFERENCE: dhi/velero:1.18.1-debian13@sha256:be1c49e3229b1692a3d8aaa765ac97f3a26418cc9073c5a4f5b83ff4a07cab43
  VERSION: 12.0.3
contents:
  builds:
    - name: velero
      uses: dhi.io/helm:3.21.2-debian13-dev@sha256:fc6fdd4be364fc8d33537d170a24eccb64b6c087c17f81ce2f31029301909d91
      contents:
        files:
          - url: git+https://github.com/vmware-tanzu/helm-charts.git#velero-12.0.3
            checksum: 39efb90d063ff715a458fa3940954e00d5cd3a24
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/velero
          with:
            chart:
              appRef: velero
              description: Docker Hardened Images Helm chart for Velero
              images:
                - name: velero
                  ref: dhi/velero:1.18.1-debian13@sha256:be1c49e3229b1692a3d8aaa765ac97f3a26418cc9073c5a4f5b83ff4a07cab43
                - name: kubectl
                  ref: dhi/kubectl:1.35.6-debian13-compat@sha256:8bab4d118d059615deae9d75dda860a3069353a3f4b4fab0b1b4c0b917729c57
              name: velero-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/vmware-tanzu/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/velero
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            process-templates: true
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          with:
            chart: ${source.dir}/helm-charts/charts/velero
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: velero
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: ${source.dir}/helm-charts/charts/velero
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/velero/config
