# syntax=dhi.io/build:2-helm3

name: Strimzi Kafka Operator Helm chart 1.x
image: dhi.io/strimzi-kafka-operator-chart
variant: helm
tags:
  - 1.0.1
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: 833dbbd4fc745678f11ad96ed66571704cd73cd0
  CHART_HELM_NAME: strimzi-kafka-operator-chart
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_VERSION: 4.1.4-2
  KAFKA_VERSION: 4.2.0
  SEMVER_MAJOR_MINOR_VERSION: "1.0"
  SEMVER_MAJOR_VERSION: "1"
  SEMVER_VERSION: 1.0.1
  STRIMZI_KAFKA_REFERENCE: dhi/strimzi-kafka:1.1.0-debian13-kafka-4.2.1@sha256:d0eb952ec4ecfbfe2d83e779dba6d35afe4636e011489b3f9c6be580ebf08df0
  STRIMZI_OPERATOR_REFERENCE: dhi/strimzi-operator:1.0.1-debian13@sha256:7efdb60b7b8b61fdfeac883bbe9a13c17fd15fcd6c9d3e7966e951b74fdabb36
  VERSION: 1.0.1
  VERSION_MATCH: 1.0.1
  url: git+https://github.com/strimzi/strimzi-kafka-operator.git#1.0.1
contents:
  repositories:
    - deb [signed-by=/usr/share/keyrings/dhi-deb-main.gpg] http://dhi.io/deb/debian/main trixie main
  keyring:
    - https://dhi.io/keyring/dhi-deb-gpg.D46852F6925E9F71.key
  builds:
    - name: strimzi-kafka-operator
      work-dir: ${source.dir}/helm-charts/helm-charts/helm3/strimzi-kafka-operator
      contents:
        packages:
          - bash
          - coreutils
          - yq-go
          - helm=4.1.4-2
        files:
          - url: git+https://github.com/strimzi/strimzi-kafka-operator.git#1.0.1
            checksum: 833dbbd4fc745678f11ad96ed66571704cd73cd0
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/helm-charts/helm3/strimzi-kafka-operator
          with:
            chart:
              appRef: strimzi-operator
              description: Docker Hardened Images Helm chart for Strimzi Kafka Operator
              images:
                - name: strimzi-operator
                  ref: dhi/strimzi-operator:1.0.1-debian13@sha256:7efdb60b7b8b61fdfeac883bbe9a13c17fd15fcd6c9d3e7966e951b74fdabb36
                - name: strimzi-kafka
                  ref: dhi/strimzi-kafka:1.1.0-debian13-kafka-4.2.1@sha256:d0eb952ec4ecfbfe2d83e779dba6d35afe4636e011489b3f9c6be580ebf08df0
              name: strimzi-kafka-operator-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/strimzi/strimzi-kafka-operator
              version: 1.0.1
            cmd: prepare
            registry: dhi.io
        - name: update version
          uses: yq/patch@v1
          with:
            file: Chart.yaml
            patches:
              - .version = "1.0.1"
        - name: relocate chart
          uses: helm/rudder@v1
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          with:
            chart: .
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: .
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/strimzi-kafka-operator/config
