# syntax=dhi.io/build:2-helm3

name: Clickhouse Operator Helm chart 0.x
image: dhi.io/clickhouse-operator-chart
variant: helm
tags:
  - 0.27.0
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: 0069fdf80236a42c865fcab066b966320df42785
  CLICKHOUSE_METRICS_EXPORTER_REFERENCE: dhi/clickhouse-metrics-exporter:0.25.6-debian13@sha256:aaa9366a81b09146be6476df22c25fcacb86a4ae97b79dcfb3251d23b136812f
  CLICKHOUSE_OPERATOR_REFERENCE: dhi/clickhouse-operator:0.25.6-debian13@sha256:a24eef05c8d58ec419d405fc942ee066a30202433656edbbc2756fb631891996
  CLICKHOUSE_SERVER_REFERENCE: dhi/clickhouse-server:25.8.23-debian13@sha256:122890b5ee7a93c2207556065e1ffe955e9a38cc40c1dd4454869a22eba1d7c5
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.21.0-debian13-dev@sha256:382206314efea5932384da4cbb019ef72b83d65f2cc8fb2ba0acc7e8a31e5cf8
  KUBECTL_REFERENCE: dhi/kubectl:1.34.8-alpine3.22-dev@sha256:2a2ec222032ff24a4c4fb7f2bc1cf09397335028622e0abce1e0aca6f3097181
  SEMVER_MAJOR_MINOR_VERSION: "0.27"
  SEMVER_MAJOR_VERSION: "0"
  SEMVER_VERSION: 0.27.0
  VERSION: 0.27.0
contents:
  builds:
    - name: clickhouse-operator-chart
      uses: dhi.io/helm:3.21.0-debian13-dev@sha256:382206314efea5932384da4cbb019ef72b83d65f2cc8fb2ba0acc7e8a31e5cf8
      contents:
        files:
          - url: git+https://github.com/Altinity/clickhouse-operator.git#release-0.27.0
            checksum: 0069fdf80236a42c865fcab066b966320df42785
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/deploy/helm/clickhouse-operator
          with:
            chart:
              appRef: clickhouse-operator
              description: Docker Hardened Images Helm chart for ClickHouse Operator
              images:
                - name: clickhouse-operator
                  ref: dhi/clickhouse-operator:0.25.6-debian13@sha256:a24eef05c8d58ec419d405fc942ee066a30202433656edbbc2756fb631891996
                - name: clickhouse-metrics-exporter
                  ref: dhi/clickhouse-metrics-exporter:0.25.6-debian13@sha256:aaa9366a81b09146be6476df22c25fcacb86a4ae97b79dcfb3251d23b136812f
                - name: clickhouse-server
                  ref: dhi/clickhouse-server:25.8.23-debian13@sha256:122890b5ee7a93c2207556065e1ffe955e9a38cc40c1dd4454869a22eba1d7c5
                - name: kubectl
                  ref: dhi/kubectl:1.34.8-alpine3.22-dev@sha256:2a2ec222032ff24a4c4fb7f2bc1cf09397335028622e0abce1e0aca6f3097181
              name: clickhouse-operator-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/Altinity/clickhouse-operator
            cmd: prepare
            registry: dhi.io
        - name: update values
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/deploy/helm/clickhouse-operator
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          with:
            chart: ${source.dir}/helm-charts/deploy/helm/clickhouse-operator
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/deploy/helm
          with:
            chart: clickhouse-operator
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: ${source.dir}/helm-charts/deploy/helm/clickhouse-operator
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/clickhouse-operator/config
