# syntax=dhi.io/build:2-helm3

name: Prometheus Blackbox Exporter Helm chart 11.x
image: dhi.io/blackbox-exporter-chart
variant: helm
tags:
  - 11.11.0
platforms:
  - linux/amd64
vars:
  BLACKBOX_EXPORTER_REFERENCE: dhi/blackbox-exporter:0.28.0-debian13@sha256:73ab2f419a931c81482c85260610317075f2466e29ac872bbe1174e24c77f276
  CHART_COMMIT_SHA: 5e94a1104153d953cd4c4b21bb88ba38d4783c2f
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.21.0-debian13-dev@sha256:7b9ee43cc77e81e2dcbb1b0f6e8ce376b71d63c90c81f2863e24aefff774a8da
  PROMETHEUS_CONFIG_RELOADER_IMAGE_REFERENCE: dhi/prometheus-config-reloader:0.91.0-debian13@sha256:6e7365520cc30a2eebf42b72fdbe9bdc7629d26fe939bad24af2aa2f05c9bcdd
  SEMVER_MAJOR_MINOR_VERSION: "11.11"
  SEMVER_MAJOR_VERSION: "11"
  SEMVER_VERSION: 11.11.0
  VERSION: 11.11.0
contents:
  builds:
    - name: blackbox-exporter-chart
      uses: dhi.io/helm:3.21.0-debian13-dev@sha256:7b9ee43cc77e81e2dcbb1b0f6e8ce376b71d63c90c81f2863e24aefff774a8da
      contents:
        files:
          - url: git+https://github.com/prometheus-community/helm-charts.git#prometheus-blackbox-exporter-11.11.0
            checksum: 5e94a1104153d953cd4c4b21bb88ba38d4783c2f
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/prometheus-blackbox-exporter
          with:
            chart:
              appRef: blackbox-exporter
              description: Docker Hardened Images Helm chart for Prometheus Blackbox Exporter
              images:
                - name: blackbox-exporter
                  ref: dhi/blackbox-exporter:0.28.0-debian13@sha256:73ab2f419a931c81482c85260610317075f2466e29ac872bbe1174e24c77f276
                - name: prometheus-config-reloader
                  ref: dhi/prometheus-config-reloader:0.91.0-debian13@sha256:6e7365520cc30a2eebf42b72fdbe9bdc7629d26fe939bad24af2aa2f05c9bcdd
              name: blackbox-exporter-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/prometheus-community/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/prometheus-blackbox-exporter
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          privileged: true
          with:
            chart: prometheus-blackbox-exporter
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: prometheus-blackbox-exporter
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: prometheus-blackbox-exporter
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/blackbox-exporter/config
