# syntax=dhi.io/build:2-helm3

name: Prometheus Blackbox Exporter Helm chart 11.x
image: dhi.io/blackbox-exporter-chart
variant: helm
tags:
  - 11.8.0
platforms:
  - linux/amd64
vars:
  BLACKBOX_EXPORTER_REFERENCE: dhi/blackbox-exporter:0.28.0-debian13@sha256:ec0f54b603214f340450401156ad97509c7b36458e9753be664a1f57e1d69f9a
  CHART_COMMIT_SHA: c55ebb0fd735c43a657954b0dcabc101281ed373
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.20.0-debian13-dev@sha256:d5dbc06cccf0edbcd1a8f0639a4251484de94052397a5f528b0d019f90a2e1db
  PROMETHEUS_CONFIG_RELOADER_IMAGE_REFERENCE: dhi/prometheus-config-reloader:0.89.0-debian13@sha256:f4fcb212b4d4a85f4ceee17f4f3db7624186a2eb978ac8d2ef530633b7564bf0
  SEMVER_MAJOR_MINOR_VERSION: "11.8"
  SEMVER_MAJOR_VERSION: "11"
  SEMVER_VERSION: 11.8.0
  VERSION: 11.8.0
contents:
  builds:
    - name: blackbox-exporter-chart
      uses: dhi.io/helm:3.20.0-debian13-dev@sha256:d5dbc06cccf0edbcd1a8f0639a4251484de94052397a5f528b0d019f90a2e1db
      contents:
        files:
          - url: git+https://github.com/prometheus-community/helm-charts.git#prometheus-blackbox-exporter-11.8.0
            checksum: c55ebb0fd735c43a657954b0dcabc101281ed373
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/prometheus-blackbox-exporter
          with:
            chart:
              appRef: blackbox-exporter
              description: Docker Hardened Images Helm chart for Prometheus Blackbox Exporter
              images:
                - name: blackbox-exporter
                  ref: dhi/blackbox-exporter:0.28.0-debian13@sha256:ec0f54b603214f340450401156ad97509c7b36458e9753be664a1f57e1d69f9a
                - name: prometheus-config-reloader
                  ref: dhi/prometheus-config-reloader:0.89.0-debian13@sha256:f4fcb212b4d4a85f4ceee17f4f3db7624186a2eb978ac8d2ef530633b7564bf0
              name: blackbox-exporter-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/prometheus-community/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/prometheus-blackbox-exporter
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          privileged: true
          with:
            chart: prometheus-blackbox-exporter
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: prometheus-blackbox-exporter
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: prometheus-blackbox-exporter
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/blackbox-exporter/config
