# syntax=dhi.io/build:2-helm3

name: Prometheus Blackbox Exporter Helm chart 11.x
image: dhi.io/blackbox-exporter-chart
variant: helm
tags:
  - 11.9.1
platforms:
  - linux/amd64
vars:
  BLACKBOX_EXPORTER_REFERENCE: dhi/blackbox-exporter:0.28.0-debian13@sha256:44901feec1a890f2caa1321a6801dc26f817a7a9dffd028ad46af6d38a8a264f
  CHART_COMMIT_SHA: 1e002a3365eeead267c3dc5828be285771010aec
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.20.2-debian13-dev@sha256:81e04bdcbc4f86f57589672220b5fcd235d616d28038aec4511068678778db66
  PROMETHEUS_CONFIG_RELOADER_IMAGE_REFERENCE: dhi/prometheus-config-reloader:0.90.1-debian13@sha256:750497b751f579e7b294be5c9e72d07032107675c17468575c18f45452aaf94a
  SEMVER_MAJOR_MINOR_VERSION: "11.9"
  SEMVER_MAJOR_VERSION: "11"
  SEMVER_VERSION: 11.9.1
  VERSION: 11.9.1
contents:
  builds:
    - name: blackbox-exporter-chart
      uses: dhi.io/helm:3.20.2-debian13-dev@sha256:81e04bdcbc4f86f57589672220b5fcd235d616d28038aec4511068678778db66
      contents:
        files:
          - url: git+https://github.com/prometheus-community/helm-charts.git#prometheus-blackbox-exporter-11.9.1
            checksum: 1e002a3365eeead267c3dc5828be285771010aec
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/prometheus-blackbox-exporter
          with:
            chart:
              appRef: blackbox-exporter
              description: Docker Hardened Images Helm chart for Prometheus Blackbox Exporter
              images:
                - name: blackbox-exporter
                  ref: dhi/blackbox-exporter:0.28.0-debian13@sha256:44901feec1a890f2caa1321a6801dc26f817a7a9dffd028ad46af6d38a8a264f
                - name: prometheus-config-reloader
                  ref: dhi/prometheus-config-reloader:0.90.1-debian13@sha256:750497b751f579e7b294be5c9e72d07032107675c17468575c18f45452aaf94a
              name: blackbox-exporter-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/prometheus-community/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/prometheus-blackbox-exporter
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          privileged: true
          with:
            chart: prometheus-blackbox-exporter
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: prometheus-blackbox-exporter
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: prometheus-blackbox-exporter
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/blackbox-exporter/config
