# syntax=dhi.io/build:2-helm3

name: MLFlow Helm chart 0.x
image: dhi.io/mlflow-chart
variant: helm
tags:
  - 0.1.0
platforms:
  - linux/amd64
vars:
  APP_VERSION: 3.14.0
  COMMIT_SHA: 86cd7f5a1dc25a1387ad07c87811bbc30f62951c
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.21.2-debian13-dev@sha256:2d07671ccc209a0a3e1082dcd0375511e57b8ad6a18439c74924f203d63a461c
  MLFLOW_IMAGE_REFERENCE: dhi/mlflow:3.14.0-debian13@sha256:b00d1326034d0c46d6f261c933ff3b24834f428666d3cf3a06ea575052406229
  SEMVER_MAJOR_MINOR_VERSION: "0.1"
  SEMVER_MAJOR_VERSION: "0"
  SEMVER_VERSION: 0.1.0
  VERSION: 0.1.0
contents:
  builds:
    - name: mlflow-chart
      uses: dhi.io/helm:3.21.2-debian13-dev@sha256:2d07671ccc209a0a3e1082dcd0375511e57b8ad6a18439c74924f203d63a461c
      work-dir: ${source.dir}/helm-charts/charts
      contents:
        files:
          - url: git+https://github.com/mlflow/mlflow.git#v3.14.0
            checksum: 86cd7f5a1dc25a1387ad07c87811bbc30f62951c
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart:
              appRef: mlflow
              dependencies: null
              description: Docker Hardened Images Helm chart for MLFlow
              images:
                - name: mlflow
                  ref: dhi/mlflow:3.14.0-debian13@sha256:b00d1326034d0c46d6f261c933ff3b24834f428666d3cf3a06ea575052406229
              name: mlflow-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/mlflow/mlflow/tree/master/charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          with:
            chart: .
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: .
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/mlflow/config
