# syntax=dhi.io/build:2-helm3

name: Fluent Bit Helm chart 0.x
image: dhi.io/fluent-bit-chart
variant: helm
tags:
  - 0.57.3
platforms:
  - linux/amd64
vars:
  BUSYBOX_REFERENCE: dhi/busybox:1.37.0-alpine3.22@sha256:eaa4c2f2095e8692b35dceeda1de6250e75e9d3a3ab1d24ead080755cf51c5ca
  CHART_COMMIT_SHA: 4bf73db4996b259a1fb8dffa36d2b789c49b15e1
  CONFIGMAP_RELOAD_REFERENCE: dhi/configmap-reload:0.15.0-debian13@sha256:5d6bf90139cf29553353c9f7f867eb4cc1e12c49066bcb7b8ef8c9bad48bb16f
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  FLUENT_BIT_REFERENCE: dhi/fluent-bit:4.2.4-debian13@sha256:817c1d8898b31ab5b06dd393ae8ebf92f0230da3cbf4a2673d8fee45b93b32de
  HELM_REFERENCE: dhi/helm:3.20.2-debian13-dev@sha256:ce95680846fc18d3d179f82f9d633c8274f41cd0d0f8213cbfc4039fbe2cd112
  SEMVER_MAJOR_MINOR_VERSION: "0.57"
  SEMVER_MAJOR_VERSION: "0"
  SEMVER_VERSION: 0.57.3
  VERSION: 0.57.3
contents:
  builds:
    - name: fluent-bit
      uses: dhi.io/helm:3.20.2-debian13-dev@sha256:ce95680846fc18d3d179f82f9d633c8274f41cd0d0f8213cbfc4039fbe2cd112
      contents:
        packages:
          - bash
          - build-essential
          - coreutils
          - grep
          - libc-bin
          - sed
        files:
          - url: git+https://github.com/fluent/helm-charts.git#fluent-bit-0.57.3
            checksum: 4bf73db4996b259a1fb8dffa36d2b789c49b15e1
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/fluent-bit
          with:
            chart:
              appRef: fluent-bit
              description: Docker Hardened Images Helm chart for Fluent Bit
              images:
                - name: fluent-bit
                  ref: dhi/fluent-bit:4.2.4-debian13@sha256:817c1d8898b31ab5b06dd393ae8ebf92f0230da3cbf4a2673d8fee45b93b32de
                - name: configmap-reload
                  ref: dhi/configmap-reload:0.15.0-debian13@sha256:5d6bf90139cf29553353c9f7f867eb4cc1e12c49066bcb7b8ef8c9bad48bb16f
                - name: busybox
                  ref: dhi/busybox:1.37.0-alpine3.22@sha256:eaa4c2f2095e8692b35dceeda1de6250e75e9d3a3ab1d24ead080755cf51c5ca
              name: fluent-bit-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/fluent/fluent-bit
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/fluent-bit
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: fluent-bit
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: fluent-bit
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/fluent-bit/config
