# syntax=dhi.io/build:2-helm3

name: Grafana Loki Helm chart 13.x
image: dhi.io/loki-chart
variant: helm
tags:
  - 13.6.3
platforms:
  - linux/amd64
vars:
  ACCESS_LOG_EXPORTER_REFERENCE: dhi/access-log-exporter:0.3.12-debian13@sha256:bca2b66595f85bdf5288cfccc981a9e97b9ecf71b904f5398dd2af8fe46a3527
  CHART_COMMIT_SHA: a3eb6e658fdba0c0015d66a63bc09a9368e695c6
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.20.2-debian13-dev@sha256:bfafe601001f13954055f12d8e3ca13ab35f3af84965902e670824f33f2d2f2c
  K8S_SIDECAR_REFERENCE: dhi/k8s-sidecar:2.7.1-debian13@sha256:1107aa067dc30c9952fbae931e7a9ea9f28b1a0005e36cb04187069d271b1090
  KUBECTL_REFERENCE: dhi/kubectl:1.35.4-debian13@sha256:664ebea9a9f57b02182afc649436075c6ca821296aa594c7e0f289b6a3cef0c3
  LOKI_CANARY_REFERENCE: dhi/loki-canary:3.7.1-debian13@sha256:78d36d5abc27c1d95616e39e0c22e3437317cdbc0d4b5dbad9cc8ad1305fa062
  LOKI_HELM_TEST_REFERENCE: dhi/loki-helm-test:3.7.1-debian13@sha256:026e21e9ed4d98bdc5fa128def1420ce1a2cd58e0705839def45b03d6530c14d
  LOKI_REFERENCE: dhi/loki:3.7.1-debian13@sha256:69ecf174e86706c49718af4593e6ce24a2185caa3dc04e280a30991db69d2949
  MEMCACHED_EXPORTER_REFERENCE: dhi/memcached-exporter:0.16.0-debian13@sha256:6a2fbd3d14c08ccb010b4c8b6e49ce8a25b81873d81f40b75890dafbd3fa85c0
  MEMCACHED_REFERENCE: dhi/memcached:1.6.41-debian13@sha256:f2315b97d7f49b661950e60603196b01323508ce4defb422ea7363f84b568eb9
  NGINX_REFERENCE: dhi/nginx:1.30.0-debian13@sha256:595bf8694e4a023f8f2843247919aa1f7cf61b1afcf51cf8e62b7237fb5382c0
  ROLLOUT_OPERATOR_CHART_REFERENCE: dhi/grafana-rollout-operator-chart:0.48.0@sha256:ed5b143194b6c36272047f449e3bc1fb59031f7cd49607cb97eda6c33653a3a9
  SEMVER_MAJOR_MINOR_VERSION: "13.6"
  SEMVER_MAJOR_VERSION: "13"
  SEMVER_VERSION: 13.6.3
  VERSION: 13.6.3
  checksum: 02327afab1a59e6a4abc504fac25467772b32b1f
contents:
  builds:
    - name: loki
      uses: dhi.io/helm:3.20.2-debian13-dev@sha256:bfafe601001f13954055f12d8e3ca13ab35f3af84965902e670824f33f2d2f2c
      work-dir: ${source.dir}/helm-charts/charts/loki
      contents:
        files:
          - url: git+https://github.com/grafana-community/helm-charts.git#loki-13.6.3
            checksum: a3eb6e658fdba0c0015d66a63bc09a9368e695c6
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          with:
            chart:
              appRef: loki
              debug: true
              dependencies:
                - alias: rollout_operator
                  condition: rollout_operator.enabled
                  name: rollout-operator
                  ref: dhi/grafana-rollout-operator-chart:0.48.0@sha256:ed5b143194b6c36272047f449e3bc1fb59031f7cd49607cb97eda6c33653a3a9
              description: Docker Hardened Images Helm chart for Grafana Loki
              images:
                - name: loki
                  ref: dhi/loki:3.7.1-debian13@sha256:69ecf174e86706c49718af4593e6ce24a2185caa3dc04e280a30991db69d2949
                - name: loki-canary
                  ref: dhi/loki-canary:3.7.1-debian13@sha256:78d36d5abc27c1d95616e39e0c22e3437317cdbc0d4b5dbad9cc8ad1305fa062
                - name: loki-helm-test
                  ref: dhi/loki-helm-test:3.7.1-debian13@sha256:026e21e9ed4d98bdc5fa128def1420ce1a2cd58e0705839def45b03d6530c14d
                - name: nginx
                  ref: dhi/nginx:1.30.0-debian13@sha256:595bf8694e4a023f8f2843247919aa1f7cf61b1afcf51cf8e62b7237fb5382c0
                - name: k8s-sidecar
                  ref: dhi/k8s-sidecar:2.7.1-debian13@sha256:1107aa067dc30c9952fbae931e7a9ea9f28b1a0005e36cb04187069d271b1090
                - name: memcached
                  ref: dhi/memcached:1.6.41-debian13@sha256:f2315b97d7f49b661950e60603196b01323508ce4defb422ea7363f84b568eb9
                - name: memcached-exporter
                  ref: dhi/memcached-exporter:0.16.0-debian13@sha256:6a2fbd3d14c08ccb010b4c8b6e49ce8a25b81873d81f40b75890dafbd3fa85c0
                - name: access-log-exporter
                  ref: dhi/access-log-exporter:0.3.12-debian13@sha256:bca2b66595f85bdf5288cfccc981a9e97b9ecf71b904f5398dd2af8fe46a3527
                - name: kubectl
                  ref: dhi/kubectl:1.35.4-debian13@sha256:664ebea9a9f57b02182afc649436075c6ca821296aa594c7e0f289b6a3cef0c3
              name: loki-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/grafana/loki
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: helm login
          uses: helm/login@v1
          with:
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          privileged: true
          with:
            chart: .
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          with:
            chart: .
            cmd: lint . --set loki.useTestSchema=true
        - name: package
          uses: helm/package@v1
          with:
            chart: .
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/loki/config
