# syntax=dhi.io/build:2-helm3

name: Grafana Loki Helm chart 13.x
image: dhi.io/loki-chart
variant: helm
tags:
  - 13.2.3
platforms:
  - linux/amd64
vars:
  ACCESS_LOG_EXPORTER_REFERENCE: dhi/access-log-exporter:0.3.11-debian13@sha256:562b90612c15f436f5a370ca6bf4c75a6b693366ddc283a0b6d36e5b759f9e9f
  CHART_COMMIT_SHA: 9fc36af8861c65142a44270849e5fcb76136e297
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.20.2-debian13-dev@sha256:f9dd4a356298b0769dc4c2f718b9f564b631ddf37c19e061d61af9081bc7da13
  K8S_SIDECAR_REFERENCE: dhi/k8s-sidecar:2.6.0-debian13@sha256:e8252ff856f31948b3ca7e78a33517c61e571b13e0c240ace1ca90b48376a75b
  LOKI_CANARY_REFERENCE: dhi/loki-canary:3.6.10-debian13@sha256:5f25fee7a9831eee33a2b9f5838035334eb6010b3331eb95025a10b9444aa536
  LOKI_HELM_TEST_REFERENCE: dhi/loki-helm-test:3.6.10-debian13@sha256:e51d8dca429785157767ce97419c291dbd9a2dc5bb247a7a20a74bbae3bf2875
  LOKI_REFERENCE: dhi/loki:3.6.10-debian13@sha256:f3f170a3df0e310d0788b28c4a2f3181e315f34c57654c457aad8a299eb376f3
  MEMCACHED_EXPORTER_REFERENCE: dhi/memcached-exporter:0.15.5-debian13@sha256:0e2142cd985901af06b688b09251489270b39fc23a38affec5e0a69fd8a31fbc
  MEMCACHED_REFERENCE: dhi/memcached:1.6.41-debian13@sha256:f2315b97d7f49b661950e60603196b01323508ce4defb422ea7363f84b568eb9
  NGINX_REFERENCE: dhi/nginx:1.30.0-debian13@sha256:595bf8694e4a023f8f2843247919aa1f7cf61b1afcf51cf8e62b7237fb5382c0
  ROLLOUT_OPERATOR_CHART_REFERENCE: dhi/grafana-rollout-operator-chart:0.47.0@sha256:614d1b7cbec011c8816dd0a93ef807a3b7ea0e0e69b83a7e23eeea0860993a57
  SEMVER_MAJOR_MINOR_VERSION: "13.2"
  SEMVER_MAJOR_VERSION: "13"
  SEMVER_VERSION: 13.2.3
  VERSION: 13.2.3
  checksum: 02327afab1a59e6a4abc504fac25467772b32b1f
contents:
  builds:
    - name: loki
      uses: dhi.io/helm:3.20.2-debian13-dev@sha256:f9dd4a356298b0769dc4c2f718b9f564b631ddf37c19e061d61af9081bc7da13
      work-dir: ${source.dir}/helm-charts/charts/loki
      contents:
        files:
          - url: git+https://github.com/grafana-community/helm-charts.git#loki-13.2.3
            checksum: 9fc36af8861c65142a44270849e5fcb76136e297
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          with:
            chart:
              appRef: loki
              debug: true
              dependencies:
                - alias: rollout_operator
                  condition: rollout_operator.enabled
                  name: rollout-operator
                  ref: dhi/grafana-rollout-operator-chart:0.47.0@sha256:614d1b7cbec011c8816dd0a93ef807a3b7ea0e0e69b83a7e23eeea0860993a57
              description: Docker Hardened Images Helm chart for Grafana Loki
              images:
                - name: loki
                  ref: dhi/loki:3.6.10-debian13@sha256:f3f170a3df0e310d0788b28c4a2f3181e315f34c57654c457aad8a299eb376f3
                - name: loki-canary
                  ref: dhi/loki-canary:3.6.10-debian13@sha256:5f25fee7a9831eee33a2b9f5838035334eb6010b3331eb95025a10b9444aa536
                - name: loki-helm-test
                  ref: dhi/loki-helm-test:3.6.10-debian13@sha256:e51d8dca429785157767ce97419c291dbd9a2dc5bb247a7a20a74bbae3bf2875
                - name: nginx
                  ref: dhi/nginx:1.30.0-debian13@sha256:595bf8694e4a023f8f2843247919aa1f7cf61b1afcf51cf8e62b7237fb5382c0
                - name: k8s-sidecar
                  ref: dhi/k8s-sidecar:2.6.0-debian13@sha256:e8252ff856f31948b3ca7e78a33517c61e571b13e0c240ace1ca90b48376a75b
                - name: memcached
                  ref: dhi/memcached:1.6.41-debian13@sha256:f2315b97d7f49b661950e60603196b01323508ce4defb422ea7363f84b568eb9
                - name: memcached-exporter
                  ref: dhi/memcached-exporter:0.15.5-debian13@sha256:0e2142cd985901af06b688b09251489270b39fc23a38affec5e0a69fd8a31fbc
                - name: access-log-exporter
                  ref: dhi/access-log-exporter:0.3.11-debian13@sha256:562b90612c15f436f5a370ca6bf4c75a6b693366ddc283a0b6d36e5b759f9e9f
              name: loki-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/grafana/loki
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: helm login
          uses: helm/login@v1
          with:
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          privileged: true
          with:
            chart: .
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          with:
            chart: .
            cmd: lint . --set loki.useTestSchema=true
        - name: package
          uses: helm/package@v1
          with:
            chart: .
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/loki/config
