# syntax=dhi.io/build:2-helm3

name: Grafana Loki Helm chart 13.x
image: dhi.io/loki-chart
variant: helm
tags:
  - 13.7.2
platforms:
  - linux/amd64
vars:
  ACCESS_LOG_EXPORTER_REFERENCE: dhi/access-log-exporter:0.3.12-debian13@sha256:cc98860e18345c51256bfc58825660fa31f79cc64c18cc1eeb0f466819dea4a4
  CHART_COMMIT_SHA: 318302c04398971a6ebae358a4d5b2a388f1ce58
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.20.2-debian13-dev@sha256:f02ac6614478ca43e2100b63d13de77e9362a1223f275ddd4e1c5cfb9e2812c7
  K8S_SIDECAR_REFERENCE: dhi/k8s-sidecar:2.7.3-debian13@sha256:e99657bfb3089d2759e4c6f3b5cf2922291cf58b852f31d49988d6208d52c246
  KUBECTL_REFERENCE: dhi/kubectl:1.35.5-debian13@sha256:b54a2e8d4bac4ee6ffd6f321e653175781b8b4201575672c793f736a55e6a743
  LOKI_CANARY_REFERENCE: dhi/loki-canary:3.7.1-debian13@sha256:41ce27199cdc5f8b584a71bed19006e916019d44521dea7e7d26abdf6f32823e
  LOKI_HELM_TEST_REFERENCE: dhi/loki-helm-test:3.7.2-debian13@sha256:f02cf107bccee7ad7b0f74d9e0ec2533654076d5b7d1296683981aa912dc8679
  LOKI_REFERENCE: dhi/loki:3.7.1-debian13@sha256:b23ac83a1775a408b6c4b9ca86c3af77647c02e1910dcd4567fdc673859cf8ab
  MEMCACHED_EXPORTER_REFERENCE: dhi/memcached-exporter:0.16.0-debian13@sha256:bd96304bd8494a62bfdbf78d53d3d5fbdaa2f4517194e3fd454f045b4076822c
  MEMCACHED_REFERENCE: dhi/memcached:1.6.41-debian13@sha256:f2315b97d7f49b661950e60603196b01323508ce4defb422ea7363f84b568eb9
  NGINX_REFERENCE: dhi/nginx:1.31.0-debian13@sha256:67367ff028b9b75cc1dca14b21ab4ee724f4d636957f4a75df0cd44edec717bd
  ROLLOUT_OPERATOR_CHART_REFERENCE: dhi/grafana-rollout-operator-chart:0.49.0@sha256:e159c57f2e6fd0d7ee6fd0b2585d9d01729cead2593d8c9388cf7a45f51ef90d
  SEMVER_MAJOR_MINOR_VERSION: "13.7"
  SEMVER_MAJOR_VERSION: "13"
  SEMVER_VERSION: 13.7.2
  VERSION: 13.7.2
  checksum: 02327afab1a59e6a4abc504fac25467772b32b1f
contents:
  builds:
    - name: loki
      uses: dhi.io/helm:3.20.2-debian13-dev@sha256:f02ac6614478ca43e2100b63d13de77e9362a1223f275ddd4e1c5cfb9e2812c7
      work-dir: ${source.dir}/helm-charts/charts/loki
      contents:
        files:
          - url: git+https://github.com/grafana-community/helm-charts.git#loki-13.7.2
            checksum: 318302c04398971a6ebae358a4d5b2a388f1ce58
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          with:
            chart:
              appRef: loki
              debug: true
              dependencies:
                - alias: rollout_operator
                  condition: rollout_operator.enabled
                  name: rollout-operator
                  ref: dhi/grafana-rollout-operator-chart:0.49.0@sha256:e159c57f2e6fd0d7ee6fd0b2585d9d01729cead2593d8c9388cf7a45f51ef90d
              description: Docker Hardened Images Helm chart for Grafana Loki
              images:
                - name: loki
                  ref: dhi/loki:3.7.1-debian13@sha256:b23ac83a1775a408b6c4b9ca86c3af77647c02e1910dcd4567fdc673859cf8ab
                - name: loki-canary
                  ref: dhi/loki-canary:3.7.1-debian13@sha256:41ce27199cdc5f8b584a71bed19006e916019d44521dea7e7d26abdf6f32823e
                - name: loki-helm-test
                  ref: dhi/loki-helm-test:3.7.2-debian13@sha256:f02cf107bccee7ad7b0f74d9e0ec2533654076d5b7d1296683981aa912dc8679
                - name: nginx
                  ref: dhi/nginx:1.31.0-debian13@sha256:67367ff028b9b75cc1dca14b21ab4ee724f4d636957f4a75df0cd44edec717bd
                - name: k8s-sidecar
                  ref: dhi/k8s-sidecar:2.7.3-debian13@sha256:e99657bfb3089d2759e4c6f3b5cf2922291cf58b852f31d49988d6208d52c246
                - name: memcached
                  ref: dhi/memcached:1.6.41-debian13@sha256:f2315b97d7f49b661950e60603196b01323508ce4defb422ea7363f84b568eb9
                - name: memcached-exporter
                  ref: dhi/memcached-exporter:0.16.0-debian13@sha256:bd96304bd8494a62bfdbf78d53d3d5fbdaa2f4517194e3fd454f045b4076822c
                - name: access-log-exporter
                  ref: dhi/access-log-exporter:0.3.12-debian13@sha256:cc98860e18345c51256bfc58825660fa31f79cc64c18cc1eeb0f466819dea4a4
                - name: kubectl
                  ref: dhi/kubectl:1.35.5-debian13@sha256:b54a2e8d4bac4ee6ffd6f321e653175781b8b4201575672c793f736a55e6a743
              name: loki-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/grafana/loki
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: helm login
          uses: helm/login@v1
          with:
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          privileged: true
          with:
            chart: .
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          with:
            chart: .
            cmd: lint . --set loki.useTestSchema=true
        - name: package
          uses: helm/package@v1
          with:
            chart: .
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/loki/config
