# syntax=dhi.io/build:2-helm3

name: Grafana Loki Helm chart 17.x
image: dhi.io/loki-chart
variant: helm
tags:
  - 17.3.1
platforms:
  - linux/amd64
vars:
  ACCESS_LOG_EXPORTER_REFERENCE: dhi/access-log-exporter:0.3.18-debian13@sha256:c501ff9dda875423ae416ee5e51f2a1a8880426c710108501f36de5f95e1ee72
  CHART_COMMIT_SHA: 6ad4381da1d8332f39f7b865661b8a55c90633d2
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.21.0-debian13-dev@sha256:ece8efeb889adab72837b0042d8419283ac7fdf2b5c2c8fe09a34e4b8a34ae2e
  K8S_SIDECAR_REFERENCE: dhi/k8s-sidecar:2.7.3-debian13@sha256:4431066af12befdebf58ec57fe89ed301c1b12e00d8944b0bd6d517fc31a7e9d
  KUBECTL_REFERENCE: dhi/kubectl:1.36.1-debian13@sha256:27238f8a3a9affc19319c6e713356648e4848b74717a1999d8a4f4d2c3acebf3
  LOKI_CANARY_REFERENCE: dhi/loki-canary:3.7.2-debian13@sha256:50ce23fa9dca5321285c40e07225a04f0b428e8d23babf65b85dcc5d19fac5da
  LOKI_HELM_TEST_REFERENCE: dhi/loki-helm-test:3.7.2-debian13@sha256:e0de951e118c18f4f2c8341aa70bf85ba566ef89057a3de3dea15f8ee520d3d0
  LOKI_REFERENCE: dhi/loki:3.7.2-debian13@sha256:85dd34659cd4fe6f310b121ec5adbca6746a3ff32b3151a2ec7498e990b1b5a1
  MEMCACHED_EXPORTER_REFERENCE: dhi/memcached-exporter:0.16.0-debian13@sha256:c17389f566b339720d19038130730afa8003387b7cb91389014e040d22d3ed06
  MEMCACHED_REFERENCE: dhi/memcached:1.6.42-debian13@sha256:3ebc872380c8c005d7dc1390bcedc6350dcb6362c34e0507923c8db565c4f709
  NGINX_REFERENCE: dhi/nginx:1.31.1-debian13@sha256:4aca154cf2aaa8fe05bb6c156d963227c0498e756b40b97c86aa76685c5ec3e3
  ROLLOUT_OPERATOR_CHART_REFERENCE: dhi/grafana-rollout-operator-chart:0.50.0@sha256:0436266e8d95f7594adeb486699ef7ee371c9e0b8be3bf85936b59c96ca64da4
  SEMVER_MAJOR_MINOR_VERSION: "17.3"
  SEMVER_MAJOR_VERSION: "17"
  SEMVER_VERSION: 17.3.1
  VERSION: 17.3.1
  checksum: 02327afab1a59e6a4abc504fac25467772b32b1f
contents:
  builds:
    - name: loki
      uses: dhi.io/helm:3.21.0-debian13-dev@sha256:ece8efeb889adab72837b0042d8419283ac7fdf2b5c2c8fe09a34e4b8a34ae2e
      work-dir: ${source.dir}/helm-charts/charts/loki
      contents:
        files:
          - url: git+https://github.com/grafana-community/helm-charts.git#loki-17.3.1
            checksum: 6ad4381da1d8332f39f7b865661b8a55c90633d2
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          with:
            chart:
              appRef: loki
              debug: true
              dependencies:
                - alias: rollout_operator
                  condition: rollout_operator.enabled
                  name: rollout-operator
                  ref: dhi/grafana-rollout-operator-chart:0.50.0@sha256:0436266e8d95f7594adeb486699ef7ee371c9e0b8be3bf85936b59c96ca64da4
              description: Docker Hardened Images Helm chart for Grafana Loki
              images:
                - name: loki
                  ref: dhi/loki:3.7.2-debian13@sha256:85dd34659cd4fe6f310b121ec5adbca6746a3ff32b3151a2ec7498e990b1b5a1
                - name: loki-canary
                  ref: dhi/loki-canary:3.7.2-debian13@sha256:50ce23fa9dca5321285c40e07225a04f0b428e8d23babf65b85dcc5d19fac5da
                - name: loki-helm-test
                  ref: dhi/loki-helm-test:3.7.2-debian13@sha256:e0de951e118c18f4f2c8341aa70bf85ba566ef89057a3de3dea15f8ee520d3d0
                - name: nginx
                  ref: dhi/nginx:1.31.1-debian13@sha256:4aca154cf2aaa8fe05bb6c156d963227c0498e756b40b97c86aa76685c5ec3e3
                - name: k8s-sidecar
                  ref: dhi/k8s-sidecar:2.7.3-debian13@sha256:4431066af12befdebf58ec57fe89ed301c1b12e00d8944b0bd6d517fc31a7e9d
                - name: memcached
                  ref: dhi/memcached:1.6.42-debian13@sha256:3ebc872380c8c005d7dc1390bcedc6350dcb6362c34e0507923c8db565c4f709
                - name: memcached-exporter
                  ref: dhi/memcached-exporter:0.16.0-debian13@sha256:c17389f566b339720d19038130730afa8003387b7cb91389014e040d22d3ed06
                - name: access-log-exporter
                  ref: dhi/access-log-exporter:0.3.18-debian13@sha256:c501ff9dda875423ae416ee5e51f2a1a8880426c710108501f36de5f95e1ee72
                - name: kubectl
                  ref: dhi/kubectl:1.36.1-debian13@sha256:27238f8a3a9affc19319c6e713356648e4848b74717a1999d8a4f4d2c3acebf3
              name: loki-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/grafana/loki
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: helm login
          uses: helm/login@v1
          with:
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          privileged: true
          with:
            chart: .
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          with:
            chart: .
            cmd: lint . --set loki.useTestSchema=true
        - name: package
          uses: helm/package@v1
          with:
            chart: .
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/loki/config
