# syntax=dhi.io/build:2-helm3

name: Grafana Loki Helm chart 17.x
image: dhi.io/loki-chart
variant: helm
tags:
  - 17.4.11
platforms:
  - linux/amd64
vars:
  ACCESS_LOG_EXPORTER_REFERENCE: dhi/access-log-exporter:0.4.4-debian13@sha256:51bed3031d01da65cb392f61625009b756e37cb517e8a04c0f3811c80a206867
  CHART_COMMIT_SHA: aad8b01a41c00230cf3a48761ea73c608a31c7f3
  CHART_HELM_NAME: loki-chart
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  GRAFANA_ROLLOUT_OPERATOR_CHART_REFERENCE: dhi/grafana-rollout-operator-chart:0.50.0@sha256:303788b1409d05dd8ed9a1fe05858a7f2354aca832e37c4b8682df2eb0c626f8
  HELM_REFERENCE: dhi/helm:3.21.2-debian13-dev@sha256:e30b522f3f39307b7710b304f082f76d7b8fc0d0140bfc44bdf2892c5411519f
  K8S_SIDECAR_REFERENCE: dhi/k8s-sidecar:2.8.1-debian13@sha256:d0ec52fde5b74e541840bc1ff727c719b25db792b76618855fadb143413cd4dd
  KUBECTL_REFERENCE: dhi/kubectl:1.36.2-debian13@sha256:686f9197a4722c17b9afc44bb69aff49bad5700fec88f7772123d2bd2a3d5f3d
  LOKI_CANARY_REFERENCE: dhi/loki-canary:3.7.3-debian13@sha256:2e357070777374b1b6b3e88f29292751a596dfe6390b13b77116feee5598cdc8
  LOKI_HELM_TEST_REFERENCE: dhi/loki-helm-test:3.7.3-debian13@sha256:9f577328404852edeac08b08727d9de3cf89fff0b5a34d08321dc49ed94876ac
  LOKI_REFERENCE: dhi/loki:3.7.3-debian13@sha256:d3b84f00db6883794d7478e9ea48aee08b71e0b32fa7be51efb56b53bcfa34e8
  MEMCACHED_EXPORTER_REFERENCE: dhi/memcached-exporter:0.16.0-debian13@sha256:1c87c99449ce717496631951c87912e564bdfed91890f1caeb00461fd1f54d2a
  MEMCACHED_REFERENCE: dhi/memcached:1.6.43-debian13@sha256:2a7784709f188f676c4402356446d092f5f192b846dddfe3db6558e54f240a51
  NGINX_REFERENCE: dhi/nginx:1.31.2-debian13@sha256:de8730b879576024c97094e2b5d2001a7a4f10f46d1058ec5bad48fe64f740c4
  SEMVER_MAJOR_MINOR_VERSION: "17.4"
  SEMVER_MAJOR_VERSION: "17"
  SEMVER_VERSION: 17.4.11
  VERSION: 17.4.11
  checksum: 02327afab1a59e6a4abc504fac25467772b32b1f
contents:
  builds:
    - name: loki
      uses: dhi.io/helm:3.21.2-debian13-dev@sha256:e30b522f3f39307b7710b304f082f76d7b8fc0d0140bfc44bdf2892c5411519f
      work-dir: ${source.dir}/helm-charts/charts/loki
      contents:
        files:
          - url: git+https://github.com/grafana-community/helm-charts.git#loki-17.4.11
            checksum: aad8b01a41c00230cf3a48761ea73c608a31c7f3
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          with:
            chart:
              appRef: loki
              debug: true
              dependencies:
                - alias: rollout_operator
                  condition: rollout_operator.enabled
                  name: rollout-operator
                  ref: dhi/grafana-rollout-operator-chart:0.50.0@sha256:303788b1409d05dd8ed9a1fe05858a7f2354aca832e37c4b8682df2eb0c626f8
              description: Docker Hardened Images Helm chart for Grafana Loki
              images:
                - name: loki
                  ref: dhi/loki:3.7.3-debian13@sha256:d3b84f00db6883794d7478e9ea48aee08b71e0b32fa7be51efb56b53bcfa34e8
                - name: loki-canary
                  ref: dhi/loki-canary:3.7.3-debian13@sha256:2e357070777374b1b6b3e88f29292751a596dfe6390b13b77116feee5598cdc8
                - name: loki-helm-test
                  ref: dhi/loki-helm-test:3.7.3-debian13@sha256:9f577328404852edeac08b08727d9de3cf89fff0b5a34d08321dc49ed94876ac
                - name: nginx
                  ref: dhi/nginx:1.31.2-debian13@sha256:de8730b879576024c97094e2b5d2001a7a4f10f46d1058ec5bad48fe64f740c4
                - name: k8s-sidecar
                  ref: dhi/k8s-sidecar:2.8.1-debian13@sha256:d0ec52fde5b74e541840bc1ff727c719b25db792b76618855fadb143413cd4dd
                - name: memcached
                  ref: dhi/memcached:1.6.43-debian13@sha256:2a7784709f188f676c4402356446d092f5f192b846dddfe3db6558e54f240a51
                - name: memcached-exporter
                  ref: dhi/memcached-exporter:0.16.0-debian13@sha256:1c87c99449ce717496631951c87912e564bdfed91890f1caeb00461fd1f54d2a
                - name: access-log-exporter
                  ref: dhi/access-log-exporter:0.4.4-debian13@sha256:51bed3031d01da65cb392f61625009b756e37cb517e8a04c0f3811c80a206867
                - name: kubectl
                  ref: dhi/kubectl:1.36.2-debian13@sha256:686f9197a4722c17b9afc44bb69aff49bad5700fec88f7772123d2bd2a3d5f3d
              name: loki-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/grafana/loki
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: helm login
          uses: helm/login@v1
          with:
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          privileged: true
          with:
            chart: .
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          with:
            chart: .
            cmd: lint . --set loki.useTestSchema=true
        - name: package
          uses: helm/package@v1
          with:
            chart: .
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/loki/config
