# syntax=dhi.io/build:2-helm3

name: Grafana Loki Helm chart 17.x
image: dhi.io/loki-chart
variant: helm
tags:
  - 17.4.11
platforms:
  - linux/amd64
vars:
  ACCESS_LOG_EXPORTER_REFERENCE: dhi/access-log-exporter:0.4.4-debian13@sha256:51bed3031d01da65cb392f61625009b756e37cb517e8a04c0f3811c80a206867
  CHART_COMMIT_SHA: aad8b01a41c00230cf3a48761ea73c608a31c7f3
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.21.2-debian13-dev@sha256:e30b522f3f39307b7710b304f082f76d7b8fc0d0140bfc44bdf2892c5411519f
  K8S_SIDECAR_REFERENCE: dhi/k8s-sidecar:2.8.0-debian13@sha256:0b976fd11234f62a6992e7d9ee38d2dc65b4b7388cdc72ec1a29a57112c5e0cb
  KUBECTL_REFERENCE: dhi/kubectl:1.36.2-debian13@sha256:686f9197a4722c17b9afc44bb69aff49bad5700fec88f7772123d2bd2a3d5f3d
  LOKI_CANARY_REFERENCE: dhi/loki-canary:3.7.2-debian13@sha256:4df1843adb628e6f8846dc2b6ec6d2ea78a7a26dc80fc3c36ce4bf3421f0463d
  LOKI_HELM_TEST_REFERENCE: dhi/loki-helm-test:3.7.3-debian13@sha256:46a6f247350cd67c73e1f040cf4b353f60cecfd5e529c0d497585dd90d202e3b
  LOKI_REFERENCE: dhi/loki:3.7.2-debian13@sha256:66333cede67e937c08022912f3fde49f616bdc4f520193927739295b54206b57
  MEMCACHED_EXPORTER_REFERENCE: dhi/memcached-exporter:0.16.0-debian13@sha256:1c87c99449ce717496631951c87912e564bdfed91890f1caeb00461fd1f54d2a
  MEMCACHED_REFERENCE: dhi/memcached:1.6.42-debian13@sha256:a4c08425f2002c95ba81ec89c650719a0a9eb84821d7c56aadbe80672ec39819
  NGINX_REFERENCE: dhi/nginx:1.31.2-debian13@sha256:de8730b879576024c97094e2b5d2001a7a4f10f46d1058ec5bad48fe64f740c4
  ROLLOUT_OPERATOR_CHART_REFERENCE: dhi/grafana-rollout-operator-chart:0.50.0@sha256:e3a0cca14a9d40868cc6f3578fd8cb9e65fcfb752e46a132a78a3a7145bc7a5e
  SEMVER_MAJOR_MINOR_VERSION: "17.4"
  SEMVER_MAJOR_VERSION: "17"
  SEMVER_VERSION: 17.4.11
  VERSION: 17.4.11
  checksum: 02327afab1a59e6a4abc504fac25467772b32b1f
contents:
  builds:
    - name: loki
      uses: dhi.io/helm:3.21.2-debian13-dev@sha256:e30b522f3f39307b7710b304f082f76d7b8fc0d0140bfc44bdf2892c5411519f
      work-dir: ${source.dir}/helm-charts/charts/loki
      contents:
        files:
          - url: git+https://github.com/grafana-community/helm-charts.git#loki-17.4.11
            checksum: aad8b01a41c00230cf3a48761ea73c608a31c7f3
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          with:
            chart:
              appRef: loki
              debug: true
              dependencies:
                - alias: rollout_operator
                  condition: rollout_operator.enabled
                  name: rollout-operator
                  ref: dhi/grafana-rollout-operator-chart:0.50.0@sha256:e3a0cca14a9d40868cc6f3578fd8cb9e65fcfb752e46a132a78a3a7145bc7a5e
              description: Docker Hardened Images Helm chart for Grafana Loki
              images:
                - name: loki
                  ref: dhi/loki:3.7.2-debian13@sha256:66333cede67e937c08022912f3fde49f616bdc4f520193927739295b54206b57
                - name: loki-canary
                  ref: dhi/loki-canary:3.7.2-debian13@sha256:4df1843adb628e6f8846dc2b6ec6d2ea78a7a26dc80fc3c36ce4bf3421f0463d
                - name: loki-helm-test
                  ref: dhi/loki-helm-test:3.7.3-debian13@sha256:46a6f247350cd67c73e1f040cf4b353f60cecfd5e529c0d497585dd90d202e3b
                - name: nginx
                  ref: dhi/nginx:1.31.2-debian13@sha256:de8730b879576024c97094e2b5d2001a7a4f10f46d1058ec5bad48fe64f740c4
                - name: k8s-sidecar
                  ref: dhi/k8s-sidecar:2.8.0-debian13@sha256:0b976fd11234f62a6992e7d9ee38d2dc65b4b7388cdc72ec1a29a57112c5e0cb
                - name: memcached
                  ref: dhi/memcached:1.6.42-debian13@sha256:a4c08425f2002c95ba81ec89c650719a0a9eb84821d7c56aadbe80672ec39819
                - name: memcached-exporter
                  ref: dhi/memcached-exporter:0.16.0-debian13@sha256:1c87c99449ce717496631951c87912e564bdfed91890f1caeb00461fd1f54d2a
                - name: access-log-exporter
                  ref: dhi/access-log-exporter:0.4.4-debian13@sha256:51bed3031d01da65cb392f61625009b756e37cb517e8a04c0f3811c80a206867
                - name: kubectl
                  ref: dhi/kubectl:1.36.2-debian13@sha256:686f9197a4722c17b9afc44bb69aff49bad5700fec88f7772123d2bd2a3d5f3d
              name: loki-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/grafana/loki
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: helm login
          uses: helm/login@v1
          with:
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          privileged: true
          with:
            chart: .
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          with:
            chart: .
            cmd: lint . --set loki.useTestSchema=true
        - name: package
          uses: helm/package@v1
          with:
            chart: .
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/loki/config
