# syntax=dhi.io/build:2-helm3

name: Grafana Loki Helm chart 18.x
image: dhi.io/loki-chart
variant: helm
tags:
  - 18.13.7
platforms:
  - linux/amd64
vars:
  ACCESS_LOG_EXPORTER_REFERENCE: dhi/access-log-exporter:0.4.21-debian13@sha256:f06aa8a9dbb110a073e55558f603fe46c984e93cb1c37b734f637a68d4e7ec5c
  APPVERSION: 3.7.8
  CHART_COMMIT_SHA: 8fe7bd856d34c2fd8c929dce0b993727d3e23f55
  CHART_HELM_NAME: loki-chart
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  GRAFANA_ROLLOUT_OPERATOR_CHART_REFERENCE: dhi/grafana-rollout-operator-chart:0.52.0@sha256:e484e7fdca1209078aff2f6927f57705281a0fef8c99cc77d6d2d028652a158b
  HELM_VERSION: 4.1.4-2
  K8S_SIDECAR_REFERENCE: dhi/k8s-sidecar:2.11.2-debian13@sha256:280cfb310dfa1dda319baaa380e899ed6b4493723f9c3949d54edcdbc9052b0c
  KUBECTL_REFERENCE: dhi/kubectl:1.37.1-debian13@sha256:a4b3c66483217b64b6ad3c70b559504da5cde437d28247eedbae461df99d4124
  LOKI_CANARY_REFERENCE: dhi/loki-canary:3.7.8-debian13@sha256:aaf16e0c3c1e8587ddac60b03174d352d0c8c1501349d9424be0a96f6058231f
  LOKI_HELM_TEST_REFERENCE: dhi/loki-helm-test:3.7.8-debian13@sha256:3854ade0c504ffe0194f8cf95e719d8b637cae44af895b2140b35c2dfe415f6b
  LOKI_REFERENCE: dhi/loki:3.7.8-debian13@sha256:602ba15bb7e10e71ead719821672516deb671e4e95bdbba9dc979c3d49da6316
  MEMCACHED_EXPORTER_REFERENCE: dhi/memcached-exporter:0.17.0-debian13@sha256:079826ea980ce9d923f82bb06e6a3dc116e75f5c7bd6bc1073c00bb93972e77b
  MEMCACHED_REFERENCE: dhi/memcached:1.6.45-debian13@sha256:8de3f86c644b006454104f68b1587b69ae2a7417de5ae1b8d017bba6c1d0ea55
  NGINX_REFERENCE: dhi/nginx:1.31.6-debian13@sha256:773bcbbe9534e0bf71f96b1bc232bf6dadd815fa96467280aef8f5bb8fb2e0de
  SEMVER_MAJOR_MINOR_VERSION: "18.13"
  SEMVER_MAJOR_VERSION: "18"
  SEMVER_VERSION: 18.13.7
  VERSION: 18.13.7
  checksum: 02327afab1a59e6a4abc504fac25467772b32b1f
contents:
  repositories:
    - deb [signed-by=/usr/share/keyrings/dhi-deb-main.gpg] http://dhi.io/deb/debian/main trixie main
  keyring:
    - https://dhi.io/keyring/dhi-deb-gpg.D46852F6925E9F71.key
  builds:
    - name: loki
      work-dir: ${source.dir}/helm-charts/charts/loki
      contents:
        packages:
          - bash
          - ca-certificates
          - coreutils
          - helm=4.1.4-2
        files:
          - url: git+https://github.com/grafana-community/helm-charts.git#loki-18.13.7
            checksum: 8fe7bd856d34c2fd8c929dce0b993727d3e23f55
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          with:
            chart:
              appRef: loki
              debug: true
              dependencies:
                - alias: rollout_operator
                  condition: rollout_operator.enabled
                  name: rollout-operator
                  ref: dhi/grafana-rollout-operator-chart:0.52.0@sha256:e484e7fdca1209078aff2f6927f57705281a0fef8c99cc77d6d2d028652a158b
              description: Docker Hardened Images Helm chart for Grafana Loki
              images:
                - name: loki
                  ref: dhi/loki:3.7.8-debian13@sha256:602ba15bb7e10e71ead719821672516deb671e4e95bdbba9dc979c3d49da6316
                - name: loki-canary
                  ref: dhi/loki-canary:3.7.8-debian13@sha256:aaf16e0c3c1e8587ddac60b03174d352d0c8c1501349d9424be0a96f6058231f
                - name: loki-helm-test
                  ref: dhi/loki-helm-test:3.7.8-debian13@sha256:3854ade0c504ffe0194f8cf95e719d8b637cae44af895b2140b35c2dfe415f6b
                - name: nginx
                  ref: dhi/nginx:1.31.6-debian13@sha256:773bcbbe9534e0bf71f96b1bc232bf6dadd815fa96467280aef8f5bb8fb2e0de
                - name: k8s-sidecar
                  ref: dhi/k8s-sidecar:2.11.2-debian13@sha256:280cfb310dfa1dda319baaa380e899ed6b4493723f9c3949d54edcdbc9052b0c
                - name: memcached
                  ref: dhi/memcached:1.6.45-debian13@sha256:8de3f86c644b006454104f68b1587b69ae2a7417de5ae1b8d017bba6c1d0ea55
                - name: memcached-exporter
                  ref: dhi/memcached-exporter:0.17.0-debian13@sha256:079826ea980ce9d923f82bb06e6a3dc116e75f5c7bd6bc1073c00bb93972e77b
                - name: access-log-exporter
                  ref: dhi/access-log-exporter:0.4.21-debian13@sha256:f06aa8a9dbb110a073e55558f603fe46c984e93cb1c37b734f637a68d4e7ec5c
                - name: kubectl
                  ref: dhi/kubectl:1.37.1-debian13@sha256:a4b3c66483217b64b6ad3c70b559504da5cde437d28247eedbae461df99d4124
              name: loki-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/grafana/loki
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: helm login
          uses: helm/login@v1
          with:
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          privileged: true
          with:
            chart: .
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          with:
            chart: .
            cmd: lint . --set loki.useTestSchema=true
        - name: package
          uses: helm/package@v1
          with:
            chart: .
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/loki/config
