# syntax=dhi.io/build:2-helm3

name: Grafana Loki Helm chart 18.x
image: dhi.io/loki-chart
variant: helm
tags:
  - 18.13.4
platforms:
  - linux/amd64
vars:
  ACCESS_LOG_EXPORTER_REFERENCE: dhi/access-log-exporter:0.4.13-debian13@sha256:976e98e9bfab4fc78aaf314a64875f61397fc187c0b60e7156f353723631af5d
  APPVERSION: 3.7.8
  CHART_COMMIT_SHA: 78afff3b70bf1f20d6561cb096b1c57ba7bbb9d1
  CHART_HELM_NAME: loki-chart
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  GRAFANA_ROLLOUT_OPERATOR_CHART_REFERENCE: dhi/grafana-rollout-operator-chart:0.52.0@sha256:e484e7fdca1209078aff2f6927f57705281a0fef8c99cc77d6d2d028652a158b
  HELM_VERSION: 4.1.4-2
  K8S_SIDECAR_REFERENCE: dhi/k8s-sidecar:2.11.2-debian13@sha256:2de106ec46cf6dcb96357855a3e56295bb772f385a5992823f649003a2dac54b
  KUBECTL_REFERENCE: dhi/kubectl:1.37.0-debian13@sha256:b1165982728a3de0941878713eead61dfeed329abb43caae6e33a86332dd3700
  LOKI_CANARY_REFERENCE: dhi/loki-canary:3.7.7-debian13@sha256:c1bbaebe8608ed808158a5f714f4e69545ca9411cf0da53abef7e7e4636647b3
  LOKI_HELM_TEST_REFERENCE: dhi/loki-helm-test:3.7.8-debian13@sha256:3854ade0c504ffe0194f8cf95e719d8b637cae44af895b2140b35c2dfe415f6b
  LOKI_REFERENCE: dhi/loki:3.7.8-debian13@sha256:51e8268903a255464a5f0cfe665fc0b2e6f01c61d0171ede60fcfe258e3bb7b3
  MEMCACHED_EXPORTER_REFERENCE: dhi/memcached-exporter:0.17.0-debian13@sha256:079826ea980ce9d923f82bb06e6a3dc116e75f5c7bd6bc1073c00bb93972e77b
  MEMCACHED_REFERENCE: dhi/memcached:1.6.45-debian13@sha256:bc9ef694d009996e8c6ddc1724ea6af6f94398a16e9b8c4fb22d09ad2620407f
  NGINX_REFERENCE: dhi/nginx:1.31.6-debian13@sha256:01378d311584144860a1516bb0240a4ce0c6070792ada0f2a4b763fdd3dcde49
  SEMVER_MAJOR_MINOR_VERSION: "18.13"
  SEMVER_MAJOR_VERSION: "18"
  SEMVER_VERSION: 18.13.4
  VERSION: 18.13.4
  checksum: 02327afab1a59e6a4abc504fac25467772b32b1f
contents:
  repositories:
    - deb [signed-by=/usr/share/keyrings/dhi-deb-main.gpg] http://dhi.io/deb/debian/main trixie main
  keyring:
    - https://dhi.io/keyring/dhi-deb-gpg.D46852F6925E9F71.key
  builds:
    - name: loki
      work-dir: ${source.dir}/helm-charts/charts/loki
      contents:
        packages:
          - bash
          - ca-certificates
          - coreutils
          - helm=4.1.4-2
        files:
          - url: git+https://github.com/grafana-community/helm-charts.git#loki-18.13.4
            checksum: 78afff3b70bf1f20d6561cb096b1c57ba7bbb9d1
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          with:
            chart:
              appRef: loki
              debug: true
              dependencies:
                - alias: rollout_operator
                  condition: rollout_operator.enabled
                  name: rollout-operator
                  ref: dhi/grafana-rollout-operator-chart:0.52.0@sha256:e484e7fdca1209078aff2f6927f57705281a0fef8c99cc77d6d2d028652a158b
              description: Docker Hardened Images Helm chart for Grafana Loki
              images:
                - name: loki
                  ref: dhi/loki:3.7.8-debian13@sha256:51e8268903a255464a5f0cfe665fc0b2e6f01c61d0171ede60fcfe258e3bb7b3
                - name: loki-canary
                  ref: dhi/loki-canary:3.7.7-debian13@sha256:c1bbaebe8608ed808158a5f714f4e69545ca9411cf0da53abef7e7e4636647b3
                - name: loki-helm-test
                  ref: dhi/loki-helm-test:3.7.8-debian13@sha256:3854ade0c504ffe0194f8cf95e719d8b637cae44af895b2140b35c2dfe415f6b
                - name: nginx
                  ref: dhi/nginx:1.31.6-debian13@sha256:01378d311584144860a1516bb0240a4ce0c6070792ada0f2a4b763fdd3dcde49
                - name: k8s-sidecar
                  ref: dhi/k8s-sidecar:2.11.2-debian13@sha256:2de106ec46cf6dcb96357855a3e56295bb772f385a5992823f649003a2dac54b
                - name: memcached
                  ref: dhi/memcached:1.6.45-debian13@sha256:bc9ef694d009996e8c6ddc1724ea6af6f94398a16e9b8c4fb22d09ad2620407f
                - name: memcached-exporter
                  ref: dhi/memcached-exporter:0.17.0-debian13@sha256:079826ea980ce9d923f82bb06e6a3dc116e75f5c7bd6bc1073c00bb93972e77b
                - name: access-log-exporter
                  ref: dhi/access-log-exporter:0.4.13-debian13@sha256:976e98e9bfab4fc78aaf314a64875f61397fc187c0b60e7156f353723631af5d
                - name: kubectl
                  ref: dhi/kubectl:1.37.0-debian13@sha256:b1165982728a3de0941878713eead61dfeed329abb43caae6e33a86332dd3700
              name: loki-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/grafana/loki
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: helm login
          uses: helm/login@v1
          with:
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          privileged: true
          with:
            chart: .
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          with:
            chart: .
            cmd: lint . --set loki.useTestSchema=true
        - name: package
          uses: helm/package@v1
          with:
            chart: .
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/loki/config
