# syntax=dhi.io/build:2-helm3

name: Grafana Loki Helm chart 18.x
image: dhi.io/loki-chart
variant: helm
tags:
  - 18.4.4
platforms:
  - linux/amd64
vars:
  ACCESS_LOG_EXPORTER_REFERENCE: dhi/access-log-exporter:0.4.6-debian13@sha256:b62092795c8bfc5e0401e6d429e6213914e273ce5922c88590c9cdc0377fe8cf
  APPVERSION: 3.7.3
  CHART_COMMIT_SHA: 40d8dbeab05b9cf616f0adb2bc4ec9bfc1dbce4f
  CHART_HELM_NAME: loki-chart
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  GRAFANA_ROLLOUT_OPERATOR_CHART_REFERENCE: dhi/grafana-rollout-operator-chart:0.50.0@sha256:85a24793b9d2fd89acf5486f5d5f3da72c13c20296e2eee77b61c51e0eb22a41
  HELM_VERSION: 4.1.4-2
  K8S_SIDECAR_REFERENCE: dhi/k8s-sidecar:2.8.1-debian13@sha256:7598f1db25c9557baa9835c97dca7b014a25e5af6e5009b1ac9f905be9038bbe
  KUBECTL_REFERENCE: dhi/kubectl:1.36.2-debian13@sha256:ccb62a5ecee3c085e0779385124e3cafd02c68560ae01d61535acf18295a2f5a
  LOKI_CANARY_REFERENCE: dhi/loki-canary:3.7.3-debian13@sha256:119f8e56021924d0edfa8d6b9113db6f6538f85d0f577d219ef9a4fd4bc89224
  LOKI_HELM_TEST_REFERENCE: dhi/loki-helm-test:3.7.3-debian13@sha256:c0465a7de0630fe627e631a1282c48a1e48e4a34a1140f19dbe2f5208cf608e4
  LOKI_REFERENCE: dhi/loki:3.7.3-debian13@sha256:abafe2374acfc0a644edc8e10f98cedb13f329cc2365d169dbcf917362dd97f9
  MEMCACHED_EXPORTER_REFERENCE: dhi/memcached-exporter:0.16.0-debian13@sha256:af40175a62d1bd6a095c129541d9ff0163d70659b999147f5c1a43cea695cf67
  MEMCACHED_REFERENCE: dhi/memcached:1.6.45-debian13@sha256:10e2435cd2bd776b961b1d759067177092debe779a378350bd44300a1fcc7963
  NGINX_REFERENCE: dhi/nginx:1.31.2-debian13@sha256:4c2416233eb6b5e4d81ab6a4f8ba25937b1c33896af0f8cd116c0b16bb2cc06d
  SEMVER_MAJOR_MINOR_VERSION: "18.4"
  SEMVER_MAJOR_VERSION: "18"
  SEMVER_VERSION: 18.4.4
  VERSION: 18.4.4
  checksum: 02327afab1a59e6a4abc504fac25467772b32b1f
contents:
  repositories:
    - deb [signed-by=/usr/share/keyrings/dhi-deb-main.gpg] http://dhi.io/deb/debian/main trixie main
  keyring:
    - https://dhi.io/keyring/dhi-deb-gpg.D46852F6925E9F71.key
  builds:
    - name: loki
      work-dir: ${source.dir}/helm-charts/charts/loki
      contents:
        packages:
          - bash
          - ca-certificates
          - coreutils
          - helm=4.1.4-2
        files:
          - url: git+https://github.com/grafana-community/helm-charts.git#loki-18.4.4
            checksum: 40d8dbeab05b9cf616f0adb2bc4ec9bfc1dbce4f
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          with:
            chart:
              appRef: loki
              debug: true
              dependencies:
                - alias: rollout_operator
                  condition: rollout_operator.enabled
                  name: rollout-operator
                  ref: dhi/grafana-rollout-operator-chart:0.50.0@sha256:85a24793b9d2fd89acf5486f5d5f3da72c13c20296e2eee77b61c51e0eb22a41
              description: Docker Hardened Images Helm chart for Grafana Loki
              images:
                - name: loki
                  ref: dhi/loki:3.7.3-debian13@sha256:abafe2374acfc0a644edc8e10f98cedb13f329cc2365d169dbcf917362dd97f9
                - name: loki-canary
                  ref: dhi/loki-canary:3.7.3-debian13@sha256:119f8e56021924d0edfa8d6b9113db6f6538f85d0f577d219ef9a4fd4bc89224
                - name: loki-helm-test
                  ref: dhi/loki-helm-test:3.7.3-debian13@sha256:c0465a7de0630fe627e631a1282c48a1e48e4a34a1140f19dbe2f5208cf608e4
                - name: nginx
                  ref: dhi/nginx:1.31.2-debian13@sha256:4c2416233eb6b5e4d81ab6a4f8ba25937b1c33896af0f8cd116c0b16bb2cc06d
                - name: k8s-sidecar
                  ref: dhi/k8s-sidecar:2.8.1-debian13@sha256:7598f1db25c9557baa9835c97dca7b014a25e5af6e5009b1ac9f905be9038bbe
                - name: memcached
                  ref: dhi/memcached:1.6.45-debian13@sha256:10e2435cd2bd776b961b1d759067177092debe779a378350bd44300a1fcc7963
                - name: memcached-exporter
                  ref: dhi/memcached-exporter:0.16.0-debian13@sha256:af40175a62d1bd6a095c129541d9ff0163d70659b999147f5c1a43cea695cf67
                - name: access-log-exporter
                  ref: dhi/access-log-exporter:0.4.6-debian13@sha256:b62092795c8bfc5e0401e6d429e6213914e273ce5922c88590c9cdc0377fe8cf
                - name: kubectl
                  ref: dhi/kubectl:1.36.2-debian13@sha256:ccb62a5ecee3c085e0779385124e3cafd02c68560ae01d61535acf18295a2f5a
              name: loki-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/grafana/loki
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: helm login
          uses: helm/login@v1
          with:
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          privileged: true
          with:
            chart: .
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          with:
            chart: .
            cmd: lint . --set loki.useTestSchema=true
        - name: package
          uses: helm/package@v1
          with:
            chart: .
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/loki/config
