metadata:
  display-name: KGateway CRDs Helm chart
  short-description: Installs the Gateway API and KGateway Custom Resource Definitions required by the KGateway controller.
  featured: false
  home-url: https://github.com/kgateway-dev/kgateway/tree/main/install/helm/kgateway-crds
  categories:
    - networking
