# syntax=dhi.io/build:2-helm3

name: Zero to JupyterHub Helm chart 4.x
image: dhi.io/zero-to-jupyterhub-k8s-chart
variant: helm
tags:
  - 4.4.2
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: ec77affd8cf847ad95b2bbcdb57aa17fb5c23c8b
  CHART_HELM_NAME: zero-to-jupyterhub-k8s-chart
  CONFIGURABLE_HTTP_PROXY_REFERENCE: dhi/configurable-http-proxy:5.3.0-debian13@sha256:539b164d4935c3908591bff25ea950da96ea48323aa3a0a7a9341fdecd45bdd7
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_VERSION: 4.1.4-2
  JUPYTERHUB_K8S_HUB_REFERENCE: dhi/jupyterhub-k8s-hub:4.4.2-debian13@sha256:78fad34b2268ae131450ec61c22bc7ab51b4acc16e5979d541a5220946dc06ed
  JUPYTERHUB_K8S_IMAGE_AWAITER_REFERENCE: dhi/jupyterhub-k8s-image-awaiter:4.4.2-alpine3.24@sha256:201046070e707909027cc17f23eb38dc87b31c4f557353261d8bfadb83bb0693
  JUPYTERHUB_K8S_NETWORK_TOOLS_REFERENCE: dhi/jupyterhub-k8s-network-tools:4.4.2-alpine3.24@sha256:6fcef87450cd0b8db0b7fedca9e0f1a1480309a3ccd83f39d1c674ac9b3c030e
  JUPYTERHUB_K8S_SECRET_SYNC_REFERENCE: dhi/jupyterhub-k8s-secret-sync:4.4.2-debian13@sha256:b6f5ae9cd4454a1d7121a8e060268cf6098bad6be436f9a1348cadf880ef1d64
  JUPYTERHUB_K8S_SINGLEUSER_SAMPLE_REFERENCE: dhi/jupyterhub-k8s-singleuser-sample:4.4.2-debian13-compat@sha256:95ecfa5e18094171c8fdc16ae144b62f9c46e3720e0d7d50bde91ae2d0c9d1e2
  KUBE_SCHEDULER_REFERENCE: dhi/kube-scheduler:1.36.4-debian13@sha256:77e092821011eb12a2331f998f8e7f69947b402924d4ec62bc41a1653c903d57
  KUBERNETES_PAUSE_REFERENCE: dhi/kubernetes-pause:3.10.2-debian13@sha256:c23200da8c68413820169abfb3c4ce799240b13dff49294ca679b0218587d0e4
  SEMVER_MAJOR_MINOR_VERSION: "4.4"
  SEMVER_MAJOR_VERSION: "4"
  SEMVER_VERSION: 4.4.2
  TRAEFIK_REFERENCE: dhi/traefik:3.7.12-debian13@sha256:159329be55fdf7eb0fe5d5abb198b7ada55f16077215a4afdd839bc0c5b801a8
  VERSION: 4.4.2
contents:
  repositories:
    - deb [signed-by=/usr/share/keyrings/dhi-deb-main.gpg] http://dhi.io/deb/debian/main trixie main
  keyring:
    - https://dhi.io/keyring/dhi-deb-gpg.D46852F6925E9F71.key
  builds:
    - name: jupyterhub
      work-dir: ${source.dir}/helm-charts/jupyterhub
      contents:
        packages:
          - bash
          - ca-certificates
          - coreutils
          - helm=4.1.4-2
        files:
          - url: git+https://github.com/jupyterhub/zero-to-jupyterhub-k8s.git#4.4.2
            checksum: ec77affd8cf847ad95b2bbcdb57aa17fb5c23c8b
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          with:
            chart:
              appRef: hub
              description: Docker Hardened Images Helm chart for Zero to JupyterHub on Kubernetes
              images:
                - name: hub
                  ref: dhi/jupyterhub-k8s-hub:4.4.2-debian13@sha256:78fad34b2268ae131450ec61c22bc7ab51b4acc16e5979d541a5220946dc06ed
                - name: chp
                  ref: dhi/configurable-http-proxy:5.3.0-debian13@sha256:539b164d4935c3908591bff25ea950da96ea48323aa3a0a7a9341fdecd45bdd7
                - name: secret-sync
                  ref: dhi/jupyterhub-k8s-secret-sync:4.4.2-debian13@sha256:b6f5ae9cd4454a1d7121a8e060268cf6098bad6be436f9a1348cadf880ef1d64
                - name: network-tools
                  ref: dhi/jupyterhub-k8s-network-tools:4.4.2-alpine3.24@sha256:6fcef87450cd0b8db0b7fedca9e0f1a1480309a3ccd83f39d1c674ac9b3c030e
                - name: singleuser
                  ref: dhi/jupyterhub-k8s-singleuser-sample:4.4.2-debian13-compat@sha256:95ecfa5e18094171c8fdc16ae144b62f9c46e3720e0d7d50bde91ae2d0c9d1e2
                - name: image-awaiter
                  ref: dhi/jupyterhub-k8s-image-awaiter:4.4.2-alpine3.24@sha256:201046070e707909027cc17f23eb38dc87b31c4f557353261d8bfadb83bb0693
                - name: pause
                  ref: dhi/kubernetes-pause:3.10.2-debian13@sha256:c23200da8c68413820169abfb3c4ce799240b13dff49294ca679b0218587d0e4
                - name: kube-scheduler
                  ref: dhi/kube-scheduler:1.36.4-debian13@sha256:77e092821011eb12a2331f998f8e7f69947b402924d4ec62bc41a1653c903d57
                - name: traefik
                  ref: dhi/traefik:3.7.12-debian13@sha256:159329be55fdf7eb0fe5d5abb198b7ada55f16077215a4afdd839bc0c5b801a8
              name: zero-to-jupyterhub-k8s-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/jupyterhub/zero-to-jupyterhub-k8s
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          with:
            chart: .
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: .
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/zero-to-jupyterhub-k8s/config
