# syntax=dhi.io/build:2-helm3

name: Zero to JupyterHub Helm chart 4.x
image: dhi.io/zero-to-jupyterhub-k8s-chart
variant: helm
tags:
  - 4.4.2
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: ec77affd8cf847ad95b2bbcdb57aa17fb5c23c8b
  CHART_HELM_NAME: zero-to-jupyterhub-k8s-chart
  CONFIGURABLE_HTTP_PROXY_REFERENCE: dhi/configurable-http-proxy:5.3.0-debian13@sha256:539b164d4935c3908591bff25ea950da96ea48323aa3a0a7a9341fdecd45bdd7
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_VERSION: 4.1.4-2
  JUPYTERHUB_K8S_HUB_REFERENCE: dhi/jupyterhub-k8s-hub:4.4.2-debian13@sha256:c20eff8892d157ca4f0599b5f7c6ecd48f026d70008d19a31cd85f4bc175ad41
  JUPYTERHUB_K8S_IMAGE_AWAITER_REFERENCE: dhi/jupyterhub-k8s-image-awaiter:4.4.2-alpine3.24@sha256:201046070e707909027cc17f23eb38dc87b31c4f557353261d8bfadb83bb0693
  JUPYTERHUB_K8S_NETWORK_TOOLS_REFERENCE: dhi/jupyterhub-k8s-network-tools:4.4.2-alpine3.24@sha256:6fcef87450cd0b8db0b7fedca9e0f1a1480309a3ccd83f39d1c674ac9b3c030e
  JUPYTERHUB_K8S_SECRET_SYNC_REFERENCE: dhi/jupyterhub-k8s-secret-sync:4.4.2-debian13@sha256:cbfbbbd7d09bf19f0bdc93117911bebca755f0fe56bf41857dc3feb42fd8c365
  JUPYTERHUB_K8S_SINGLEUSER_SAMPLE_REFERENCE: dhi/jupyterhub-k8s-singleuser-sample:4.4.2-debian13-compat@sha256:9d4c2e2c20c45e2505bb519ccf1efde11637ff851cd28b206094e8649150915e
  KUBE_SCHEDULER_REFERENCE: dhi/kube-scheduler:1.36.4-debian13@sha256:69528a7027957fce1449aafaa9dd4fc008a7a9e6aa33ad07d7616280676ffb90
  KUBERNETES_PAUSE_REFERENCE: dhi/kubernetes-pause:3.10.2-debian13@sha256:c23200da8c68413820169abfb3c4ce799240b13dff49294ca679b0218587d0e4
  SEMVER_MAJOR_MINOR_VERSION: "4.4"
  SEMVER_MAJOR_VERSION: "4"
  SEMVER_VERSION: 4.4.2
  TRAEFIK_REFERENCE: dhi/traefik:3.7.13-debian13@sha256:ab68851efd3bc9e63450790b2804f0cb32cb6ad74f9354c6ec5effb7f332229c
  VERSION: 4.4.2
contents:
  repositories:
    - deb [signed-by=/usr/share/keyrings/dhi-deb-main.gpg] http://dhi.io/deb/debian/main trixie main
  keyring:
    - https://dhi.io/keyring/dhi-deb-gpg.D46852F6925E9F71.key
  builds:
    - name: jupyterhub
      work-dir: ${source.dir}/helm-charts/jupyterhub
      contents:
        packages:
          - bash
          - ca-certificates
          - coreutils
          - helm=4.1.4-2
        files:
          - url: git+https://github.com/jupyterhub/zero-to-jupyterhub-k8s.git#4.4.2
            checksum: ec77affd8cf847ad95b2bbcdb57aa17fb5c23c8b
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          with:
            chart:
              appRef: hub
              description: Docker Hardened Images Helm chart for Zero to JupyterHub on Kubernetes
              images:
                - name: hub
                  ref: dhi/jupyterhub-k8s-hub:4.4.2-debian13@sha256:c20eff8892d157ca4f0599b5f7c6ecd48f026d70008d19a31cd85f4bc175ad41
                - name: chp
                  ref: dhi/configurable-http-proxy:5.3.0-debian13@sha256:539b164d4935c3908591bff25ea950da96ea48323aa3a0a7a9341fdecd45bdd7
                - name: secret-sync
                  ref: dhi/jupyterhub-k8s-secret-sync:4.4.2-debian13@sha256:cbfbbbd7d09bf19f0bdc93117911bebca755f0fe56bf41857dc3feb42fd8c365
                - name: network-tools
                  ref: dhi/jupyterhub-k8s-network-tools:4.4.2-alpine3.24@sha256:6fcef87450cd0b8db0b7fedca9e0f1a1480309a3ccd83f39d1c674ac9b3c030e
                - name: singleuser
                  ref: dhi/jupyterhub-k8s-singleuser-sample:4.4.2-debian13-compat@sha256:9d4c2e2c20c45e2505bb519ccf1efde11637ff851cd28b206094e8649150915e
                - name: image-awaiter
                  ref: dhi/jupyterhub-k8s-image-awaiter:4.4.2-alpine3.24@sha256:201046070e707909027cc17f23eb38dc87b31c4f557353261d8bfadb83bb0693
                - name: pause
                  ref: dhi/kubernetes-pause:3.10.2-debian13@sha256:c23200da8c68413820169abfb3c4ce799240b13dff49294ca679b0218587d0e4
                - name: kube-scheduler
                  ref: dhi/kube-scheduler:1.36.4-debian13@sha256:69528a7027957fce1449aafaa9dd4fc008a7a9e6aa33ad07d7616280676ffb90
                - name: traefik
                  ref: dhi/traefik:3.7.13-debian13@sha256:ab68851efd3bc9e63450790b2804f0cb32cb6ad74f9354c6ec5effb7f332229c
              name: zero-to-jupyterhub-k8s-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/jupyterhub/zero-to-jupyterhub-k8s
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          with:
            chart: .
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: .
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/zero-to-jupyterhub-k8s/config
