# syntax=dhi.io/build:2-helm3

name: OpenTelemetry Operator Helm chart 0.x
image: dhi.io/opentelemetry-operator-chart
variant: helm
tags:
  - 0.114.0
platforms:
  - linux/amd64
vars:
  APPVERSION: 0.152.0
  BUSYBOX_REFERENCE: dhi/busybox:1.37.0-debian13@sha256:e0cbe035dd7d7072e088172c5833bf756bfba3618567c0f5e73288e97e3a19bf
  CHART_COMMIT_SHA: 171b8765ebcff26f17a21249e2d627b8b2b2a024
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.21.0-debian13-dev@sha256:6506c914dff9353ce03ce64c8d30089cf14419d8d39f026c53917e1451fb8b21
  OPENTELEMETRY_AUTOINSTRUMENTATION_GO_REFERENCE: dhi/opentelemetry-autoinstrumentation-go:0.24.0-debian13@sha256:3a446f42e3d6d39613bbfd9fc251a3075449cac9d94dc8104597919726a3e8b2
  OPENTELEMETRY_COLLECTOR_REFERENCE: dhi/opentelemetry-collector:0.152.0-debian13@sha256:61185817248ede0c9a30d8b7832f6ffdd402e1f9813b9832b8bccbfe80b8278a
  OPENTELEMETRY_OPERATOR_REFERENCE: dhi/opentelemetry-operator:0.152.0-debian13@sha256:5af4311b37df909c857361b7cefcee4963a0c629f7d71b23fdbc725a606e9472
  SEMVER_MAJOR_MINOR_VERSION: "0.114"
  SEMVER_MAJOR_VERSION: "0"
  SEMVER_VERSION: 0.114.0
  VERSION: 0.114.0
contents:
  builds:
    - name: opentelemetry-operator
      uses: dhi.io/helm:3.21.0-debian13-dev@sha256:6506c914dff9353ce03ce64c8d30089cf14419d8d39f026c53917e1451fb8b21
      work-dir: ${source.dir}/helm-charts/charts/opentelemetry-operator
      contents:
        files:
          - url: git+https://github.com/open-telemetry/opentelemetry-helm-charts.git#opentelemetry-operator-0.114.0
            checksum: 171b8765ebcff26f17a21249e2d627b8b2b2a024
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          with:
            chart:
              appRef: opentelemetry-operator
              description: Docker Hardened Images Helm chart for OpenTelemetry Operator
              images:
                - name: opentelemetry-operator
                  ref: dhi/opentelemetry-operator:0.152.0-debian13@sha256:5af4311b37df909c857361b7cefcee4963a0c629f7d71b23fdbc725a606e9472
                - name: opentelemetry-collector
                  ref: dhi/opentelemetry-collector:0.152.0-debian13@sha256:61185817248ede0c9a30d8b7832f6ffdd402e1f9813b9832b8bccbfe80b8278a
                - name: busybox
                  ref: dhi/busybox:1.37.0-debian13@sha256:e0cbe035dd7d7072e088172c5833bf756bfba3618567c0f5e73288e97e3a19bf
                - name: opentelemetry-autoinstrumentation-go
                  ref: dhi/opentelemetry-autoinstrumentation-go:0.24.0-debian13@sha256:3a446f42e3d6d39613bbfd9fc251a3075449cac9d94dc8104597919726a3e8b2
              name: opentelemetry-operator-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/open-telemetry/opentelemetry-helm-charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          with:
            chart: .
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: .
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/opentelemetry-operator/config
