# syntax=dhi.io/build:2-helm3

name: OpenTelemetry Operator Helm chart 0.x
image: dhi.io/opentelemetry-operator-chart
variant: helm
tags:
  - 0.123.0
platforms:
  - linux/amd64
vars:
  APPVERSION: 0.159.0
  BUSYBOX_REFERENCE: dhi/busybox:1.37.0-debian13@sha256:abcd06d567c6ecda4aae78cff5334a231bd3e663b69b671612566d4a4c949899
  CHART_COMMIT_SHA: 6dfe19bd2203f1e51e97075e8ac9199764f9fdd9
  CHART_HELM_NAME: opentelemetry-operator-chart
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_VERSION: 4.1.4-2
  OPENTELEMETRY_AUTOINSTRUMENTATION_GO_REFERENCE: dhi/opentelemetry-autoinstrumentation-go:0.24.0-debian13@sha256:e7d018d2f459f09c269c0a9eb4ced87e258a3b713eff716b9408aee568df04fd
  OPENTELEMETRY_COLLECTOR_REFERENCE: dhi/opentelemetry-collector:0.159.0-debian13@sha256:639ce4e311cb9d18228b49588f76bbe8c73feba07898d6fe34f2beaef94c2877
  OPENTELEMETRY_OPERATOR_REFERENCE: dhi/opentelemetry-operator:0.159.0-debian13@sha256:1e1044dbc589c042e11301f509576746463bf8c11075a83f45963892b45309fb
  SEMVER_MAJOR_MINOR_VERSION: "0.123"
  SEMVER_MAJOR_VERSION: "0"
  SEMVER_VERSION: 0.123.0
  VERSION: 0.123.0
contents:
  repositories:
    - deb [signed-by=/usr/share/keyrings/dhi-deb-main.gpg] http://dhi.io/deb/debian/main trixie main
  keyring:
    - https://dhi.io/keyring/dhi-deb-gpg.D46852F6925E9F71.key
  builds:
    - name: opentelemetry-operator
      work-dir: ${source.dir}/helm-charts/charts/opentelemetry-operator
      contents:
        packages:
          - bash
          - ca-certificates
          - coreutils
          - helm=4.1.4-2
        files:
          - url: git+https://github.com/open-telemetry/opentelemetry-helm-charts.git#opentelemetry-operator-0.123.0
            checksum: 6dfe19bd2203f1e51e97075e8ac9199764f9fdd9
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          with:
            chart:
              appRef: opentelemetry-operator
              description: Docker Hardened Images Helm chart for OpenTelemetry Operator
              images:
                - name: opentelemetry-operator
                  ref: dhi/opentelemetry-operator:0.159.0-debian13@sha256:1e1044dbc589c042e11301f509576746463bf8c11075a83f45963892b45309fb
                - name: opentelemetry-collector
                  ref: dhi/opentelemetry-collector:0.159.0-debian13@sha256:639ce4e311cb9d18228b49588f76bbe8c73feba07898d6fe34f2beaef94c2877
                - name: busybox
                  ref: dhi/busybox:1.37.0-debian13@sha256:abcd06d567c6ecda4aae78cff5334a231bd3e663b69b671612566d4a4c949899
                - name: opentelemetry-autoinstrumentation-go
                  ref: dhi/opentelemetry-autoinstrumentation-go:0.24.0-debian13@sha256:e7d018d2f459f09c269c0a9eb4ced87e258a3b713eff716b9408aee568df04fd
              name: opentelemetry-operator-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/open-telemetry/opentelemetry-helm-charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          with:
            chart: .
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: .
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/opentelemetry-operator/config
