# syntax=dhi.io/build:2-helm3

name: Goldilocks Helm chart 10.x
image: dhi.io/goldilocks-chart
variant: helm
tags:
  - 10.4.0
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: a20eff7ed5e98de4220b78aedded825447b7cd25
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  FAIRWINDS_VPA_CHART_REFERENCE: dhi/fairwinds-vpa-chart:4.12.2@sha256:44616eed917b77196179a6be611c89b472fa9092d113b5428fc571d63cc18659
  GOLDILOCKS_REFERENCE: dhi/goldilocks:4.15.1-debian13@sha256:22388f874c7ccd87fb953532264cf0419819ff42c647a43fe72135ba0464c1ea
  HELM_REFERENCE: dhi/helm:3.21.2-debian13-dev@sha256:44218c50feae45f17602aa1b67db039b70881c9275057ce0647f6d50d3def16e
  METRICS_SERVER_CHART_REFERENCE: dhi/metrics-server-chart:3.13.1@sha256:7d5d2ac450874b86ddf47ee9ed920ebe8eefa2380e75e77088922b8504bcfaf4
  SEMVER_MAJOR_MINOR_VERSION: "10.4"
  SEMVER_MAJOR_VERSION: "10"
  SEMVER_VERSION: 10.4.0
  VERSION: 10.4.0
contents:
  builds:
    - name: goldilocks-chart
      uses: dhi.io/helm:3.21.2-debian13-dev@sha256:44218c50feae45f17602aa1b67db039b70881c9275057ce0647f6d50d3def16e
      contents:
        files:
          - url: git+https://github.com/FairwindsOps/charts.git#a20eff7ed5e98de4220b78aedded825447b7cd25
            checksum: a20eff7ed5e98de4220b78aedded825447b7cd25
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/stable/goldilocks
          with:
            chart:
              appRef: goldilocks
              dependencies:
                - alias: metrics-server
                  condition: metrics-server.enabled
                  name: metrics-server
                  ref: dhi/metrics-server-chart:3.13.1@sha256:7d5d2ac450874b86ddf47ee9ed920ebe8eefa2380e75e77088922b8504bcfaf4
                - alias: vpa
                  condition: vpa.enabled
                  name: vpa
                  ref: dhi/fairwinds-vpa-chart:4.12.2@sha256:44616eed917b77196179a6be611c89b472fa9092d113b5428fc571d63cc18659
              description: Docker Hardened Images Helm chart for Goldilocks
              images:
                - name: goldilocks
                  ref: dhi/goldilocks:4.15.1-debian13@sha256:22388f874c7ccd87fb953532264cf0419819ff42c647a43fe72135ba0464c1ea
              name: goldilocks-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/FairwindsOps/charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/stable/goldilocks
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: helm login
          uses: helm/login@v1
          with:
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/stable
          privileged: true
          with:
            chart: goldilocks
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/stable
          with:
            chart: goldilocks
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/stable
          with:
            chart: goldilocks
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/goldilocks/config
