# syntax=dhi.io/build:2-helm3

name: Flux Helm chart 2.x
image: dhi.io/flux-chart
variant: helm
tags:
  - 2.18.4
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: 3ed91bfd691e1780e94a47ed6cc244218fea4f17
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  FLUX_CLI_REFERENCE: dhi/flux-cli:2.8.8-debian13@sha256:8e0b4023c7d19d4ef7edfa0cd5053d872c500f1de112d74a6c57a000f8696481
  HELM_CONTROLLER_REFERENCE: dhi/fluxcd-helm-controller:1.5.5-debian13@sha256:a543c6c08d348879b536ee8c0846fb25c35560a3b57e6ebbc1c00e79245afb81
  HELM_REFERENCE: dhi/helm:3.21.2-debian13-dev@sha256:2d07671ccc209a0a3e1082dcd0375511e57b8ad6a18439c74924f203d63a461c
  IMAGE_AUTOMATION_CONTROLLER_REFERENCE: dhi/fluxcd-image-automation-controller:1.2.0-debian13@sha256:0d85a3e76cb5ec4500f32fc91a502316d0a7172c059f2be77e80518215552e58
  IMAGE_REFLECTOR_CONTROLLER_REFERENCE: dhi/fluxcd-image-reflector-controller:1.2.0-debian13@sha256:e04384514e2f48c48e05e4903355f1e826cd024d8ea6254901d3873d566f9c5b
  KUSTOMIZE_CONTROLLER_REFERENCE: dhi/fluxcd-kustomize-controller:1.9.0-debian13@sha256:1b69d12b089d7f08eb8ab06b8cfb3ddcda118f8feaf232ac8368a8169a1630db
  NOTIFICATION_CONTROLLER_REFERENCE: dhi/fluxcd-notification-controller:1.8.4-debian13@sha256:0bd93ea31a88f96671b60d172c04e9547f043a0c40f647c5ead104f6fee3869f
  SEMVER_MAJOR_MINOR_VERSION: "2.18"
  SEMVER_MAJOR_VERSION: "2"
  SEMVER_VERSION: 2.18.4
  SOURCE_CONTROLLER_REFERENCE: dhi/fluxcd-source-controller:1.8.5-debian13@sha256:0f4bce0baf73f6305528cd269397c6c7703bcb6bb5f7cf07920e82d3df3af284
  SOURCE_WATCHER_REFERENCE: dhi/fluxcd-source-watcher:2.1.1-debian13@sha256:31e10d71d4fa4f8097e3edd6d621d77259586ac4640e5f2ab7058cf3b6115bc0
  VERSION: 2.18.4
contents:
  builds:
    - name: flux-chart
      uses: dhi.io/helm:3.21.2-debian13-dev@sha256:2d07671ccc209a0a3e1082dcd0375511e57b8ad6a18439c74924f203d63a461c
      work-dir: ${source.dir}/helm-charts/charts/flux2
      contents:
        files:
          - url: git+https://github.com/fluxcd-community/helm-charts.git#flux2-2.18.4
            checksum: 3ed91bfd691e1780e94a47ed6cc244218fea4f17
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          with:
            chart:
              appRef: flux-cli
              description: Docker Hardened Images Helm chart for Flux
              images:
                - name: flux-cli
                  ref: dhi/flux-cli:2.8.8-debian13@sha256:8e0b4023c7d19d4ef7edfa0cd5053d872c500f1de112d74a6c57a000f8696481
                - name: fluxcd-helm-controller
                  ref: dhi/fluxcd-helm-controller:1.5.5-debian13@sha256:a543c6c08d348879b536ee8c0846fb25c35560a3b57e6ebbc1c00e79245afb81
                - name: fluxcd-image-automation-controller
                  ref: dhi/fluxcd-image-automation-controller:1.2.0-debian13@sha256:0d85a3e76cb5ec4500f32fc91a502316d0a7172c059f2be77e80518215552e58
                - name: fluxcd-image-reflector-controller
                  ref: dhi/fluxcd-image-reflector-controller:1.2.0-debian13@sha256:e04384514e2f48c48e05e4903355f1e826cd024d8ea6254901d3873d566f9c5b
                - name: fluxcd-kustomize-controller
                  ref: dhi/fluxcd-kustomize-controller:1.9.0-debian13@sha256:1b69d12b089d7f08eb8ab06b8cfb3ddcda118f8feaf232ac8368a8169a1630db
                - name: fluxcd-notification-controller
                  ref: dhi/fluxcd-notification-controller:1.8.4-debian13@sha256:0bd93ea31a88f96671b60d172c04e9547f043a0c40f647c5ead104f6fee3869f
                - name: fluxcd-source-controller
                  ref: dhi/fluxcd-source-controller:1.8.5-debian13@sha256:0f4bce0baf73f6305528cd269397c6c7703bcb6bb5f7cf07920e82d3df3af284
                - name: fluxcd-source-watcher
                  ref: dhi/fluxcd-source-watcher:2.1.1-debian13@sha256:31e10d71d4fa4f8097e3edd6d621d77259586ac4640e5f2ab7058cf3b6115bc0
              name: flux-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/fluxcd/flux2
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          with:
            chart: .
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: .
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/flux/config
