# syntax=dhi.io/build:2-helm3

name: Flux Helm chart 2.x
image: dhi.io/flux-chart
variant: helm
tags:
  - 2.19.0
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: b2c8e7838dd7902b6f7b4925e2d611c756858fc8
  CHART_HELM_NAME: flux-chart
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  FLUX_CLI_REFERENCE: dhi/flux-cli:2.9.3-debian13@sha256:4ae3ad994152cb383b02f00016e996c21053fe4548023a8865652999acb72a68
  FLUXCD_HELM_CONTROLLER_REFERENCE: dhi/fluxcd-helm-controller:1.6.3-debian13@sha256:d84e71aed67df650f8db9f171a43d3cd5441ad99ee19765c98f54da0222e341b
  FLUXCD_IMAGE_AUTOMATION_CONTROLLER_REFERENCE: dhi/fluxcd-image-automation-controller:1.2.3-debian13@sha256:b62269d8510231f707733cf08f4318ea58ae8edcb981fdf89af78736d9139807
  FLUXCD_IMAGE_REFLECTOR_CONTROLLER_REFERENCE: dhi/fluxcd-image-reflector-controller:1.2.3-debian13@sha256:71270c853793bc7f4204a63fb177ccf2effc0cd8c4c38c7a0f6b01c5c8ef5bd7
  FLUXCD_KUSTOMIZE_CONTROLLER_REFERENCE: dhi/fluxcd-kustomize-controller:1.9.4-debian13@sha256:5024a9d8055b1131e66670a8ce38768739831386935ecc155ca3a778490b1c1a
  FLUXCD_NOTIFICATION_CONTROLLER_REFERENCE: dhi/fluxcd-notification-controller:1.9.2-debian13@sha256:6ac1cf092f99fe29739bad7b6f59c450e75b091a5e8d8ad4e9d58586703caec9
  FLUXCD_SOURCE_CONTROLLER_REFERENCE: dhi/fluxcd-source-controller:1.9.3-debian13@sha256:156f6d4b3783b18b35d2cd3d49cf1842deb2ace2b93b4e3c5fa761aa7e94ed9b
  FLUXCD_SOURCE_WATCHER_REFERENCE: dhi/fluxcd-source-watcher:2.2.2-debian13@sha256:f67ae13d3e21c4e5b623415641a7781bec66bec987db8dc33a7a40a1d6a96e24
  HELM_VERSION: 4.1.4-2
  SEMVER_MAJOR_MINOR_VERSION: "2.19"
  SEMVER_MAJOR_VERSION: "2"
  SEMVER_VERSION: 2.19.0
  VERSION: 2.19.0
contents:
  repositories:
    - deb [signed-by=/usr/share/keyrings/dhi-deb-main.gpg] http://dhi.io/deb/debian/main trixie main
  keyring:
    - https://dhi.io/keyring/dhi-deb-gpg.D46852F6925E9F71.key
  builds:
    - name: flux-chart
      work-dir: ${source.dir}/helm-charts/charts/flux2
      contents:
        packages:
          - bash
          - ca-certificates
          - coreutils
          - helm=4.1.4-2
        files:
          - url: git+https://github.com/fluxcd-community/helm-charts.git#flux2-2.19.0
            checksum: b2c8e7838dd7902b6f7b4925e2d611c756858fc8
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          with:
            chart:
              appRef: flux-cli
              description: Docker Hardened Images Helm chart for Flux
              images:
                - name: flux-cli
                  ref: dhi/flux-cli:2.9.3-debian13@sha256:4ae3ad994152cb383b02f00016e996c21053fe4548023a8865652999acb72a68
                - name: fluxcd-helm-controller
                  ref: dhi/fluxcd-helm-controller:1.6.3-debian13@sha256:d84e71aed67df650f8db9f171a43d3cd5441ad99ee19765c98f54da0222e341b
                - name: fluxcd-image-automation-controller
                  ref: dhi/fluxcd-image-automation-controller:1.2.3-debian13@sha256:b62269d8510231f707733cf08f4318ea58ae8edcb981fdf89af78736d9139807
                - name: fluxcd-image-reflector-controller
                  ref: dhi/fluxcd-image-reflector-controller:1.2.3-debian13@sha256:71270c853793bc7f4204a63fb177ccf2effc0cd8c4c38c7a0f6b01c5c8ef5bd7
                - name: fluxcd-kustomize-controller
                  ref: dhi/fluxcd-kustomize-controller:1.9.4-debian13@sha256:5024a9d8055b1131e66670a8ce38768739831386935ecc155ca3a778490b1c1a
                - name: fluxcd-notification-controller
                  ref: dhi/fluxcd-notification-controller:1.9.2-debian13@sha256:6ac1cf092f99fe29739bad7b6f59c450e75b091a5e8d8ad4e9d58586703caec9
                - name: fluxcd-source-controller
                  ref: dhi/fluxcd-source-controller:1.9.3-debian13@sha256:156f6d4b3783b18b35d2cd3d49cf1842deb2ace2b93b4e3c5fa761aa7e94ed9b
                - name: fluxcd-source-watcher
                  ref: dhi/fluxcd-source-watcher:2.2.2-debian13@sha256:f67ae13d3e21c4e5b623415641a7781bec66bec987db8dc33a7a40a1d6a96e24
              name: flux-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/fluxcd/flux2
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          with:
            chart: .
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: .
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/flux/config
