# syntax=dhi.io/build:2-helm3

name: Flux Helm chart 2.x
image: dhi.io/flux-chart
variant: helm
tags:
  - 2.19.0
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: b2c8e7838dd7902b6f7b4925e2d611c756858fc8
  CHART_HELM_NAME: flux-chart
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  FLUX_CLI_REFERENCE: dhi/flux-cli:2.9.5-debian13@sha256:a30544a5eb14455a2ef1fbd0697c21e256b756af664c3bdeafbf9edac6277888
  FLUXCD_HELM_CONTROLLER_REFERENCE: dhi/fluxcd-helm-controller:1.6.4-debian13@sha256:754e66ac675c7e3380ad80e73895c681c49107ed768c35ab75d3aa13e28f2f95
  FLUXCD_IMAGE_AUTOMATION_CONTROLLER_REFERENCE: dhi/fluxcd-image-automation-controller:1.2.5-debian13@sha256:61da7f2b310d727659043a6f7b511d519cfb851b05f704cf1f452d990eb3da43
  FLUXCD_IMAGE_REFLECTOR_CONTROLLER_REFERENCE: dhi/fluxcd-image-reflector-controller:1.2.5-debian13@sha256:b393743c546e80b9fdf3568f46d6f56b5933321d35b06721de63ecdca38651ec
  FLUXCD_KUSTOMIZE_CONTROLLER_REFERENCE: dhi/fluxcd-kustomize-controller:1.9.5-debian13@sha256:10c0025f5e305e0045e5fb013e75f34e1e98904f21942fb8a63c39f19b701a0c
  FLUXCD_NOTIFICATION_CONTROLLER_REFERENCE: dhi/fluxcd-notification-controller:1.9.4-debian13@sha256:50def92286ee676b35110bf4910d657cb441a809cf62fa537a928f6ac7e7d085
  FLUXCD_SOURCE_CONTROLLER_REFERENCE: dhi/fluxcd-source-controller:1.9.5-debian13@sha256:00cda2a54b850559bafcaf9648cc7edfb1fd6d30868a2fdff2cd58879883602f
  FLUXCD_SOURCE_WATCHER_REFERENCE: dhi/fluxcd-source-watcher:2.2.4-debian13@sha256:3bf59c3d7268de3dce190940077d7893e379ef82f84da9eacd7f03f628ab74ca
  HELM_VERSION: 4.1.4-2
  SEMVER_MAJOR_MINOR_VERSION: "2.19"
  SEMVER_MAJOR_VERSION: "2"
  SEMVER_VERSION: 2.19.0
  VERSION: 2.19.0
contents:
  repositories:
    - deb [signed-by=/usr/share/keyrings/dhi-deb-main.gpg] http://dhi.io/deb/debian/main trixie main
  keyring:
    - https://dhi.io/keyring/dhi-deb-gpg.D46852F6925E9F71.key
  builds:
    - name: flux-chart
      work-dir: ${source.dir}/helm-charts/charts/flux2
      contents:
        packages:
          - bash
          - ca-certificates
          - coreutils
          - helm=4.1.4-2
        files:
          - url: git+https://github.com/fluxcd-community/helm-charts.git#flux2-2.19.0
            checksum: b2c8e7838dd7902b6f7b4925e2d611c756858fc8
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          with:
            chart:
              appRef: flux-cli
              description: Docker Hardened Images Helm chart for Flux
              images:
                - name: flux-cli
                  ref: dhi/flux-cli:2.9.5-debian13@sha256:a30544a5eb14455a2ef1fbd0697c21e256b756af664c3bdeafbf9edac6277888
                - name: fluxcd-helm-controller
                  ref: dhi/fluxcd-helm-controller:1.6.4-debian13@sha256:754e66ac675c7e3380ad80e73895c681c49107ed768c35ab75d3aa13e28f2f95
                - name: fluxcd-image-automation-controller
                  ref: dhi/fluxcd-image-automation-controller:1.2.5-debian13@sha256:61da7f2b310d727659043a6f7b511d519cfb851b05f704cf1f452d990eb3da43
                - name: fluxcd-image-reflector-controller
                  ref: dhi/fluxcd-image-reflector-controller:1.2.5-debian13@sha256:b393743c546e80b9fdf3568f46d6f56b5933321d35b06721de63ecdca38651ec
                - name: fluxcd-kustomize-controller
                  ref: dhi/fluxcd-kustomize-controller:1.9.5-debian13@sha256:10c0025f5e305e0045e5fb013e75f34e1e98904f21942fb8a63c39f19b701a0c
                - name: fluxcd-notification-controller
                  ref: dhi/fluxcd-notification-controller:1.9.4-debian13@sha256:50def92286ee676b35110bf4910d657cb441a809cf62fa537a928f6ac7e7d085
                - name: fluxcd-source-controller
                  ref: dhi/fluxcd-source-controller:1.9.5-debian13@sha256:00cda2a54b850559bafcaf9648cc7edfb1fd6d30868a2fdff2cd58879883602f
                - name: fluxcd-source-watcher
                  ref: dhi/fluxcd-source-watcher:2.2.4-debian13@sha256:3bf59c3d7268de3dce190940077d7893e379ef82f84da9eacd7f03f628ab74ca
              name: flux-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/fluxcd/flux2
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          with:
            chart: .
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: .
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/flux/config
