# syntax=dhi.io/build:2-helm3

name: Opencost Helm chart 2.x
image: dhi.io/opencost-chart
variant: helm
tags:
  - 2.5.21
platforms:
  - linux/amd64
vars:
  APPVERSION: 1.120.2
  AWS_SIGV4_PROXY_IMAGE_REFERENCE: dhi/aws-sigv4-proxy:1.11.1-debian13@sha256:242c3ffdaf0648304f1e75bda46f7d1543c8a4602421966ad320d54f06f2bed6
  CHART_COMMIT_SHA: e57ce64e64c39075fe2e04ff2cd5012a7a56dec4
  CURL_IMAGE_REFERENCE: dhi/curl:8.14.1-debian13@sha256:cf9eef6aba4db36f3faa5e4f1c881fc30dca9e7ee8697744c1d647d92e7f184b
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.21.0-debian13-dev@sha256:e3d7fb6de37608485fd22d3dd04ed6b0f9cc68431cb21697c2383978e2847ed2
  OPENCOST_IMAGE_REFERENCE: dhi/opencost:1.120.2-debian13@sha256:7bd66b62f8d745ca8789b7bf19f6e78515acd44df2388e353aaf8252841f43a8
  OPENCOST_UI_IMAGE_REFERENCE: dhi/opencost-ui:1.120.2-debian13@sha256:f7a95016cc5494f47a6a6573f6328e15b5318ac5731c0dd4bae137784d3d8b53
  SEMVER_MAJOR_MINOR_VERSION: "2.5"
  SEMVER_MAJOR_VERSION: "2"
  SEMVER_VERSION: 2.5.21
  VERSION: 2.5.21
contents:
  builds:
    - name: opencost-chart
      uses: dhi.io/helm:3.21.0-debian13-dev@sha256:e3d7fb6de37608485fd22d3dd04ed6b0f9cc68431cb21697c2383978e2847ed2
      work-dir: ${source.dir}/helm-charts/charts/opencost
      contents:
        files:
          - url: git+https://github.com/opencost/opencost-helm-chart.git#opencost-2.5.21
            checksum: e57ce64e64c39075fe2e04ff2cd5012a7a56dec4
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/opencost
          with:
            chart:
              appRef: opencost
              description: Docker Hardened Images Helm chart for Opencost
              images:
                - name: opencost
                  ref: dhi/opencost:1.120.2-debian13@sha256:7bd66b62f8d745ca8789b7bf19f6e78515acd44df2388e353aaf8252841f43a8
                - name: opencost-ui
                  ref: dhi/opencost-ui:1.120.2-debian13@sha256:f7a95016cc5494f47a6a6573f6328e15b5318ac5731c0dd4bae137784d3d8b53
                - name: aws-sigv4-proxy
                  ref: dhi/aws-sigv4-proxy:1.11.1-debian13@sha256:242c3ffdaf0648304f1e75bda46f7d1543c8a4602421966ad320d54f06f2bed6
                - name: curl
                  ref: dhi/curl:8.14.1-debian13@sha256:cf9eef6aba4db36f3faa5e4f1c881fc30dca9e7ee8697744c1d647d92e7f184b
              name: opencost-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/opencost/opencost
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          with:
            chart: .
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: .
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/opencost/config
