# syntax=dhi.io/build:2-helm3

name: Opencost Helm chart 2.x
image: dhi.io/opencost-chart
variant: helm
tags:
  - 2.5.32
platforms:
  - linux/amd64
vars:
  APPVERSION: 1.121.3
  AWS_SIGV4_PROXY_REFERENCE: dhi/aws-sigv4-proxy:1.11.1-debian13@sha256:3c8ccbf4f4707a5b07639523268e05cbf921c35735570155309e1639db0ea7dc
  CHART_COMMIT_SHA: b015eaaf94a7b4c837812d3441ef059c4d8b80a8
  CHART_HELM_NAME: opencost-chart
  CURL_REFERENCE: dhi/curl:8.14.1-debian13@sha256:941ad5150dee5c1662176761f36aee068cacfc75c299455b9e10c41b197e706c
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_VERSION: 4.1.4-2
  OPENCOST_REFERENCE: dhi/opencost:1.121.3-debian13@sha256:fffe4127179d73c41f285b4d7ce39427fd9f3237d261e6a4f5f7df6051dcf74e
  OPENCOST_UI_REFERENCE: dhi/opencost-ui:1.121.3-debian13@sha256:19a7d8333676087cc5405ff3dc3fa5ea0df414cc1d5f13c66d8e88b698af6047
  SEMVER_MAJOR_MINOR_VERSION: "2.5"
  SEMVER_MAJOR_VERSION: "2"
  SEMVER_VERSION: 2.5.32
  VERSION: 2.5.32
contents:
  repositories:
    - deb [signed-by=/usr/share/keyrings/dhi-deb-main.gpg] http://dhi.io/deb/debian/main trixie main
  keyring:
    - https://dhi.io/keyring/dhi-deb-gpg.D46852F6925E9F71.key
  builds:
    - name: opencost-chart
      work-dir: ${source.dir}/helm-charts/charts/opencost
      contents:
        packages:
          - bash
          - ca-certificates
          - coreutils
          - helm=4.1.4-2
        files:
          - url: git+https://github.com/opencost/opencost-helm-chart.git#opencost-2.5.32
            checksum: b015eaaf94a7b4c837812d3441ef059c4d8b80a8
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/opencost
          with:
            chart:
              appRef: opencost
              description: Docker Hardened Images Helm chart for Opencost
              images:
                - name: opencost
                  ref: dhi/opencost:1.121.3-debian13@sha256:fffe4127179d73c41f285b4d7ce39427fd9f3237d261e6a4f5f7df6051dcf74e
                - name: opencost-ui
                  ref: dhi/opencost-ui:1.121.3-debian13@sha256:19a7d8333676087cc5405ff3dc3fa5ea0df414cc1d5f13c66d8e88b698af6047
                - name: aws-sigv4-proxy
                  ref: dhi/aws-sigv4-proxy:1.11.1-debian13@sha256:3c8ccbf4f4707a5b07639523268e05cbf921c35735570155309e1639db0ea7dc
                - name: curl
                  ref: dhi/curl:8.14.1-debian13@sha256:941ad5150dee5c1662176761f36aee068cacfc75c299455b9e10c41b197e706c
              name: opencost-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/opencost/opencost
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          with:
            chart: .
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: .
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/opencost/config
