# syntax=dhi.io/build:2-helm3

name: Opencost Helm chart 2.x
image: dhi.io/opencost-chart
variant: helm
tags:
  - 2.5.23
platforms:
  - linux/amd64
vars:
  APPVERSION: 1.120.3
  AWS_SIGV4_PROXY_IMAGE_REFERENCE: dhi/aws-sigv4-proxy:1.11.1-debian13@sha256:7bb25a49c60fa380b05380a3f36bc1d6bb2c27dbfdcdb156f13d9692b120dcf2
  CHART_COMMIT_SHA: 7d6f0c8626dca9f4b8119558c14cc983fa177a64
  CURL_IMAGE_REFERENCE: dhi/curl:8.14.1-debian13@sha256:53cb07c0702c04c750fd2c58641b81766603917aebab571b3bb739d24464f1e3
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.21.0-debian13-dev@sha256:7c201a9174a2b56cb13136f19d87b23309d09eb2fc8a24e8c08a31ebd907a943
  OPENCOST_IMAGE_REFERENCE: dhi/opencost:1.120.3-debian13@sha256:d2be32d5d9796c4b30c9529338a6843bba40450e9035158121d1b4f2c67c6ffe
  OPENCOST_UI_IMAGE_REFERENCE: dhi/opencost-ui:1.120.3-debian13@sha256:aa447eec9e5663fa0462047e2c31db1cca2bd8b476e9a09c05dba7870361412b
  SEMVER_MAJOR_MINOR_VERSION: "2.5"
  SEMVER_MAJOR_VERSION: "2"
  SEMVER_VERSION: 2.5.23
  VERSION: 2.5.23
contents:
  builds:
    - name: opencost-chart
      uses: dhi.io/helm:3.21.0-debian13-dev@sha256:7c201a9174a2b56cb13136f19d87b23309d09eb2fc8a24e8c08a31ebd907a943
      work-dir: ${source.dir}/helm-charts/charts/opencost
      contents:
        files:
          - url: git+https://github.com/opencost/opencost-helm-chart.git#opencost-2.5.23
            checksum: 7d6f0c8626dca9f4b8119558c14cc983fa177a64
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/opencost
          with:
            chart:
              appRef: opencost
              description: Docker Hardened Images Helm chart for Opencost
              images:
                - name: opencost
                  ref: dhi/opencost:1.120.3-debian13@sha256:d2be32d5d9796c4b30c9529338a6843bba40450e9035158121d1b4f2c67c6ffe
                - name: opencost-ui
                  ref: dhi/opencost-ui:1.120.3-debian13@sha256:aa447eec9e5663fa0462047e2c31db1cca2bd8b476e9a09c05dba7870361412b
                - name: aws-sigv4-proxy
                  ref: dhi/aws-sigv4-proxy:1.11.1-debian13@sha256:7bb25a49c60fa380b05380a3f36bc1d6bb2c27dbfdcdb156f13d9692b120dcf2
                - name: curl
                  ref: dhi/curl:8.14.1-debian13@sha256:53cb07c0702c04c750fd2c58641b81766603917aebab571b3bb739d24464f1e3
              name: opencost-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/opencost/opencost
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          with:
            chart: .
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: .
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/opencost/config
