name: Feature Request
description: Suggest a new feature or improvement for Docker Hardened Images
title: "[feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please provide detailed information to help us understand your proposal.

  - type: input
    id: image
    attributes:
      label: Target Image(s)
      description: Which hardened image(s) would this feature apply to?
      placeholder: e.g., nginx-hardened, all images, new image for Apache
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What's the motivation?
      placeholder: Describe the problem or use case this feature would address...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution in detail
      placeholder: What would you like to happen? How should this feature work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative solutions or workarounds?
      placeholder: Describe any alternative solutions or features you've considered...

  - type: textarea
    id: benefits
    attributes:
      label: Benefits
      description: How would this feature benefit the community?
      placeholder: |
        - Improves security by...
        - Reduces complexity by...
        - Enables new use cases such as...

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Important for my use case
        - Critical - Blocking my adoption
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas
      description: Do you have ideas about how this could be implemented?
      placeholder: Any thoughts on implementation approach, technical considerations, etc.

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues to ensure this feature hasn't been requested before
          required: true
        - label: This feature request is related to Docker Hardened Images
          required: true
        - label: I have provided sufficient detail about the proposed feature
          required: true
