name: Image Request
description: Request a new image or Helm chart for Docker Hardened Images
title: "[image]: "
labels: ["image", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for your interest in Docker Hardened Images! Please provide as much detail as possible to help us understand your request.

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: What are you requesting?
      options:
        - Package
        - Image
        - Helm Chart
  
  - type: input
    id: image
    attributes:
      label: Package/Image/Chart Name
      description: Which package, image or Helm chart are you requesting?
      placeholder: e.g., nginx, python, external-dns, binutils
    validations:
      required: true
    
  - type: input
    id: versions
    attributes:
      label: Versions
      description: Which versions of the package, image or Helm chart are you requesting?
      placeholder: e.g., 1.0.0, 2.0.0
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Details
      description: Provide links to upstream Dockerfile, source repository and public Docker image
      placeholder: |
        Source Repository: <URL>
        Dockerfile: <URL>
        Docker Image: <registry/image:tag>
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues to ensure this image, package or Helm chart hasn't been requested before
          required: true
        - label: I have provided all the requested information above
          required: true
