name: Question or Help
description: Ask a question about Docker Hardened Images
title: "[Question]: "
labels: ["question", "help-wanted"]
body:
  - type: markdown
    attributes:
      value: |
        Have a question? We're here to help! Please provide as much context as possible.
        
        💡 **Tip**: Consider using [GitHub Discussions](https://github.com/docker-hardened-images/discussion/discussions) for general questions and community interaction.

  - type: input
    id: image
    attributes:
      label: Related Image(s)
      description: Which hardened image(s) is your question about?
      placeholder: e.g., nginx-hardened, alpine-hardened, general question
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Question Category
      description: What type of question is this?
      options:
        - Configuration - How to configure or customize
        - Deployment - How to deploy or orchestrate
        - Security - Security-related questions
        - Best Practices - Recommendations and best practices
        - Troubleshooting - Having issues or errors
        - Comparison - Comparing with other images
        - Documentation - Questions about documentation
        - Other - General questions
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: Please describe your question in detail...
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context and Background
      description: Provide context about your use case, what you're trying to achieve, etc.
      placeholder: |
        - What are you trying to accomplish?
        - What's your current setup?
        - Any constraints or requirements?

  - type: textarea
    id: attempted
    attributes:
      label: What Have You Tried?
      description: What approaches have you already attempted?
      placeholder: |
        - Searched documentation
        - Tried configuration X
        - Looked at similar issues

  - type: textarea
    id: environment
    attributes:
      label: Environment (if relevant)
      description: Your environment details if relevant to the question
      placeholder: |
        - OS: 
        - Docker Version: 
        - Orchestration Platform:
        - Current Image Version:

  - type: checkboxes
    id: checklist
    attributes:
      label: Question Checklist
      options:
        - label: I have searched existing issues and discussions for similar questions
          required: true
        - label: I have provided sufficient context for my question
          required: true
        - label: This question is related to Docker Hardened Images
          required: true