# syntax=dhi.io/build:2-helm3

name: Grafana Alloy Helm chart 1.x
image: dhi.io/alloy-chart
variant: helm
tags:
  - 1.11.0
platforms:
  - linux/amd64
vars:
  ALLOY_REFERENCE: dhi/alloy:1.18.0-debian13@sha256:e088aba1bf8eed94f711b521d8a83c8f538ee6e1c504d7365106e540e5c28e22
  CHART_COMMIT_SHA: 6a3d2e39422c25361f63ab9d4a072502863db466
  CHART_HELM_NAME: alloy-chart
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_VERSION: 4.1.4-2
  PROMETHEUS_CONFIG_RELOADER_REFERENCE: dhi/prometheus-config-reloader:0.93.0-debian13@sha256:4cca6ce2a0d854ffef9da6d171044e254572dfca98224d5edd97c5a27f594453
  SEMVER_MAJOR_MINOR_VERSION: "1.11"
  SEMVER_MAJOR_VERSION: "1"
  SEMVER_VERSION: 1.11.0
  VERSION: 1.11.0
contents:
  repositories:
    - deb [signed-by=/usr/share/keyrings/dhi-deb-main.gpg] http://dhi.io/deb/debian/main trixie main
  keyring:
    - https://dhi.io/keyring/dhi-deb-gpg.D46852F6925E9F71.key
  builds:
    - name: alloy
      contents:
        packages:
          - bash
          - build-essential
          - coreutils
          - grep
          - libc-bin
          - sed
          - helm=4.1.4-2
        files:
          - url: git+https://github.com/grafana/alloy.git#helm-chart/1.11.0
            checksum: 6a3d2e39422c25361f63ab9d4a072502863db466
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/operations/helm/charts/alloy
          with:
            chart:
              appRef: alloy
              dependencies:
                - keep: true
                  name: crds
              description: Docker Hardened Images Helm chart for Grafana Alloy
              images:
                - name: alloy
                  ref: dhi/alloy:1.18.0-debian13@sha256:e088aba1bf8eed94f711b521d8a83c8f538ee6e1c504d7365106e540e5c28e22
                - name: prometheus-config-reloader
                  ref: dhi/prometheus-config-reloader:0.93.0-debian13@sha256:4cca6ce2a0d854ffef9da6d171044e254572dfca98224d5edd97c5a27f594453
              name: alloy-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/grafana/alloy
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/operations/helm/charts/alloy
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/operations/helm/charts
          with:
            chart: alloy
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/operations/helm/charts
          with:
            chart: alloy
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/alloy/config
