# syntax=dhi.io/build:2-helm3

name: Grafana Alloy Helm chart 1.x
image: dhi.io/alloy-chart
variant: helm
tags:
  - 1.9.0
platforms:
  - linux/amd64
vars:
  ALLOY_REFERENCE: dhi/alloy:1.16.2-debian13@sha256:6fc73033f65b6bcb55e22983a20aa02c17b383d6e455d2ef0301d175f2f6a89d
  CHART_COMMIT_SHA: b33be39df7a84cd4c2de4910b2570f79e622e49f
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.21.0-debian13-dev@sha256:7b9ee43cc77e81e2dcbb1b0f6e8ce376b71d63c90c81f2863e24aefff774a8da
  PROMETHEUS_CONFIG_RELOADER_REFERENCE: dhi/prometheus-config-reloader:0.91.0-debian13@sha256:318fa9c4eacd8fb709e4515d172a1c024236aff13d105e1be38cde3723d8a691
  SEMVER_MAJOR_MINOR_VERSION: "1.9"
  SEMVER_MAJOR_VERSION: "1"
  SEMVER_VERSION: 1.9.0
  VERSION: 1.9.0
contents:
  builds:
    - name: alloy
      uses: dhi.io/helm:3.21.0-debian13-dev@sha256:7b9ee43cc77e81e2dcbb1b0f6e8ce376b71d63c90c81f2863e24aefff774a8da
      contents:
        packages:
          - bash
          - build-essential
          - coreutils
          - grep
          - libc-bin
          - sed
        files:
          - url: git+https://github.com/grafana/alloy.git#helm-chart/1.9.0
            checksum: b33be39df7a84cd4c2de4910b2570f79e622e49f
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/operations/helm/charts/alloy
          with:
            chart:
              appRef: alloy
              dependencies:
                - keep: true
                  name: crds
              description: Docker Hardened Images Helm chart for Grafana Alloy
              images:
                - name: alloy
                  ref: dhi/alloy:1.16.2-debian13@sha256:6fc73033f65b6bcb55e22983a20aa02c17b383d6e455d2ef0301d175f2f6a89d
                - name: prometheus-config-reloader
                  ref: dhi/prometheus-config-reloader:0.91.0-debian13@sha256:318fa9c4eacd8fb709e4515d172a1c024236aff13d105e1be38cde3723d8a691
              name: alloy-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/grafana/alloy
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/operations/helm/charts/alloy
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/operations/helm/charts
          with:
            chart: alloy
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/operations/helm/charts
          with:
            chart: alloy
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/alloy/config
