# syntax=dhi.io/build:2-helm3

name: Grafana Alloy Helm chart 1.x
image: dhi.io/alloy-chart
variant: helm
tags:
  - 1.12.1
platforms:
  - linux/amd64
vars:
  ALLOY_REFERENCE: dhi/alloy:1.19.2-debian13@sha256:327c12312bff6ee2f4b39f6441208e8d277ae0e8d4c5c8588128b9bc7807cb8e
  CHART_COMMIT_SHA: 5975f1be5e7e343ee3df4497942446ed23ae902a
  CHART_HELM_NAME: alloy-chart
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_VERSION: 4.1.4-2
  PROMETHEUS_CONFIG_RELOADER_REFERENCE: dhi/prometheus-config-reloader:0.93.1-debian13@sha256:07dd01c91ec48d3e65cc1b3557dd24425dfdf17ccc0724904e6349a0e4a665b2
  SEMVER_MAJOR_MINOR_VERSION: "1.12"
  SEMVER_MAJOR_VERSION: "1"
  SEMVER_VERSION: 1.12.1
  VERSION: 1.12.1
contents:
  repositories:
    - deb [signed-by=/usr/share/keyrings/dhi-deb-main.gpg] http://dhi.io/deb/debian/main trixie main
  keyring:
    - https://dhi.io/keyring/dhi-deb-gpg.D46852F6925E9F71.key
  builds:
    - name: alloy
      contents:
        packages:
          - bash
          - build-essential
          - coreutils
          - grep
          - libc-bin
          - sed
          - helm=4.1.4-2
        files:
          - url: git+https://github.com/grafana/alloy.git#helm-chart/1.12.1
            checksum: 5975f1be5e7e343ee3df4497942446ed23ae902a
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/operations/helm/charts/alloy
          with:
            chart:
              appRef: alloy
              dependencies:
                - keep: true
                  name: crds
              description: Docker Hardened Images Helm chart for Grafana Alloy
              images:
                - name: alloy
                  ref: dhi/alloy:1.19.2-debian13@sha256:327c12312bff6ee2f4b39f6441208e8d277ae0e8d4c5c8588128b9bc7807cb8e
                - name: prometheus-config-reloader
                  ref: dhi/prometheus-config-reloader:0.93.1-debian13@sha256:07dd01c91ec48d3e65cc1b3557dd24425dfdf17ccc0724904e6349a0e4a665b2
              name: alloy-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/grafana/alloy
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/operations/helm/charts/alloy
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/operations/helm/charts
          with:
            chart: alloy
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/operations/helm/charts
          with:
            chart: alloy
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/alloy/config
