# syntax=dhi.io/build:2-helm3

name: Tigera Operator Helm chart 3.32.x
image: dhi.io/tigera-operator-chart
variant: helm
tags:
  - 3.32.2
platforms:
  - linux/amd64
vars:
  CALICO_CNI_REFERENCE: dhi/calico-cni:3.32.2-debian13@sha256:014c1ba3aaaa6b09dd33e138b17d093d39333cbdc865e7ac56137aca63d2158f
  CALICO_CSI_REFERENCE: dhi/calico-csi:3.32.2-debian13@sha256:c4e22dd5851ba671aa5f8f3292977a17c6f828ccb2450d5e896e1dc3481ef9ab
  CALICO_CTL_REFERENCE: dhi/calico-ctl:3.32.2-debian13@sha256:e3d54262ad8711f5d177612f2bba219d2ea00c46870f461754733163a4b53b7b
  CALICO_GOLDMANE_REFERENCE: dhi/calico-goldmane:3.32.2-debian13@sha256:008643951da4e4fe1e303725f82ea30ed4fd41373eb1be16fb2b5db776c393d9
  CALICO_KUBE_CONTROLLERS_REFERENCE: dhi/calico-kube-controllers:3.32.2-debian13@sha256:eb4307e76ba4e368386144253d9dd20ad04e5b71aa3852c48af53a01d16157e3
  CALICO_NODE_DRIVER_REGISTRAR_REFERENCE: dhi/calico-node-driver-registrar:3.32.2-debian13@sha256:f552b9bf4d79b3e4149d05d28e06159ba4a9c943febd7800921b5e0773c83bc3
  CALICO_NODE_REFERENCE: dhi/calico-node:3.32.2-debian13@sha256:5529a0170467bdf8d80e8b6573afc8c9fcc06bf9a8e275f24ca494603d062a72
  CALICO_POD2DAEMON_FLEXVOL_REFERENCE: dhi/calico-pod2daemon-flexvol:3.32.2-debian13@sha256:cdc0ab88a13a2978e086fd13e9b4853da4dee6c753d763f900673dc88c5750f6
  CALICO_TYPHA_REFERENCE: dhi/calico-typha:3.32.2-debian13@sha256:c0c93d41aaecb2e635b31fe888515faceaa9347c02c47ea99866acfbf9322379
  CALICO_WEBHOOKS_REFERENCE: dhi/calico-webhooks:3.32.2-debian13@sha256:f4ee634e7107749373315504ceb1946879419c797c1c2e4ecec0078911cd4941
  CALICO_WHISKER_BACKEND_REFERENCE: dhi/calico-whisker-backend:3.32.2-debian13@sha256:49bdaf5fe85bb8d4c661a07dadc08b426ea4f4258edc0add4a4ff1bf3c4e4f23
  CALICO_WHISKER_REFERENCE: dhi/calico-whisker:3.32.2-debian13@sha256:da2f1a90c6eb3cb36a84b045ce097d45cb05e67b1c8c80e469efed22dbee12c2
  CHART_COMMIT_SHA: db255c554b929afd73552fd3ac81d691107a1607
  CHART_HELM_NAME: tigera-operator-chart
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_VERSION: 4.1.4-2
  OPERATOR_VERSION: 1.42.6
  SEMVER_MAJOR_MINOR_VERSION: "3.32"
  SEMVER_MAJOR_VERSION: "3"
  SEMVER_VERSION: 3.32.2
  TIGERA_OPERATOR_REFERENCE: dhi/tigera-operator:1.42.6-debian13@sha256:4b1655578ed0e6b201ae86f65e6bacbab58c96ac2abecee1ff80e0fc291788be
  VERSION: 3.32.2
contents:
  repositories:
    - deb [signed-by=/usr/share/keyrings/dhi-deb-main.gpg] http://dhi.io/deb/debian/main trixie main
  keyring:
    - https://dhi.io/keyring/dhi-deb-gpg.D46852F6925E9F71.key
  builds:
    - name: tigera-operator
      work-dir: ${source.dir}/helm-charts/charts/tigera-operator
      contents:
        packages:
          - bash
          - ca-certificates
          - coreutils
          - helm=4.1.4-2
          - yq-go
        files:
          - url: git+https://github.com/projectcalico/calico.git#v3.32.2
            checksum: db255c554b929afd73552fd3ac81d691107a1607
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          with:
            chart:
              appRef: tigera-operator
              description: Docker Hardened Images Helm chart for the Tigera operator (installs Calico)
              images:
                - name: tigera-operator
                  ref: dhi/tigera-operator:1.42.6-debian13@sha256:4b1655578ed0e6b201ae86f65e6bacbab58c96ac2abecee1ff80e0fc291788be
                - name: calico-whisker
                  ref: dhi/calico-whisker:3.32.2-debian13@sha256:da2f1a90c6eb3cb36a84b045ce097d45cb05e67b1c8c80e469efed22dbee12c2
                - name: calico-whisker-backend
                  ref: dhi/calico-whisker-backend:3.32.2-debian13@sha256:49bdaf5fe85bb8d4c661a07dadc08b426ea4f4258edc0add4a4ff1bf3c4e4f23
                - name: calico-ctl
                  ref: dhi/calico-ctl:3.32.2-debian13@sha256:e3d54262ad8711f5d177612f2bba219d2ea00c46870f461754733163a4b53b7b
                - name: calico-cni
                  ref: dhi/calico-cni:3.32.2-debian13@sha256:014c1ba3aaaa6b09dd33e138b17d093d39333cbdc865e7ac56137aca63d2158f
                - name: calico-csi
                  ref: dhi/calico-csi:3.32.2-debian13@sha256:c4e22dd5851ba671aa5f8f3292977a17c6f828ccb2450d5e896e1dc3481ef9ab
                - name: calico-goldmane
                  ref: dhi/calico-goldmane:3.32.2-debian13@sha256:008643951da4e4fe1e303725f82ea30ed4fd41373eb1be16fb2b5db776c393d9
                - name: calico-kube-controllers
                  ref: dhi/calico-kube-controllers:3.32.2-debian13@sha256:eb4307e76ba4e368386144253d9dd20ad04e5b71aa3852c48af53a01d16157e3
                - name: calico-node
                  ref: dhi/calico-node:3.32.2-debian13@sha256:5529a0170467bdf8d80e8b6573afc8c9fcc06bf9a8e275f24ca494603d062a72
                - name: calico-node-driver-registrar
                  ref: dhi/calico-node-driver-registrar:3.32.2-debian13@sha256:f552b9bf4d79b3e4149d05d28e06159ba4a9c943febd7800921b5e0773c83bc3
                - name: calico-pod2daemon-flexvol
                  ref: dhi/calico-pod2daemon-flexvol:3.32.2-debian13@sha256:cdc0ab88a13a2978e086fd13e9b4853da4dee6c753d763f900673dc88c5750f6
                - name: calico-typha
                  ref: dhi/calico-typha:3.32.2-debian13@sha256:c0c93d41aaecb2e635b31fe888515faceaa9347c02c47ea99866acfbf9322379
                - name: calico-webhooks
                  ref: dhi/calico-webhooks:3.32.2-debian13@sha256:f4ee634e7107749373315504ceb1946879419c797c1c2e4ecec0078911cd4941
              name: tigera-operator-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/projectcalico/calico
            cmd: prepare
            registry: dhi.io
        - name: update version
          uses: yq/patch@v1
          with:
            file: Chart.yaml
            patches:
              - .version = "3.32.2"
        - name: relocate chart
          uses: helm/rudder@v1
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          with:
            chart: .
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: .
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/tigera-operator/config
