# syntax=dhi.io/build:2-helm3

name: Tigera Operator Helm chart 3.32.x
image: dhi.io/tigera-operator-chart
variant: helm
tags:
  - 3.32.2
platforms:
  - linux/amd64
vars:
  CALICO_CNI_REFERENCE: dhi/calico-cni:3.32.2-debian13@sha256:e02a0410f54ade6503565758c888550156b81edd55f904befa0c70fb48ea4e66
  CALICO_CSI_REFERENCE: dhi/calico-csi:3.32.2-debian13@sha256:c4e22dd5851ba671aa5f8f3292977a17c6f828ccb2450d5e896e1dc3481ef9ab
  CALICO_CTL_REFERENCE: dhi/calico-ctl:3.32.2-debian13@sha256:e3d54262ad8711f5d177612f2bba219d2ea00c46870f461754733163a4b53b7b
  CALICO_GOLDMANE_REFERENCE: dhi/calico-goldmane:3.32.2-debian13@sha256:c70dca02b70d0374e04e2b733538e4825be85bde73e2b538102dab9febc7323f
  CALICO_KUBE_CONTROLLERS_REFERENCE: dhi/calico-kube-controllers:3.32.2-debian13@sha256:b4e18308f8754a0dd38ed6401a1942429ce84e841b88ab8af4daef94bdb2f67a
  CALICO_NODE_DRIVER_REGISTRAR_REFERENCE: dhi/calico-node-driver-registrar:3.32.2-debian13@sha256:f552b9bf4d79b3e4149d05d28e06159ba4a9c943febd7800921b5e0773c83bc3
  CALICO_NODE_REFERENCE: dhi/calico-node:3.32.2-debian13@sha256:20ee67b0800b3dc5c9be134a8b3ed9ad89e7b4a4caecbef896a65f59355b79ad
  CALICO_POD2DAEMON_FLEXVOL_REFERENCE: dhi/calico-pod2daemon-flexvol:3.32.2-debian13@sha256:cdc0ab88a13a2978e086fd13e9b4853da4dee6c753d763f900673dc88c5750f6
  CALICO_TYPHA_REFERENCE: dhi/calico-typha:3.32.2-debian13@sha256:2af35adf566b88494c0b16b20d58f7870e82b8160ace34d7aee1b8b7915d2ea2
  CALICO_WEBHOOKS_REFERENCE: dhi/calico-webhooks:3.32.2-debian13@sha256:f45738bf2707838c098a1602f073c8d7054b601b44a4694f21c19b74aacdac5e
  CALICO_WHISKER_BACKEND_REFERENCE: dhi/calico-whisker-backend:3.32.2-debian13@sha256:fbd57477f2be5f266722581bb4ddede558fb9adb0d3c20e35c36a6c65a74d8f6
  CALICO_WHISKER_REFERENCE: dhi/calico-whisker:3.32.2-debian13@sha256:f7361021124a9b163d41409f815819ccd8d8d5916203d6efacb5241906a12468
  CHART_COMMIT_SHA: db255c554b929afd73552fd3ac81d691107a1607
  CHART_HELM_NAME: tigera-operator-chart
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_VERSION: 4.1.4-2
  OPERATOR_VERSION: 1.42.6
  SEMVER_MAJOR_MINOR_VERSION: "3.32"
  SEMVER_MAJOR_VERSION: "3"
  SEMVER_VERSION: 3.32.2
  TIGERA_OPERATOR_REFERENCE: dhi/tigera-operator:1.42.6-debian13@sha256:bf7e5f8a130d6a7309ae2f069df7e305db697400007a65776fe99f27c2f13d5e
  VERSION: 3.32.2
contents:
  repositories:
    - deb [signed-by=/usr/share/keyrings/dhi-deb-main.gpg] http://dhi.io/deb/debian/main trixie main
  keyring:
    - https://dhi.io/keyring/dhi-deb-gpg.D46852F6925E9F71.key
  builds:
    - name: tigera-operator
      work-dir: ${source.dir}/helm-charts/charts/tigera-operator
      contents:
        packages:
          - bash
          - ca-certificates
          - coreutils
          - helm=4.1.4-2
          - yq-go
        files:
          - url: git+https://github.com/projectcalico/calico.git#v3.32.2
            checksum: db255c554b929afd73552fd3ac81d691107a1607
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          with:
            chart:
              appRef: tigera-operator
              description: Docker Hardened Images Helm chart for the Tigera operator (installs Calico)
              images:
                - name: tigera-operator
                  ref: dhi/tigera-operator:1.42.6-debian13@sha256:bf7e5f8a130d6a7309ae2f069df7e305db697400007a65776fe99f27c2f13d5e
                - name: calico-whisker
                  ref: dhi/calico-whisker:3.32.2-debian13@sha256:f7361021124a9b163d41409f815819ccd8d8d5916203d6efacb5241906a12468
                - name: calico-whisker-backend
                  ref: dhi/calico-whisker-backend:3.32.2-debian13@sha256:fbd57477f2be5f266722581bb4ddede558fb9adb0d3c20e35c36a6c65a74d8f6
                - name: calico-ctl
                  ref: dhi/calico-ctl:3.32.2-debian13@sha256:e3d54262ad8711f5d177612f2bba219d2ea00c46870f461754733163a4b53b7b
                - name: calico-cni
                  ref: dhi/calico-cni:3.32.2-debian13@sha256:e02a0410f54ade6503565758c888550156b81edd55f904befa0c70fb48ea4e66
                - name: calico-csi
                  ref: dhi/calico-csi:3.32.2-debian13@sha256:c4e22dd5851ba671aa5f8f3292977a17c6f828ccb2450d5e896e1dc3481ef9ab
                - name: calico-goldmane
                  ref: dhi/calico-goldmane:3.32.2-debian13@sha256:c70dca02b70d0374e04e2b733538e4825be85bde73e2b538102dab9febc7323f
                - name: calico-kube-controllers
                  ref: dhi/calico-kube-controllers:3.32.2-debian13@sha256:b4e18308f8754a0dd38ed6401a1942429ce84e841b88ab8af4daef94bdb2f67a
                - name: calico-node
                  ref: dhi/calico-node:3.32.2-debian13@sha256:20ee67b0800b3dc5c9be134a8b3ed9ad89e7b4a4caecbef896a65f59355b79ad
                - name: calico-node-driver-registrar
                  ref: dhi/calico-node-driver-registrar:3.32.2-debian13@sha256:f552b9bf4d79b3e4149d05d28e06159ba4a9c943febd7800921b5e0773c83bc3
                - name: calico-pod2daemon-flexvol
                  ref: dhi/calico-pod2daemon-flexvol:3.32.2-debian13@sha256:cdc0ab88a13a2978e086fd13e9b4853da4dee6c753d763f900673dc88c5750f6
                - name: calico-typha
                  ref: dhi/calico-typha:3.32.2-debian13@sha256:2af35adf566b88494c0b16b20d58f7870e82b8160ace34d7aee1b8b7915d2ea2
                - name: calico-webhooks
                  ref: dhi/calico-webhooks:3.32.2-debian13@sha256:f45738bf2707838c098a1602f073c8d7054b601b44a4694f21c19b74aacdac5e
              name: tigera-operator-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/projectcalico/calico
            cmd: prepare
            registry: dhi.io
        - name: update version
          uses: yq/patch@v1
          with:
            file: Chart.yaml
            patches:
              - .version = "3.32.2"
        - name: relocate chart
          uses: helm/rudder@v1
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          with:
            chart: .
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: .
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/tigera-operator/config
