# syntax=dhi.io/build:2-helm3

name: Tigera Operator Helm chart 3.x
image: dhi.io/tigera-operator-chart
variant: helm
tags:
  - 3.32.1
platforms:
  - linux/amd64
vars:
  CALICO_CTL_REFERENCE: dhi/calico-ctl:3.32.1-debian13@sha256:6392d48628d507ad071d78ff33d8bf187461ecf06e5371870f5503bcce89a432
  CALICO_WHISKER_BACKEND_REFERENCE: dhi/calico-whisker-backend:3.32.1-debian13@sha256:45d8f4ca2d0511594eae65d186ec3576159cc629b984a45e28c11b71133c8889
  CALICO_WHISKER_REFERENCE: dhi/calico-whisker:3.32.1-debian13@sha256:64f260c43a8ac97d048910259dac93dd32b7ddf070397284a04dd8bcc13948fe
  CHART_COMMIT_SHA: 0ca9d1b93644778cafdf1812f3dda02ac0c361e8
  CHART_HELM_NAME: tigera-operator-chart
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_VERSION: 4.1.4-2
  SEMVER_MAJOR_MINOR_VERSION: "3.32"
  SEMVER_MAJOR_VERSION: "3"
  SEMVER_VERSION: 3.32.1
  TIGERA_OPERATOR_REFERENCE: dhi/tigera-operator:1.42.4-debian13@sha256:727b5d367127ef5b591fa3daa0499a6c4659fd1f0d6a3dc51976bbb9bed2f5ab
  VERSION: 3.32.1
contents:
  repositories:
    - deb [signed-by=/usr/share/keyrings/dhi-deb-main.gpg] http://dhi.io/deb/debian/main trixie main
  keyring:
    - https://dhi.io/keyring/dhi-deb-gpg.D46852F6925E9F71.key
  builds:
    - name: tigera-operator
      work-dir: ${source.dir}/helm-charts/charts/tigera-operator
      contents:
        packages:
          - bash
          - ca-certificates
          - coreutils
          - helm=4.1.4-2
        files:
          - url: git+https://github.com/projectcalico/calico.git#v3.32.1
            checksum: 0ca9d1b93644778cafdf1812f3dda02ac0c361e8
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          with:
            chart:
              appRef: tigera-operator
              description: Docker Hardened Images Helm chart for the Tigera operator (installs Calico)
              images:
                - name: tigera-operator
                  ref: dhi/tigera-operator:1.42.4-debian13@sha256:727b5d367127ef5b591fa3daa0499a6c4659fd1f0d6a3dc51976bbb9bed2f5ab
                - name: calico-whisker
                  ref: dhi/calico-whisker:3.32.1-debian13@sha256:64f260c43a8ac97d048910259dac93dd32b7ddf070397284a04dd8bcc13948fe
                - name: calico-whisker-backend
                  ref: dhi/calico-whisker-backend:3.32.1-debian13@sha256:45d8f4ca2d0511594eae65d186ec3576159cc629b984a45e28c11b71133c8889
                - name: calico-ctl
                  ref: dhi/calico-ctl:3.32.1-debian13@sha256:6392d48628d507ad071d78ff33d8bf187461ecf06e5371870f5503bcce89a432
              name: tigera-operator-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/projectcalico/calico
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          with:
            chart: .
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: .
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/tigera-operator/config
