# syntax=dhi.io/build:2-helm3

name: Tigera Operator Helm chart 3.x
image: dhi.io/tigera-operator-chart
variant: helm
tags:
  - 3.32.2
platforms:
  - linux/amd64
vars:
  CALICO_CTL_REFERENCE: dhi/calico-ctl:3.32.2-debian13@sha256:e3d54262ad8711f5d177612f2bba219d2ea00c46870f461754733163a4b53b7b
  CALICO_WHISKER_BACKEND_REFERENCE: dhi/calico-whisker-backend:3.32.2-debian13@sha256:49bdaf5fe85bb8d4c661a07dadc08b426ea4f4258edc0add4a4ff1bf3c4e4f23
  CALICO_WHISKER_REFERENCE: dhi/calico-whisker:3.32.2-debian13@sha256:a531bfdfe3587a502e603115ea3dc70118ec4e84a8af73491ecd945eb18eff73
  CHART_COMMIT_SHA: db255c554b929afd73552fd3ac81d691107a1607
  CHART_HELM_NAME: tigera-operator-chart
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_VERSION: 4.1.4-2
  SEMVER_MAJOR_MINOR_VERSION: "3.32"
  SEMVER_MAJOR_VERSION: "3"
  SEMVER_VERSION: 3.32.2
  TIGERA_OPERATOR_REFERENCE: dhi/tigera-operator:1.42.6-debian13@sha256:4b1655578ed0e6b201ae86f65e6bacbab58c96ac2abecee1ff80e0fc291788be
  VERSION: 3.32.2
contents:
  repositories:
    - deb [signed-by=/usr/share/keyrings/dhi-deb-main.gpg] http://dhi.io/deb/debian/main trixie main
  keyring:
    - https://dhi.io/keyring/dhi-deb-gpg.D46852F6925E9F71.key
  builds:
    - name: tigera-operator
      work-dir: ${source.dir}/helm-charts/charts/tigera-operator
      contents:
        packages:
          - bash
          - ca-certificates
          - coreutils
          - helm=4.1.4-2
        files:
          - url: git+https://github.com/projectcalico/calico.git#v3.32.2
            checksum: db255c554b929afd73552fd3ac81d691107a1607
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          with:
            chart:
              appRef: tigera-operator
              description: Docker Hardened Images Helm chart for the Tigera operator (installs Calico)
              images:
                - name: tigera-operator
                  ref: dhi/tigera-operator:1.42.6-debian13@sha256:4b1655578ed0e6b201ae86f65e6bacbab58c96ac2abecee1ff80e0fc291788be
                - name: calico-whisker
                  ref: dhi/calico-whisker:3.32.2-debian13@sha256:a531bfdfe3587a502e603115ea3dc70118ec4e84a8af73491ecd945eb18eff73
                - name: calico-whisker-backend
                  ref: dhi/calico-whisker-backend:3.32.2-debian13@sha256:49bdaf5fe85bb8d4c661a07dadc08b426ea4f4258edc0add4a4ff1bf3c4e4f23
                - name: calico-ctl
                  ref: dhi/calico-ctl:3.32.2-debian13@sha256:e3d54262ad8711f5d177612f2bba219d2ea00c46870f461754733163a4b53b7b
              name: tigera-operator-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/projectcalico/calico
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          with:
            chart: .
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: .
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/tigera-operator/config
