# syntax=dhi.io/build:2-helm3

name: OAuth2 Proxy Helm chart 10.x
image: dhi.io/oauth2-proxy-chart
variant: helm
tags:
  - 10.6.0
platforms:
  - linux/amd64
vars:
  ALPINE_BASE_REFERENCE: dhi/alpine-base:3.22-alpine3.22@sha256:e46de8d59c111eb1455c81e2e3deea7437a7d7e26e340ad8c756878f519f5f13
  CHART_COMMIT_SHA: 529c2f6581a2f76103ed1672f78fdfd0d2349bc0
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.21.0-debian13-dev@sha256:6506c914dff9353ce03ce64c8d30089cf14419d8d39f026c53917e1451fb8b21
  OAUTH2_PROXY_REFERENCE: dhi/oauth2-proxy:7.15.2-debian13@sha256:cd724aa7c4547fc3b0c33b2100767002cec4d4a3de2dc17c175d6bf8c05abfa2
  REDIS_CHART_REFERENCE: dhi/redis-chart:23.0.7@sha256:d080cabda28b86e85e25721e00fbf63fdc3cd72d2abd9694ea5a36b575073df6
  SEMVER_MAJOR_MINOR_VERSION: "10.6"
  SEMVER_MAJOR_VERSION: "10"
  SEMVER_VERSION: 10.6.0
  VERSION: 10.6.0
contents:
  builds:
    - name: oauth2-proxy
      uses: dhi.io/helm:3.21.0-debian13-dev@sha256:6506c914dff9353ce03ce64c8d30089cf14419d8d39f026c53917e1451fb8b21
      contents:
        files:
          - url: git+https://github.com/oauth2-proxy/manifests.git#oauth2-proxy-10.6.0
            checksum: 529c2f6581a2f76103ed1672f78fdfd0d2349bc0
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/helm/oauth2-proxy
          with:
            chart:
              appRef: oauth2-proxy
              dependencies:
                - alias: redis
                  condition: redis-ha.enabled
                  name: redis-chart
                  ref: dhi/redis-chart:23.0.7@sha256:d080cabda28b86e85e25721e00fbf63fdc3cd72d2abd9694ea5a36b575073df6
              description: Docker Hardened Images Helm chart for OAuth2 Proxy
              images:
                - name: oauth2-proxy
                  ref: dhi/oauth2-proxy:7.15.2-debian13@sha256:cd724aa7c4547fc3b0c33b2100767002cec4d4a3de2dc17c175d6bf8c05abfa2
                - name: alpine-base
                  ref: dhi/alpine-base:3.22-alpine3.22@sha256:e46de8d59c111eb1455c81e2e3deea7437a7d7e26e340ad8c756878f519f5f13
              name: oauth2-proxy-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/oauth2-proxy/manifests
            cmd: prepare
            registry: dhi.io
        - name: patch helpers
          work-dir: ${source.dir}/helm-charts/helm/oauth2-proxy/templates
          runs: |
            set -eux -o pipefail

            sed -i 's/include "redis-ha.fullname"/include "common.names.fullname"/' _helpers.tpl
            sed -i 's/(dict "Chart" (dict "Name" "redis-ha")/(dict "Chart" (dict "Name" "redis")/' _helpers.tpl
            sed -i 's|printf "redis://%s:%.0f"|printf "redis://%s-master:%.0f"|' _helpers.tpl
            sed -i 's/$redisValues.redis.port/.Values.redis.master.service.ports.redis/' _helpers.tpl
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/helm/oauth2-proxy
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: helm login
          uses: helm/login@v1
          with:
            registry: dhi.io
        - name: pull dependencies
          uses: helm/cmd@v1
          privileged: true
          with:
            chart: ${source.dir}/helm-charts/helm/oauth2-proxy
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/helm
          with:
            chart: oauth2-proxy
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: ${source.dir}/helm-charts/helm/oauth2-proxy
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/oauth2-proxy/config
