# syntax=dhi.io/build:2-helm3

name: Grafana Agent Helm chart 0.x
image: dhi.io/grafana-agent-chart
variant: helm
tags:
  - 0.44.2
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: 5ef5377b3d5421e754bff1028fd1ce4b3259cf5f
  CONFIGMAP_RELOAD_REFERENCE: dhi/configmap-reload:0.15.0-debian13@sha256:2498d648a10f330f00bd4c8d485b9bcde4e0438109894c9004125fe951656825
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  GRAFANA_AGENT_REFERENCE: dhi/grafana-agent:0.44.8-debian13@sha256:2e5214fc7905f1299e5667fb086b125af61496e15e6d255d5bea5cc222f5091a
  HELM_REFERENCE: dhi/helm:3.20.2-debian13-dev@sha256:f9dd4a356298b0769dc4c2f718b9f564b631ddf37c19e061d61af9081bc7da13
  SEMVER_MAJOR_MINOR_VERSION: "0.44"
  SEMVER_MAJOR_VERSION: "0"
  SEMVER_VERSION: 0.44.2
  VERSION: 0.44.2
contents:
  builds:
    - name: grafana-agent
      uses: dhi.io/helm:3.20.2-debian13-dev@sha256:f9dd4a356298b0769dc4c2f718b9f564b631ddf37c19e061d61af9081bc7da13
      contents:
        packages:
          - bash
          - build-essential
          - coreutils
          - grep
          - libc-bin
          - sed
        files:
          - url: git+https://github.com/grafana/agent.git#helm-chart/0.44.2
            checksum: 5ef5377b3d5421e754bff1028fd1ce4b3259cf5f
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/operations/helm/charts/grafana-agent
          with:
            chart:
              appRef: grafana-agent
              description: Docker Hardened Images Helm chart for Grafana Agent
              images:
                - name: grafana-agent
                  ref: dhi/grafana-agent:0.44.8-debian13@sha256:2e5214fc7905f1299e5667fb086b125af61496e15e6d255d5bea5cc222f5091a
                - name: configmap-reload
                  ref: dhi/configmap-reload:0.15.0-debian13@sha256:2498d648a10f330f00bd4c8d485b9bcde4e0438109894c9004125fe951656825
              name: grafana-agent-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/grafana/agent
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/operations/helm/charts/grafana-agent
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/operations/helm/charts
          with:
            chart: grafana-agent
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/operations/helm/charts
          with:
            chart: grafana-agent
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/grafana-agent/config
