# syntax=dhi.io/build:2-helm3

name: Kube State Metrics Helm chart 7.x
image: dhi.io/kube-state-metrics-chart
variant: helm
tags:
  - 7.2.1
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: fc92926ffc1a6a8525a25eb868653e919dfe3e7e
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.20.1-debian13-dev@sha256:20c25fd3dfe3acda51121e86555d2090b3c6720ff8cad90030326774a4b01272
  KUBE_RBAC_PROXY_REFERENCE: dhi/kube-rbac-proxy:0.21.1-debian13@sha256:4ea8d8e5f960d9c34ecb44ac7e21d320a3bbf8b2716733e91edd59e1065f204b
  KUBE_STATE_METRICS_REFERENCE: dhi/kube-state-metrics:2.18.0-debian13@sha256:bfc8460f9631ba785ba98788779ad32fb27f73c333d414a91061ca2a88f742d8
  SEMVER_MAJOR_MINOR_VERSION: "7.2"
  SEMVER_MAJOR_VERSION: "7"
  SEMVER_VERSION: 7.2.1
  VERSION: 7.2.1
contents:
  builds:
    - name: kube-state-metrics-chart
      uses: dhi.io/helm:3.20.1-debian13-dev@sha256:20c25fd3dfe3acda51121e86555d2090b3c6720ff8cad90030326774a4b01272
      contents:
        files:
          - url: git+https://github.com/prometheus-community/helm-charts.git#kube-state-metrics-7.2.1
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/kube-state-metrics
          with:
            chart:
              appRef: kube-state-metrics
              description: Docker Hardened Images Helm chart for Kube State Metrics
              images:
                - name: kube-state-metrics
                  ref: dhi/kube-state-metrics:2.18.0-debian13@sha256:bfc8460f9631ba785ba98788779ad32fb27f73c333d414a91061ca2a88f742d8
                - name: kube-rbac-proxy
                  ref: dhi/kube-rbac-proxy:0.21.1-debian13@sha256:4ea8d8e5f960d9c34ecb44ac7e21d320a3bbf8b2716733e91edd59e1065f204b
              name: kube-state-metrics-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/prometheus-community/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/kube-state-metrics
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          privileged: true
          with:
            chart: ${source.dir}/helm-charts/charts/kube-state-metrics
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: kube-state-metrics
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: ${source.dir}/helm-charts/charts/kube-state-metrics
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/kube-state-metrics/config
