# syntax=dhi.io/build:2-helm3

name: Kube State Metrics Helm chart 7.x
image: dhi.io/kube-state-metrics-chart
variant: helm
tags:
  - 7.4.0
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: 31a0ef706d03730630debcd72cd005f8afa117b8
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.21.0-debian13-dev@sha256:0ee5c30c2d65033300ceb74755e2bd6bc49120d9116a1e8c2880500483315e9b
  KUBE_RBAC_PROXY_REFERENCE: dhi/kube-rbac-proxy:0.22.0-debian13@sha256:8478efda0d25ac2b4c73d4741cd479a7000909dd7391a5446ff739c5f87014ad
  KUBE_STATE_METRICS_REFERENCE: dhi/kube-state-metrics:2.19.0-debian13@sha256:8f332280e64461d56aaf7e6f423ee237110458da0bfd578804775fe5dd2fd8f3
  SEMVER_MAJOR_MINOR_VERSION: "7.4"
  SEMVER_MAJOR_VERSION: "7"
  SEMVER_VERSION: 7.4.0
  VERSION: 7.4.0
contents:
  builds:
    - name: kube-state-metrics-chart
      uses: dhi.io/helm:3.21.0-debian13-dev@sha256:0ee5c30c2d65033300ceb74755e2bd6bc49120d9116a1e8c2880500483315e9b
      contents:
        files:
          - url: git+https://github.com/prometheus-community/helm-charts.git#kube-state-metrics-7.4.0
            checksum: 31a0ef706d03730630debcd72cd005f8afa117b8
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/kube-state-metrics
          with:
            chart:
              appRef: kube-state-metrics
              description: Docker Hardened Images Helm chart for Kube State Metrics
              images:
                - name: kube-state-metrics
                  ref: dhi/kube-state-metrics:2.19.0-debian13@sha256:8f332280e64461d56aaf7e6f423ee237110458da0bfd578804775fe5dd2fd8f3
                - name: kube-rbac-proxy
                  ref: dhi/kube-rbac-proxy:0.22.0-debian13@sha256:8478efda0d25ac2b4c73d4741cd479a7000909dd7391a5446ff739c5f87014ad
              name: kube-state-metrics-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/prometheus-community/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/kube-state-metrics
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          privileged: true
          with:
            chart: ${source.dir}/helm-charts/charts/kube-state-metrics
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: kube-state-metrics
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: ${source.dir}/helm-charts/charts/kube-state-metrics
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/kube-state-metrics/config
