# syntax=dhi.io/build:2-helm3

name: Kube Prometheus Stack Helm chart 86.x
image: dhi.io/kube-prometheus-stack-chart
variant: helm
tags:
  - 86.2.2
platforms:
  - linux/amd64
vars:
  ADMISSION_WEBHOOK_REFERENCE: dhi/prometheus-operator-admission-webhook:0.91.0-debian13@sha256:1607cf3037c4614f65df00f20688e6e10e723c1b1b73ccfacd9050f6b334451f
  ALERTMANAGER_REFERENCE: dhi/alertmanager:0.32.2-debian13@sha256:3e155cbc3dd9728c1098fa2589916fa3a6515db059d7dce203d93e368fb6f884
  BUSYBOX_REFERENCE: dhi/busybox:1.37.0-debian13@sha256:e0cbe035dd7d7072e088172c5833bf756bfba3618567c0f5e73288e97e3a19bf
  CHART_COMMIT_SHA: 67b525798bd384fe110a8ad6a3e6cf765d200d5f
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  GRAFANA_CHART_REFERENCE: dhi/grafana-chart:12.4.4@sha256:d5c2a091311552d9b84548a1fc3cbea2b1464d0661d97a98d77d6b8369fac446
  HELM_REFERENCE: dhi/helm:3.21.0-debian13-dev@sha256:7c201a9174a2b56cb13136f19d87b23309d09eb2fc8a24e8c08a31ebd907a943
  KUBE_STATE_METRICS_CHART_REFERENCE: dhi/kube-state-metrics-chart:7.4.0@sha256:4854b45f2217f36b5db4bc37ec9d74c0562680c7c0b9e089d211f145bdb80f81
  KUBE_WEBHOOK_CERTGEN_REFERENCE: dhi/kube-webhook-certgen:1.8.3-debian13@sha256:4afe5086a3217becb4f9eb79ce1b62617f7c69ea0ac0e3ae11d470850e6840cf
  KUBECTL_REFERENCE: dhi/kubectl:1.36.1-debian13@sha256:27238f8a3a9affc19319c6e713356648e4848b74717a1999d8a4f4d2c3acebf3
  NODE_EXPORTER_CHART_REFERENCE: dhi/node-exporter-chart:4.55.0@sha256:0956d586ded9c1bda579e2a13332868ef2a06196b5dab7604557ce0f9e86e55e
  PROMETHEUS_CONFIG_RELOADER_REFERENCE: dhi/prometheus-config-reloader:0.91.0-debian13@sha256:b1c2fee8e80da925328f7a24f940468dda23164c56ef7674a3d60deb79e2441d
  PROMETHEUS_OPERATOR_REFERENCE: dhi/prometheus-operator:0.91.0-debian13@sha256:be57dc596462832ec52f4f0d58b72e3ed4f99fb94627b369aad4848fd47c8ab1
  PROMETHEUS_REFERENCE: dhi/prometheus:3.12.0-debian13@sha256:adfb8432ca30b4f4e176fb895a67d55407ab2690109ab44c0830153bd673488b
  SEMVER_MAJOR_MINOR_VERSION: "86.2"
  SEMVER_MAJOR_VERSION: "86"
  SEMVER_VERSION: 86.2.2
  THANOS_REFERENCE: dhi/thanos:0.41.0-debian13@sha256:2e2f5e6f83f6c08bcd9c9d7a45d36060c3496e6237f8ef3c0004f757528a4baa
  VERSION: 86.2.2
contents:
  builds:
    - name: kube-prometheus-stack-chart
      uses: dhi.io/helm:3.21.0-debian13-dev@sha256:7c201a9174a2b56cb13136f19d87b23309d09eb2fc8a24e8c08a31ebd907a943
      contents:
        packages:
          - bash
          - build-essential
          - coreutils
          - grep
          - libc-bin
          - sed
        files:
          - url: git+https://github.com/prometheus-community/helm-charts.git#kube-prometheus-stack-86.2.2
            checksum: 67b525798bd384fe110a8ad6a3e6cf765d200d5f
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/kube-prometheus-stack
          with:
            chart:
              appRef: prometheus-operator
              dependencies:
                - condition: crds.enabled
                  keep: true
                  name: crds
                - alias: kube-state-metrics
                  condition: kubeStateMetrics.enabled
                  name: kube-state-metrics
                  ref: dhi/kube-state-metrics-chart:7.4.0@sha256:4854b45f2217f36b5db4bc37ec9d74c0562680c7c0b9e089d211f145bdb80f81
                - alias: prometheus-node-exporter
                  condition: nodeExporter.enabled
                  name: node-exporter
                  ref: dhi/node-exporter-chart:4.55.0@sha256:0956d586ded9c1bda579e2a13332868ef2a06196b5dab7604557ce0f9e86e55e
                - alias: grafana
                  condition: grafana.enabled
                  name: grafana
                  ref: dhi/grafana-chart:12.4.4@sha256:d5c2a091311552d9b84548a1fc3cbea2b1464d0661d97a98d77d6b8369fac446
              description: Docker Hardened Images Helm chart for Kube Prometheus Stack
              images:
                - name: busybox
                  ref: dhi/busybox:1.37.0-debian13@sha256:e0cbe035dd7d7072e088172c5833bf756bfba3618567c0f5e73288e97e3a19bf
                - name: kubectl
                  ref: dhi/kubectl:1.36.1-debian13@sha256:27238f8a3a9affc19319c6e713356648e4848b74717a1999d8a4f4d2c3acebf3
                - name: alertmanager
                  ref: dhi/alertmanager:0.32.2-debian13@sha256:3e155cbc3dd9728c1098fa2589916fa3a6515db059d7dce203d93e368fb6f884
                - name: prometheus-operator-admission-webhook
                  ref: dhi/prometheus-operator-admission-webhook:0.91.0-debian13@sha256:1607cf3037c4614f65df00f20688e6e10e723c1b1b73ccfacd9050f6b334451f
                - name: kube-webhook-certgen
                  ref: dhi/kube-webhook-certgen:1.8.3-debian13@sha256:4afe5086a3217becb4f9eb79ce1b62617f7c69ea0ac0e3ae11d470850e6840cf
                - name: prometheus-operator
                  ref: dhi/prometheus-operator:0.91.0-debian13@sha256:be57dc596462832ec52f4f0d58b72e3ed4f99fb94627b369aad4848fd47c8ab1
                - name: prometheus-config-reloader
                  ref: dhi/prometheus-config-reloader:0.91.0-debian13@sha256:b1c2fee8e80da925328f7a24f940468dda23164c56ef7674a3d60deb79e2441d
                - name: thanos
                  ref: dhi/thanos:0.41.0-debian13@sha256:2e2f5e6f83f6c08bcd9c9d7a45d36060c3496e6237f8ef3c0004f757528a4baa
                - name: prometheus
                  ref: dhi/prometheus:3.12.0-debian13@sha256:adfb8432ca30b4f4e176fb895a67d55407ab2690109ab44c0830153bd673488b
              name: kube-prometheus-stack-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/prometheus-community/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/kube-prometheus-stack
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: helm login
          uses: helm/login@v1
          with:
            registry: dhi.io
        - name: pull dependencies
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          privileged: true
          with:
            chart: kube-prometheus-stack
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: kube-prometheus-stack
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: kube-prometheus-stack
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/kube-prometheus-stack/config
