# syntax=dhi.io/build:2-helm3

name: Kube Prometheus Stack Helm chart 85.x
image: dhi.io/kube-prometheus-stack-chart
variant: helm
tags:
  - 85.3.3
platforms:
  - linux/amd64
vars:
  ADMISSION_WEBHOOK_REFERENCE: dhi/prometheus-operator-admission-webhook:0.91.0-debian13@sha256:c787c6cb6694fc4fd4c122ad8c067645772410254e5b1bd85c92a1132ab64bfc
  ALERTMANAGER_REFERENCE: dhi/alertmanager:0.32.1-debian13@sha256:af18cd3afd45f9232c5fbcecc99f9cd06d9dd902741aa40c58e69d38b6974969
  BUSYBOX_REFERENCE: dhi/busybox:1.37.0-debian13@sha256:f05f53964b498b59b389a4f28b1ec0c588f8612ba78a79154ab793d32e55641b
  CHART_COMMIT_SHA: 8bc765bc01bf950546527baf2f17dce8d8d2026f
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  GRAFANA_CHART_REFERENCE: dhi/grafana-chart:12.3.3@sha256:ce936e914916aefbe6d43d5a28f208206606e36db4fbb3246a81780b22e7ab63
  HELM_REFERENCE: dhi/helm:3.21.0-debian13-dev@sha256:6506c914dff9353ce03ce64c8d30089cf14419d8d39f026c53917e1451fb8b21
  KUBE_STATE_METRICS_CHART_REFERENCE: dhi/kube-state-metrics-chart:7.4.0@sha256:2640b6a5fbb13cd83a48202d40c47b7ee0735da5d222aff43a4cb1d56b3c6233
  KUBE_WEBHOOK_CERTGEN_REFERENCE: dhi/kube-webhook-certgen:1.8.3-debian13@sha256:00f0e0462f300e9986c3f3b3c8b040e39037bde0568ff49d50554b6565bc8aa7
  KUBECTL_REFERENCE: dhi/kubectl:1.35.5-debian13@sha256:90639b2223d4e76c3d272cabe1d3ef91008db06fcaacb0968ced11a62b8b7d46
  NODE_EXPORTER_CHART_REFERENCE: dhi/node-exporter-chart:4.55.0@sha256:20ba150ad1b2ed3145db888b792264a24f10415a33918a77a38d6092193ba755
  PROMETHEUS_CONFIG_RELOADER_REFERENCE: dhi/prometheus-config-reloader:0.91.0-debian13@sha256:47197c688978a73cd26519e9da0cac2a10a4e2b1cbb020e5c590457b2a73dee7
  PROMETHEUS_OPERATOR_REFERENCE: dhi/prometheus-operator:0.91.0-debian13@sha256:3064234f37d11421cdae89c231099b7dcfec047685055bf752eb6bad9c03ac07
  PROMETHEUS_REFERENCE: dhi/prometheus:3.11.3-debian13@sha256:e7e82ee5d73f7b5eaabc0e23e0160059dcfe01bfbd78609e4ca865a10cfa995a
  SEMVER_MAJOR_MINOR_VERSION: "85.3"
  SEMVER_MAJOR_VERSION: "85"
  SEMVER_VERSION: 85.3.3
  THANOS_REFERENCE: dhi/thanos:0.41.0-debian13@sha256:282fa8225b55f4650a3ef97f477ccadc7b079ae6ff4a3255f849e1014a4d25fd
  VERSION: 85.3.3
contents:
  builds:
    - name: kube-prometheus-stack-chart
      uses: dhi.io/helm:3.21.0-debian13-dev@sha256:6506c914dff9353ce03ce64c8d30089cf14419d8d39f026c53917e1451fb8b21
      contents:
        packages:
          - bash
          - build-essential
          - coreutils
          - grep
          - libc-bin
          - sed
        files:
          - url: git+https://github.com/prometheus-community/helm-charts.git#kube-prometheus-stack-85.3.3
            checksum: 8bc765bc01bf950546527baf2f17dce8d8d2026f
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/kube-prometheus-stack
          with:
            chart:
              appRef: prometheus-operator
              dependencies:
                - condition: crds.enabled
                  keep: true
                  name: crds
                - alias: kube-state-metrics
                  condition: kubeStateMetrics.enabled
                  name: kube-state-metrics
                  ref: dhi/kube-state-metrics-chart:7.4.0@sha256:2640b6a5fbb13cd83a48202d40c47b7ee0735da5d222aff43a4cb1d56b3c6233
                - alias: prometheus-node-exporter
                  condition: nodeExporter.enabled
                  name: node-exporter
                  ref: dhi/node-exporter-chart:4.55.0@sha256:20ba150ad1b2ed3145db888b792264a24f10415a33918a77a38d6092193ba755
                - alias: grafana
                  condition: grafana.enabled
                  name: grafana
                  ref: dhi/grafana-chart:12.3.3@sha256:ce936e914916aefbe6d43d5a28f208206606e36db4fbb3246a81780b22e7ab63
              description: Docker Hardened Images Helm chart for Kube Prometheus Stack
              images:
                - name: busybox
                  ref: dhi/busybox:1.37.0-debian13@sha256:f05f53964b498b59b389a4f28b1ec0c588f8612ba78a79154ab793d32e55641b
                - name: kubectl
                  ref: dhi/kubectl:1.35.5-debian13@sha256:90639b2223d4e76c3d272cabe1d3ef91008db06fcaacb0968ced11a62b8b7d46
                - name: alertmanager
                  ref: dhi/alertmanager:0.32.1-debian13@sha256:af18cd3afd45f9232c5fbcecc99f9cd06d9dd902741aa40c58e69d38b6974969
                - name: prometheus-operator-admission-webhook
                  ref: dhi/prometheus-operator-admission-webhook:0.91.0-debian13@sha256:c787c6cb6694fc4fd4c122ad8c067645772410254e5b1bd85c92a1132ab64bfc
                - name: kube-webhook-certgen
                  ref: dhi/kube-webhook-certgen:1.8.3-debian13@sha256:00f0e0462f300e9986c3f3b3c8b040e39037bde0568ff49d50554b6565bc8aa7
                - name: prometheus-operator
                  ref: dhi/prometheus-operator:0.91.0-debian13@sha256:3064234f37d11421cdae89c231099b7dcfec047685055bf752eb6bad9c03ac07
                - name: prometheus-config-reloader
                  ref: dhi/prometheus-config-reloader:0.91.0-debian13@sha256:47197c688978a73cd26519e9da0cac2a10a4e2b1cbb020e5c590457b2a73dee7
                - name: thanos
                  ref: dhi/thanos:0.41.0-debian13@sha256:282fa8225b55f4650a3ef97f477ccadc7b079ae6ff4a3255f849e1014a4d25fd
                - name: prometheus
                  ref: dhi/prometheus:3.11.3-debian13@sha256:e7e82ee5d73f7b5eaabc0e23e0160059dcfe01bfbd78609e4ca865a10cfa995a
              name: kube-prometheus-stack-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/prometheus-community/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/kube-prometheus-stack
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: helm login
          uses: helm/login@v1
          with:
            registry: dhi.io
        - name: pull dependencies
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          privileged: true
          with:
            chart: kube-prometheus-stack
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: kube-prometheus-stack
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: kube-prometheus-stack
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/kube-prometheus-stack/config
