# syntax=dhi.io/build:2-helm3

name: Kube Prometheus Stack Helm chart 85.x
image: dhi.io/kube-prometheus-stack-chart
variant: helm
tags:
  - 85.2.2
platforms:
  - linux/amd64
vars:
  ADMISSION_WEBHOOK_REFERENCE: dhi/prometheus-operator-admission-webhook:0.91.0-debian13@sha256:c9c80a1513359b22cb9b25a113b2275c206115f2b908e2dfd8068a4d194d0701
  ALERTMANAGER_REFERENCE: dhi/alertmanager:0.32.1-debian13@sha256:af18cd3afd45f9232c5fbcecc99f9cd06d9dd902741aa40c58e69d38b6974969
  BUSYBOX_REFERENCE: dhi/busybox:1.37.0-debian13@sha256:f05f53964b498b59b389a4f28b1ec0c588f8612ba78a79154ab793d32e55641b
  CHART_COMMIT_SHA: fcebcd3539a7aeb3c47e478cb6123740f32f3e8c
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  GRAFANA_CHART_REFERENCE: dhi/grafana-chart:12.3.3@sha256:ce936e914916aefbe6d43d5a28f208206606e36db4fbb3246a81780b22e7ab63
  HELM_REFERENCE: dhi/helm:3.21.0-debian13-dev@sha256:0ee5c30c2d65033300ceb74755e2bd6bc49120d9116a1e8c2880500483315e9b
  KUBE_STATE_METRICS_CHART_REFERENCE: dhi/kube-state-metrics-chart:7.3.0@sha256:1badcff2120fa407f09860c93d08a485a353e2e08cc95fe3c62bc8e9a1a685ed
  KUBE_WEBHOOK_CERTGEN_REFERENCE: dhi/kube-webhook-certgen:1.8.2-debian13@sha256:843587c303e179531e1d803d5b022a551ac1122083d99bcde319c6d6d658bcbd
  KUBECTL_REFERENCE: dhi/kubectl:1.35.5-debian13@sha256:90639b2223d4e76c3d272cabe1d3ef91008db06fcaacb0968ced11a62b8b7d46
  NODE_EXPORTER_CHART_REFERENCE: dhi/node-exporter-chart:4.55.0@sha256:20ba150ad1b2ed3145db888b792264a24f10415a33918a77a38d6092193ba755
  PROMETHEUS_CONFIG_RELOADER_REFERENCE: dhi/prometheus-config-reloader:0.91.0-debian13@sha256:bdd4839f8c6137d4a2015ec77a750fa0c268dc27d2b21dd168b0e4e90b4d6b4f
  PROMETHEUS_OPERATOR_REFERENCE: dhi/prometheus-operator:0.91.0-debian13@sha256:836d9386ee2fcadf48e93694cbe1627cf834ea7b741303994f810f5f80d7e0e0
  PROMETHEUS_REFERENCE: dhi/prometheus:3.11.3-debian13@sha256:3876abaa0b95dfadcbf4d5f395c40be9059002b5ebc0a86d9c03e92d901fc48c
  SEMVER_MAJOR_MINOR_VERSION: "85.2"
  SEMVER_MAJOR_VERSION: "85"
  SEMVER_VERSION: 85.2.2
  THANOS_REFERENCE: dhi/thanos:0.41.0-debian13@sha256:deb3bddfafd597f811666006b4a05861d1b6b56068f4daf80f2bf02ff9a1a2ae
  VERSION: 85.2.2
contents:
  builds:
    - name: kube-prometheus-stack-chart
      uses: dhi.io/helm:3.21.0-debian13-dev@sha256:0ee5c30c2d65033300ceb74755e2bd6bc49120d9116a1e8c2880500483315e9b
      contents:
        packages:
          - bash
          - build-essential
          - coreutils
          - grep
          - libc-bin
          - sed
        files:
          - url: git+https://github.com/prometheus-community/helm-charts.git#kube-prometheus-stack-85.2.2
            checksum: fcebcd3539a7aeb3c47e478cb6123740f32f3e8c
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/kube-prometheus-stack
          with:
            chart:
              appRef: prometheus-operator
              dependencies:
                - condition: crds.enabled
                  keep: true
                  name: crds
                - alias: kube-state-metrics
                  condition: kubeStateMetrics.enabled
                  name: kube-state-metrics
                  ref: dhi/kube-state-metrics-chart:7.3.0@sha256:1badcff2120fa407f09860c93d08a485a353e2e08cc95fe3c62bc8e9a1a685ed
                - alias: prometheus-node-exporter
                  condition: nodeExporter.enabled
                  name: node-exporter
                  ref: dhi/node-exporter-chart:4.55.0@sha256:20ba150ad1b2ed3145db888b792264a24f10415a33918a77a38d6092193ba755
                - alias: grafana
                  condition: grafana.enabled
                  name: grafana
                  ref: dhi/grafana-chart:12.3.3@sha256:ce936e914916aefbe6d43d5a28f208206606e36db4fbb3246a81780b22e7ab63
              description: Docker Hardened Images Helm chart for Kube Prometheus Stack
              images:
                - name: busybox
                  ref: dhi/busybox:1.37.0-debian13@sha256:f05f53964b498b59b389a4f28b1ec0c588f8612ba78a79154ab793d32e55641b
                - name: kubectl
                  ref: dhi/kubectl:1.35.5-debian13@sha256:90639b2223d4e76c3d272cabe1d3ef91008db06fcaacb0968ced11a62b8b7d46
                - name: alertmanager
                  ref: dhi/alertmanager:0.32.1-debian13@sha256:af18cd3afd45f9232c5fbcecc99f9cd06d9dd902741aa40c58e69d38b6974969
                - name: prometheus-operator-admission-webhook
                  ref: dhi/prometheus-operator-admission-webhook:0.91.0-debian13@sha256:c9c80a1513359b22cb9b25a113b2275c206115f2b908e2dfd8068a4d194d0701
                - name: kube-webhook-certgen
                  ref: dhi/kube-webhook-certgen:1.8.2-debian13@sha256:843587c303e179531e1d803d5b022a551ac1122083d99bcde319c6d6d658bcbd
                - name: prometheus-operator
                  ref: dhi/prometheus-operator:0.91.0-debian13@sha256:836d9386ee2fcadf48e93694cbe1627cf834ea7b741303994f810f5f80d7e0e0
                - name: prometheus-config-reloader
                  ref: dhi/prometheus-config-reloader:0.91.0-debian13@sha256:bdd4839f8c6137d4a2015ec77a750fa0c268dc27d2b21dd168b0e4e90b4d6b4f
                - name: thanos
                  ref: dhi/thanos:0.41.0-debian13@sha256:deb3bddfafd597f811666006b4a05861d1b6b56068f4daf80f2bf02ff9a1a2ae
                - name: prometheus
                  ref: dhi/prometheus:3.11.3-debian13@sha256:3876abaa0b95dfadcbf4d5f395c40be9059002b5ebc0a86d9c03e92d901fc48c
              name: kube-prometheus-stack-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/prometheus-community/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/kube-prometheus-stack
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: helm login
          uses: helm/login@v1
          with:
            registry: dhi.io
        - name: pull dependencies
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          privileged: true
          with:
            chart: kube-prometheus-stack
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: kube-prometheus-stack
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: kube-prometheus-stack
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/kube-prometheus-stack/config
