# syntax=dhi.io/build:2-helm3

name: Kube Prometheus Stack Helm chart 87.x
image: dhi.io/kube-prometheus-stack-chart
variant: helm
tags:
  - 87.21.0
platforms:
  - linux/amd64
vars:
  ALERTMANAGER_REFERENCE: dhi/alertmanager:0.34.0-debian13@sha256:b0ab57b4f374fb9fd6abe255b94aee5c6979b652f5f134f803ee6fc7a7202667
  BUSYBOX_REFERENCE: dhi/busybox:1.37.0-debian13@sha256:abcd06d567c6ecda4aae78cff5334a231bd3e663b69b671612566d4a4c949899
  CHART_COMMIT_SHA: 2017b1a385179833e2948de2c35625abde38b826
  CHART_HELM_NAME: kube-prometheus-stack-chart
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  GRAFANA_CHART_REFERENCE: dhi/grafana-chart:12.11.2@sha256:c3e7795000254fe41110a53ba41e73fe41e206273b72521be9a342ffeac8b989
  HELM_VERSION: 4.1.4-2
  KUBE_STATE_METRICS_CHART_REFERENCE: dhi/kube-state-metrics-chart:8.5.0@sha256:fa56e838e6c636d2e3bdd6d8cbf30595d47b4e4b9a553340d97a9658bc550d42
  KUBE_WEBHOOK_CERTGEN_REFERENCE: dhi/kube-webhook-certgen:1.8.8-debian13@sha256:769451713e86dc834087cc4accc221452e016b859bf43a99a3354336b17f09b1
  KUBECTL_REFERENCE: dhi/kubectl:1.37.0-debian13@sha256:897b7b063c2b87bcd7cbab09e2c681856422dec1a668f6b596efd51a23e19e6c
  NODE_EXPORTER_CHART_REFERENCE: dhi/node-exporter-chart:4.57.0@sha256:aac7535b131614caf06f5506caaac14a7c4ddbb0e5e3eef5459fa73703fcdd19
  PROMETHEUS_CONFIG_RELOADER_REFERENCE: dhi/prometheus-config-reloader:0.94.0-debian13@sha256:91b3b2f375e5139a89184c0afcf3d08e07345db784003af0bc0aca41fedc192f
  PROMETHEUS_OPERATOR_ADMISSION_WEBHOOK_REFERENCE: dhi/prometheus-operator-admission-webhook:0.94.0-debian13@sha256:0c06958ba1a5a2c146f40869216698903183c7651193e8271b626b69c20a58e0
  PROMETHEUS_OPERATOR_REFERENCE: dhi/prometheus-operator:0.94.0-debian13@sha256:e94999ab398d631bbf387d1c7d3041811b423e8765df623037f636147bc27d54
  PROMETHEUS_REFERENCE: dhi/prometheus:3.14.0-debian13@sha256:5700b5e591bde80259e24aceabfb04fcfc099f0190a1a22485a681dc2ef24ffc
  SEMVER_MAJOR_MINOR_VERSION: "87.21"
  SEMVER_MAJOR_VERSION: "87"
  SEMVER_VERSION: 87.21.0
  THANOS_REFERENCE: dhi/thanos:0.42.4-debian13@sha256:633a568c9164db273aaaf39a7ffb789c51c1541291ea867a637cf59a6d610eea
  VERSION: 87.21.0
contents:
  repositories:
    - deb [signed-by=/usr/share/keyrings/dhi-deb-main.gpg] http://dhi.io/deb/debian/main trixie main
  keyring:
    - https://dhi.io/keyring/dhi-deb-gpg.D46852F6925E9F71.key
  builds:
    - name: kube-prometheus-stack-chart
      contents:
        packages:
          - bash
          - ca-certificates
          - coreutils
          - yq-go
          - helm=4.1.4-2
        files:
          - url: git+https://github.com/prometheus-community/helm-charts.git#kube-prometheus-stack-87.21.0
            checksum: 2017b1a385179833e2948de2c35625abde38b826
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/kube-prometheus-stack
          with:
            chart:
              appRef: prometheus-operator
              dependencies:
                - condition: crds.enabled
                  keep: true
                  name: crds
                - alias: kube-state-metrics
                  condition: kubeStateMetrics.enabled
                  name: kube-state-metrics
                  ref: dhi/kube-state-metrics-chart:8.5.0@sha256:fa56e838e6c636d2e3bdd6d8cbf30595d47b4e4b9a553340d97a9658bc550d42
                - alias: prometheus-node-exporter
                  condition: nodeExporter.enabled
                  name: node-exporter
                  ref: dhi/node-exporter-chart:4.57.0@sha256:aac7535b131614caf06f5506caaac14a7c4ddbb0e5e3eef5459fa73703fcdd19
                - alias: grafana
                  condition: grafana.enabled
                  name: grafana
                  ref: dhi/grafana-chart:12.11.2@sha256:c3e7795000254fe41110a53ba41e73fe41e206273b72521be9a342ffeac8b989
              description: Docker Hardened Images Helm chart for Kube Prometheus Stack
              images:
                - name: busybox
                  ref: dhi/busybox:1.37.0-debian13@sha256:abcd06d567c6ecda4aae78cff5334a231bd3e663b69b671612566d4a4c949899
                - name: kubectl
                  ref: dhi/kubectl:1.37.0-debian13@sha256:897b7b063c2b87bcd7cbab09e2c681856422dec1a668f6b596efd51a23e19e6c
                - name: alertmanager
                  ref: dhi/alertmanager:0.34.0-debian13@sha256:b0ab57b4f374fb9fd6abe255b94aee5c6979b652f5f134f803ee6fc7a7202667
                - name: prometheus-operator-admission-webhook
                  ref: dhi/prometheus-operator-admission-webhook:0.94.0-debian13@sha256:0c06958ba1a5a2c146f40869216698903183c7651193e8271b626b69c20a58e0
                - name: kube-webhook-certgen
                  ref: dhi/kube-webhook-certgen:1.8.8-debian13@sha256:769451713e86dc834087cc4accc221452e016b859bf43a99a3354336b17f09b1
                - name: prometheus-operator
                  ref: dhi/prometheus-operator:0.94.0-debian13@sha256:e94999ab398d631bbf387d1c7d3041811b423e8765df623037f636147bc27d54
                - name: prometheus-config-reloader
                  ref: dhi/prometheus-config-reloader:0.94.0-debian13@sha256:91b3b2f375e5139a89184c0afcf3d08e07345db784003af0bc0aca41fedc192f
                - name: thanos
                  ref: dhi/thanos:0.42.4-debian13@sha256:633a568c9164db273aaaf39a7ffb789c51c1541291ea867a637cf59a6d610eea
                - name: prometheus
                  ref: dhi/prometheus:3.14.0-debian13@sha256:5700b5e591bde80259e24aceabfb04fcfc099f0190a1a22485a681dc2ef24ffc
              name: kube-prometheus-stack-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/prometheus-community/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/kube-prometheus-stack
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update values
          uses: yq/patch@v1
          work-dir: ${source.dir}/helm-charts/charts/kube-prometheus-stack
          with:
            file: values.yaml
            patches:
              - del(.prometheus-windows-exporter)
        - name: helm login
          uses: helm/login@v1
          with:
            registry: dhi.io
        - name: pull dependencies
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          privileged: true
          with:
            chart: kube-prometheus-stack
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: kube-prometheus-stack
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: kube-prometheus-stack
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/kube-prometheus-stack/config
