# syntax=dhi.io/build:2-helm3

name: Kube Prometheus Stack Helm chart 87.x
image: dhi.io/kube-prometheus-stack-chart
variant: helm
tags:
  - 87.21.0
platforms:
  - linux/amd64
vars:
  ALERTMANAGER_REFERENCE: dhi/alertmanager:0.33.1-debian13@sha256:6499d5eec2e74ad8fb8dee2536fcfc333c358876ac9978fe141e2f1ccf71be35
  BUSYBOX_REFERENCE: dhi/busybox:1.37.0-debian13@sha256:95e068d111cb60d71a1ffcb522ee149abf7754bfde3f1796c20aeff637691669
  CHART_COMMIT_SHA: 2017b1a385179833e2948de2c35625abde38b826
  CHART_HELM_NAME: kube-prometheus-stack-chart
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  GRAFANA_CHART_REFERENCE: dhi/grafana-chart:12.10.2@sha256:4aded000779527b0b0d5cf9a288ee2346d9510c30bed187b97e88aa6dd9f37f8
  HELM_VERSION: 4.1.4-2
  KUBE_STATE_METRICS_CHART_REFERENCE: dhi/kube-state-metrics-chart:8.1.3@sha256:7791ec516f6ec552c66280621463676676716251b4f4ecbd27027294e21d1381
  KUBE_WEBHOOK_CERTGEN_REFERENCE: dhi/kube-webhook-certgen:1.8.5-debian13@sha256:1791318015ccd12809db275fa00ca991b0aedbd1cb4e1f33db741af85f76d882
  KUBECTL_REFERENCE: dhi/kubectl:1.36.3-debian13@sha256:4bfd1866f908e17a0106f27afa61187739f1c67117961f8ad2f06ab982f8ccf2
  NODE_EXPORTER_CHART_REFERENCE: dhi/node-exporter-chart:4.56.1@sha256:2f51939f2a4fd07f895d412df1c611f4c100e9a39f6baba01107415067ca5ccf
  PROMETHEUS_CONFIG_RELOADER_REFERENCE: dhi/prometheus-config-reloader:0.93.0-debian13@sha256:4cca6ce2a0d854ffef9da6d171044e254572dfca98224d5edd97c5a27f594453
  PROMETHEUS_OPERATOR_ADMISSION_WEBHOOK_REFERENCE: dhi/prometheus-operator-admission-webhook:0.93.0-debian13@sha256:cac7e5e84b70f59cb8dc1661927fd295f526579bf99be2ba9b8f2e069909d61b
  PROMETHEUS_OPERATOR_REFERENCE: dhi/prometheus-operator:0.93.0-debian13@sha256:f259d0f92629a5f2dea2888c0cbfc0869d9809707d672ae0db99a3e59f6bcf2a
  PROMETHEUS_REFERENCE: dhi/prometheus:3.13.2-debian13@sha256:a65d65621ad32257d77f5f7c8d6a5a54b0c6d6b53def998ac1134439b6b938ca
  SEMVER_MAJOR_MINOR_VERSION: "87.21"
  SEMVER_MAJOR_VERSION: "87"
  SEMVER_VERSION: 87.21.0
  THANOS_REFERENCE: dhi/thanos:0.42.4-debian13@sha256:482a1d1d1ee87712266ea93cdf2d4e9ed061edafef88acb4fa79a147d5fe0417
  VERSION: 87.21.0
contents:
  repositories:
    - deb [signed-by=/usr/share/keyrings/dhi-deb-main.gpg] http://dhi.io/deb/debian/main trixie main
  keyring:
    - https://dhi.io/keyring/dhi-deb-gpg.D46852F6925E9F71.key
  builds:
    - name: kube-prometheus-stack-chart
      contents:
        packages:
          - bash
          - ca-certificates
          - coreutils
          - yq-go
          - helm=4.1.4-2
        files:
          - url: git+https://github.com/prometheus-community/helm-charts.git#kube-prometheus-stack-87.21.0
            checksum: 2017b1a385179833e2948de2c35625abde38b826
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/kube-prometheus-stack
          with:
            chart:
              appRef: prometheus-operator
              dependencies:
                - condition: crds.enabled
                  keep: true
                  name: crds
                - alias: kube-state-metrics
                  condition: kubeStateMetrics.enabled
                  name: kube-state-metrics
                  ref: dhi/kube-state-metrics-chart:8.1.3@sha256:7791ec516f6ec552c66280621463676676716251b4f4ecbd27027294e21d1381
                - alias: prometheus-node-exporter
                  condition: nodeExporter.enabled
                  name: node-exporter
                  ref: dhi/node-exporter-chart:4.56.1@sha256:2f51939f2a4fd07f895d412df1c611f4c100e9a39f6baba01107415067ca5ccf
                - alias: grafana
                  condition: grafana.enabled
                  name: grafana
                  ref: dhi/grafana-chart:12.10.2@sha256:4aded000779527b0b0d5cf9a288ee2346d9510c30bed187b97e88aa6dd9f37f8
              description: Docker Hardened Images Helm chart for Kube Prometheus Stack
              images:
                - name: busybox
                  ref: dhi/busybox:1.37.0-debian13@sha256:95e068d111cb60d71a1ffcb522ee149abf7754bfde3f1796c20aeff637691669
                - name: kubectl
                  ref: dhi/kubectl:1.36.3-debian13@sha256:4bfd1866f908e17a0106f27afa61187739f1c67117961f8ad2f06ab982f8ccf2
                - name: alertmanager
                  ref: dhi/alertmanager:0.33.1-debian13@sha256:6499d5eec2e74ad8fb8dee2536fcfc333c358876ac9978fe141e2f1ccf71be35
                - name: prometheus-operator-admission-webhook
                  ref: dhi/prometheus-operator-admission-webhook:0.93.0-debian13@sha256:cac7e5e84b70f59cb8dc1661927fd295f526579bf99be2ba9b8f2e069909d61b
                - name: kube-webhook-certgen
                  ref: dhi/kube-webhook-certgen:1.8.5-debian13@sha256:1791318015ccd12809db275fa00ca991b0aedbd1cb4e1f33db741af85f76d882
                - name: prometheus-operator
                  ref: dhi/prometheus-operator:0.93.0-debian13@sha256:f259d0f92629a5f2dea2888c0cbfc0869d9809707d672ae0db99a3e59f6bcf2a
                - name: prometheus-config-reloader
                  ref: dhi/prometheus-config-reloader:0.93.0-debian13@sha256:4cca6ce2a0d854ffef9da6d171044e254572dfca98224d5edd97c5a27f594453
                - name: thanos
                  ref: dhi/thanos:0.42.4-debian13@sha256:482a1d1d1ee87712266ea93cdf2d4e9ed061edafef88acb4fa79a147d5fe0417
                - name: prometheus
                  ref: dhi/prometheus:3.13.2-debian13@sha256:a65d65621ad32257d77f5f7c8d6a5a54b0c6d6b53def998ac1134439b6b938ca
              name: kube-prometheus-stack-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/prometheus-community/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/kube-prometheus-stack
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update values
          uses: yq/patch@v1
          work-dir: ${source.dir}/helm-charts/charts/kube-prometheus-stack
          with:
            file: values.yaml
            patches:
              - del(.prometheus-windows-exporter)
        - name: helm login
          uses: helm/login@v1
          with:
            registry: dhi.io
        - name: pull dependencies
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          privileged: true
          with:
            chart: kube-prometheus-stack
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: kube-prometheus-stack
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: kube-prometheus-stack
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/kube-prometheus-stack/config
