# syntax=dhi.io/build:2-helm3

name: Kube Prometheus Stack Helm chart 87.x
image: dhi.io/kube-prometheus-stack-chart
variant: helm
tags:
  - 87.21.0
platforms:
  - linux/amd64
vars:
  ALERTMANAGER_REFERENCE: dhi/alertmanager:0.34.0-debian13@sha256:31d81236c2d65dad32eefd334c8c0347524b01d2aa43a671a8f1b1cf171aa90c
  BUSYBOX_REFERENCE: dhi/busybox:1.37.0-debian13@sha256:9ab7bde7a4cce6fc63ca449de0fe074ae007151f620f1b8b35915a584b0f39e8
  CHART_COMMIT_SHA: 2017b1a385179833e2948de2c35625abde38b826
  CHART_HELM_NAME: kube-prometheus-stack-chart
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  GRAFANA_CHART_REFERENCE: dhi/grafana-chart:12.11.0@sha256:c4fa208d787849e3d5f753ee00c5da58ca605870e2c7c9d6eebc736b0d4d4e13
  HELM_VERSION: 4.1.4-2
  KUBE_STATE_METRICS_CHART_REFERENCE: dhi/kube-state-metrics-chart:8.4.0@sha256:6d85361182b62cc9fcb9e32cf1a78c1423ef11e45963bffc24981928af0502cc
  KUBE_WEBHOOK_CERTGEN_REFERENCE: dhi/kube-webhook-certgen:1.8.5-debian13@sha256:ae2a8177da1b9ca6f564e0356fc840619dc67d6b920eeda64709e7ee27311e9f
  KUBECTL_REFERENCE: dhi/kubectl:1.36.3-debian13@sha256:e641ef4647c4d73abc2a4d0538f83c3c816708446c0aac00d74a33afdeb28cbc
  NODE_EXPORTER_CHART_REFERENCE: dhi/node-exporter-chart:4.56.1@sha256:93b0226ba36948019c48d05273292899f6db0bafbdd196fd1c9904c3b22ebc37
  PROMETHEUS_CONFIG_RELOADER_REFERENCE: dhi/prometheus-config-reloader:0.93.1-debian13@sha256:32ece1b4fad3b0839683c2bbe9603d9a102e511deac48da598e256885ba479bc
  PROMETHEUS_OPERATOR_ADMISSION_WEBHOOK_REFERENCE: dhi/prometheus-operator-admission-webhook:0.93.1-debian13@sha256:97c030a03c384067cb67b050a038226f194e91685c34de0b19e0dfcdfebf90a5
  PROMETHEUS_OPERATOR_REFERENCE: dhi/prometheus-operator:0.93.1-debian13@sha256:4245a785a691bd3743da8b6e341522ba45610214ddd1e6f6060cea0929f47e99
  PROMETHEUS_REFERENCE: dhi/prometheus:3.14.0-debian13@sha256:2b50627146923953a3f0ec24c0e793f23c0b2eee2022d5989647271bd5aee905
  SEMVER_MAJOR_MINOR_VERSION: "87.21"
  SEMVER_MAJOR_VERSION: "87"
  SEMVER_VERSION: 87.21.0
  THANOS_REFERENCE: dhi/thanos:0.42.4-debian13@sha256:8bf03acd251400119148c557aa53e464bee82928e44ef3cd7826918c90aa7cba
  VERSION: 87.21.0
contents:
  repositories:
    - deb [signed-by=/usr/share/keyrings/dhi-deb-main.gpg] http://dhi.io/deb/debian/main trixie main
  keyring:
    - https://dhi.io/keyring/dhi-deb-gpg.D46852F6925E9F71.key
  builds:
    - name: kube-prometheus-stack-chart
      contents:
        packages:
          - bash
          - ca-certificates
          - coreutils
          - yq-go
          - helm=4.1.4-2
        files:
          - url: git+https://github.com/prometheus-community/helm-charts.git#kube-prometheus-stack-87.21.0
            checksum: 2017b1a385179833e2948de2c35625abde38b826
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/kube-prometheus-stack
          with:
            chart:
              appRef: prometheus-operator
              dependencies:
                - condition: crds.enabled
                  keep: true
                  name: crds
                - alias: kube-state-metrics
                  condition: kubeStateMetrics.enabled
                  name: kube-state-metrics
                  ref: dhi/kube-state-metrics-chart:8.4.0@sha256:6d85361182b62cc9fcb9e32cf1a78c1423ef11e45963bffc24981928af0502cc
                - alias: prometheus-node-exporter
                  condition: nodeExporter.enabled
                  name: node-exporter
                  ref: dhi/node-exporter-chart:4.56.1@sha256:93b0226ba36948019c48d05273292899f6db0bafbdd196fd1c9904c3b22ebc37
                - alias: grafana
                  condition: grafana.enabled
                  name: grafana
                  ref: dhi/grafana-chart:12.11.0@sha256:c4fa208d787849e3d5f753ee00c5da58ca605870e2c7c9d6eebc736b0d4d4e13
              description: Docker Hardened Images Helm chart for Kube Prometheus Stack
              images:
                - name: busybox
                  ref: dhi/busybox:1.37.0-debian13@sha256:9ab7bde7a4cce6fc63ca449de0fe074ae007151f620f1b8b35915a584b0f39e8
                - name: kubectl
                  ref: dhi/kubectl:1.36.3-debian13@sha256:e641ef4647c4d73abc2a4d0538f83c3c816708446c0aac00d74a33afdeb28cbc
                - name: alertmanager
                  ref: dhi/alertmanager:0.34.0-debian13@sha256:31d81236c2d65dad32eefd334c8c0347524b01d2aa43a671a8f1b1cf171aa90c
                - name: prometheus-operator-admission-webhook
                  ref: dhi/prometheus-operator-admission-webhook:0.93.1-debian13@sha256:97c030a03c384067cb67b050a038226f194e91685c34de0b19e0dfcdfebf90a5
                - name: kube-webhook-certgen
                  ref: dhi/kube-webhook-certgen:1.8.5-debian13@sha256:ae2a8177da1b9ca6f564e0356fc840619dc67d6b920eeda64709e7ee27311e9f
                - name: prometheus-operator
                  ref: dhi/prometheus-operator:0.93.1-debian13@sha256:4245a785a691bd3743da8b6e341522ba45610214ddd1e6f6060cea0929f47e99
                - name: prometheus-config-reloader
                  ref: dhi/prometheus-config-reloader:0.93.1-debian13@sha256:32ece1b4fad3b0839683c2bbe9603d9a102e511deac48da598e256885ba479bc
                - name: thanos
                  ref: dhi/thanos:0.42.4-debian13@sha256:8bf03acd251400119148c557aa53e464bee82928e44ef3cd7826918c90aa7cba
                - name: prometheus
                  ref: dhi/prometheus:3.14.0-debian13@sha256:2b50627146923953a3f0ec24c0e793f23c0b2eee2022d5989647271bd5aee905
              name: kube-prometheus-stack-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/prometheus-community/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/kube-prometheus-stack
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update values
          uses: yq/patch@v1
          work-dir: ${source.dir}/helm-charts/charts/kube-prometheus-stack
          with:
            file: values.yaml
            patches:
              - del(.prometheus-windows-exporter)
        - name: helm login
          uses: helm/login@v1
          with:
            registry: dhi.io
        - name: pull dependencies
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          privileged: true
          with:
            chart: kube-prometheus-stack
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: kube-prometheus-stack
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: kube-prometheus-stack
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/kube-prometheus-stack/config
