# syntax=dhi.io/build:2-helm3

name: Kube Prometheus Stack Helm chart 88.x
image: dhi.io/kube-prometheus-stack-chart
variant: helm
tags:
  - 88.3.0
platforms:
  - linux/amd64
vars:
  ALERTMANAGER_REFERENCE: dhi/alertmanager:0.33.1-debian13@sha256:6499d5eec2e74ad8fb8dee2536fcfc333c358876ac9978fe141e2f1ccf71be35
  BUSYBOX_REFERENCE: dhi/busybox:1.37.0-debian13@sha256:95e068d111cb60d71a1ffcb522ee149abf7754bfde3f1796c20aeff637691669
  CHART_COMMIT_SHA: 54199b5bd7cdc3e6f27457791d744dd2761d378e
  CHART_HELM_NAME: kube-prometheus-stack-chart
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  GRAFANA_CHART_REFERENCE: dhi/grafana-chart:12.10.4@sha256:97c7b548d10cc08ea38fbed8f743a164c72742551551c92dbd9ba53f4874dda7
  HELM_VERSION: 4.1.4-2
  KUBE_STATE_METRICS_CHART_REFERENCE: dhi/kube-state-metrics-chart:8.3.0@sha256:7920ad3f5ee75e6235a65fbe7b544bdf2e5b2933e5269cafec04ea79b0370ef7
  KUBE_WEBHOOK_CERTGEN_REFERENCE: dhi/kube-webhook-certgen:1.8.5-debian13@sha256:0f55a6d705e78d47722b95167875e53da67e24d4da1b0905c8446a945f3a7432
  KUBECTL_REFERENCE: dhi/kubectl:1.36.3-debian13@sha256:8e054e7574d7b11e972426795d1c6cb1fdb807367a416c78aab80f7316d7c732
  NODE_EXPORTER_CHART_REFERENCE: dhi/node-exporter-chart:4.56.1@sha256:2f51939f2a4fd07f895d412df1c611f4c100e9a39f6baba01107415067ca5ccf
  PROMETHEUS_CONFIG_RELOADER_REFERENCE: dhi/prometheus-config-reloader:0.93.1-debian13@sha256:32ece1b4fad3b0839683c2bbe9603d9a102e511deac48da598e256885ba479bc
  PROMETHEUS_OPERATOR_ADMISSION_WEBHOOK_REFERENCE: dhi/prometheus-operator-admission-webhook:0.93.1-debian13@sha256:f734714e1552532f4c2daa5532f760ff64d48861947621faacb426f044820d7d
  PROMETHEUS_OPERATOR_REFERENCE: dhi/prometheus-operator:0.93.1-debian13@sha256:dbe74b27f5c62d7361cf2522501242086ccb98393617832abb688678913eb369
  PROMETHEUS_REFERENCE: dhi/prometheus:3.13.2-debian13@sha256:585a54e52b97d4400aaa4c7ef9470add072362b236cd7fb4e8aacdd371121109
  SEMVER_MAJOR_MINOR_VERSION: "88.3"
  SEMVER_MAJOR_VERSION: "88"
  SEMVER_VERSION: 88.3.0
  THANOS_REFERENCE: dhi/thanos:0.42.4-debian13@sha256:8bf03acd251400119148c557aa53e464bee82928e44ef3cd7826918c90aa7cba
  VERSION: 88.3.0
contents:
  repositories:
    - deb [signed-by=/usr/share/keyrings/dhi-deb-main.gpg] http://dhi.io/deb/debian/main trixie main
  keyring:
    - https://dhi.io/keyring/dhi-deb-gpg.D46852F6925E9F71.key
  builds:
    - name: kube-prometheus-stack-chart
      contents:
        packages:
          - bash
          - ca-certificates
          - coreutils
          - yq-go
          - helm=4.1.4-2
        files:
          - url: git+https://github.com/prometheus-community/helm-charts.git#kube-prometheus-stack-88.3.0
            checksum: 54199b5bd7cdc3e6f27457791d744dd2761d378e
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/kube-prometheus-stack
          with:
            chart:
              appRef: prometheus-operator
              dependencies:
                - condition: crds.enabled
                  keep: true
                  name: crds
                - alias: kube-state-metrics
                  condition: kubeStateMetrics.enabled
                  name: kube-state-metrics
                  ref: dhi/kube-state-metrics-chart:8.3.0@sha256:7920ad3f5ee75e6235a65fbe7b544bdf2e5b2933e5269cafec04ea79b0370ef7
                - alias: prometheus-node-exporter
                  condition: nodeExporter.enabled
                  name: node-exporter
                  ref: dhi/node-exporter-chart:4.56.1@sha256:2f51939f2a4fd07f895d412df1c611f4c100e9a39f6baba01107415067ca5ccf
                - alias: grafana
                  condition: grafana.enabled
                  name: grafana
                  ref: dhi/grafana-chart:12.10.4@sha256:97c7b548d10cc08ea38fbed8f743a164c72742551551c92dbd9ba53f4874dda7
              description: Docker Hardened Images Helm chart for Kube Prometheus Stack
              images:
                - name: busybox
                  ref: dhi/busybox:1.37.0-debian13@sha256:95e068d111cb60d71a1ffcb522ee149abf7754bfde3f1796c20aeff637691669
                - name: kubectl
                  ref: dhi/kubectl:1.36.3-debian13@sha256:8e054e7574d7b11e972426795d1c6cb1fdb807367a416c78aab80f7316d7c732
                - name: alertmanager
                  ref: dhi/alertmanager:0.33.1-debian13@sha256:6499d5eec2e74ad8fb8dee2536fcfc333c358876ac9978fe141e2f1ccf71be35
                - name: prometheus-operator-admission-webhook
                  ref: dhi/prometheus-operator-admission-webhook:0.93.1-debian13@sha256:f734714e1552532f4c2daa5532f760ff64d48861947621faacb426f044820d7d
                - name: kube-webhook-certgen
                  ref: dhi/kube-webhook-certgen:1.8.5-debian13@sha256:0f55a6d705e78d47722b95167875e53da67e24d4da1b0905c8446a945f3a7432
                - name: prometheus-operator
                  ref: dhi/prometheus-operator:0.93.1-debian13@sha256:dbe74b27f5c62d7361cf2522501242086ccb98393617832abb688678913eb369
                - name: prometheus-config-reloader
                  ref: dhi/prometheus-config-reloader:0.93.1-debian13@sha256:32ece1b4fad3b0839683c2bbe9603d9a102e511deac48da598e256885ba479bc
                - name: thanos
                  ref: dhi/thanos:0.42.4-debian13@sha256:8bf03acd251400119148c557aa53e464bee82928e44ef3cd7826918c90aa7cba
                - name: prometheus
                  ref: dhi/prometheus:3.13.2-debian13@sha256:585a54e52b97d4400aaa4c7ef9470add072362b236cd7fb4e8aacdd371121109
              name: kube-prometheus-stack-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/prometheus-community/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/kube-prometheus-stack
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update values
          uses: yq/patch@v1
          work-dir: ${source.dir}/helm-charts/charts/kube-prometheus-stack
          with:
            file: values.yaml
            patches:
              - del(.prometheus-windows-exporter)
        - name: helm login
          uses: helm/login@v1
          with:
            registry: dhi.io
        - name: pull dependencies
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          privileged: true
          with:
            chart: kube-prometheus-stack
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: kube-prometheus-stack
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: kube-prometheus-stack
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/kube-prometheus-stack/config
