# syntax=dhi.io/build:2-helm3

name: Kube Prometheus Stack Helm chart 88.x
image: dhi.io/kube-prometheus-stack-chart
variant: helm
tags:
  - 88.6.4
platforms:
  - linux/amd64
vars:
  ALERTMANAGER_REFERENCE: dhi/alertmanager:0.34.0-debian13@sha256:04c918f2165c67df6d4e2b255c76a3bab610b21f5d849d26b5fe31887e695a21
  BUSYBOX_REFERENCE: dhi/busybox:1.37.0-debian13@sha256:eb0e5b0b63bf4f8570e9d7d1787fc6c3be218dae07035de8fe41497778aa3338
  CHART_COMMIT_SHA: 55d909953430eb21f7226684309d503e934db6f5
  CHART_HELM_NAME: kube-prometheus-stack-chart
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  GRAFANA_CHART_REFERENCE: dhi/grafana-chart:12.11.2@sha256:8319e51b3d1a960aade16bf575e337beee1379036d17536c23700fe6617c74d9
  HELM_VERSION: 4.1.4-2
  KUBE_STATE_METRICS_CHART_REFERENCE: dhi/kube-state-metrics-chart:8.4.1@sha256:c21fe493faa064cc08ff237eaa30563ee3032440606197c0b0cc90755a2d53a3
  KUBE_WEBHOOK_CERTGEN_REFERENCE: dhi/kube-webhook-certgen:1.8.8-debian13@sha256:6aed899264ea93b2d78d387e35aab65390cb70f70712d153a70b78f90f58ab5c
  KUBECTL_REFERENCE: dhi/kubectl:1.36.4-debian13@sha256:f5d1e38dc82870673e06710665ee18147f89678613482a00a337a7dc572bdd48
  NODE_EXPORTER_CHART_REFERENCE: dhi/node-exporter-chart:4.56.3@sha256:ee43da36fda71cf0ff1d821b16c310818d0b8708afcfc35ea5cb891906753cf7
  PROMETHEUS_CONFIG_RELOADER_REFERENCE: dhi/prometheus-config-reloader:0.93.1-debian13@sha256:8d5d5fd139d10d3c9852c670017981700dbc61820e6b15d18fc5a82af85b1d08
  PROMETHEUS_OPERATOR_ADMISSION_WEBHOOK_REFERENCE: dhi/prometheus-operator-admission-webhook:0.93.1-debian13@sha256:76d03b6ab740673201e74b49cf7ee2909a4ffba4798772482cb67f860e72a253
  PROMETHEUS_OPERATOR_REFERENCE: dhi/prometheus-operator:0.93.1-debian13@sha256:2e801a3fe8c2004d11b6367831983858b0958e3f93e3a4167a7ca7c1fbc3fa30
  PROMETHEUS_REFERENCE: dhi/prometheus:3.14.0-debian13@sha256:f18dc10d186c66cf49d6e165f47bd5643dc27f760b20f9ff1d29c690f5da5808
  SEMVER_MAJOR_MINOR_VERSION: "88.6"
  SEMVER_MAJOR_VERSION: "88"
  SEMVER_VERSION: 88.6.4
  THANOS_REFERENCE: dhi/thanos:0.42.4-debian13@sha256:5d3f20ff8fa8e380b031046734c53931b4425ed2764a74fa151d13bbe0d76972
  VERSION: 88.6.4
contents:
  repositories:
    - deb [signed-by=/usr/share/keyrings/dhi-deb-main.gpg] http://dhi.io/deb/debian/main trixie main
  keyring:
    - https://dhi.io/keyring/dhi-deb-gpg.D46852F6925E9F71.key
  builds:
    - name: kube-prometheus-stack-chart
      contents:
        packages:
          - bash
          - ca-certificates
          - coreutils
          - yq-go
          - helm=4.1.4-2
        files:
          - url: git+https://github.com/prometheus-community/helm-charts.git#kube-prometheus-stack-88.6.4
            checksum: 55d909953430eb21f7226684309d503e934db6f5
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/kube-prometheus-stack
          with:
            chart:
              appRef: prometheus-operator
              dependencies:
                - condition: crds.enabled
                  keep: true
                  name: crds
                - alias: kube-state-metrics
                  condition: kubeStateMetrics.enabled
                  name: kube-state-metrics
                  ref: dhi/kube-state-metrics-chart:8.4.1@sha256:c21fe493faa064cc08ff237eaa30563ee3032440606197c0b0cc90755a2d53a3
                - alias: prometheus-node-exporter
                  condition: nodeExporter.enabled
                  name: node-exporter
                  ref: dhi/node-exporter-chart:4.56.3@sha256:ee43da36fda71cf0ff1d821b16c310818d0b8708afcfc35ea5cb891906753cf7
                - alias: grafana
                  condition: grafana.enabled
                  name: grafana
                  ref: dhi/grafana-chart:12.11.2@sha256:8319e51b3d1a960aade16bf575e337beee1379036d17536c23700fe6617c74d9
              description: Docker Hardened Images Helm chart for Kube Prometheus Stack
              images:
                - name: busybox
                  ref: dhi/busybox:1.37.0-debian13@sha256:eb0e5b0b63bf4f8570e9d7d1787fc6c3be218dae07035de8fe41497778aa3338
                - name: kubectl
                  ref: dhi/kubectl:1.36.4-debian13@sha256:f5d1e38dc82870673e06710665ee18147f89678613482a00a337a7dc572bdd48
                - name: alertmanager
                  ref: dhi/alertmanager:0.34.0-debian13@sha256:04c918f2165c67df6d4e2b255c76a3bab610b21f5d849d26b5fe31887e695a21
                - name: prometheus-operator-admission-webhook
                  ref: dhi/prometheus-operator-admission-webhook:0.93.1-debian13@sha256:76d03b6ab740673201e74b49cf7ee2909a4ffba4798772482cb67f860e72a253
                - name: kube-webhook-certgen
                  ref: dhi/kube-webhook-certgen:1.8.8-debian13@sha256:6aed899264ea93b2d78d387e35aab65390cb70f70712d153a70b78f90f58ab5c
                - name: prometheus-operator
                  ref: dhi/prometheus-operator:0.93.1-debian13@sha256:2e801a3fe8c2004d11b6367831983858b0958e3f93e3a4167a7ca7c1fbc3fa30
                - name: prometheus-config-reloader
                  ref: dhi/prometheus-config-reloader:0.93.1-debian13@sha256:8d5d5fd139d10d3c9852c670017981700dbc61820e6b15d18fc5a82af85b1d08
                - name: thanos
                  ref: dhi/thanos:0.42.4-debian13@sha256:5d3f20ff8fa8e380b031046734c53931b4425ed2764a74fa151d13bbe0d76972
                - name: prometheus
                  ref: dhi/prometheus:3.14.0-debian13@sha256:f18dc10d186c66cf49d6e165f47bd5643dc27f760b20f9ff1d29c690f5da5808
              name: kube-prometheus-stack-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/prometheus-community/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/kube-prometheus-stack
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update values
          uses: yq/patch@v1
          work-dir: ${source.dir}/helm-charts/charts/kube-prometheus-stack
          with:
            file: values.yaml
            patches:
              - del(.prometheus-windows-exporter)
        - name: helm login
          uses: helm/login@v1
          with:
            registry: dhi.io
        - name: pull dependencies
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          privileged: true
          with:
            chart: kube-prometheus-stack
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: kube-prometheus-stack
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: kube-prometheus-stack
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/kube-prometheus-stack/config
