# syntax=dhi.io/build:2-debian13

name: ArgoCD 3.4.x
image: dhi.io/argocd
variant: runtime
tags:
  - "3"
  - "3.4"
  - 3.4.1
  - 3-debian13
  - 3.4-debian13
  - 3.4.1-debian13
platforms:
  - linux/amd64
  - linux/arm64
dates:
  release: "2026-05-06"
vars:
  ARGOCD_USER_ID: "999"
  COMMIT_SHA: bafd59bd37138ed731d3c3aad8e18731d72aed46
  EXPAT_REF: dhi/pkg-expat:2.8.0-debian13@sha256:3f7e47c85e35abd2031652077771f838457f8762e6045d7cfdf5a68664d67310
  GIT_LFS_REF: dhi/pkg-git-lfs:3.7.1-debian13@sha256:2fbc870889703e10a6e1543ddad4fc40fe7e289e63a1d2e08492016e75125a39
  GOLANG_REFERENCE: dhi/golang:1.26.3-debian13-dev@sha256:972b3b41ae70170229bd24c019dd60465130be297739a9bb64d834c21ac1a27b
  HELM_REF: dhi/helm:3.20.2-debian13@sha256:ba27c299614df6cb958a5922dab4c91fb1446cfe383dc4c25005670ea9a1d954
  KUSTOMIZE_REF: dhi/kustomize:5.8.1-debian13@sha256:5e01d1cf17a687728c337fe35d2273253c7f71c05cf30154301aef0a0f8995c6
  NODE_REF: dhi/node:20.20.2-debian13-dev@sha256:f1a76fe106cffe8bb415ff517d7cbbe3378a4b59248b5f977ef75e226287d4cc
  SEMVER_MAJOR_MINOR_VERSION: "3.4"
  SEMVER_MAJOR_VERSION: "3"
  SEMVER_VERSION: 3.4.1
  VERSION: 3.4.1
contents:
  packages:
    - '!libelogind0'
    - '!libexpat1'
    - '!mawk'
    - '!original-awk'
    - base-files
    - ca-certificates
    - coreutils
    - dash
    - git
    - gnupg
    - gpg
    - gpg-agent
    - openssh-client
    - tini
    - tzdata
  builds:
    - name: argocd-go
      uses: dhi.io/golang:1.26.3-debian13-dev@sha256:972b3b41ae70170229bd24c019dd60465130be297739a9bb64d834c21ac1a27b
      contents:
        packages:
          - curl
          - git
          - gnupg
          - gpg
          - gpg-agent
          - grep
          - gzip
          - openssh-client
          - sed
        files:
          - url: git+https://github.com/argoproj/argo-cd.git#v3.4.1
            checksum: bafd59bd37138ed731d3c3aad8e18731d72aed46
            path: /go/src/github.com/argoproj/argo-cd/v3
            spdx:
              name: argocd
              version: 3.4.1
              packages:
                - name: argocd
                  purl: pkg:dhi/argocd@3.4.1
                  license: Apache-2.0
            uid: 0
            gid: 0
        artifacts:
          - name: dhi.io/node:20.20.2-debian13-dev@sha256:f1a76fe106cffe8bb415ff517d7cbbe3378a4b59248b5f977ef75e226287d4cc
            includes:
              - opt/nodejs
              - opt/yarn
              - usr/local/bin/node
              - usr/local/bin/yarn
            uid: 0
            gid: 0
          - name: dhi.io/helm:3.20.2-debian13@sha256:ba27c299614df6cb958a5922dab4c91fb1446cfe383dc4c25005670ea9a1d954
            includes:
              - opt/**
              - usr/**
            uid: 0
            gid: 0
          - name: dhi.io/pkg-git-lfs:3.7.1-debian13@sha256:2fbc870889703e10a6e1543ddad4fc40fe7e289e63a1d2e08492016e75125a39
            includes:
              - opt/**
              - usr/**
            uid: 0
            gid: 0
          - name: dhi.io/kustomize:5.8.1-debian13@sha256:5e01d1cf17a687728c337fe35d2273253c7f71c05cf30154301aef0a0f8995c6
            includes:
              - opt/**
              - usr/**
            uid: 0
            gid: 0
      pipeline:
        - name: patch-go (3.4 only)
          uses: go/bump@v1
          work-dir: /go/src/github.com/argoproj/argo-cd/v3
          caches:
            - path: /go/pkg/mod
          with:
            deps:
              - github.com/cloudflare/circl@v1.6.3
              - github.com/go-git/go-git/v5@v5.18.0
              - github.com/moby/spdystream@v0.5.1
              - go.opentelemetry.io/otel/sdk@v1.43.0
            download: true
        - name: patch-node
          uses: yarn/bump@v2
          caches:
            - path: /usr/local/share/.cache/yarn
          with:
            bumps: ${source.dir}/patches/yarn-patches-3.4.json
            yarn-root: /go/src/github.com/argoproj/argo-cd/v3/ui
        - name: build-ui
          work-dir: /go/src/github.com/argoproj/argo-cd/v3/ui
          privileged: true
          caches:
            - path: /usr/local/share/.cache/yarn
          runs: |
            set -eux -o pipefail

            yarn
            yarn run build
        - name: prepare ui for sbom
          work-dir: /go/src/github.com/argoproj/argo-cd/v3/ui
          privileged: true
          caches:
            - path: /usr/local/share/.cache/yarn
          runs: |
            set -eux -o pipefail

            rm -rf node_modules
            # tsx is included in the dependencies of argocd-ui but should not.
            yarn remove tsx
            # Issue opened: https://github.com/argoproj/argo-cd/issues/24978
            yarn remove react-hot-loader # CVE-2025-57352
            yarn install --production
        - name: ui-sbom
          uses: sbom@v1
          with:
            prefix: argocd-ui
            source: /go/src/github.com/argoproj/argo-cd/v3/ui
        - name: build
          uses: go/build@v1
          work-dir: /go/src/github.com/argoproj/argo-cd/v3
          environment:
            GODEBUG: tarinsecurepath=0,zipinsecurepath=0
          caches:
            - path: /go/pkg/mod
          with:
            ldflags:
              - -extldflags '-static'
              - -X github.com/argoproj/argo-cd/v3/common.version=3.4.1
              - -X github.com/argoproj/argo-cd/v3/common.gitTag=v3.4.1
              - -X github.com/argoproj/argo-cd/v3/common.buildDate=$(date -ud @${SOURCE_DATE_EPOCH} +'%Y-%m-%dT%H:%M:%SZ')
              - -X github.com/argoproj/argo-cd/v3/common.gitCommit=bafd59bd37138ed731d3c3aad8e18731d72aed46
              - -X github.com/argoproj/argo-cd/v3/common.gitTreeState=clean
              - -X github.com/argoproj/argo-cd/v3/common.kubectlVersion=$(go list -m k8s.io/client-go | head -n 1 | rev | cut -d' ' -f1 | rev)
            output: ${target.dir}/usr/local/bin/argocd
            packages: ./cmd
            tidy: true
      paths:
        - type: file
          path: /src/patches/yarn-patches-3.4.json
          uid: 0
          gid: 0
          source: image/argocd/patch/yarn-patches-3.4.json
      outputs:
        - source: ${target.dir}/usr/local/bin/argocd
          target: /usr/local/bin/argocd
          uid: 0
          gid: 0
        - source: /go/src/github.com/argoproj/argo-cd/v3/hack/gpg-wrapper.sh
          target: /usr/local/bin/gpg-wrapper.sh
          uid: 0
          gid: 0
        - source: /go/src/github.com/argoproj/argo-cd/v3/hack/git-verify-wrapper.sh
          target: /usr/local/bin/git-verify-wrapper.sh
          uid: 0
          gid: 0
        - source: /opt/docker/sbom/argocd
          target: /opt/docker/sbom/argocd
          uid: 0
          gid: 0
        - source: /opt/docker/sbom/argocd-ui
          target: /opt/docker/sbom/argocd-ui
          uid: 0
          gid: 0
  artifacts:
    - name: dhi.io/pkg-expat:2.8.0-debian13@sha256:3f7e47c85e35abd2031652077771f838457f8762e6045d7cfdf5a68664d67310
      includes:
        - opt/**
        - usr/**
        - var/lib/dpkg/status.d
      uid: 0
      gid: 0
    - name: dhi.io/helm:3.20.2-debian13@sha256:ba27c299614df6cb958a5922dab4c91fb1446cfe383dc4c25005670ea9a1d954
      includes:
        - opt/**
        - usr/**
      uid: 0
      gid: 0
    - name: dhi.io/pkg-git-lfs:3.7.1-debian13@sha256:2fbc870889703e10a6e1543ddad4fc40fe7e289e63a1d2e08492016e75125a39
      includes:
        - opt/**
        - usr/**
      uid: 0
      gid: 0
    - name: dhi.io/kustomize:5.8.1-debian13@sha256:5e01d1cf17a687728c337fe35d2273253c7f71c05cf30154301aef0a0f8995c6
      includes:
        - opt/**
        - usr/**
      uid: 0
      gid: 0
accounts:
  run-as: "999"
  users:
    - name: argocd
      uid: 999
      gid: 999
  groups:
    - name: argocd
      gid: 999
      members:
        - argocd
os-release:
  name: Docker Hardened Images (Debian)
  id: debian
  version-id: "13"
  version-codename: trixie
  pretty-name: Docker Hardened Images/Debian GNU/Linux 13 (trixie)
  home-url: https://docker.com/products/hardened-images/
  bug-report-url: https://docker.com/support/
environment:
  ARGOCD_USER_ID: "999"
paths:
  - type: emptyfile
    path: /app/config/ssh/ssh_known_hosts
    uid: 0
    gid: 0
  - type: directory
    path: /etc/ssh
    uid: 0
    gid: 0
  - type: symlink
    path: /etc/ssh/ssh_known_hosts
    uid: 0
    gid: 0
    source: /app/config/ssh/ssh_known_hosts
  - type: directory
    path: /app/config/gpg/source
    uid: 0
    gid: 0
    recursive: true
  - type: directory
    path: /app/config/gpg/keys
    uid: 999
    gid: 999
    mode: "0700"
    recursive: true
  - type: symlink
    path: /usr/local/bin/argocd-server
    uid: 0
    gid: 0
    source: /usr/local/bin/argocd
  - type: symlink
    path: /usr/local/bin/argocd-repo-server
    uid: 0
    gid: 0
    source: /usr/local/bin/argocd
  - type: symlink
    path: /usr/local/bin/argocd-cmp-server
    uid: 0
    gid: 0
    source: /usr/local/bin/argocd
  - type: symlink
    path: /usr/local/bin/argocd-application-controller
    uid: 0
    gid: 0
    source: /usr/local/bin/argocd
  - type: symlink
    path: /usr/local/bin/argocd-dex
    uid: 0
    gid: 0
    source: /usr/local/bin/argocd
  - type: symlink
    path: /usr/local/bin/argocd-notifications
    uid: 0
    gid: 0
    source: /usr/local/bin/argocd
  - type: symlink
    path: /usr/local/bin/argocd-applicationset-controller
    uid: 0
    gid: 0
    source: /usr/local/bin/argocd
  - type: symlink
    path: /usr/local/bin/argocd-k8s-auth
    uid: 0
    gid: 0
    source: /usr/local/bin/argocd
  - type: symlink
    path: /usr/local/bin/argocd-commit-server
    uid: 0
    gid: 0
    source: /usr/local/bin/argocd
annotations:
  org.opencontainers.image.description: A minimal ArgoCD image
  org.opencontainers.image.licenses: Apache-2.0
entrypoint:
  - /usr/bin/tini
  - --
