# syntax=dhi.io/build:2-helm3

name: MongoDB Helm chart 18.x
image: dhi.io/mongodb-chart
variant: helm
tags:
  - 18.0.2
platforms:
  - linux/amd64
vars:
  BASH_REFERENCE: dhi/bash:5.2.37-debian13-compat@sha256:9d6eda9f7d4d5f36aa03ebd77bffe7c4c7f9e5162273fd78259454426fe04de4
  CHART_COMMIT_SHA: a817233509d8cc7dca1345d5ca109a944b4f7a8b
  CHART_HELM_NAME: mongodb-chart
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_VERSION: 4.1.4-2
  KUBECTL_REFERENCE: dhi/kubectl:1.34.12-debian13-compat@sha256:5345f9a09f21035f5af7833678ea315420a4e2b2bc2c9b64bd7cbf457d41a09a
  MONGODB_EXPORTER_REFERENCE: dhi/mongodb-exporter:0.53.0-debian13-compat@sha256:3cc8133ad5de9fa176a3f5c2c1b8687a81bd29c8db502fdaea2bf6b9a4e53b45
  MONGODB_REFERENCE: dhi/mongodb:8.3.11-debian13-compat@sha256:0183546c954bef67e0304d41baefae4bacbecb23fd6afc37480cdb2881c67bfd
  NGINX_REFERENCE: dhi/nginx:1.31.6-debian13-compat@sha256:58804c02659c54921802735fd67ae98ced29e59001c27a6b1d6e68b997c2948a
  SEMVER_MAJOR_MINOR_VERSION: "18.0"
  SEMVER_MAJOR_VERSION: "18"
  SEMVER_VERSION: 18.0.2
  VERSION: 18.0.2
contents:
  repositories:
    - deb [signed-by=/usr/share/keyrings/dhi-deb-main.gpg] http://dhi.io/deb/debian/main trixie main
  keyring:
    - https://dhi.io/keyring/dhi-deb-gpg.D46852F6925E9F71.key
  builds:
    - name: mongodb
      work-dir: ${source.dir}/helm-charts/mongodb
      contents:
        packages:
          - bash
          - ca-certificates
          - coreutils
          - helm=4.1.4-2
        files:
          - url: git+https://github.com/docker-hardened-images/helm-charts.git#mongodb/18.0.2
            checksum: a817233509d8cc7dca1345d5ca109a944b4f7a8b
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          with:
            chart:
              appRef: mongodb
              description: Docker Hardened Images Helm chart for MongoDB
              images:
                - name: mongodb
                  ref: dhi/mongodb:8.3.11-debian13-compat@sha256:0183546c954bef67e0304d41baefae4bacbecb23fd6afc37480cdb2881c67bfd
                - name: mongodb-exporter
                  ref: dhi/mongodb-exporter:0.53.0-debian13-compat@sha256:3cc8133ad5de9fa176a3f5c2c1b8687a81bd29c8db502fdaea2bf6b9a4e53b45
                - name: nginx
                  ref: dhi/nginx:1.31.6-debian13-compat@sha256:58804c02659c54921802735fd67ae98ced29e59001c27a6b1d6e68b997c2948a
                - name: kubectl
                  ref: dhi/kubectl:1.34.12-debian13-compat@sha256:5345f9a09f21035f5af7833678ea315420a4e2b2bc2c9b64bd7cbf457d41a09a
                - name: bash
                  ref: dhi/bash:5.2.37-debian13-compat@sha256:9d6eda9f7d4d5f36aa03ebd77bffe7c4c7f9e5162273fd78259454426fe04de4
              name: mongodb-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/docker-hardened-images/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: update chart values
          uses: helm/rudder@v1
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          privileged: true
          with:
            chart: .
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          with:
            chart: .
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: .
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/mongodb/config
