# syntax=dhi.io/build:2-helm3

name: Prometheus Node Exporter Helm chart 4.x
image: dhi.io/node-exporter-chart
variant: helm
tags:
  - 4.59.0
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: ea0da98ddae1bd6a3457e39cd8ca70d56b5138a6
  CHART_HELM_NAME: node-exporter-chart
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_VERSION: 4.1.4-2
  KUBE_RBAC_PROXY_REFERENCE: dhi/kube-rbac-proxy:0.22.1-debian13@sha256:48101a5d042182bdc2138e031c8094a090e2214d1c2d26ffd79291e2bacbf9df
  NODE_EXPORTER_REFERENCE: dhi/node-exporter:1.12.1-debian13@sha256:09e7c92c4ff5f925adb2c66e2728596c47c7a8e070bf3236401783fa429a15ac
  SEMVER_MAJOR_MINOR_VERSION: "4.59"
  SEMVER_MAJOR_VERSION: "4"
  SEMVER_VERSION: 4.59.0
  VERSION: 4.59.0
contents:
  repositories:
    - deb [signed-by=/usr/share/keyrings/dhi-deb-main.gpg] http://dhi.io/deb/debian/main trixie main
  keyring:
    - https://dhi.io/keyring/dhi-deb-gpg.D46852F6925E9F71.key
  builds:
    - name: node-exporter-chart
      contents:
        packages:
          - bash
          - ca-certificates
          - coreutils
          - helm=4.1.4-2
        files:
          - url: git+https://github.com/prometheus-community/helm-charts.git#prometheus-node-exporter-4.59.0
            checksum: ea0da98ddae1bd6a3457e39cd8ca70d56b5138a6
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/prometheus-node-exporter
          with:
            chart:
              appRef: node-exporter
              description: Docker Hardened Images Helm chart for Prometheus Node Exporter
              images:
                - name: node-exporter
                  ref: dhi/node-exporter:1.12.1-debian13@sha256:09e7c92c4ff5f925adb2c66e2728596c47c7a8e070bf3236401783fa429a15ac
                - name: kube-rbac-proxy
                  ref: dhi/kube-rbac-proxy:0.22.1-debian13@sha256:48101a5d042182bdc2138e031c8094a090e2214d1c2d26ffd79291e2bacbf9df
              name: node-exporter-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/prometheus-community/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/prometheus-node-exporter
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          privileged: true
          with:
            chart: prometheus-node-exporter
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: prometheus-node-exporter
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: prometheus-node-exporter
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/node-exporter/config
