# syntax=dhi.io/build:2-helm3

name: Prometheus Node Exporter Helm chart 4.x
image: dhi.io/node-exporter-chart
variant: helm
tags:
  - 4.52.1
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: c6b6050abd74951faf2c11112732da094014497c
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.20.1-debian13-dev@sha256:a2c1b2e1c9d947d8feabde6c5ae3d2f9b1f0883a4d6cd01d49ccb0e509465920
  KUBE_RBAC_PROXY_REFERENCE: dhi/kube-rbac-proxy:0.21.1-debian13@sha256:65698effc3edab390057ed439b9d300a7c329ddc08be6dfc9bc4c90441141442
  NODE_EXPORTER_REFERENCE: dhi/node-exporter:1.10.2-debian13@sha256:5ae118df49732b7dd2218e5009654f6ae5def309cac02702d790c1fbf5c82c26
  SEMVER_MAJOR_MINOR_VERSION: "4.52"
  SEMVER_MAJOR_VERSION: "4"
  SEMVER_VERSION: 4.52.1
  VERSION: 4.52.1
contents:
  builds:
    - name: node-exporter-chart
      uses: dhi.io/helm:3.20.1-debian13-dev@sha256:a2c1b2e1c9d947d8feabde6c5ae3d2f9b1f0883a4d6cd01d49ccb0e509465920
      contents:
        files:
          - url: git+https://github.com/prometheus-community/helm-charts.git#prometheus-node-exporter-4.52.1
            checksum: c6b6050abd74951faf2c11112732da094014497c
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/prometheus-node-exporter
          with:
            chart:
              appRef: node-exporter
              description: Docker Hardened Images Helm chart for Prometheus Node Exporter
              images:
                - name: node-exporter
                  ref: dhi/node-exporter:1.10.2-debian13@sha256:5ae118df49732b7dd2218e5009654f6ae5def309cac02702d790c1fbf5c82c26
                - name: kube-rbac-proxy
                  ref: dhi/kube-rbac-proxy:0.21.1-debian13@sha256:65698effc3edab390057ed439b9d300a7c329ddc08be6dfc9bc4c90441141442
              name: node-exporter-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/prometheus-community/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/prometheus-node-exporter
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          privileged: true
          with:
            chart: prometheus-node-exporter
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: prometheus-node-exporter
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: prometheus-node-exporter
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/node-exporter/config
