# syntax=dhi.io/build:2-helm3

name: Kyverno Helm chart 3.7.x
image: dhi.io/kyverno-chart
variant: helm
tags:
  - 3.7.2
platforms:
  - linux/amd64
vars:
  APPVERSION: 1.17.2
  CHART_COMMIT_SHA: eafa8fe9fe933a6314feaa9dcb49b700a9bc74a5
  CHART_HELM_NAME: kyverno-chart
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_VERSION: 4.1.4-2
  KUBECTL_REFERENCE: dhi/kubectl:1.35.8-debian13@sha256:c8034e53067ba36fe7cfd8fd274de199eeb4b265052d8bb826ccc11c2e2cefd7
  KYVERNO_BACKGROUND_CONTROLLER_REFERENCE: dhi/kyverno-background-controller:1.17.2-debian13@sha256:c4421d380b4a647b0563f2e8f9d4f3bd81322c9a6697d7735569c37c2ac6dabd
  KYVERNO_CLEANUP_CONTROLLER_REFERENCE: dhi/kyverno-cleanup-controller:1.17.2-debian13@sha256:fdcb3cf3eaaf48b2027d3595c0c1d74a2f57aaebf9eb6889b1c0d4d6acbd5708
  KYVERNO_CLI_REFERENCE: dhi/kyverno-cli:1.17.2-debian13@sha256:1a8299c263563fbf8681c4ba8a6f9af4931c0a4eaee1ff33825bc3a5b4192746
  KYVERNO_INIT_REFERENCE: dhi/kyverno-init:1.17.2-debian13@sha256:bfbc9f42af0a77aa1abf6f2c9fead5a81ea9ae0626fe98a02d0d9220f6d1c97f
  KYVERNO_READINESS_CHECKER_REFERENCE: dhi/kyverno-readiness-checker:1.17.2-debian13@sha256:41b0828ec4aa3a4dd4bf99d24d4edc64936ac59c22a785bb395c2f9a253202a9
  KYVERNO_REFERENCE: dhi/kyverno:1.17.2-debian13@sha256:cdca8b23780c7ee7f2e96044876287a4541392db80ddad437ca1229808150e03
  KYVERNO_REPORTS_CONTROLLER_REFERENCE: dhi/kyverno-reports-controller:1.17.2-debian13@sha256:8de782e28a15486341686d09e4d7dae53bf62118ba9b757c1720003005787d17
  KYVERNO_REPORTS_SERVER_CHART_REFERENCE: dhi/kyverno-reports-server-chart:0.1.7@sha256:18177152757ad83d846604c9ee1a05b7067e5a9c7b356b7f311a2d842301e33e
  SEMVER_MAJOR_MINOR_VERSION: "3.7"
  SEMVER_MAJOR_VERSION: "3"
  SEMVER_VERSION: 3.7.2
  VERSION: 3.7.2
contents:
  repositories:
    - deb [signed-by=/usr/share/keyrings/dhi-deb-main.gpg] http://dhi.io/deb/debian/main trixie main
  keyring:
    - https://dhi.io/keyring/dhi-deb-gpg.D46852F6925E9F71.key
  builds:
    - name: kyverno-chart
      work-dir: ${source.dir}/helm-charts/charts/kyverno
      contents:
        packages:
          - bash
          - ca-certificates
          - coreutils
          - helm=4.1.4-2
        files:
          - url: git+https://github.com/kyverno/kyverno.git#kyverno-chart-3.7.2
            checksum: eafa8fe9fe933a6314feaa9dcb49b700a9bc74a5
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          with:
            chart:
              appRef: kyverno
              dependencies:
                - condition: crds.install
                  keep: true
                  name: crds
                - condition: grafana.enabled
                  keep: true
                  name: grafana
                - condition: crds.install
                  keep: true
                  name: kyverno-api
                - condition: openreports.installCrds
                  keep: true
                  name: openreports
                - alias: reports-server
                  condition: reportsServer.enabled
                  name: kyverno-reports-server
                  ref: dhi/kyverno-reports-server-chart:0.1.7@sha256:18177152757ad83d846604c9ee1a05b7067e5a9c7b356b7f311a2d842301e33e
              description: Docker Hardened Images Helm chart for Kyverno
              images:
                - name: kyverno
                  ref: dhi/kyverno:1.17.2-debian13@sha256:cdca8b23780c7ee7f2e96044876287a4541392db80ddad437ca1229808150e03
                - name: kyverno-cli
                  ref: dhi/kyverno-cli:1.17.2-debian13@sha256:1a8299c263563fbf8681c4ba8a6f9af4931c0a4eaee1ff33825bc3a5b4192746
                - name: kyverno-readiness-checker
                  ref: dhi/kyverno-readiness-checker:1.17.2-debian13@sha256:41b0828ec4aa3a4dd4bf99d24d4edc64936ac59c22a785bb395c2f9a253202a9
                - name: kubectl
                  ref: dhi/kubectl:1.35.8-debian13@sha256:c8034e53067ba36fe7cfd8fd274de199eeb4b265052d8bb826ccc11c2e2cefd7
                - name: kyverno-init
                  ref: dhi/kyverno-init:1.17.2-debian13@sha256:bfbc9f42af0a77aa1abf6f2c9fead5a81ea9ae0626fe98a02d0d9220f6d1c97f
                - name: kyverno-background-controller
                  ref: dhi/kyverno-background-controller:1.17.2-debian13@sha256:c4421d380b4a647b0563f2e8f9d4f3bd81322c9a6697d7735569c37c2ac6dabd
                - name: kyverno-cleanup-controller
                  ref: dhi/kyverno-cleanup-controller:1.17.2-debian13@sha256:fdcb3cf3eaaf48b2027d3595c0c1d74a2f57aaebf9eb6889b1c0d4d6acbd5708
                - name: kyverno-reports-controller
                  ref: dhi/kyverno-reports-controller:1.17.2-debian13@sha256:8de782e28a15486341686d09e4d7dae53bf62118ba9b757c1720003005787d17
              name: kyverno-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/kyverno/kyverno
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: patch version specific values
          uses: helm/rudder@v1
          with:
            cmd: patch
            patches:
              apply:
                - "on": values.yaml
                  patch: ${source.dir}/config/values-3.7.yaml
            registry: dhi.io
        - name: helm login
          uses: helm/login@v1
          with:
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          privileged: true
          with:
            chart: kyverno
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          with:
            chart: .
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: .
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/kyverno/config
