# syntax=dhi.io/build:2-helm3

name: Kyverno Helm chart 3.7.x
image: dhi.io/kyverno-chart
variant: helm
tags:
  - 3.7.2
platforms:
  - linux/amd64
vars:
  APPVERSION: 1.17.2
  CHART_COMMIT_SHA: eafa8fe9fe933a6314feaa9dcb49b700a9bc74a5
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.21.0-debian13-dev@sha256:ce37cdc271f28789f84db63c8fe5d86522cc98922637f8dde8c2aca4f0cc1632
  KUBECTL_IMAGE_REFERENCE: dhi/kubectl:1.35.5-debian13@sha256:a5e7a22a5c4a56c1ffd4dd63e4ad11ea531d422546219194706d1d65a713e2dd
  KYVERNO_BACKGROUND_CONTROLLER_IMAGE_REFERENCE: dhi/kyverno-background-controller:1.17.2-debian13@sha256:8ae8090b3788536b5afc8f60bb3e36b2e19f05a0354fa775a29a46e0fdbe8516
  KYVERNO_CLEANUP_CONTROLLER_IMAGE_REFERENCE: dhi/kyverno-cleanup-controller:1.17.2-debian13@sha256:c61d6f3c20c8aff45ecf174aa141770a879519f3db6e80d1426c01689d409cd7
  KYVERNO_CLI_IMAGE_REFERENCE: dhi/kyverno-cli:1.17.2-debian13@sha256:d14981259863fa19786c32a8ef84b6b069f914c1a914b80350a550588a4a5a3f
  KYVERNO_IMAGE_REFERENCE: dhi/kyverno:1.17.2-debian13@sha256:faed4e6fcf8110882cb41c739e53050762d2574add765543abcb913309ff6289
  KYVERNO_INIT_IMAGE_REFERENCE: dhi/kyverno-init:1.17.2-debian13@sha256:9f0989b0cd3b576dfb4eda49da914a9cbb1c6cd4a02385ce62b89b4ef672d76e
  KYVERNO_READINESS_CHECKER_IMAGE_REFERENCE: dhi/kyverno-readiness-checker:1.17.2-debian13@sha256:c7560a24c514f92425d8cc3af506e6f7fb5fd64636decb8a5f0272b54b42d2b6
  KYVERNO_REPORTS_CONTROLLER_IMAGE_REFERENCE: dhi/kyverno-reports-controller:1.17.2-debian13@sha256:07bb4db28938334f828520680dc21be874988199b02e4cdcc0ee0a3587f59429
  KYVERNO_REPORTS_SERVER_CHART_REFERENCE: dhi/kyverno-reports-server-chart:0.1.7@sha256:f0956d7baacbe73d9380b9846b65593cf4a0d2a7452f12e345ed7f24f12bde7b
  SEMVER_MAJOR_MINOR_VERSION: "3.7"
  SEMVER_MAJOR_VERSION: "3"
  SEMVER_VERSION: 3.7.2
  VERSION: 3.7.2
contents:
  builds:
    - name: kyverno-chart
      uses: dhi.io/helm:3.21.0-debian13-dev@sha256:ce37cdc271f28789f84db63c8fe5d86522cc98922637f8dde8c2aca4f0cc1632
      work-dir: ${source.dir}/helm-charts/charts/kyverno
      contents:
        files:
          - url: git+https://github.com/kyverno/kyverno.git#kyverno-chart-3.7.2
            checksum: eafa8fe9fe933a6314feaa9dcb49b700a9bc74a5
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          with:
            chart:
              appRef: kyverno
              dependencies:
                - condition: crds.install
                  keep: true
                  name: crds
                - condition: grafana.enabled
                  keep: true
                  name: grafana
                - condition: crds.install
                  keep: true
                  name: kyverno-api
                - condition: openreports.installCrds
                  keep: true
                  name: openreports
                - alias: reports-server
                  condition: reportsServer.enabled
                  name: kyverno-reports-server
                  ref: dhi/kyverno-reports-server-chart:0.1.7@sha256:f0956d7baacbe73d9380b9846b65593cf4a0d2a7452f12e345ed7f24f12bde7b
              description: Docker Hardened Images Helm chart for Kyverno
              images:
                - name: kyverno
                  ref: dhi/kyverno:1.17.2-debian13@sha256:faed4e6fcf8110882cb41c739e53050762d2574add765543abcb913309ff6289
                - name: kyverno-cli
                  ref: dhi/kyverno-cli:1.17.2-debian13@sha256:d14981259863fa19786c32a8ef84b6b069f914c1a914b80350a550588a4a5a3f
                - name: kyverno-readiness-checker
                  ref: dhi/kyverno-readiness-checker:1.17.2-debian13@sha256:c7560a24c514f92425d8cc3af506e6f7fb5fd64636decb8a5f0272b54b42d2b6
                - name: kubectl
                  ref: dhi/kubectl:1.35.5-debian13@sha256:a5e7a22a5c4a56c1ffd4dd63e4ad11ea531d422546219194706d1d65a713e2dd
                - name: kyverno-init
                  ref: dhi/kyverno-init:1.17.2-debian13@sha256:9f0989b0cd3b576dfb4eda49da914a9cbb1c6cd4a02385ce62b89b4ef672d76e
                - name: kyverno-background-controller
                  ref: dhi/kyverno-background-controller:1.17.2-debian13@sha256:8ae8090b3788536b5afc8f60bb3e36b2e19f05a0354fa775a29a46e0fdbe8516
                - name: kyverno-cleanup-controller
                  ref: dhi/kyverno-cleanup-controller:1.17.2-debian13@sha256:c61d6f3c20c8aff45ecf174aa141770a879519f3db6e80d1426c01689d409cd7
                - name: kyverno-reports-controller
                  ref: dhi/kyverno-reports-controller:1.17.2-debian13@sha256:07bb4db28938334f828520680dc21be874988199b02e4cdcc0ee0a3587f59429
              name: kyverno-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/kyverno/kyverno
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: helm login
          uses: helm/login@v1
          with:
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          privileged: true
          with:
            chart: kyverno
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          with:
            chart: .
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: .
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/kyverno/config
