# syntax=dhi.io/build:2-helm3

name: Kyverno Helm chart 3.7.x
image: dhi.io/kyverno-chart
variant: helm
tags:
  - 3.7.2
platforms:
  - linux/amd64
vars:
  APPVERSION: 1.17.2
  CHART_COMMIT_SHA: eafa8fe9fe933a6314feaa9dcb49b700a9bc74a5
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.21.0-debian13-dev@sha256:ed0c764ca91c1084c850f3b00e7248f9127153bb3a5803058a337ac99ba6d479
  KUBECTL_IMAGE_REFERENCE: dhi/kubectl:1.35.5-debian13@sha256:b3fae1410cf4eb76b669f868679a35756ad52535d4988a6eb73baef34c74c181
  KYVERNO_BACKGROUND_CONTROLLER_IMAGE_REFERENCE: dhi/kyverno-background-controller:1.17.2-debian13@sha256:ae1edb8489b0f47013957c21e7b2c5b6dc7f3c4b816db3ff209dc2b5fa6f52a7
  KYVERNO_CLEANUP_CONTROLLER_IMAGE_REFERENCE: dhi/kyverno-cleanup-controller:1.17.2-debian13@sha256:86fb73dad07e8035def4c7ceb56e074b65e1601ce38547a94a9eab30e7742fed
  KYVERNO_CLI_IMAGE_REFERENCE: dhi/kyverno-cli:1.17.2-debian13@sha256:06f5d0cc866c5a9ff9f38f7e92bb7c0fd348b84f197c8d5af2dd6bfeefeecc2d
  KYVERNO_IMAGE_REFERENCE: dhi/kyverno:1.17.2-debian13@sha256:9c721206bc81eabf7f2578ff4e557ba2ca3e87fd28c95e1a9e976c6ddeb49ec2
  KYVERNO_INIT_IMAGE_REFERENCE: dhi/kyverno-init:1.17.2-debian13@sha256:0bbac0ce508132d2f43c4ba93201d7619e4fbb1f191d497c0e0fe3b0129c997d
  KYVERNO_READINESS_CHECKER_IMAGE_REFERENCE: dhi/kyverno-readiness-checker:1.17.2-debian13@sha256:e428fe076205fd0cef54a1bc9d164ee81f08466daab0d3576ef1ac4627153826
  KYVERNO_REPORTS_CONTROLLER_IMAGE_REFERENCE: dhi/kyverno-reports-controller:1.17.2-debian13@sha256:9dbeff8a6fa1556b98972867a33c04215c2db81e867408b682f63c14d58f230b
  KYVERNO_REPORTS_SERVER_CHART_REFERENCE: dhi/kyverno-reports-server-chart:0.1.7@sha256:46136c61407fadabbcfe5ccdd4374cb8950a3c0529190487b45b30e75f18ee01
  SEMVER_MAJOR_MINOR_VERSION: "3.7"
  SEMVER_MAJOR_VERSION: "3"
  SEMVER_VERSION: 3.7.2
  VERSION: 3.7.2
contents:
  builds:
    - name: kyverno-chart
      uses: dhi.io/helm:3.21.0-debian13-dev@sha256:ed0c764ca91c1084c850f3b00e7248f9127153bb3a5803058a337ac99ba6d479
      work-dir: ${source.dir}/helm-charts/charts/kyverno
      contents:
        files:
          - url: git+https://github.com/kyverno/kyverno.git#kyverno-chart-3.7.2
            checksum: eafa8fe9fe933a6314feaa9dcb49b700a9bc74a5
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          with:
            chart:
              appRef: kyverno
              dependencies:
                - condition: crds.install
                  keep: true
                  name: crds
                - condition: grafana.enabled
                  keep: true
                  name: grafana
                - condition: crds.install
                  keep: true
                  name: kyverno-api
                - condition: openreports.installCrds
                  keep: true
                  name: openreports
                - alias: reports-server
                  condition: reportsServer.enabled
                  name: kyverno-reports-server
                  ref: dhi/kyverno-reports-server-chart:0.1.7@sha256:46136c61407fadabbcfe5ccdd4374cb8950a3c0529190487b45b30e75f18ee01
              description: Docker Hardened Images Helm chart for Kyverno
              images:
                - name: kyverno
                  ref: dhi/kyverno:1.17.2-debian13@sha256:9c721206bc81eabf7f2578ff4e557ba2ca3e87fd28c95e1a9e976c6ddeb49ec2
                - name: kyverno-cli
                  ref: dhi/kyverno-cli:1.17.2-debian13@sha256:06f5d0cc866c5a9ff9f38f7e92bb7c0fd348b84f197c8d5af2dd6bfeefeecc2d
                - name: kyverno-readiness-checker
                  ref: dhi/kyverno-readiness-checker:1.17.2-debian13@sha256:e428fe076205fd0cef54a1bc9d164ee81f08466daab0d3576ef1ac4627153826
                - name: kubectl
                  ref: dhi/kubectl:1.35.5-debian13@sha256:b3fae1410cf4eb76b669f868679a35756ad52535d4988a6eb73baef34c74c181
                - name: kyverno-init
                  ref: dhi/kyverno-init:1.17.2-debian13@sha256:0bbac0ce508132d2f43c4ba93201d7619e4fbb1f191d497c0e0fe3b0129c997d
                - name: kyverno-background-controller
                  ref: dhi/kyverno-background-controller:1.17.2-debian13@sha256:ae1edb8489b0f47013957c21e7b2c5b6dc7f3c4b816db3ff209dc2b5fa6f52a7
                - name: kyverno-cleanup-controller
                  ref: dhi/kyverno-cleanup-controller:1.17.2-debian13@sha256:86fb73dad07e8035def4c7ceb56e074b65e1601ce38547a94a9eab30e7742fed
                - name: kyverno-reports-controller
                  ref: dhi/kyverno-reports-controller:1.17.2-debian13@sha256:9dbeff8a6fa1556b98972867a33c04215c2db81e867408b682f63c14d58f230b
              name: kyverno-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/kyverno/kyverno
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: helm login
          uses: helm/login@v1
          with:
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          privileged: true
          with:
            chart: kyverno
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          with:
            chart: .
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: .
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/kyverno/config
