# syntax=dhi.io/build:2-helm3

name: Kyverno Helm chart 3.8.x
image: dhi.io/kyverno-chart
variant: helm
tags:
  - 3.8.2
platforms:
  - linux/amd64
vars:
  APPVERSION: 1.18.2
  CHART_COMMIT_SHA: 0591bee075db55030d8d2e841f32f5c4ef5c85aa
  CHART_HELM_NAME: kyverno-chart
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_VERSION: 4.1.4-2
  KUBECTL_REFERENCE: dhi/kubectl:1.35.7-debian13@sha256:ad1c264b4072a3afa666a0cb220e36324e2f7dc0f23a4a79e73b7da151a04cd4
  KYVERNO_BACKGROUND_CONTROLLER_REFERENCE: dhi/kyverno-background-controller:1.18.2-debian13@sha256:ed11e4c196b53684cc0ebc3c26c512d0103b4cce4e3068a004d903e9ad553008
  KYVERNO_CLEANUP_CONTROLLER_REFERENCE: dhi/kyverno-cleanup-controller:1.18.2-debian13@sha256:3644ca9e0a9ee2e1aa3887379234aa295c90c601e3b31445cb5fdd4a76019f50
  KYVERNO_CLI_REFERENCE: dhi/kyverno-cli:1.18.2-debian13@sha256:c55aa4044f0e090dfb85deed716ebcabbf9531eaacb41ec2a5f399f026232bc1
  KYVERNO_INIT_REFERENCE: dhi/kyverno-init:1.18.2-debian13@sha256:d48f54f7851e15139e73107f6fecb58f08dd6647f569c3a1ef452eada9e36121
  KYVERNO_READINESS_CHECKER_REFERENCE: dhi/kyverno-readiness-checker:1.18.2-debian13@sha256:5fb463021ab632d34832de9b208232daef171a4b09fa317bd2dff153c680d802
  KYVERNO_REFERENCE: dhi/kyverno:1.18.2-debian13@sha256:e250b7ca2cbc23016a806fcd98c48b2a98f8f1aa03c46c3c62bfdc3c9137d65b
  KYVERNO_REPORTS_CONTROLLER_REFERENCE: dhi/kyverno-reports-controller:1.18.2-debian13@sha256:7080fdda7ed86389988bfd24233d46b1d7e11ba3b88312f0ef475992b94604a1
  KYVERNO_REPORTS_SERVER_CHART_REFERENCE: dhi/kyverno-reports-server-chart:0.1.7@sha256:d5e307d3251ff4b9f7ade56c814896e4bec5876fe087b8f08d41853c26106f99
  SEMVER_MAJOR_MINOR_VERSION: "3.8"
  SEMVER_MAJOR_VERSION: "3"
  SEMVER_VERSION: 3.8.2
  VERSION: 3.8.2
contents:
  repositories:
    - deb [signed-by=/usr/share/keyrings/dhi-deb-main.gpg] http://dhi.io/deb/debian/main trixie main
  keyring:
    - https://dhi.io/keyring/dhi-deb-gpg.D46852F6925E9F71.key
  builds:
    - name: kyverno-chart
      work-dir: ${source.dir}/helm-charts/charts/kyverno
      contents:
        packages:
          - bash
          - ca-certificates
          - coreutils
          - helm=4.1.4-2
        files:
          - url: git+https://github.com/kyverno/kyverno.git#kyverno-chart-3.8.2
            checksum: 0591bee075db55030d8d2e841f32f5c4ef5c85aa
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          with:
            chart:
              appRef: kyverno
              dependencies:
                - condition: crds.install
                  keep: true
                  name: crds
                - condition: grafana.enabled
                  keep: true
                  name: grafana
                - condition: crds.install
                  keep: true
                  name: kyverno-api
                - condition: openreports.installCrds
                  keep: true
                  name: openreports
                - alias: reports-server
                  condition: reportsServer.enabled
                  name: kyverno-reports-server
                  ref: dhi/kyverno-reports-server-chart:0.1.7@sha256:d5e307d3251ff4b9f7ade56c814896e4bec5876fe087b8f08d41853c26106f99
              description: Docker Hardened Images Helm chart for Kyverno
              images:
                - name: kyverno
                  ref: dhi/kyverno:1.18.2-debian13@sha256:e250b7ca2cbc23016a806fcd98c48b2a98f8f1aa03c46c3c62bfdc3c9137d65b
                - name: kyverno-cli
                  ref: dhi/kyverno-cli:1.18.2-debian13@sha256:c55aa4044f0e090dfb85deed716ebcabbf9531eaacb41ec2a5f399f026232bc1
                - name: kyverno-readiness-checker
                  ref: dhi/kyverno-readiness-checker:1.18.2-debian13@sha256:5fb463021ab632d34832de9b208232daef171a4b09fa317bd2dff153c680d802
                - name: kubectl
                  ref: dhi/kubectl:1.35.7-debian13@sha256:ad1c264b4072a3afa666a0cb220e36324e2f7dc0f23a4a79e73b7da151a04cd4
                - name: kyverno-init
                  ref: dhi/kyverno-init:1.18.2-debian13@sha256:d48f54f7851e15139e73107f6fecb58f08dd6647f569c3a1ef452eada9e36121
                - name: kyverno-background-controller
                  ref: dhi/kyverno-background-controller:1.18.2-debian13@sha256:ed11e4c196b53684cc0ebc3c26c512d0103b4cce4e3068a004d903e9ad553008
                - name: kyverno-cleanup-controller
                  ref: dhi/kyverno-cleanup-controller:1.18.2-debian13@sha256:3644ca9e0a9ee2e1aa3887379234aa295c90c601e3b31445cb5fdd4a76019f50
                - name: kyverno-reports-controller
                  ref: dhi/kyverno-reports-controller:1.18.2-debian13@sha256:7080fdda7ed86389988bfd24233d46b1d7e11ba3b88312f0ef475992b94604a1
              name: kyverno-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/kyverno/kyverno
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: patch version specific values
          uses: helm/rudder@v1
          with:
            cmd: patch
            patches:
              apply:
                - "on": values.yaml
                  patch: ${source.dir}/config/values-3.8.yaml
            registry: dhi.io
        - name: helm login
          uses: helm/login@v1
          with:
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          privileged: true
          with:
            chart: kyverno
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          with:
            chart: .
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: .
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/kyverno/config
