# syntax=dhi.io/build:2-helm3

name: Kyverno Helm chart 3.8.x
image: dhi.io/kyverno-chart
variant: helm
tags:
  - 3.8.2
platforms:
  - linux/amd64
vars:
  APPVERSION: 1.18.2
  CHART_COMMIT_SHA: 0591bee075db55030d8d2e841f32f5c4ef5c85aa
  CHART_HELM_NAME: kyverno-chart
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_VERSION: 4.1.4-2
  KUBECTL_REFERENCE: dhi/kubectl:1.35.6-debian13@sha256:867ad18be7eda8205d79ba117f370039e494a322f39de5233cefb3de473a5fbc
  KYVERNO_BACKGROUND_CONTROLLER_REFERENCE: dhi/kyverno-background-controller:1.18.2-debian13@sha256:a932d973e4efc629aea9b26fe83a136e1677123750a2e727a70c60f45caf3412
  KYVERNO_CLEANUP_CONTROLLER_REFERENCE: dhi/kyverno-cleanup-controller:1.18.2-debian13@sha256:9d89e2b96ae009c4b36cea167e94e58aec326117eb1972d393b35c321df30e7f
  KYVERNO_CLI_REFERENCE: dhi/kyverno-cli:1.18.2-debian13@sha256:cef69983fbe1af8a888cb8416b8d21fce0bb5810a44f2360e56b49bb68ea7e54
  KYVERNO_INIT_REFERENCE: dhi/kyverno-init:1.18.2-debian13@sha256:9f5e1947859061bcffcc72123e989b347a284939e1f492a32ae8b896c54a8931
  KYVERNO_READINESS_CHECKER_REFERENCE: dhi/kyverno-readiness-checker:1.18.2-debian13@sha256:17f35524d9e6bf9a09b88e2e2e2a66a16ecbc94c4a98d98f8b36a51062d9c7bb
  KYVERNO_REFERENCE: dhi/kyverno:1.18.2-debian13@sha256:a4e9280bbf92a8cfb46db154de856e1c7b668a476299f091101fa16d42e93422
  KYVERNO_REPORTS_CONTROLLER_REFERENCE: dhi/kyverno-reports-controller:1.18.2-debian13@sha256:d19656571fdb76990b8e588b458422a7a105c486df7dea20ddfc325ae17acaed
  KYVERNO_REPORTS_SERVER_CHART_REFERENCE: dhi/kyverno-reports-server-chart:0.1.7@sha256:c61d65bb4c1fe73fa0a166b5047edbd670070d8bb98bd1c4d000dc8512d4834d
  SEMVER_MAJOR_MINOR_VERSION: "3.8"
  SEMVER_MAJOR_VERSION: "3"
  SEMVER_VERSION: 3.8.2
  VERSION: 3.8.2
contents:
  repositories:
    - deb [signed-by=/usr/share/keyrings/dhi-deb-main.gpg] http://dhi.io/deb/debian/main trixie main
  keyring:
    - https://dhi.io/keyring/dhi-deb-gpg.D46852F6925E9F71.key
  builds:
    - name: kyverno-chart
      work-dir: ${source.dir}/helm-charts/charts/kyverno
      contents:
        packages:
          - bash
          - ca-certificates
          - coreutils
          - helm=4.1.4-2
        files:
          - url: git+https://github.com/kyverno/kyverno.git#kyverno-chart-3.8.2
            checksum: 0591bee075db55030d8d2e841f32f5c4ef5c85aa
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          with:
            chart:
              appRef: kyverno
              dependencies:
                - condition: crds.install
                  keep: true
                  name: crds
                - condition: grafana.enabled
                  keep: true
                  name: grafana
                - condition: crds.install
                  keep: true
                  name: kyverno-api
                - condition: openreports.installCrds
                  keep: true
                  name: openreports
                - alias: reports-server
                  condition: reportsServer.enabled
                  name: kyverno-reports-server
                  ref: dhi/kyverno-reports-server-chart:0.1.7@sha256:c61d65bb4c1fe73fa0a166b5047edbd670070d8bb98bd1c4d000dc8512d4834d
              description: Docker Hardened Images Helm chart for Kyverno
              images:
                - name: kyverno
                  ref: dhi/kyverno:1.18.2-debian13@sha256:a4e9280bbf92a8cfb46db154de856e1c7b668a476299f091101fa16d42e93422
                - name: kyverno-cli
                  ref: dhi/kyverno-cli:1.18.2-debian13@sha256:cef69983fbe1af8a888cb8416b8d21fce0bb5810a44f2360e56b49bb68ea7e54
                - name: kyverno-readiness-checker
                  ref: dhi/kyverno-readiness-checker:1.18.2-debian13@sha256:17f35524d9e6bf9a09b88e2e2e2a66a16ecbc94c4a98d98f8b36a51062d9c7bb
                - name: kubectl
                  ref: dhi/kubectl:1.35.6-debian13@sha256:867ad18be7eda8205d79ba117f370039e494a322f39de5233cefb3de473a5fbc
                - name: kyverno-init
                  ref: dhi/kyverno-init:1.18.2-debian13@sha256:9f5e1947859061bcffcc72123e989b347a284939e1f492a32ae8b896c54a8931
                - name: kyverno-background-controller
                  ref: dhi/kyverno-background-controller:1.18.2-debian13@sha256:a932d973e4efc629aea9b26fe83a136e1677123750a2e727a70c60f45caf3412
                - name: kyverno-cleanup-controller
                  ref: dhi/kyverno-cleanup-controller:1.18.2-debian13@sha256:9d89e2b96ae009c4b36cea167e94e58aec326117eb1972d393b35c321df30e7f
                - name: kyverno-reports-controller
                  ref: dhi/kyverno-reports-controller:1.18.2-debian13@sha256:d19656571fdb76990b8e588b458422a7a105c486df7dea20ddfc325ae17acaed
              name: kyverno-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/kyverno/kyverno
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: patch version specific values
          uses: helm/rudder@v1
          with:
            cmd: patch
            patches:
              apply:
                - "on": values.yaml
                  patch: ${source.dir}/config/values-3.8.yaml
            registry: dhi.io
        - name: helm login
          uses: helm/login@v1
          with:
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          privileged: true
          with:
            chart: kyverno
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          with:
            chart: .
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: .
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/kyverno/config
