# syntax=dhi.io/build:2-helm3

name: Kyverno Helm chart 3.8.x
image: dhi.io/kyverno-chart
variant: helm
tags:
  - 3.8.1
platforms:
  - linux/amd64
vars:
  APPVERSION: 1.18.1
  CHART_COMMIT_SHA: 57908e9b6a9ddd1fea5e3fca2bafdf4ca87f7f9b
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.21.2-debian13-dev@sha256:e30b522f3f39307b7710b304f082f76d7b8fc0d0140bfc44bdf2892c5411519f
  KUBECTL_IMAGE_REFERENCE: dhi/kubectl:1.35.6-debian13@sha256:535d3e2e1bfc09d74f69d2aaca75126d8da520de71bd1c0a52901dc9cad51c9a
  KYVERNO_BACKGROUND_CONTROLLER_IMAGE_REFERENCE: dhi/kyverno-background-controller:1.18.1-debian13@sha256:6bb30010f34ebec06bc8e603cd724ba3159ea193abdfce99dc63e124d8b282cf
  KYVERNO_CLEANUP_CONTROLLER_IMAGE_REFERENCE: dhi/kyverno-cleanup-controller:1.18.1-debian13@sha256:88729accf44fa348df3a4a4242eb2d34296aadcbe39c2d931ec7ed7b75e91dda
  KYVERNO_CLI_IMAGE_REFERENCE: dhi/kyverno-cli:1.18.1-debian13@sha256:90bc2bf723b6d41bf840816b12e2a2c559343ead5044ac932f1c0c2091059c8b
  KYVERNO_IMAGE_REFERENCE: dhi/kyverno:1.18.1-debian13@sha256:c6bb6e127c5b473c7d126eaf3784a9f305f852be7bdb7151def70188b6110edb
  KYVERNO_INIT_IMAGE_REFERENCE: dhi/kyverno-init:1.18.1-debian13@sha256:9f21ed785da2391970ee715a279f827f447eb234ff93383eede97b0b87aa814a
  KYVERNO_READINESS_CHECKER_IMAGE_REFERENCE: dhi/kyverno-readiness-checker:1.18.1-debian13@sha256:cece680464aa3a860ec14c8a5e7b4e0e23427c3f242411f5aa255af2b55c2dc1
  KYVERNO_REPORTS_CONTROLLER_IMAGE_REFERENCE: dhi/kyverno-reports-controller:1.18.1-debian13@sha256:ba81869af865948f73fdfe57b2497c4811b098dcb3831b10cc7fee7f1953aec8
  KYVERNO_REPORTS_SERVER_CHART_REFERENCE: dhi/kyverno-reports-server-chart:0.1.7@sha256:cac7ac0f382911ae61f171e33890c007d878e2eff9addae9804a99bef076c90a
  SEMVER_MAJOR_MINOR_VERSION: "3.8"
  SEMVER_MAJOR_VERSION: "3"
  SEMVER_VERSION: 3.8.1
  VERSION: 3.8.1
contents:
  builds:
    - name: kyverno-chart
      uses: dhi.io/helm:3.21.2-debian13-dev@sha256:e30b522f3f39307b7710b304f082f76d7b8fc0d0140bfc44bdf2892c5411519f
      work-dir: ${source.dir}/helm-charts/charts/kyverno
      contents:
        files:
          - url: git+https://github.com/kyverno/kyverno.git#kyverno-chart-3.8.1
            checksum: 57908e9b6a9ddd1fea5e3fca2bafdf4ca87f7f9b
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          with:
            chart:
              appRef: kyverno
              dependencies:
                - condition: crds.install
                  keep: true
                  name: crds
                - condition: grafana.enabled
                  keep: true
                  name: grafana
                - condition: crds.install
                  keep: true
                  name: kyverno-api
                - condition: openreports.installCrds
                  keep: true
                  name: openreports
                - alias: reports-server
                  condition: reportsServer.enabled
                  name: kyverno-reports-server
                  ref: dhi/kyverno-reports-server-chart:0.1.7@sha256:cac7ac0f382911ae61f171e33890c007d878e2eff9addae9804a99bef076c90a
              description: Docker Hardened Images Helm chart for Kyverno
              images:
                - name: kyverno
                  ref: dhi/kyverno:1.18.1-debian13@sha256:c6bb6e127c5b473c7d126eaf3784a9f305f852be7bdb7151def70188b6110edb
                - name: kyverno-cli
                  ref: dhi/kyverno-cli:1.18.1-debian13@sha256:90bc2bf723b6d41bf840816b12e2a2c559343ead5044ac932f1c0c2091059c8b
                - name: kyverno-readiness-checker
                  ref: dhi/kyverno-readiness-checker:1.18.1-debian13@sha256:cece680464aa3a860ec14c8a5e7b4e0e23427c3f242411f5aa255af2b55c2dc1
                - name: kubectl
                  ref: dhi/kubectl:1.35.6-debian13@sha256:535d3e2e1bfc09d74f69d2aaca75126d8da520de71bd1c0a52901dc9cad51c9a
                - name: kyverno-init
                  ref: dhi/kyverno-init:1.18.1-debian13@sha256:9f21ed785da2391970ee715a279f827f447eb234ff93383eede97b0b87aa814a
                - name: kyverno-background-controller
                  ref: dhi/kyverno-background-controller:1.18.1-debian13@sha256:6bb30010f34ebec06bc8e603cd724ba3159ea193abdfce99dc63e124d8b282cf
                - name: kyverno-cleanup-controller
                  ref: dhi/kyverno-cleanup-controller:1.18.1-debian13@sha256:88729accf44fa348df3a4a4242eb2d34296aadcbe39c2d931ec7ed7b75e91dda
                - name: kyverno-reports-controller
                  ref: dhi/kyverno-reports-controller:1.18.1-debian13@sha256:ba81869af865948f73fdfe57b2497c4811b098dcb3831b10cc7fee7f1953aec8
              name: kyverno-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/kyverno/kyverno
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: patch version specific values
          uses: helm/rudder@v1
          with:
            cmd: patch
            patches:
              apply:
                - "on": values.yaml
                  patch: ${source.dir}/config/values-3.8.yaml
            registry: dhi.io
        - name: helm login
          uses: helm/login@v1
          with:
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          privileged: true
          with:
            chart: kyverno
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          with:
            chart: .
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: .
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/kyverno/config
