# syntax=dhi.io/build:2-helm3

name: Kyverno Helm chart 3.9.x
image: dhi.io/kyverno-chart
variant: helm
tags:
  - 3.9.0
platforms:
  - linux/amd64
vars:
  APPVERSION: 1.19.0
  CHART_COMMIT_SHA: cfb501731a318b28dfca9879fb6b131be8e5465f
  CHART_HELM_NAME: kyverno-chart
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_VERSION: 4.1.4-2
  KUBECTL_REFERENCE: dhi/kubectl:1.35.8-debian13@sha256:7c9f595fc5000289c5e8d843ab89360a0f65def76e099f5edf5631906ca955a9
  KYVERNO_BACKGROUND_CONTROLLER_REFERENCE: dhi/kyverno-background-controller:1.19.0-debian13@sha256:1dda5940a7cc1bed1ed4dd3ab98ac4ce848bf6d731998fea6cbe38591b217157
  KYVERNO_CLEANUP_CONTROLLER_REFERENCE: dhi/kyverno-cleanup-controller:1.19.0-debian13@sha256:4b6f04efcce5122e98bc4887df37c787b171747374e1596ed55a57e33289f8f5
  KYVERNO_CLI_REFERENCE: dhi/kyverno-cli:1.19.0-debian13@sha256:0739fd5c1086a24489fd886b154305665979a71780b58900389ac0907995f1e5
  KYVERNO_INIT_REFERENCE: dhi/kyverno-init:1.19.0-debian13@sha256:a3f5288794e57e419d790209602c0fe3df1832babe8f4a9fd5cc93bf9ea5f2b8
  KYVERNO_READINESS_CHECKER_REFERENCE: dhi/kyverno-readiness-checker:1.19.0-debian13@sha256:32c07c06d4e0b3b0bce0fd200c12ec3b968fc3b7b8ea2917bf36d46883ee8cac
  KYVERNO_REFERENCE: dhi/kyverno:1.19.0-debian13@sha256:1ca376419c439d879b37d9a8f74196606baa24d503e90b284cf68662f71a37e9
  KYVERNO_REPORTS_CONTROLLER_REFERENCE: dhi/kyverno-reports-controller:1.19.0-debian13@sha256:edf2438bb28b4629fd496d17b16bd689953f2ff84e921ef97decd956824e234a
  KYVERNO_REPORTS_SERVER_CHART_REFERENCE: dhi/kyverno-reports-server-chart:0.1.7@sha256:c0709ebc8e1be7d3fc9246818a2e01772b6e783cb406adadee040dd78c01950a
  SEMVER_MAJOR_MINOR_VERSION: "3.9"
  SEMVER_MAJOR_VERSION: "3"
  SEMVER_VERSION: 3.9.0
  VERSION: 3.9.0
contents:
  repositories:
    - deb [signed-by=/usr/share/keyrings/dhi-deb-main.gpg] http://dhi.io/deb/debian/main trixie main
  keyring:
    - https://dhi.io/keyring/dhi-deb-gpg.D46852F6925E9F71.key
  builds:
    - name: kyverno-chart
      work-dir: ${source.dir}/helm-charts/charts/kyverno
      contents:
        packages:
          - bash
          - ca-certificates
          - coreutils
          - helm=4.1.4-2
        files:
          - url: git+https://github.com/kyverno/kyverno.git#kyverno-chart-3.9.0
            checksum: cfb501731a318b28dfca9879fb6b131be8e5465f
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          with:
            chart:
              appRef: kyverno
              dependencies:
                - condition: crds.install
                  keep: true
                  name: crds
                - condition: grafana.enabled
                  keep: true
                  name: grafana
                - condition: crds.install
                  keep: true
                  name: kyverno-api
                - condition: openreports.installCrds
                  keep: true
                  name: openreports
                - alias: reports-server
                  condition: reportsServer.enabled
                  name: kyverno-reports-server
                  ref: dhi/kyverno-reports-server-chart:0.1.7@sha256:c0709ebc8e1be7d3fc9246818a2e01772b6e783cb406adadee040dd78c01950a
              description: Docker Hardened Images Helm chart for Kyverno
              images:
                - name: kyverno
                  ref: dhi/kyverno:1.19.0-debian13@sha256:1ca376419c439d879b37d9a8f74196606baa24d503e90b284cf68662f71a37e9
                - name: kyverno-cli
                  ref: dhi/kyverno-cli:1.19.0-debian13@sha256:0739fd5c1086a24489fd886b154305665979a71780b58900389ac0907995f1e5
                - name: kyverno-readiness-checker
                  ref: dhi/kyverno-readiness-checker:1.19.0-debian13@sha256:32c07c06d4e0b3b0bce0fd200c12ec3b968fc3b7b8ea2917bf36d46883ee8cac
                - name: kubectl
                  ref: dhi/kubectl:1.35.8-debian13@sha256:7c9f595fc5000289c5e8d843ab89360a0f65def76e099f5edf5631906ca955a9
                - name: kyverno-init
                  ref: dhi/kyverno-init:1.19.0-debian13@sha256:a3f5288794e57e419d790209602c0fe3df1832babe8f4a9fd5cc93bf9ea5f2b8
                - name: kyverno-background-controller
                  ref: dhi/kyverno-background-controller:1.19.0-debian13@sha256:1dda5940a7cc1bed1ed4dd3ab98ac4ce848bf6d731998fea6cbe38591b217157
                - name: kyverno-cleanup-controller
                  ref: dhi/kyverno-cleanup-controller:1.19.0-debian13@sha256:4b6f04efcce5122e98bc4887df37c787b171747374e1596ed55a57e33289f8f5
                - name: kyverno-reports-controller
                  ref: dhi/kyverno-reports-controller:1.19.0-debian13@sha256:edf2438bb28b4629fd496d17b16bd689953f2ff84e921ef97decd956824e234a
              name: kyverno-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/kyverno/kyverno
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: patch version specific values
          uses: helm/rudder@v1
          with:
            cmd: patch
            patches:
              apply:
                - "on": values.yaml
                  patch: ${source.dir}/config/values-3.9.yaml
            registry: dhi.io
        - name: helm login
          uses: helm/login@v1
          with:
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          privileged: true
          with:
            chart: kyverno
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          with:
            chart: .
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: .
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/kyverno/config
