# syntax=dhi.io/build:2-helm3

name: Kyverno Helm chart 3.9.x
image: dhi.io/kyverno-chart
variant: helm
tags:
  - 3.9.1
platforms:
  - linux/amd64
vars:
  APPVERSION: 1.19.1
  CHART_COMMIT_SHA: 584b91d178ea1b3db1da5720655a3dec8f0027b4
  CHART_HELM_NAME: kyverno-chart
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_VERSION: 4.1.4-2
  KUBECTL_REFERENCE: dhi/kubectl:1.35.9-debian13@sha256:e91956f5d0964a003e220aba19f292689d5c670460f78069bcdf8f02d15e0eb4
  KYVERNO_BACKGROUND_CONTROLLER_REFERENCE: dhi/kyverno-background-controller:1.19.1-debian13@sha256:c3f04e1cecf16cf03f960c82b3d3c99d7e0a338b8342ffe90ebcf68683c8d1e3
  KYVERNO_CLEANUP_CONTROLLER_REFERENCE: dhi/kyverno-cleanup-controller:1.19.1-debian13@sha256:7ddfbb48e280565e8bcfa9cb841390a362bbfdaf1f1d41da3e406b29952c90fe
  KYVERNO_CLI_REFERENCE: dhi/kyverno-cli:1.19.1-debian13@sha256:3ba7572d9d35960828305160213c3cb6daf7c98bd92fb16b1d606587957cc420
  KYVERNO_INIT_REFERENCE: dhi/kyverno-init:1.19.1-debian13@sha256:25018ea5ef4461f5cc8c0b0be18ba3cf4fa1e40b58ce721b4526b97adf283751
  KYVERNO_READINESS_CHECKER_REFERENCE: dhi/kyverno-readiness-checker:1.19.1-debian13@sha256:c433c6eb0ec766bb0e68302cfd5f85ed7d9eda5a9277e98413a89b96a038a88a
  KYVERNO_REFERENCE: dhi/kyverno:1.19.1-debian13@sha256:3d04295edeff998bdd46c0f2b8f88a9f2f0e55781f71acc4af67f4a9829220b6
  KYVERNO_REPORTS_CONTROLLER_REFERENCE: dhi/kyverno-reports-controller:1.19.1-debian13@sha256:4d40f555401bf55762624bc5d32fdf84cd9880b35eab31fa3b10547e7fcdab69
  KYVERNO_REPORTS_SERVER_CHART_REFERENCE: dhi/kyverno-reports-server-chart:0.1.7@sha256:8a80a3b65bac0b3092ec7755e37688a74f91f5ca2de32a4fd5ce243331c59c4e
  SEMVER_MAJOR_MINOR_VERSION: "3.9"
  SEMVER_MAJOR_VERSION: "3"
  SEMVER_VERSION: 3.9.1
  VERSION: 3.9.1
contents:
  repositories:
    - deb [signed-by=/usr/share/keyrings/dhi-deb-main.gpg] http://dhi.io/deb/debian/main trixie main
  keyring:
    - https://dhi.io/keyring/dhi-deb-gpg.D46852F6925E9F71.key
  builds:
    - name: kyverno-chart
      work-dir: ${source.dir}/helm-charts/charts/kyverno
      contents:
        packages:
          - bash
          - ca-certificates
          - coreutils
          - helm=4.1.4-2
        files:
          - url: git+https://github.com/kyverno/kyverno.git#kyverno-chart-3.9.1
            checksum: 584b91d178ea1b3db1da5720655a3dec8f0027b4
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          with:
            chart:
              appRef: kyverno
              dependencies:
                - condition: crds.install
                  keep: true
                  name: crds
                - condition: grafana.enabled
                  keep: true
                  name: grafana
                - condition: crds.install
                  keep: true
                  name: kyverno-api
                - condition: openreports.installCrds
                  keep: true
                  name: openreports
                - alias: reports-server
                  condition: reportsServer.enabled
                  name: kyverno-reports-server
                  ref: dhi/kyverno-reports-server-chart:0.1.7@sha256:8a80a3b65bac0b3092ec7755e37688a74f91f5ca2de32a4fd5ce243331c59c4e
              description: Docker Hardened Images Helm chart for Kyverno
              images:
                - name: kyverno
                  ref: dhi/kyverno:1.19.1-debian13@sha256:3d04295edeff998bdd46c0f2b8f88a9f2f0e55781f71acc4af67f4a9829220b6
                - name: kyverno-cli
                  ref: dhi/kyverno-cli:1.19.1-debian13@sha256:3ba7572d9d35960828305160213c3cb6daf7c98bd92fb16b1d606587957cc420
                - name: kyverno-readiness-checker
                  ref: dhi/kyverno-readiness-checker:1.19.1-debian13@sha256:c433c6eb0ec766bb0e68302cfd5f85ed7d9eda5a9277e98413a89b96a038a88a
                - name: kubectl
                  ref: dhi/kubectl:1.35.9-debian13@sha256:e91956f5d0964a003e220aba19f292689d5c670460f78069bcdf8f02d15e0eb4
                - name: kyverno-init
                  ref: dhi/kyverno-init:1.19.1-debian13@sha256:25018ea5ef4461f5cc8c0b0be18ba3cf4fa1e40b58ce721b4526b97adf283751
                - name: kyverno-background-controller
                  ref: dhi/kyverno-background-controller:1.19.1-debian13@sha256:c3f04e1cecf16cf03f960c82b3d3c99d7e0a338b8342ffe90ebcf68683c8d1e3
                - name: kyverno-cleanup-controller
                  ref: dhi/kyverno-cleanup-controller:1.19.1-debian13@sha256:7ddfbb48e280565e8bcfa9cb841390a362bbfdaf1f1d41da3e406b29952c90fe
                - name: kyverno-reports-controller
                  ref: dhi/kyverno-reports-controller:1.19.1-debian13@sha256:4d40f555401bf55762624bc5d32fdf84cd9880b35eab31fa3b10547e7fcdab69
              name: kyverno-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/kyverno/kyverno
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: patch version specific values
          uses: helm/rudder@v1
          with:
            cmd: patch
            patches:
              apply:
                - "on": values.yaml
                  patch: ${source.dir}/config/values-3.9.yaml
            registry: dhi.io
        - name: helm login
          uses: helm/login@v1
          with:
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          privileged: true
          with:
            chart: kyverno
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          with:
            chart: .
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: .
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/kyverno/config
