# syntax=dhi.io/build:2-helm3

name: Istio Ingress Helm chart 1.29.x
image: dhi.io/istio-ingress-chart
variant: helm
tags:
  - 1.29.5
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: fe1d6ad986110a26ad4e8b4044589f2b112daac1
  CHART_HELM_NAME: istio-ingress-chart
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_VERSION: 4.1.4-2
  ISTIO_PROXYV2_REFERENCE: dhi/istio-proxyv2:1.29.5-debian13@sha256:773821b4f6b205e4301b67e2ae950803c595e4a412c10a37b887fdff5c6d44a6
  SEMVER_MAJOR_MINOR_VERSION: "1.29"
  SEMVER_MAJOR_VERSION: "1"
  SEMVER_VERSION: 1.29.5
  VERSION: 1.29.5
contents:
  repositories:
    - deb [signed-by=/usr/share/keyrings/dhi-deb-main.gpg] http://dhi.io/deb/debian/main trixie main
  keyring:
    - https://dhi.io/keyring/dhi-deb-gpg.D46852F6925E9F71.key
  builds:
    - name: istio-ingress
      work-dir: ${source.dir}/helm-charts/manifests/charts/gateways/istio-ingress
      contents:
        packages:
          - bash
          - ca-certificates
          - coreutils
          - helm=4.1.4-2
        files:
          - url: git+https://github.com/istio/istio.git#1.29.5
            checksum: fe1d6ad986110a26ad4e8b4044589f2b112daac1
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          with:
            chart:
              appRef: proxyv2
              description: Docker Hardened Images Helm chart for Istio Ingress
              images:
                - name: proxyv2
                  ref: dhi/istio-proxyv2:1.29.5-debian13@sha256:773821b4f6b205e4301b67e2ae950803c595e4a412c10a37b887fdff5c6d44a6
              name: istio-ingress-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/istio/istio
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          with:
            chart: .
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: .
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/istio-ingress/config
