# syntax=dhi.io/build:2-helm3

name: Istio Ingress Helm chart 1.30.x
image: dhi.io/istio-ingress-chart
variant: helm
tags:
  - 1.30.2
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: f888ab4c8a0c3d0427bb0053fbebbe6b1f7e9a91
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.21.2-debian13-dev@sha256:e30b522f3f39307b7710b304f082f76d7b8fc0d0140bfc44bdf2892c5411519f
  ISTIO_PROXYV2_REFERENCE: dhi/istio-proxyv2:1.30.2-debian13@sha256:5235eab4320b3bdfba199bc8935fd5d18516675a23c9f3acc1b0eb06e63bbf8d
  SEMVER_MAJOR_MINOR_VERSION: "1.30"
  SEMVER_MAJOR_VERSION: "1"
  SEMVER_VERSION: 1.30.2
  VERSION: 1.30.2
contents:
  builds:
    - name: istio-ingress
      uses: dhi.io/helm:3.21.2-debian13-dev@sha256:e30b522f3f39307b7710b304f082f76d7b8fc0d0140bfc44bdf2892c5411519f
      work-dir: ${source.dir}/helm-charts/manifests/charts/gateways/istio-ingress
      contents:
        files:
          - url: git+https://github.com/istio/istio.git#1.30.2
            checksum: f888ab4c8a0c3d0427bb0053fbebbe6b1f7e9a91
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          with:
            chart:
              appRef: proxyv2
              description: Docker Hardened Images Helm chart for Istio Ingress
              images:
                - name: proxyv2
                  ref: dhi/istio-proxyv2:1.30.2-debian13@sha256:5235eab4320b3bdfba199bc8935fd5d18516675a23c9f3acc1b0eb06e63bbf8d
              name: istio-ingress-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/istio/istio
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          with:
            chart: .
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: .
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/istio-ingress/config
