# syntax=dhi.io/build:2-helm3

name: Grafana Helm chart 11.x
image: dhi.io/grafana-chart
variant: helm
tags:
  - 11.3.3
platforms:
  - linux/amd64
vars:
  BATS_REFERENCE: dhi/bats:1.13.0-debian13@sha256:d4e3d771225f4becb87d5e152e4c9c28d74a8d9595cda5cd310ce192cd310cb9
  BUSYBOX_REFERENCE: dhi/busybox:1.37.0-debian13@sha256:19defb1059fdfbf20742eb8057c823d9a46d2aa9c0506ada9e9e211f53b32ac6
  CHART_COMMIT_SHA: c80038d15d5acec5ae16b1b30adab680bb126ba4
  CURL_REFERENCE: dhi/curl:8.14.1-debian13@sha256:571b666b14e3a39be196b9b8118d2a81a1d09a206139f6e3299e2dc587725e01
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  GRAFANA_IMAGE_RENDERER_REFERENCE: dhi/grafana-image-renderer:5.7.2-debian13@sha256:c44f9369d08b455432a6dae1a253c15c341a2da363631dd93d23074b83ac4a24
  GRAFANA_REFERENCE: dhi/grafana:12.3.5-debian13@sha256:377fe8fe2ad54b19b3d6cbfa3c30ef2ae63a0bfc5576bf90a4d0b7d1048c41d9
  HELM_REFERENCE: dhi/helm:3.20.1-debian13-dev@sha256:92e43232140b33018c99c7b178d2f7302cfb0f0017267731b0512ac206cd8690
  K8S_SIDECAR_REFERENCE: dhi/k8s-sidecar:2.5.1-debian13@sha256:c5bf1c6486e341c085f2e39a9a2c6b4a3f3bbf31e83a2de44ac569b20440b715
  SEMVER_MAJOR_MINOR_VERSION: "11.3"
  SEMVER_MAJOR_VERSION: "11"
  SEMVER_VERSION: 11.3.3
  VERSION: 11.3.3
contents:
  builds:
    - name: grafana
      uses: dhi.io/helm:3.20.1-debian13-dev@sha256:92e43232140b33018c99c7b178d2f7302cfb0f0017267731b0512ac206cd8690
      contents:
        packages:
          - bash
          - build-essential
          - coreutils
          - grep
          - libc-bin
          - sed
        files:
          - url: git+https://github.com/grafana-community/helm-charts.git#grafana-11.3.3
            checksum: c80038d15d5acec5ae16b1b30adab680bb126ba4
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/grafana
          with:
            chart:
              appRef: grafana
              description: Docker Hardened Images Helm chart for Grafana
              images:
                - name: grafana
                  ref: dhi/grafana:12.3.5-debian13@sha256:377fe8fe2ad54b19b3d6cbfa3c30ef2ae63a0bfc5576bf90a4d0b7d1048c41d9
                - name: grafana-image-renderer
                  ref: dhi/grafana-image-renderer:5.7.2-debian13@sha256:c44f9369d08b455432a6dae1a253c15c341a2da363631dd93d23074b83ac4a24
                - name: bats
                  ref: dhi/bats:1.13.0-debian13@sha256:d4e3d771225f4becb87d5e152e4c9c28d74a8d9595cda5cd310ce192cd310cb9
                - name: busybox
                  ref: dhi/busybox:1.37.0-debian13@sha256:19defb1059fdfbf20742eb8057c823d9a46d2aa9c0506ada9e9e211f53b32ac6
                - name: curl
                  ref: dhi/curl:8.14.1-debian13@sha256:571b666b14e3a39be196b9b8118d2a81a1d09a206139f6e3299e2dc587725e01
                - name: k8s-sidecar
                  ref: dhi/k8s-sidecar:2.5.1-debian13@sha256:c5bf1c6486e341c085f2e39a9a2c6b4a3f3bbf31e83a2de44ac569b20440b715
              name: grafana-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/grafana-community/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/grafana
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: grafana
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: grafana
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/grafana/config
