# syntax=dhi.io/build:2-helm3

name: Grafana Helm chart 11.x
image: dhi.io/grafana-chart
variant: helm
tags:
  - 11.6.0
platforms:
  - linux/amd64
vars:
  BATS_REFERENCE: dhi/bats:1.13.0-debian13@sha256:1970372446865c7ac4b1e1cb603caeae2a44b3172778b2f2b8c8434ca5a8ae0c
  BUSYBOX_REFERENCE: dhi/busybox:1.37.0-debian13@sha256:19defb1059fdfbf20742eb8057c823d9a46d2aa9c0506ada9e9e211f53b32ac6
  CHART_COMMIT_SHA: de53fe1f0989e2fb35eb66c73cc9c237c075d254
  CURL_REFERENCE: dhi/curl:8.14.1-debian13@sha256:80683a8dea031a1edec1b29a7e96556f88d7b0b70a31fcea63cd34c7a6614da0
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  GRAFANA_IMAGE_RENDERER_REFERENCE: dhi/grafana-image-renderer:5.8.0-debian13@sha256:1d6f4a6c9c40a628507e51308dd844d4aca092de01ec35a1d9c71162c5e9b65b
  GRAFANA_REFERENCE: dhi/grafana:12.3.6-debian13@sha256:4fc56c71f8cf417388fc48528a8dc6b97de380331dd9fa4e0f0883c1eb892e9b
  HELM_REFERENCE: dhi/helm:3.20.2-debian13-dev@sha256:c7510bdef2d5afba3a1c80b20b836748adaab6991684962b98460d7a36dcdfa4
  K8S_SIDECAR_REFERENCE: dhi/k8s-sidecar:2.6.0-debian13@sha256:8a3b882e8942660108027752c343b6efcc16f13b5d1058179670464f91aa5c28
  SEMVER_MAJOR_MINOR_VERSION: "11.6"
  SEMVER_MAJOR_VERSION: "11"
  SEMVER_VERSION: 11.6.0
  VERSION: 11.6.0
contents:
  builds:
    - name: grafana
      uses: dhi.io/helm:3.20.2-debian13-dev@sha256:c7510bdef2d5afba3a1c80b20b836748adaab6991684962b98460d7a36dcdfa4
      contents:
        packages:
          - bash
          - build-essential
          - coreutils
          - grep
          - libc-bin
          - sed
        files:
          - url: git+https://github.com/grafana-community/helm-charts.git#grafana-11.6.0
            checksum: de53fe1f0989e2fb35eb66c73cc9c237c075d254
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/grafana
          with:
            chart:
              appRef: grafana
              description: Docker Hardened Images Helm chart for Grafana
              images:
                - name: grafana
                  ref: dhi/grafana:12.3.6-debian13@sha256:4fc56c71f8cf417388fc48528a8dc6b97de380331dd9fa4e0f0883c1eb892e9b
                - name: grafana-image-renderer
                  ref: dhi/grafana-image-renderer:5.8.0-debian13@sha256:1d6f4a6c9c40a628507e51308dd844d4aca092de01ec35a1d9c71162c5e9b65b
                - name: bats
                  ref: dhi/bats:1.13.0-debian13@sha256:1970372446865c7ac4b1e1cb603caeae2a44b3172778b2f2b8c8434ca5a8ae0c
                - name: busybox
                  ref: dhi/busybox:1.37.0-debian13@sha256:19defb1059fdfbf20742eb8057c823d9a46d2aa9c0506ada9e9e211f53b32ac6
                - name: curl
                  ref: dhi/curl:8.14.1-debian13@sha256:80683a8dea031a1edec1b29a7e96556f88d7b0b70a31fcea63cd34c7a6614da0
                - name: k8s-sidecar
                  ref: dhi/k8s-sidecar:2.6.0-debian13@sha256:8a3b882e8942660108027752c343b6efcc16f13b5d1058179670464f91aa5c28
              name: grafana-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/grafana-community/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/grafana
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: grafana
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: grafana
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/grafana/config
