# syntax=dhi.io/build:2-helm3

name: Grafana Helm chart 12.x
image: dhi.io/grafana-chart
variant: helm
tags:
  - 12.4.2
platforms:
  - linux/amd64
vars:
  BATS_REFERENCE: dhi/bats:1.13.0-debian13@sha256:990f842036f621b9dac7899d58f254025cfbac207cf3caa3c59bd723492a4bc4
  BUSYBOX_REFERENCE: dhi/busybox:1.37.0-debian13@sha256:e0cbe035dd7d7072e088172c5833bf756bfba3618567c0f5e73288e97e3a19bf
  CHART_COMMIT_SHA: 8ea4eb6edcec4b4ec07bd579d045c48af7515077
  CURL_REFERENCE: dhi/curl:8.14.1-debian13@sha256:cc896251fd6cc5c8ef91784abfb5cd52f51869e9e0d0bd0f13387f5f37f6b7e7
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  GRAFANA_IMAGE_RENDERER_REFERENCE: dhi/grafana-image-renderer:5.8.8-debian13@sha256:a8cdfaebec36841bf06214e287632b277eff5b304f185aac08c94300d5b10030
  GRAFANA_REFERENCE: dhi/grafana:12.4.4-debian13@sha256:5aa920b93483e36981e57c4714b571dbfd32b63cfc2120ffeb2107bf8d2c1143
  HELM_REFERENCE: dhi/helm:3.21.0-debian13-dev@sha256:ce37cdc271f28789f84db63c8fe5d86522cc98922637f8dde8c2aca4f0cc1632
  K8S_SIDECAR_REFERENCE: dhi/k8s-sidecar:2.7.3-debian13@sha256:cbc34df3f77685b2f944696f38f031133de8665f0292c158e21189c76c175002
  SEMVER_MAJOR_MINOR_VERSION: "12.4"
  SEMVER_MAJOR_VERSION: "12"
  SEMVER_VERSION: 12.4.2
  VERSION: 12.4.2
contents:
  builds:
    - name: grafana
      uses: dhi.io/helm:3.21.0-debian13-dev@sha256:ce37cdc271f28789f84db63c8fe5d86522cc98922637f8dde8c2aca4f0cc1632
      contents:
        packages:
          - bash
          - build-essential
          - coreutils
          - grep
          - libc-bin
          - sed
        files:
          - url: git+https://github.com/grafana-community/helm-charts.git#grafana-12.4.2
            checksum: 8ea4eb6edcec4b4ec07bd579d045c48af7515077
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/grafana
          with:
            chart:
              appRef: grafana
              description: Docker Hardened Images Helm chart for Grafana
              images:
                - name: grafana
                  ref: dhi/grafana:12.4.4-debian13@sha256:5aa920b93483e36981e57c4714b571dbfd32b63cfc2120ffeb2107bf8d2c1143
                - name: grafana-image-renderer
                  ref: dhi/grafana-image-renderer:5.8.8-debian13@sha256:a8cdfaebec36841bf06214e287632b277eff5b304f185aac08c94300d5b10030
                - name: bats
                  ref: dhi/bats:1.13.0-debian13@sha256:990f842036f621b9dac7899d58f254025cfbac207cf3caa3c59bd723492a4bc4
                - name: busybox
                  ref: dhi/busybox:1.37.0-debian13@sha256:e0cbe035dd7d7072e088172c5833bf756bfba3618567c0f5e73288e97e3a19bf
                - name: curl
                  ref: dhi/curl:8.14.1-debian13@sha256:cc896251fd6cc5c8ef91784abfb5cd52f51869e9e0d0bd0f13387f5f37f6b7e7
                - name: k8s-sidecar
                  ref: dhi/k8s-sidecar:2.7.3-debian13@sha256:cbc34df3f77685b2f944696f38f031133de8665f0292c158e21189c76c175002
              name: grafana-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/grafana-community/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/grafana
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: grafana
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: grafana
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/grafana/config
