# syntax=dhi.io/build:2-helm3

name: Grafana Helm chart 12.x
image: dhi.io/grafana-chart
variant: helm
tags:
  - 12.4.4
platforms:
  - linux/amd64
vars:
  BATS_REFERENCE: dhi/bats:1.13.0-debian13@sha256:d2a87ffe44ac1bdceca81fa498fb9a34719b2ae6f55d380eff64741f32709e6e
  BUSYBOX_REFERENCE: dhi/busybox:1.37.0-debian13@sha256:e0cbe035dd7d7072e088172c5833bf756bfba3618567c0f5e73288e97e3a19bf
  CHART_COMMIT_SHA: b44025959e0b17f6475946859e34939d8dbf1cd5
  CURL_REFERENCE: dhi/curl:8.14.1-debian13@sha256:53cb07c0702c04c750fd2c58641b81766603917aebab571b3bb739d24464f1e3
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  GRAFANA_IMAGE_RENDERER_REFERENCE: dhi/grafana-image-renderer:5.8.9-debian13@sha256:8616a9f6a4c962682a10e6283db0aa6190d008188cc55a630c7cabdebd5ebc76
  GRAFANA_REFERENCE: dhi/grafana:12.4.4-debian13@sha256:2ad28506bd97927ec4b4cf7acfe2befbf6c716c2bcb3a855d9e0076c7150356d
  HELM_REFERENCE: dhi/helm:3.21.0-debian13-dev@sha256:ece8efeb889adab72837b0042d8419283ac7fdf2b5c2c8fe09a34e4b8a34ae2e
  K8S_SIDECAR_REFERENCE: dhi/k8s-sidecar:2.7.3-debian13@sha256:ec51d4d917d6001ad0dbc454b07c84fd1bbe6718b5f05171658c4e11e43d5f4c
  SEMVER_MAJOR_MINOR_VERSION: "12.4"
  SEMVER_MAJOR_VERSION: "12"
  SEMVER_VERSION: 12.4.4
  VERSION: 12.4.4
contents:
  builds:
    - name: grafana
      uses: dhi.io/helm:3.21.0-debian13-dev@sha256:ece8efeb889adab72837b0042d8419283ac7fdf2b5c2c8fe09a34e4b8a34ae2e
      contents:
        packages:
          - bash
          - build-essential
          - coreutils
          - grep
          - libc-bin
          - sed
        files:
          - url: git+https://github.com/grafana-community/helm-charts.git#grafana-12.4.4
            checksum: b44025959e0b17f6475946859e34939d8dbf1cd5
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/grafana
          with:
            chart:
              appRef: grafana
              description: Docker Hardened Images Helm chart for Grafana
              images:
                - name: grafana
                  ref: dhi/grafana:12.4.4-debian13@sha256:2ad28506bd97927ec4b4cf7acfe2befbf6c716c2bcb3a855d9e0076c7150356d
                - name: grafana-image-renderer
                  ref: dhi/grafana-image-renderer:5.8.9-debian13@sha256:8616a9f6a4c962682a10e6283db0aa6190d008188cc55a630c7cabdebd5ebc76
                - name: bats
                  ref: dhi/bats:1.13.0-debian13@sha256:d2a87ffe44ac1bdceca81fa498fb9a34719b2ae6f55d380eff64741f32709e6e
                - name: busybox
                  ref: dhi/busybox:1.37.0-debian13@sha256:e0cbe035dd7d7072e088172c5833bf756bfba3618567c0f5e73288e97e3a19bf
                - name: curl
                  ref: dhi/curl:8.14.1-debian13@sha256:53cb07c0702c04c750fd2c58641b81766603917aebab571b3bb739d24464f1e3
                - name: k8s-sidecar
                  ref: dhi/k8s-sidecar:2.7.3-debian13@sha256:ec51d4d917d6001ad0dbc454b07c84fd1bbe6718b5f05171658c4e11e43d5f4c
              name: grafana-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/grafana-community/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/grafana
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: grafana
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: grafana
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/grafana/config
