# syntax=dhi.io/build:2-helm3

name: Grafana Helm chart 12.x
image: dhi.io/grafana-chart
variant: helm
tags:
  - 12.4.4
platforms:
  - linux/amd64
vars:
  BATS_REFERENCE: dhi/bats:1.13.0-debian13@sha256:3129336d4c3a4512b6bde3f0eabb31f2dab17a7a695582e6092698233ebf6111
  BUSYBOX_REFERENCE: dhi/busybox:1.37.0-debian13@sha256:e0cbe035dd7d7072e088172c5833bf756bfba3618567c0f5e73288e97e3a19bf
  CHART_COMMIT_SHA: b44025959e0b17f6475946859e34939d8dbf1cd5
  CURL_REFERENCE: dhi/curl:8.14.1-debian13@sha256:73b092d6bf608beb9435d398db79a714a77de242be381fe27e2b1d5b0e50f3f9
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  GRAFANA_IMAGE_RENDERER_REFERENCE: dhi/grafana-image-renderer:5.8.8-debian13@sha256:97410709a14c6ece771c55e574376fe10426af3f41e2a49640ed7c4d8a9670de
  GRAFANA_REFERENCE: dhi/grafana:12.4.4-debian13@sha256:7538b87493dd80f484b8fbdb3c37958a35b2a3193b5063e04ce37b66f20adf6a
  HELM_REFERENCE: dhi/helm:3.21.0-debian13-dev@sha256:7b9ee43cc77e81e2dcbb1b0f6e8ce376b71d63c90c81f2863e24aefff774a8da
  K8S_SIDECAR_REFERENCE: dhi/k8s-sidecar:2.7.3-debian13@sha256:b67a58d73b1f34cf22879b7223224dabdc43e89661a93b56ac12e27ce698141e
  SEMVER_MAJOR_MINOR_VERSION: "12.4"
  SEMVER_MAJOR_VERSION: "12"
  SEMVER_VERSION: 12.4.4
  VERSION: 12.4.4
contents:
  builds:
    - name: grafana
      uses: dhi.io/helm:3.21.0-debian13-dev@sha256:7b9ee43cc77e81e2dcbb1b0f6e8ce376b71d63c90c81f2863e24aefff774a8da
      contents:
        packages:
          - bash
          - build-essential
          - coreutils
          - grep
          - libc-bin
          - sed
        files:
          - url: git+https://github.com/grafana-community/helm-charts.git#grafana-12.4.4
            checksum: b44025959e0b17f6475946859e34939d8dbf1cd5
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/grafana
          with:
            chart:
              appRef: grafana
              description: Docker Hardened Images Helm chart for Grafana
              images:
                - name: grafana
                  ref: dhi/grafana:12.4.4-debian13@sha256:7538b87493dd80f484b8fbdb3c37958a35b2a3193b5063e04ce37b66f20adf6a
                - name: grafana-image-renderer
                  ref: dhi/grafana-image-renderer:5.8.8-debian13@sha256:97410709a14c6ece771c55e574376fe10426af3f41e2a49640ed7c4d8a9670de
                - name: bats
                  ref: dhi/bats:1.13.0-debian13@sha256:3129336d4c3a4512b6bde3f0eabb31f2dab17a7a695582e6092698233ebf6111
                - name: busybox
                  ref: dhi/busybox:1.37.0-debian13@sha256:e0cbe035dd7d7072e088172c5833bf756bfba3618567c0f5e73288e97e3a19bf
                - name: curl
                  ref: dhi/curl:8.14.1-debian13@sha256:73b092d6bf608beb9435d398db79a714a77de242be381fe27e2b1d5b0e50f3f9
                - name: k8s-sidecar
                  ref: dhi/k8s-sidecar:2.7.3-debian13@sha256:b67a58d73b1f34cf22879b7223224dabdc43e89661a93b56ac12e27ce698141e
              name: grafana-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/grafana-community/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/grafana
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: grafana
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: grafana
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/grafana/config
