# syntax=dhi.io/build:2-helm3

name: Grafana Helm chart 13.x
image: dhi.io/grafana-chart
variant: helm
tags:
  - 13.2.8
platforms:
  - linux/amd64
vars:
  BATS_REFERENCE: dhi/bats:1.14.0-debian13@sha256:e863aa79e2a9c4e9894e2ab543a3842c996609e8d4258396163b35bbc0840293
  BUSYBOX_REFERENCE: dhi/busybox:1.37.0-debian13@sha256:b3620c618e4622e1037675820c89a34ef3091fbd2e31552daaae1408a6fa1ee7
  CHART_COMMIT_SHA: 56ac2aefed98934ff69fc7a2f1eb7462d85bc842
  CHART_HELM_NAME: grafana-chart
  CURL_REFERENCE: dhi/curl:8.14.1-debian13@sha256:941ad5150dee5c1662176761f36aee068cacfc75c299455b9e10c41b197e706c
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  GRAFANA_IMAGE_RENDERER_REFERENCE: dhi/grafana-image-renderer:5.12.5-debian13@sha256:58e5d1efb1cbb190b21020914544e42a1c2d030d8474a2ea57e8e006951c2318
  GRAFANA_REFERENCE: dhi/grafana:13.2.3-debian13@sha256:55715acdf0d0160d9fe66a68b10d9f16dd9aed0abea19c3e2685271ac0594999
  HELM_VERSION: 4.1.4-2
  K8S_SIDECAR_REFERENCE: dhi/k8s-sidecar:2.11.2-debian13@sha256:afbb535d9e8b5102d81e6291f7e5c3e3500ccf2b658300b82c1ae883945477bb
  SEMVER_MAJOR_MINOR_VERSION: "13.2"
  SEMVER_MAJOR_VERSION: "13"
  SEMVER_VERSION: 13.2.8
  VERSION: 13.2.8
contents:
  repositories:
    - deb [signed-by=/usr/share/keyrings/dhi-deb-main.gpg] http://dhi.io/deb/debian/main trixie main
  keyring:
    - https://dhi.io/keyring/dhi-deb-gpg.D46852F6925E9F71.key
  builds:
    - name: grafana
      contents:
        packages:
          - bash
          - ca-certificates
          - coreutils
          - helm=4.1.4-2
        files:
          - url: git+https://github.com/grafana-community/helm-charts.git#grafana-13.2.8
            checksum: 56ac2aefed98934ff69fc7a2f1eb7462d85bc842
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/grafana
          with:
            chart:
              appRef: grafana
              description: Docker Hardened Images Helm chart for Grafana
              images:
                - name: grafana
                  ref: dhi/grafana:13.2.3-debian13@sha256:55715acdf0d0160d9fe66a68b10d9f16dd9aed0abea19c3e2685271ac0594999
                - name: grafana-image-renderer
                  ref: dhi/grafana-image-renderer:5.12.5-debian13@sha256:58e5d1efb1cbb190b21020914544e42a1c2d030d8474a2ea57e8e006951c2318
                - name: bats
                  ref: dhi/bats:1.14.0-debian13@sha256:e863aa79e2a9c4e9894e2ab543a3842c996609e8d4258396163b35bbc0840293
                - name: busybox
                  ref: dhi/busybox:1.37.0-debian13@sha256:b3620c618e4622e1037675820c89a34ef3091fbd2e31552daaae1408a6fa1ee7
                - name: curl
                  ref: dhi/curl:8.14.1-debian13@sha256:941ad5150dee5c1662176761f36aee068cacfc75c299455b9e10c41b197e706c
                - name: k8s-sidecar
                  ref: dhi/k8s-sidecar:2.11.2-debian13@sha256:afbb535d9e8b5102d81e6291f7e5c3e3500ccf2b658300b82c1ae883945477bb
              name: grafana-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/grafana-community/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/grafana
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: grafana
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: grafana
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/grafana/config
