# syntax=dhi.io/build:2-helm3

name: Grafana Operator Helm chart 5.x
image: dhi.io/grafana-operator-chart
variant: helm
tags:
  - 5.23.0
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: 4c77de5f58dd663bf779d9ddf8bda66c150654f8
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  GRAFANA_OPERATOR_REFERENCE: dhi/grafana-operator:5.22.2-debian13@sha256:9b90d1d9c259b1e0ce958fc1df79fdb0ebebb9ddbe339e0f4d6429d6f571413e
  HELM_REFERENCE: dhi/helm:3.21.0-debian13-dev@sha256:0ee5c30c2d65033300ceb74755e2bd6bc49120d9116a1e8c2880500483315e9b
  SEMVER_MAJOR_MINOR_VERSION: "5.23"
  SEMVER_MAJOR_VERSION: "5"
  SEMVER_VERSION: 5.23.0
  VERSION: 5.23.0
contents:
  builds:
    - name: grafana-operator-chart
      uses: dhi.io/helm:3.21.0-debian13-dev@sha256:0ee5c30c2d65033300ceb74755e2bd6bc49120d9116a1e8c2880500483315e9b
      contents:
        files:
          - url: git+https://github.com/grafana/grafana-operator.git#v5.23.0
            checksum: 4c77de5f58dd663bf779d9ddf8bda66c150654f8
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/deploy/helm/grafana-operator
          with:
            chart:
              appRef: grafana-operator
              description: Docker Hardened Images Helm chart for Grafana Operator
              images:
                - name: grafana-operator
                  ref: dhi/grafana-operator:5.22.2-debian13@sha256:9b90d1d9c259b1e0ce958fc1df79fdb0ebebb9ddbe339e0f4d6429d6f571413e
              name: grafana-operator-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/grafana/grafana-operator
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/deploy/helm/grafana-operator
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/deploy/helm
          privileged: true
          with:
            chart: grafana-operator
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/deploy/helm
          with:
            chart: grafana-operator
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/deploy/helm
          with:
            chart: grafana-operator
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/grafana-operator/config
