# syntax=dhi.io/build:2-helm3

name: Redis Helm chart 23.x
image: dhi.io/redis-chart
variant: helm
tags:
  - 23.0.7
platforms:
  - linux/amd64
vars:
  BASH_REFERENCE: dhi/bash:5.2.37-debian13@sha256:6551b902de6a6f1a9fd1327227ff763cb3e7b92a2a6c83c76e4d80508f7f0006
  CHART_COMMIT_SHA: 4f7288e1b226ee2bfc150e507ffdca04a98a0952
  CHART_HELM_NAME: redis-chart
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_VERSION: 4.1.4-2
  KUBECTL_REFERENCE: dhi/kubectl:1.34.12-debian13-compat@sha256:1e8e05caac546b9d07fdbdc0cb1c7ce3fb9b6d7f424a2f502ef28f63dbc91358
  REDIS_EXPORTER_REFERENCE: dhi/redis-exporter:1.93.0-debian13-compat@sha256:16a785e3491e22909be056ecb54dd2b8b0b5607948c88e2542288b99f870544d
  REDIS_REFERENCE: dhi/redis:8.10.2-debian13-compat@sha256:596c6b9c9a190bfc51893c2a0e8c10d987d1d080ed9a2ac6137d7d909ccfd0a7
  SEMVER_MAJOR_MINOR_VERSION: "23.0"
  SEMVER_MAJOR_VERSION: "23"
  SEMVER_VERSION: 23.0.7
  VERSION: 23.0.7
contents:
  repositories:
    - deb [signed-by=/usr/share/keyrings/dhi-deb-main.gpg] http://dhi.io/deb/debian/main trixie main
  keyring:
    - https://dhi.io/keyring/dhi-deb-gpg.D46852F6925E9F71.key
  builds:
    - name: redis
      contents:
        packages:
          - bash
          - ca-certificates
          - coreutils
          - helm=4.1.4-2
        files:
          - url: git+https://github.com/docker-hardened-images/helm-charts.git#redis/23.0.7
            checksum: 4f7288e1b226ee2bfc150e507ffdca04a98a0952
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/redis
          with:
            chart:
              appRef: redis
              description: Docker Hardened Images Helm chart for Redis
              images:
                - name: redis
                  ref: dhi/redis:8.10.2-debian13-compat@sha256:596c6b9c9a190bfc51893c2a0e8c10d987d1d080ed9a2ac6137d7d909ccfd0a7
                - name: redis-exporter
                  ref: dhi/redis-exporter:1.93.0-debian13-compat@sha256:16a785e3491e22909be056ecb54dd2b8b0b5607948c88e2542288b99f870544d
                - name: bash
                  ref: dhi/bash:5.2.37-debian13@sha256:6551b902de6a6f1a9fd1327227ff763cb3e7b92a2a6c83c76e4d80508f7f0006
                - name: kubectl
                  ref: dhi/kubectl:1.34.12-debian13-compat@sha256:1e8e05caac546b9d07fdbdc0cb1c7ce3fb9b6d7f424a2f502ef28f63dbc91358
              name: redis-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/docker-hardened-images/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: update chart values
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/redis
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          privileged: true
          with:
            chart: ${source.dir}/helm-charts/redis
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts
          with:
            chart: redis
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: ${source.dir}/helm-charts/redis
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/redis/config
