metadata:
  display-name: GitLab Helm chart
  short-description: GitLab DevSecOps platform using Docker Hardened Images and external stateful services
  featured: false
  fips-compliant: false
  fips-modules: []
  stig-certified: false
  home-url: https://about.gitlab.com/
  categories:
    - integration-and-delivery
    - developer-tools
    - security
  alternatives: []
