# syntax=dhi.io/build:2-helm3

name: Piraeus HA Controller Helm chart 1.x
image: dhi.io/piraeus-ha-controller-chart
variant: helm
tags:
  - 1.3.2
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: 97d304aa1d2d67985517c78ed29953f9ec91bdbc
  CHART_HELM_NAME: piraeus-ha-controller-chart
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_VERSION: 4.1.4-2
  PIRAEUS_HA_CONTROLLER_REFERENCE: dhi/piraeus-ha-controller:1.3.2-debian13@sha256:99a1b81f5010b6badce49395a67bac57924ffb70c4ce7c26c7aa455216e30437
  SEMVER_MAJOR_MINOR_VERSION: "1.3"
  SEMVER_MAJOR_VERSION: "1"
  SEMVER_VERSION: 1.3.2
  VERSION: 1.3.2
contents:
  repositories:
    - deb [signed-by=/usr/share/keyrings/dhi-deb-main.gpg] http://dhi.io/deb/debian/main trixie main
  keyring:
    - https://dhi.io/keyring/dhi-deb-gpg.D46852F6925E9F71.key
  builds:
    - name: piraeus-ha-controller
      contents:
        packages:
          - bash
          - ca-certificates
          - coreutils
          - helm=4.1.4-2
        files:
          - url: git+https://github.com/piraeusdatastore/helm-charts.git#piraeus-ha-controller-1.3.2
            checksum: 97d304aa1d2d67985517c78ed29953f9ec91bdbc
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/piraeus-ha-controller
          with:
            chart:
              appRef: piraeus-ha-controller
              description: Docker Hardened Images Helm chart for Piraeus HA Controller
              images:
                - name: piraeus-ha-controller
                  ref: dhi/piraeus-ha-controller:1.3.2-debian13@sha256:99a1b81f5010b6badce49395a67bac57924ffb70c4ce7c26c7aa455216e30437
              name: piraeus-ha-controller-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/piraeusdatastore/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/piraeus-ha-controller
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: piraeus-ha-controller
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: piraeus-ha-controller
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/piraeus-ha-controller/config
