# syntax=dhi.io/build:2-helm3

name: VictoriaMetrics Cluster Helm chart 0.x
image: dhi.io/victoriametrics-cluster-chart
variant: helm
tags:
  - 0.43.0
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: f72311aefe5185100a8df418419b2539a300437e
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.21.0-debian13-dev@sha256:27a89b8b9ac55c501c63c5ce01efab9b5e0915f98c220e54787816ff99c7abc2
  SEMVER_MAJOR_MINOR_VERSION: "0.43"
  SEMVER_MAJOR_VERSION: "0"
  SEMVER_VERSION: 0.43.0
  VERSION: 0.43.0
  VMAUTH_REFERENCE: dhi/victoriametrics-vmauth:1.144.0-debian13@sha256:427ac2792fdd2565894649f48061de3e0df0049a67909013cadf4c82f25a93c8
  VMINSERT_REFERENCE: dhi/victoriametrics-vminsert:1.144.0-debian13@sha256:8a977b1cfa81242ac67decb0e920aa719ab09450efe11377fa34c08098de0f61
  VMSELECT_REFERENCE: dhi/victoriametrics-vmselect:1.144.0-debian13@sha256:83bd8ed46e4a44410e19674f456e12e51fcb12bfcd10661a48f7c900a09b1c0e
  VMSTORAGE_REFERENCE: dhi/victoriametrics-vmstorage:1.144.0-debian13@sha256:4cdde160f2260b9b15ca785633c28ae6e6457b5b6be649b9d48a7d3c9d757f7c
contents:
  builds:
    - name: victoriametrics-cluster-chart
      uses: dhi.io/helm:3.21.0-debian13-dev@sha256:27a89b8b9ac55c501c63c5ce01efab9b5e0915f98c220e54787816ff99c7abc2
      contents:
        files:
          - url: git+https://github.com/VictoriaMetrics/helm-charts.git#victoria-metrics-cluster-0.43.0
            checksum: f72311aefe5185100a8df418419b2539a300437e
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/victoria-metrics-cluster
          with:
            chart:
              appRef: victoriametrics-vmselect
              description: Docker Hardened Images Helm chart for VictoriaMetrics Cluster
              images:
                - name: victoriametrics-vmselect
                  ref: dhi/victoriametrics-vmselect:1.144.0-debian13@sha256:83bd8ed46e4a44410e19674f456e12e51fcb12bfcd10661a48f7c900a09b1c0e
                - name: victoriametrics-vmstorage
                  ref: dhi/victoriametrics-vmstorage:1.144.0-debian13@sha256:4cdde160f2260b9b15ca785633c28ae6e6457b5b6be649b9d48a7d3c9d757f7c
                - name: victoriametrics-vminsert
                  ref: dhi/victoriametrics-vminsert:1.144.0-debian13@sha256:8a977b1cfa81242ac67decb0e920aa719ab09450efe11377fa34c08098de0f61
                - name: victoriametrics-vmauth
                  ref: dhi/victoriametrics-vmauth:1.144.0-debian13@sha256:427ac2792fdd2565894649f48061de3e0df0049a67909013cadf4c82f25a93c8
              name: victoriametrics-cluster-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/VictoriaMetrics/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: update chart values
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/victoria-metrics-cluster
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update sidecar values
          uses: yq/patch@v1
          with:
            file: ${source.dir}/helm-charts/charts/victoria-metrics-cluster/values-sidecar.yaml
            patches:
              - .extraContainers[0].image = "dhi/victoriametrics-vmauth:1.144.0-debian13@sha256:427ac2792fdd2565894649f48061de3e0df0049a67909013cadf4c82f25a93c8"
              - .extraContainers[0].securityContext.enabled = true
              - .extraContainers[0].securityContext.runAsNonRoot = true
              - .extraContainers[0].securityContext.runAsUser = 65532
              - .extraContainers[0].securityContext.runAsGroup = 65532
        - name: blank 3rd party images
          work-dir: ${source.dir}/helm-charts/charts/victoria-metrics-cluster
          runs: |
            set -eux -o pipefail

            # Blank out the 3rd party images for victoriametrics/vmbackupmanager
            sed -i '/- name: vmbackupmanager/{n;s/^\([[:space:]]*image:\).*/\1 "" #THIS IMAGE IS NOT IN THE DHI CATALOG YET, PLEASE CONTACT THE DOCKER TEAM IF NEEDED/;}' ./templates/vmstorage-server.yaml
        - name: update dependencies
          uses: helm/cmd@v1
          privileged: true
          with:
            chart: ${source.dir}/helm-charts/charts/victoria-metrics-cluster
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: victoria-metrics-cluster
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: ${source.dir}/helm-charts/charts/victoria-metrics-cluster
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/victoriametrics-cluster/config
