metadata:
  display-name: KGateway Helm chart
  short-description: KGateway Helm chart deploys a Kubernetes-native gateway implementing the Gateway API with Envoy Proxy.
  featured: false
  home-url: https://github.com/kgateway-dev/kgateway/tree/main/install/helm/kgateway
  categories:
    - networking
