metadata:
  display-name: Cilium Helm chart
  short-description: eBPF-based Networking, Security, and Observability for Kubernetes
  featured: false
  home-url: https://cilium.io/
  categories:
    - networking
    - security
