# syntax=dhi.io/build:2-helm3

name: APISIX Ingress Controller Helm chart 1.x
image: dhi.io/apisix-ingress-controller-chart
variant: helm
tags:
  - 1.2.0
platforms:
  - linux/amd64
vars:
  ADC_IMAGE_REFERENCE: dhi/adc:0.26.0-debian13@sha256:41b81bced27a0d95b503b60114ceebeba0e9a5088be0bff03c295ff61218113b
  APISIX_INGRESS_CONTROLLER_IMAGE_REFERENCE: dhi/apisix-ingress-controller:2.1.0-debian13@sha256:a5430b37078b253386157b8b56cf035cf3802fdaa9a3f76c54305c68b4e03737
  CHART_COMMIT_SHA: 5d5caccadd1d0756d44886e57e225c0039f2a358
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.21.0-debian13-dev@sha256:ed0c764ca91c1084c850f3b00e7248f9127153bb3a5803058a337ac99ba6d479
  SEMVER_MAJOR_MINOR_VERSION: "1.2"
  SEMVER_MAJOR_VERSION: "1"
  SEMVER_VERSION: 1.2.0
  VERSION: 1.2.0
contents:
  builds:
    - name: apisix-ingress-controller-chart
      uses: dhi.io/helm:3.21.0-debian13-dev@sha256:ed0c764ca91c1084c850f3b00e7248f9127153bb3a5803058a337ac99ba6d479
      contents:
        files:
          - url: git+https://github.com/apache/apisix-helm-chart.git#apisix-ingress-controller-1.2.0
            checksum: 5d5caccadd1d0756d44886e57e225c0039f2a358
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/apisix-ingress-controller
          with:
            chart:
              appRef: apisix-ingress-controller
              description: Docker Hardened Images Helm chart for APISIX Ingress Controller
              images:
                - name: apisix-ingress-controller
                  ref: dhi/apisix-ingress-controller:2.1.0-debian13@sha256:a5430b37078b253386157b8b56cf035cf3802fdaa9a3f76c54305c68b4e03737
                - name: adc
                  ref: dhi/adc:0.26.0-debian13@sha256:41b81bced27a0d95b503b60114ceebeba0e9a5088be0bff03c295ff61218113b
              name: apisix-ingress-controller-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/apache/apisix-ingress-controller
            cmd: prepare
            registry: dhi.io
        - name: add image pull secrets
          work-dir: ${source.dir}/helm-charts/charts/apisix-ingress-controller
          runs: |
            set -eux -o pipefail

            sed -i '/^      containers:/i\
                  {{- with .Values.imagePullSecrets }}\
                  imagePullSecrets:\
                    {{- range $.Values.imagePullSecrets }}\
                    - name: {{ . }}\
                    {{- end }}\
                  {{- end }}' templates/deployment.yaml
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/apisix-ingress-controller
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: apisix-ingress-controller
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: apisix-ingress-controller
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/apisix-ingress-controller/config
