# syntax=dhi.io/build:2-helm3

name: Grafana Rollout Operator Helm chart 0.x
image: dhi.io/grafana-rollout-operator-chart
variant: helm
tags:
  - 0.46.0
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: 7410eaad4501e0ab6f5efc7a7bae0d64fbbc5817
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.20.1-debian13-dev@sha256:92e43232140b33018c99c7b178d2f7302cfb0f0017267731b0512ac206cd8690
  ROLLOUT_OPERATOR_REFERENCE: dhi/grafana-rollout-operator:0.36.0-debian13@sha256:643d6f17a84de7ea662db213ed7b390be50d32c6b667445d632416b571207d96
  SEMVER_MAJOR_MINOR_VERSION: "0.46"
  SEMVER_MAJOR_VERSION: "0"
  SEMVER_VERSION: 0.46.0
  VERSION: 0.46.0
contents:
  builds:
    - name: grafana-rollout-operator-chart
      uses: dhi.io/helm:3.20.1-debian13-dev@sha256:92e43232140b33018c99c7b178d2f7302cfb0f0017267731b0512ac206cd8690
      work-dir: ${source.dir}/helm-charts/charts/rollout-operator
      contents:
        files:
          - url: git+https://github.com/grafana/helm-charts.git#rollout-operator-0.46.0
            checksum: 7410eaad4501e0ab6f5efc7a7bae0d64fbbc5817
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          with:
            chart:
              appRef: grafana-rollout-operator
              description: Docker Hardened Images Helm chart for Grafana Rollout Operator
              images:
                - name: grafana-rollout-operator
                  ref: dhi/grafana-rollout-operator:0.36.0-debian13@sha256:643d6f17a84de7ea662db213ed7b390be50d32c6b667445d632416b571207d96
              name: grafana-rollout-operator-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/grafana/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          privileged: true
          with:
            chart: .
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          with:
            chart: .
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: .
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/grafana-rollout-operator/config
