# syntax=dhi.io/build:2-helm3

name: Grafana Rollout Operator Helm chart 0.x
image: dhi.io/grafana-rollout-operator-chart
variant: helm
tags:
  - 0.50.0
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: 8ac07d41b2fa02ca16dc0fc084d8f145cb690988
  CHART_HELM_NAME: grafana-rollout-operator-chart
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.21.2-debian13-dev@sha256:e30b522f3f39307b7710b304f082f76d7b8fc0d0140bfc44bdf2892c5411519f
  ROLLOUT_OPERATOR_REFERENCE: dhi/grafana-rollout-operator:0.38.0-debian13@sha256:515025474d42086367692922b144473fa10e90211211cfc1a04c2924d73a2e10
  SEMVER_MAJOR_MINOR_VERSION: "0.50"
  SEMVER_MAJOR_VERSION: "0"
  SEMVER_VERSION: 0.50.0
  VERSION: 0.50.0
contents:
  builds:
    - name: grafana-rollout-operator-chart
      uses: dhi.io/helm:3.21.2-debian13-dev@sha256:e30b522f3f39307b7710b304f082f76d7b8fc0d0140bfc44bdf2892c5411519f
      work-dir: ${source.dir}/helm-charts/charts/rollout-operator
      contents:
        files:
          - url: git+https://github.com/grafana/helm-charts.git#rollout-operator-0.50.0
            checksum: 8ac07d41b2fa02ca16dc0fc084d8f145cb690988
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          with:
            chart:
              appRef: grafana-rollout-operator
              description: Docker Hardened Images Helm chart for Grafana Rollout Operator
              images:
                - name: grafana-rollout-operator
                  ref: dhi/grafana-rollout-operator:0.38.0-debian13@sha256:515025474d42086367692922b144473fa10e90211211cfc1a04c2924d73a2e10
              name: grafana-rollout-operator-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/grafana/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          with:
            chart: .
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: .
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/grafana-rollout-operator/config
