metadata:
  display-name: GitLab Runner Helm chart
  short-description: GitLab Runner runs your CI/CD jobs and sends the results back to GitLab.
  featured: false
  home-url: https://gitlab.com/gitlab-org/gitlab-runner
  categories:
    - integration-and-delivery
