# syntax=dhi.io/build:2-helm3

name: Vector Helm chart 0.x
image: dhi.io/vector-chart
variant: helm
tags:
  - 0.58.0
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: ca6e41c442a90dd70b5c7c04160894ce3c2472ab
  CHART_HELM_NAME: vector-chart
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HAPROXY_REFERENCE: dhi/haproxy:3.0.26-debian13@sha256:03ecc0520e80133a4f97e95e809f197585bacfbc4176cbbe2e9c3f92294b109d
  HELM_VERSION: 4.1.4-2
  SEMVER_MAJOR_MINOR_VERSION: "0.58"
  SEMVER_MAJOR_VERSION: "0"
  SEMVER_VERSION: 0.58.0
  VECTOR_REFERENCE: dhi/vector:0.57.0-debian13@sha256:9656656ac898598c6c81f4355503287517f3c9d0ed98b0535443c5c09620ac03
  VERSION: 0.58.0
contents:
  repositories:
    - deb [signed-by=/usr/share/keyrings/dhi-deb-main.gpg] http://dhi.io/deb/debian/main trixie main
  keyring:
    - https://dhi.io/keyring/dhi-deb-gpg.D46852F6925E9F71.key
  builds:
    - name: vector-chart
      contents:
        packages:
          - bash
          - ca-certificates
          - coreutils
          - helm=4.1.4-2
        files:
          - url: git+https://github.com/vectordotdev/helm-charts.git#vector-0.58.0
            checksum: ca6e41c442a90dd70b5c7c04160894ce3c2472ab
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/vector
          with:
            chart:
              appRef: vector
              description: Docker Hardened Images Helm chart for Vector
              images:
                - name: vector
                  ref: dhi/vector:0.57.0-debian13@sha256:9656656ac898598c6c81f4355503287517f3c9d0ed98b0535443c5c09620ac03
                - name: haproxy
                  ref: dhi/haproxy:3.0.26-debian13@sha256:03ecc0520e80133a4f97e95e809f197585bacfbc4176cbbe2e9c3f92294b109d
              name: vector-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/vectordotdev/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/vector
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          with:
            chart: ${source.dir}/helm-charts/charts/vector
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: vector
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: ${source.dir}/helm-charts/charts/vector
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/vector/config
