apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-dhi-gitlab-cng-scripts
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gitlab.standardLabels" . | nindent 4 }}
data:
  wait-for-deps: |
{{ .Files.Get "files/dhi-gitlab-cng/wait-for-deps" | indent 4 }}
  rails-dependencies: |
{{ .Files.Get "files/dhi-gitlab-cng/rails-dependencies" | indent 4 }}
  db-migrate: |
{{ .Files.Get "files/dhi-gitlab-cng/db-migrate" | indent 4 }}
  custom-instance-setup: |
{{ .Files.Get "files/dhi-gitlab-cng/custom-instance-setup" | indent 4 }}
  bypass_schema_version_check.rb: |
{{ .Files.Get "files/dhi-gitlab-cng/lib/bypass_schema_version_check.rb" | indent 4 }}
  clickhouse.rb: |
{{ .Files.Get "files/dhi-gitlab-cng/lib/checks/clickhouse.rb" | indent 4 }}
  postgresql.rb: |
{{ .Files.Get "files/dhi-gitlab-cng/lib/checks/postgresql.rb" | indent 4 }}
  redis.rb: |
{{ .Files.Get "files/dhi-gitlab-cng/lib/checks/redis.rb" | indent 4 }}
  topology_service.rb: |
{{ .Files.Get "files/dhi-gitlab-cng/lib/checks/topology_service.rb" | indent 4 }}
