# syntax=dhi.io/build:2-helm3

name: OpenTelemetry Collector Helm chart 0.x
image: dhi.io/opentelemetry-collector-chart
variant: helm
tags:
  - 0.147.0
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: 035d283d86a0fd3aad700ab2d25c591e4b6163a4
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.20.1-debian13-dev@sha256:caa7223ddf8951e9bb159f921683e515361321ccf67c103981ffea2ae14a64eb
  OPENTELEMETRY_COLLECTOR_REFERENCE: dhi/opentelemetry-collector:0.147.0-debian13@sha256:95b36ed750fc56f3aca22319e92dde0536eb65cfe36bd2e42b33263dcb4ab189
  SEMVER_MAJOR_MINOR_VERSION: "0.147"
  SEMVER_MAJOR_VERSION: "0"
  SEMVER_VERSION: 0.147.0
  VERSION: 0.147.0
contents:
  builds:
    - name: opentelemetry-collector
      uses: dhi.io/helm:3.20.1-debian13-dev@sha256:caa7223ddf8951e9bb159f921683e515361321ccf67c103981ffea2ae14a64eb
      contents:
        packages:
          - bash
          - build-essential
          - coreutils
          - grep
          - libc-bin
          - sed
        files:
          - url: git+https://github.com/open-telemetry/opentelemetry-helm-charts.git#opentelemetry-collector-0.147.0
            checksum: 035d283d86a0fd3aad700ab2d25c591e4b6163a4
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/opentelemetry-collector
          with:
            chart:
              appRef: opentelemetry-collector
              description: Docker Hardened Images Helm chart for OpenTelemetry Collector
              images:
                - name: opentelemetry-collector
                  ref: dhi/opentelemetry-collector:0.147.0-debian13@sha256:95b36ed750fc56f3aca22319e92dde0536eb65cfe36bd2e42b33263dcb4ab189
              name: opentelemetry-collector-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/open-telemetry/opentelemetry-helm-charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/opentelemetry-collector
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: opentelemetry-collector
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: opentelemetry-collector
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/opentelemetry-collector/config
