# syntax=dhi.io/build:2-helm3

name: OpenTelemetry Collector Helm chart 0.x
image: dhi.io/opentelemetry-collector-chart
variant: helm
tags:
  - 0.153.0
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: f0d8d49ec31d856de7deaa0e519fe15ab7bb7fdf
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.20.2-debian13-dev@sha256:bf8a03f405f8a317925ae232b32a1d29943a57b019dabfb0b7d0e624f558baf2
  OPENTELEMETRY_COLLECTOR_REFERENCE: dhi/opentelemetry-collector:0.151.0-debian13@sha256:4d7b66827eedf973416b92ae69fdac9f9a6f715bf224ef45800457a7fff65597
  SEMVER_MAJOR_MINOR_VERSION: "0.153"
  SEMVER_MAJOR_VERSION: "0"
  SEMVER_VERSION: 0.153.0
  VERSION: 0.153.0
contents:
  builds:
    - name: opentelemetry-collector
      uses: dhi.io/helm:3.20.2-debian13-dev@sha256:bf8a03f405f8a317925ae232b32a1d29943a57b019dabfb0b7d0e624f558baf2
      contents:
        packages:
          - bash
          - build-essential
          - coreutils
          - grep
          - libc-bin
          - sed
        files:
          - url: git+https://github.com/open-telemetry/opentelemetry-helm-charts.git#opentelemetry-collector-0.153.0
            checksum: f0d8d49ec31d856de7deaa0e519fe15ab7bb7fdf
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/opentelemetry-collector
          with:
            chart:
              appRef: opentelemetry-collector
              description: Docker Hardened Images Helm chart for OpenTelemetry Collector
              images:
                - name: opentelemetry-collector
                  ref: dhi/opentelemetry-collector:0.151.0-debian13@sha256:4d7b66827eedf973416b92ae69fdac9f9a6f715bf224ef45800457a7fff65597
              name: opentelemetry-collector-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/open-telemetry/opentelemetry-helm-charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/opentelemetry-collector
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: opentelemetry-collector
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: opentelemetry-collector
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/opentelemetry-collector/config
