# syntax=dhi.io/build:2-helm3

name: OpenTelemetry Collector Helm chart 0.x
image: dhi.io/opentelemetry-collector-chart
variant: helm
tags:
  - 0.158.0
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: c42f62b58c13ccf1718ec4149f0d2f96b3b6428f
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.21.0-debian13-dev@sha256:dedafe204585b6ae9934e8936b95d767cdddef288bf56081b1071ed90173bbeb
  OPENTELEMETRY_COLLECTOR_REFERENCE: dhi/opentelemetry-collector:0.153.0-debian13@sha256:e5388347fc00b18a77b20ca4f85630fbbf6cbd14823f2f11171af09ea3a5ea97
  SEMVER_MAJOR_MINOR_VERSION: "0.158"
  SEMVER_MAJOR_VERSION: "0"
  SEMVER_VERSION: 0.158.0
  VERSION: 0.158.0
contents:
  builds:
    - name: opentelemetry-collector
      uses: dhi.io/helm:3.21.0-debian13-dev@sha256:dedafe204585b6ae9934e8936b95d767cdddef288bf56081b1071ed90173bbeb
      contents:
        packages:
          - bash
          - build-essential
          - coreutils
          - grep
          - libc-bin
          - sed
        files:
          - url: git+https://github.com/open-telemetry/opentelemetry-helm-charts.git#opentelemetry-collector-0.158.0
            checksum: c42f62b58c13ccf1718ec4149f0d2f96b3b6428f
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/opentelemetry-collector
          with:
            chart:
              appRef: opentelemetry-collector
              description: Docker Hardened Images Helm chart for OpenTelemetry Collector
              images:
                - name: opentelemetry-collector
                  ref: dhi/opentelemetry-collector:0.153.0-debian13@sha256:e5388347fc00b18a77b20ca4f85630fbbf6cbd14823f2f11171af09ea3a5ea97
              name: opentelemetry-collector-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/open-telemetry/opentelemetry-helm-charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/opentelemetry-collector
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: opentelemetry-collector
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: opentelemetry-collector
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/opentelemetry-collector/config
