controller:
  image:
    registry: ${kgateway.registry}
    repository: ${kgateway.repository}
    tag: ${kgateway.tag}@${kgateway.digest}
    pullPolicy: IfNotPresent
  securityContext:
    runAsNonRoot: true
    runAsUser: 65532
    runAsGroup: 65532
