metadata:
  display-name: Envoy AI Gateway Helm chart
  short-description: Deploys Envoy AI Gateway, a provider-agnostic, OpenAI-compatible AI/LLM gateway built on Envoy Gateway.
  featured: false
  home-url: https://github.com/envoyproxy/ai-gateway/tree/main/manifests/charts/ai-gateway-helm
  categories:
    - networking
