image:
  repository: ${external-dns.registry}/${external-dns.repository}
  tag: ${external-dns.tag}@${external-dns.digest}

# No longer set to default since v1.22 (so set to v1.21's default)
policy: upsert-only
