# syntax=dhi.io/build:2-helm3

name: ECK Operator Helm chart 3.x
image: dhi.io/eck-operator-chart
variant: helm
tags:
  - 3.4.0
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: ceed5fd496a524f5bc8d27f3470d71c40389d0fc
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  ECK_OPERATOR_REFERENCE: dhi/eck-operator:3.4.0-debian13@sha256:5268d0ce742e59d0a46d3b3671da64af146657fcae71bf9dbe5091210c0c0ede
  ELASTICSEARCH_REFERENCE: dhi/elasticsearch:9.4.0-debian13@sha256:35ab72e0d27434c2514b04baaf561e1debfd4975a3411f6537cd74a5c273e32a
  HELM_REFERENCE: dhi/helm:3.20.2-debian13-dev@sha256:ce95680846fc18d3d179f82f9d633c8274f41cd0d0f8213cbfc4039fbe2cd112
  KIBANA_REFERENCE: dhi/kibana:9.3.4-debian13@sha256:093438897d54ec1dbb67b5c7f4fdf01192ddbcc242199eeabf2c88f49c5ba85b
  LOGSTASH_COMPAT_REFERENCE: dhi/logstash:9.3.4-debian13-compat@sha256:23c84f9012c44cbdc1569d7a27c5c2d191d87c292bd91a34a9de8e547a44146e
  SEMVER_MAJOR_MINOR_VERSION: "3.4"
  SEMVER_MAJOR_VERSION: "3"
  SEMVER_VERSION: 3.4.0
  VERSION: 3.4.0
contents:
  builds:
    - name: eck-operator
      uses: dhi.io/helm:3.20.2-debian13-dev@sha256:ce95680846fc18d3d179f82f9d633c8274f41cd0d0f8213cbfc4039fbe2cd112
      contents:
        files:
          - url: git+https://github.com/elastic/cloud-on-k8s.git#v3.4.0
            checksum: ceed5fd496a524f5bc8d27f3470d71c40389d0fc
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/deploy/eck-operator
          with:
            chart:
              appRef: eck-operator
              dependencies:
                - condition: installCRDs
                  keep: true
                  name: eck-operator-crds
              description: Docker Hardened Images Helm chart for Elastic Cloud on Kubernetes (ECK) Operator
              images:
                - name: eck-operator
                  ref: dhi/eck-operator:3.4.0-debian13@sha256:5268d0ce742e59d0a46d3b3671da64af146657fcae71bf9dbe5091210c0c0ede
                - name: logstash
                  ref: dhi/logstash:9.3.4-debian13-compat@sha256:23c84f9012c44cbdc1569d7a27c5c2d191d87c292bd91a34a9de8e547a44146e
                - name: kibana
                  ref: dhi/kibana:9.3.4-debian13@sha256:093438897d54ec1dbb67b5c7f4fdf01192ddbcc242199eeabf2c88f49c5ba85b
                - name: elasticsearch
                  ref: dhi/elasticsearch:9.4.0-debian13@sha256:35ab72e0d27434c2514b04baaf561e1debfd4975a3411f6537cd74a5c273e32a
              name: eck-operator-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/elastic/cloud-on-k8s
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/deploy/eck-operator
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/deploy
          with:
            chart: eck-operator
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: ${source.dir}/helm-charts/deploy/eck-operator
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/eck-operator/config
