# syntax=dhi.io/build:2-helm3

name: ECK Operator Helm chart 3.x
image: dhi.io/eck-operator-chart
variant: helm
tags:
  - 3.4.0
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: ceed5fd496a524f5bc8d27f3470d71c40389d0fc
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  ECK_OPERATOR_REFERENCE: dhi/eck-operator:3.4.0-debian13@sha256:ec9d9ceb163a06ac32ec7e53cd536299e2dcb875deb7968a9195028ed76237a5
  ELASTICSEARCH_REFERENCE: dhi/elasticsearch:9.4.0-debian13@sha256:7ba0392125958c3a9c0ef15a034109a55576a63e220252b5b6ca05314b5f312c
  HELM_REFERENCE: dhi/helm:3.20.2-debian13-dev@sha256:0e82c726efb7039ffa0875ffb88632189d0082a77f0ee94efa3a048992db3c71
  KIBANA_REFERENCE: dhi/kibana:9.3.4-debian13@sha256:935aba0841855fa294b238a70c6f68530a2fbae7a24829121fdb3692970076b6
  LOGSTASH_COMPAT_REFERENCE: dhi/logstash:9.3.4-debian13-compat@sha256:975fd8c6f8bdc85c6ac9c050d0fd692f5549ee8e04f06afe58acaf429f71ecbf
  SEMVER_MAJOR_MINOR_VERSION: "3.4"
  SEMVER_MAJOR_VERSION: "3"
  SEMVER_VERSION: 3.4.0
  VERSION: 3.4.0
contents:
  builds:
    - name: eck-operator
      uses: dhi.io/helm:3.20.2-debian13-dev@sha256:0e82c726efb7039ffa0875ffb88632189d0082a77f0ee94efa3a048992db3c71
      contents:
        files:
          - url: git+https://github.com/elastic/cloud-on-k8s.git#v3.4.0
            checksum: ceed5fd496a524f5bc8d27f3470d71c40389d0fc
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/deploy/eck-operator
          with:
            chart:
              appRef: eck-operator
              dependencies:
                - condition: installCRDs
                  keep: true
                  name: eck-operator-crds
              description: Docker Hardened Images Helm chart for Elastic Cloud on Kubernetes (ECK) Operator
              images:
                - name: eck-operator
                  ref: dhi/eck-operator:3.4.0-debian13@sha256:ec9d9ceb163a06ac32ec7e53cd536299e2dcb875deb7968a9195028ed76237a5
                - name: logstash
                  ref: dhi/logstash:9.3.4-debian13-compat@sha256:975fd8c6f8bdc85c6ac9c050d0fd692f5549ee8e04f06afe58acaf429f71ecbf
                - name: kibana
                  ref: dhi/kibana:9.3.4-debian13@sha256:935aba0841855fa294b238a70c6f68530a2fbae7a24829121fdb3692970076b6
                - name: elasticsearch
                  ref: dhi/elasticsearch:9.4.0-debian13@sha256:7ba0392125958c3a9c0ef15a034109a55576a63e220252b5b6ca05314b5f312c
              name: eck-operator-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/elastic/cloud-on-k8s
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/deploy/eck-operator
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/deploy
          with:
            chart: eck-operator
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: ${source.dir}/helm-charts/deploy/eck-operator
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/eck-operator/config
