# syntax=dhi.io/build:2-helm3

name: Cert-Manager Helm chart 1.19.x
image: dhi.io/cert-manager-chart
variant: helm
tags:
  - 1.19.6
platforms:
  - linux/amd64
vars:
  CERT_MANAGER_ACMESOLVER_REFERENCE: dhi/cert-manager-acmesolver:1.19.6-debian13@sha256:a4d38df84e392c7ec548174e3a4c6a1b57382c2d165a4c67fba8931dc45de18e
  CERT_MANAGER_CAINJECTOR_REFERENCE: dhi/cert-manager-cainjector:1.19.6-debian13@sha256:9d7218bca060ca1fc24e9c66b5ee8296b3ba52d9d1e088db2fa14c2d30dd90b1
  CERT_MANAGER_COMMIT_SHA: 60b0447cc9a64885d42567ea590862b88a62d1ad
  CERT_MANAGER_CONTROLLER_REFERENCE: dhi/cert-manager-controller:1.19.6-debian13@sha256:232f2fdba31b1cf61a576716fb454ba436d332c590df4581d8117778a40a997d
  CERT_MANAGER_MAJOR_MINOR_VERSION: "1.19"
  CERT_MANAGER_STARTUPAPICHECK_REFERENCE: dhi/cert-manager-startupapicheck:1.19.6-debian13@sha256:c20ef39d0d9e58f7d190b845a85cb05a4219af3c28a797edc856c69d3c0815d4
  CERT_MANAGER_VERSION: 1.19.6
  CERT_MANAGER_WEBHOOK_REFERENCE: dhi/cert-manager-webhook:1.19.6-debian13@sha256:52b7f6e7d819723008668b228d546b8d381068ec75b197bad5731c8c3c91a0be
  CHART_HELM_NAME: cert-manager-chart
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_VERSION: 4.1.4-2
contents:
  repositories:
    - deb [signed-by=/usr/share/keyrings/dhi-deb-main.gpg] http://dhi.io/deb/debian/main trixie main
  keyring:
    - https://dhi.io/keyring/dhi-deb-gpg.D46852F6925E9F71.key
  builds:
    - name: cert-manager
      contents:
        packages:
          - bash
          - ca-certificates
          - coreutils
          - make
          - curl
          - git
          - grep
          - gawk
          - findutils
          - helm=4.1.4-2
        files:
          - url: git+https://github.com/cert-manager/cert-manager.git#v1.19.6
            checksum: 60b0447cc9a64885d42567ea590862b88a62d1ad
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: Make Chart from template
          work-dir: ${source.dir}/helm-charts/
          privileged: true
          runs: |
            set -eux -o pipefail

            make _bin/helm/cert-manager/Chart.yaml
            cp _bin/helm/cert-manager/Chart.yaml deploy/charts/cert-manager/Chart.yaml
            rm deploy/charts/cert-manager/Chart.template.yaml
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/deploy/charts/cert-manager
          with:
            chart:
              appRef: cert-manager-controller
              description: Docker Hardened Images Helm chart for Cert-Manager
              images:
                - name: cert-manager-controller
                  ref: dhi/cert-manager-controller:1.19.6-debian13@sha256:232f2fdba31b1cf61a576716fb454ba436d332c590df4581d8117778a40a997d
                - name: cert-manager-cainjector
                  ref: dhi/cert-manager-cainjector:1.19.6-debian13@sha256:9d7218bca060ca1fc24e9c66b5ee8296b3ba52d9d1e088db2fa14c2d30dd90b1
                - name: cert-manager-acmesolver
                  ref: dhi/cert-manager-acmesolver:1.19.6-debian13@sha256:a4d38df84e392c7ec548174e3a4c6a1b57382c2d165a4c67fba8931dc45de18e
                - name: cert-manager-startupapicheck
                  ref: dhi/cert-manager-startupapicheck:1.19.6-debian13@sha256:c20ef39d0d9e58f7d190b845a85cb05a4219af3c28a797edc856c69d3c0815d4
                - name: cert-manager-webhook
                  ref: dhi/cert-manager-webhook:1.19.6-debian13@sha256:52b7f6e7d819723008668b228d546b8d381068ec75b197bad5731c8c3c91a0be
              name: cert-manager-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/cert-manager/cert-manager
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/deploy/charts/cert-manager
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/deploy/charts/
          with:
            chart: cert-manager
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/deploy/charts
          with:
            chart: cert-manager
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/cert-manager/config
