# syntax=dhi.io/build:2-helm3

name: Cert-Manager Helm chart 1.19.x
image: dhi.io/cert-manager-chart
variant: helm
tags:
  - 1.19.5
platforms:
  - linux/amd64
vars:
  CERT_MANAGER_ACMESOLVER_REFERENCE: dhi/cert-manager-acmesolver:1.19.5-debian13@sha256:df815f5b964ad60229862be516e5b172f0b4e4da41c42d16b751db99dd8fff14
  CERT_MANAGER_CAINJECTOR_REFERENCE: dhi/cert-manager-cainjector:1.19.5-debian13@sha256:34f347c6cad97db80f6b5b18f4387594c8fb06c2216408cb13ab0befbeee311b
  CERT_MANAGER_COMMIT_SHA: cda7b7896e70dafb2de66212028cf9997a5e9490
  CERT_MANAGER_CONTROLLER_REFERENCE: dhi/cert-manager-controller:1.19.5-debian13@sha256:e4901c02283255e01b68f14cda7d785efc4ade831f530077e494034c05f2faf3
  CERT_MANAGER_MAJOR_MINOR_VERSION: "1.19"
  CERT_MANAGER_STARTUPAPICHECK_REFERENCE: dhi/cert-manager-startupapicheck:1.19.5-debian13@sha256:f2bcc059849c54d9800e5cd7636d53345b6261e70d07564c82088227d0688aeb
  CERT_MANAGER_VERSION: 1.19.5
  CERT_MANAGER_WEBHOOK_REFERENCE: dhi/cert-manager-webhook:1.19.5-debian13@sha256:7b969af6d975884fef655704c48f7c071c44ecc634b4a45bd6947b27a0753e0e
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.21.0-debian13-dev@sha256:dde1e16cc0ad3d2cdeebdb78f1e676b899e6f62a12c529dd620d045bd2fd334a
contents:
  builds:
    - name: cert-manager
      uses: dhi.io/helm:3.21.0-debian13-dev@sha256:dde1e16cc0ad3d2cdeebdb78f1e676b899e6f62a12c529dd620d045bd2fd334a
      contents:
        packages:
          - make
          - curl
          - git
        files:
          - url: git+https://github.com/cert-manager/cert-manager.git#v1.19.5
            checksum: cda7b7896e70dafb2de66212028cf9997a5e9490
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: Make Chart from template
          work-dir: ${source.dir}/helm-charts/
          privileged: true
          runs: |
            set -eux -o pipefail

            make _bin/helm/cert-manager/Chart.yaml
            cp _bin/helm/cert-manager/Chart.yaml deploy/charts/cert-manager/Chart.yaml
            rm deploy/charts/cert-manager/Chart.template.yaml
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/deploy/charts/cert-manager
          with:
            chart:
              appRef: cert-manager-controller
              description: Docker Hardened Images Helm chart for Cert-Manager
              images:
                - name: cert-manager-controller
                  ref: dhi/cert-manager-controller:1.19.5-debian13@sha256:e4901c02283255e01b68f14cda7d785efc4ade831f530077e494034c05f2faf3
                - name: cert-manager-cainjector
                  ref: dhi/cert-manager-cainjector:1.19.5-debian13@sha256:34f347c6cad97db80f6b5b18f4387594c8fb06c2216408cb13ab0befbeee311b
                - name: cert-manager-acmesolver
                  ref: dhi/cert-manager-acmesolver:1.19.5-debian13@sha256:df815f5b964ad60229862be516e5b172f0b4e4da41c42d16b751db99dd8fff14
                - name: cert-manager-startupapicheck
                  ref: dhi/cert-manager-startupapicheck:1.19.5-debian13@sha256:f2bcc059849c54d9800e5cd7636d53345b6261e70d07564c82088227d0688aeb
                - name: cert-manager-webhook
                  ref: dhi/cert-manager-webhook:1.19.5-debian13@sha256:7b969af6d975884fef655704c48f7c071c44ecc634b4a45bd6947b27a0753e0e
              name: cert-manager-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/cert-manager/cert-manager
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/deploy/charts/cert-manager
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/deploy/charts/
          with:
            chart: cert-manager
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/deploy/charts
          with:
            chart: cert-manager
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/cert-manager/config
