# syntax=dhi.io/build:2-helm3

name: Cert-Manager Helm chart 1.19.x
image: dhi.io/cert-manager-chart
variant: helm
tags:
  - 1.19.5
platforms:
  - linux/amd64
vars:
  CERT_MANAGER_ACMESOLVER_REFERENCE: dhi/cert-manager-acmesolver:1.19.5-debian13@sha256:b92a11f8b6f9c0752b46e622b7e8749b5d3eb720a4218646ce9beace8d7862f6
  CERT_MANAGER_CAINJECTOR_REFERENCE: dhi/cert-manager-cainjector:1.19.5-debian13@sha256:fd50651d2a69f32cf79f4f4e1b80a6a8aa88410f65781c13a374212bacd6b1cc
  CERT_MANAGER_COMMIT_SHA: cda7b7896e70dafb2de66212028cf9997a5e9490
  CERT_MANAGER_CONTROLLER_REFERENCE: dhi/cert-manager-controller:1.19.5-debian13@sha256:e965e25f38f132f8d734681bf72779b090eb01abcf0c561668ed9155d5b282d3
  CERT_MANAGER_MAJOR_MINOR_VERSION: "1.19"
  CERT_MANAGER_STARTUPAPICHECK_REFERENCE: dhi/cert-manager-startupapicheck:1.19.5-debian13@sha256:a47aec1d1ebabb999d36b0d0555b40d5e3d94a8ef1ef5c90728461f73fff4c49
  CERT_MANAGER_VERSION: 1.19.5
  CERT_MANAGER_WEBHOOK_REFERENCE: dhi/cert-manager-webhook:1.19.5-debian13@sha256:9d325e9e3cfe17df61961678d90aa810b28b5b776e4c943929492ae31cea4872
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.21.1-debian13-dev@sha256:b7ba22256dc8a6a8d11135cef60b1df944f59de9f9cb1a4db07b73c917f01247
contents:
  builds:
    - name: cert-manager
      uses: dhi.io/helm:3.21.1-debian13-dev@sha256:b7ba22256dc8a6a8d11135cef60b1df944f59de9f9cb1a4db07b73c917f01247
      contents:
        packages:
          - make
          - curl
          - git
        files:
          - url: git+https://github.com/cert-manager/cert-manager.git#v1.19.5
            checksum: cda7b7896e70dafb2de66212028cf9997a5e9490
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: Make Chart from template
          work-dir: ${source.dir}/helm-charts/
          privileged: true
          runs: |
            set -eux -o pipefail

            make _bin/helm/cert-manager/Chart.yaml
            cp _bin/helm/cert-manager/Chart.yaml deploy/charts/cert-manager/Chart.yaml
            rm deploy/charts/cert-manager/Chart.template.yaml
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/deploy/charts/cert-manager
          with:
            chart:
              appRef: cert-manager-controller
              description: Docker Hardened Images Helm chart for Cert-Manager
              images:
                - name: cert-manager-controller
                  ref: dhi/cert-manager-controller:1.19.5-debian13@sha256:e965e25f38f132f8d734681bf72779b090eb01abcf0c561668ed9155d5b282d3
                - name: cert-manager-cainjector
                  ref: dhi/cert-manager-cainjector:1.19.5-debian13@sha256:fd50651d2a69f32cf79f4f4e1b80a6a8aa88410f65781c13a374212bacd6b1cc
                - name: cert-manager-acmesolver
                  ref: dhi/cert-manager-acmesolver:1.19.5-debian13@sha256:b92a11f8b6f9c0752b46e622b7e8749b5d3eb720a4218646ce9beace8d7862f6
                - name: cert-manager-startupapicheck
                  ref: dhi/cert-manager-startupapicheck:1.19.5-debian13@sha256:a47aec1d1ebabb999d36b0d0555b40d5e3d94a8ef1ef5c90728461f73fff4c49
                - name: cert-manager-webhook
                  ref: dhi/cert-manager-webhook:1.19.5-debian13@sha256:9d325e9e3cfe17df61961678d90aa810b28b5b776e4c943929492ae31cea4872
              name: cert-manager-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/cert-manager/cert-manager
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/deploy/charts/cert-manager
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/deploy/charts/
          with:
            chart: cert-manager
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/deploy/charts
          with:
            chart: cert-manager
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/cert-manager/config
