# syntax=dhi.io/build:2-helm3

name: Cert-Manager Helm chart 1.20.x
image: dhi.io/cert-manager-chart
variant: helm
tags:
  - 1.20.2
platforms:
  - linux/amd64
vars:
  CERT_MANAGER_ACMESOLVER_REFERENCE: dhi/cert-manager-acmesolver:1.20.2-debian13@sha256:4db7a6bed89b1b7e556524d1a7738dff0261b22a8c1c6255e520644c232e2bd0
  CERT_MANAGER_CAINJECTOR_REFERENCE: dhi/cert-manager-cainjector:1.20.2-debian13@sha256:7b446ba10b1c8a4417b2bb4cac4364784525eeef19f3ac972c300dbb631d708c
  CERT_MANAGER_COMMIT_SHA: e5b7b18450dd2c4b993b95bcd680b1a057205b00
  CERT_MANAGER_CONTROLLER_REFERENCE: dhi/cert-manager-controller:1.20.2-debian13@sha256:a3e32e754511fb6abb5e93a470ddde0207cafa6532d23368b21882716ce49416
  CERT_MANAGER_MAJOR_MINOR_VERSION: "1.20"
  CERT_MANAGER_STARTUPAPICHECK_REFERENCE: dhi/cert-manager-startupapicheck:1.20.2-debian13@sha256:238980e00362fc9cb583d0259c46ea4442c71a91ce4f977aa7579dc2c1ee23db
  CERT_MANAGER_VERSION: 1.20.2
  CERT_MANAGER_WEBHOOK_REFERENCE: dhi/cert-manager-webhook:1.20.2-debian13@sha256:db785d05ef4df1251f6ff6a7c93a045654f2e23f9a05371e18792bd11627f901
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.21.0-debian13-dev@sha256:e3d7fb6de37608485fd22d3dd04ed6b0f9cc68431cb21697c2383978e2847ed2
contents:
  builds:
    - name: cert-manager
      uses: dhi.io/helm:3.21.0-debian13-dev@sha256:e3d7fb6de37608485fd22d3dd04ed6b0f9cc68431cb21697c2383978e2847ed2
      contents:
        packages:
          - make
          - curl
          - git
        files:
          - url: git+https://github.com/cert-manager/cert-manager.git#v1.20.2
            checksum: e5b7b18450dd2c4b993b95bcd680b1a057205b00
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: Make Chart from template
          work-dir: ${source.dir}/helm-charts/
          privileged: true
          runs: |
            set -eux -o pipefail

            make _bin/helm/cert-manager/Chart.yaml
            cp _bin/helm/cert-manager/Chart.yaml deploy/charts/cert-manager/Chart.yaml
            rm deploy/charts/cert-manager/Chart.template.yaml
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/deploy/charts/cert-manager
          with:
            chart:
              appRef: cert-manager-controller
              description: Docker Hardened Images Helm chart for Cert-Manager
              images:
                - name: cert-manager-controller
                  ref: dhi/cert-manager-controller:1.20.2-debian13@sha256:a3e32e754511fb6abb5e93a470ddde0207cafa6532d23368b21882716ce49416
                - name: cert-manager-cainjector
                  ref: dhi/cert-manager-cainjector:1.20.2-debian13@sha256:7b446ba10b1c8a4417b2bb4cac4364784525eeef19f3ac972c300dbb631d708c
                - name: cert-manager-acmesolver
                  ref: dhi/cert-manager-acmesolver:1.20.2-debian13@sha256:4db7a6bed89b1b7e556524d1a7738dff0261b22a8c1c6255e520644c232e2bd0
                - name: cert-manager-startupapicheck
                  ref: dhi/cert-manager-startupapicheck:1.20.2-debian13@sha256:238980e00362fc9cb583d0259c46ea4442c71a91ce4f977aa7579dc2c1ee23db
                - name: cert-manager-webhook
                  ref: dhi/cert-manager-webhook:1.20.2-debian13@sha256:db785d05ef4df1251f6ff6a7c93a045654f2e23f9a05371e18792bd11627f901
              name: cert-manager-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/cert-manager/cert-manager
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/deploy/charts/cert-manager
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/deploy/charts/
          with:
            chart: cert-manager
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/deploy/charts
          with:
            chart: cert-manager
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/cert-manager/config
