# syntax=dhi.io/build:2-helm3

name: Cert-Manager Helm chart 1.x
image: dhi.io/cert-manager-chart
variant: helm
tags:
  - "1"
  - 1.20.2
platforms:
  - linux/amd64
vars:
  CERT_MANAGER_ACMESOLVER_REFERENCE: dhi/cert-manager-acmesolver:1.20.2-debian13@sha256:9fe550881119ef17a08ad38f0a556d74495b7c331ddf5fbe38af0af2b50c78d0
  CERT_MANAGER_CAINJECTOR_REFERENCE: dhi/cert-manager-cainjector:1.20.2-debian13@sha256:f1e1c536e392d4e384deedc5530d0ec0b50c97271e44fddb3355fb1e0472c371
  CERT_MANAGER_COMMIT_SHA: e5b7b18450dd2c4b993b95bcd680b1a057205b00
  CERT_MANAGER_CONTROLLER_REFERENCE: dhi/cert-manager-controller:1.20.2-debian13@sha256:6c3801fe3f1d05001cf12466f70d2490f20abb06e4884ca5866b8c92aebaede0
  CERT_MANAGER_MAJOR_VERSION: "1"
  CERT_MANAGER_STARTUPAPICHECK_REFERENCE: dhi/cert-manager-startupapicheck:1.20.2-debian13@sha256:b9d99131be57d9f091dbbeb2b8070e0c403134a1f3835742b52e4aece1eb70ee
  CERT_MANAGER_VERSION: 1.20.2
  CERT_MANAGER_WEBHOOK_REFERENCE: dhi/cert-manager-webhook:1.20.2-debian13@sha256:7342df0b4c8e7c1047d35b86bbaa0f1eb559283ce7689ede163d942666c341d0
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.20.2-debian13-dev@sha256:81e04bdcbc4f86f57589672220b5fcd235d616d28038aec4511068678778db66
contents:
  builds:
    - name: cert-manager
      uses: dhi.io/helm:3.20.2-debian13-dev@sha256:81e04bdcbc4f86f57589672220b5fcd235d616d28038aec4511068678778db66
      contents:
        packages:
          - make
          - curl
          - git
        files:
          - url: git+https://github.com/cert-manager/cert-manager.git#v1.20.2
            checksum: e5b7b18450dd2c4b993b95bcd680b1a057205b00
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: Make Chart from template
          work-dir: ${source.dir}/helm-charts/
          privileged: true
          runs: |
            set -eux -o pipefail

            make _bin/helm/cert-manager/Chart.yaml
            cp _bin/helm/cert-manager/Chart.yaml deploy/charts/cert-manager/Chart.yaml
            rm deploy/charts/cert-manager/Chart.template.yaml
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/deploy/charts/cert-manager
          with:
            chart:
              appRef: cert-manager-controller
              description: Docker Hardened Images Helm chart for Cert-Manager
              images:
                - name: cert-manager-controller
                  ref: dhi/cert-manager-controller:1.20.2-debian13@sha256:6c3801fe3f1d05001cf12466f70d2490f20abb06e4884ca5866b8c92aebaede0
                - name: cert-manager-cainjector
                  ref: dhi/cert-manager-cainjector:1.20.2-debian13@sha256:f1e1c536e392d4e384deedc5530d0ec0b50c97271e44fddb3355fb1e0472c371
                - name: cert-manager-acmesolver
                  ref: dhi/cert-manager-acmesolver:1.20.2-debian13@sha256:9fe550881119ef17a08ad38f0a556d74495b7c331ddf5fbe38af0af2b50c78d0
                - name: cert-manager-startupapicheck
                  ref: dhi/cert-manager-startupapicheck:1.20.2-debian13@sha256:b9d99131be57d9f091dbbeb2b8070e0c403134a1f3835742b52e4aece1eb70ee
                - name: cert-manager-webhook
                  ref: dhi/cert-manager-webhook:1.20.2-debian13@sha256:7342df0b4c8e7c1047d35b86bbaa0f1eb559283ce7689ede163d942666c341d0
              name: cert-manager-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/cert-manager/cert-manager
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/deploy/charts/cert-manager
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/deploy/charts/
          with:
            chart: cert-manager
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/deploy/charts
          with:
            chart: cert-manager
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/cert-manager/config
