# syntax=dhi.io/build:2-helm3

name: Cert-Manager Helm chart 1.20.x
image: dhi.io/cert-manager-chart
variant: helm
tags:
  - 1.20.4
platforms:
  - linux/amd64
vars:
  CERT_MANAGER_ACMESOLVER_REFERENCE: dhi/cert-manager-acmesolver:1.20.4-debian13@sha256:94fa21316f5c26ebb32dab8ccf1bc4570ed0fb0b4c2b0a758a9c17b1108649e7
  CERT_MANAGER_CAINJECTOR_REFERENCE: dhi/cert-manager-cainjector:1.20.4-debian13@sha256:59fef0dc52ba5cbe58dfe22d9edc4ac82aada6f24bc9dd71617fd32f1e42a96e
  CERT_MANAGER_COMMIT_SHA: 0b9448974868c5669d4f3e7499f5afd393889e22
  CERT_MANAGER_CONTROLLER_REFERENCE: dhi/cert-manager-controller:1.20.4-debian13@sha256:8d43c558513a33239c2e2ce9c843178cfcac39c5c1a1f22f03e5c12c9bf360aa
  CERT_MANAGER_MAJOR_MINOR_VERSION: "1.20"
  CERT_MANAGER_STARTUPAPICHECK_REFERENCE: dhi/cert-manager-startupapicheck:1.20.4-debian13@sha256:480515e2b4f09fd93e8df1af11988c1738e11fc24df26128fc51beae6204b0f3
  CERT_MANAGER_VERSION: 1.20.4
  CERT_MANAGER_WEBHOOK_REFERENCE: dhi/cert-manager-webhook:1.20.4-debian13@sha256:09d8a46a33f14255aa4944971d06a5f7f49112896ea9f21d6bd6cb6b78d41da0
  CHART_HELM_NAME: cert-manager-chart
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_VERSION: 4.1.4-2
contents:
  repositories:
    - deb [signed-by=/usr/share/keyrings/dhi-deb-main.gpg] http://dhi.io/deb/debian/main trixie main
  keyring:
    - https://dhi.io/keyring/dhi-deb-gpg.D46852F6925E9F71.key
  builds:
    - name: cert-manager
      contents:
        packages:
          - bash
          - ca-certificates
          - coreutils
          - make
          - curl
          - git
          - grep
          - gawk
          - findutils
          - helm=4.1.4-2
        files:
          - url: git+https://github.com/cert-manager/cert-manager.git#v1.20.4
            checksum: 0b9448974868c5669d4f3e7499f5afd393889e22
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: Make Chart from template
          work-dir: ${source.dir}/helm-charts/
          privileged: true
          runs: |
            set -eux -o pipefail

            make _bin/helm/cert-manager/Chart.yaml
            cp _bin/helm/cert-manager/Chart.yaml deploy/charts/cert-manager/Chart.yaml
            rm deploy/charts/cert-manager/Chart.template.yaml
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/deploy/charts/cert-manager
          with:
            chart:
              appRef: cert-manager-controller
              description: Docker Hardened Images Helm chart for Cert-Manager
              images:
                - name: cert-manager-controller
                  ref: dhi/cert-manager-controller:1.20.4-debian13@sha256:8d43c558513a33239c2e2ce9c843178cfcac39c5c1a1f22f03e5c12c9bf360aa
                - name: cert-manager-cainjector
                  ref: dhi/cert-manager-cainjector:1.20.4-debian13@sha256:59fef0dc52ba5cbe58dfe22d9edc4ac82aada6f24bc9dd71617fd32f1e42a96e
                - name: cert-manager-acmesolver
                  ref: dhi/cert-manager-acmesolver:1.20.4-debian13@sha256:94fa21316f5c26ebb32dab8ccf1bc4570ed0fb0b4c2b0a758a9c17b1108649e7
                - name: cert-manager-startupapicheck
                  ref: dhi/cert-manager-startupapicheck:1.20.4-debian13@sha256:480515e2b4f09fd93e8df1af11988c1738e11fc24df26128fc51beae6204b0f3
                - name: cert-manager-webhook
                  ref: dhi/cert-manager-webhook:1.20.4-debian13@sha256:09d8a46a33f14255aa4944971d06a5f7f49112896ea9f21d6bd6cb6b78d41da0
              name: cert-manager-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/cert-manager/cert-manager
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/deploy/charts/cert-manager
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/deploy/charts/
          with:
            chart: cert-manager
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/deploy/charts
          with:
            chart: cert-manager
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/cert-manager/config
