# syntax=dhi.io/build:2-helm3

name: Cert-Manager Helm chart 1.21.x
image: dhi.io/cert-manager-chart
variant: helm
tags:
  - 1.21.2
platforms:
  - linux/amd64
vars:
  CERT_MANAGER_ACMESOLVER_REFERENCE: dhi/cert-manager-acmesolver:1.21.2-debian13@sha256:e9c7b6c21cb51469598b07fdf933009596afaff5658e54513b03b65dadef8975
  CERT_MANAGER_CAINJECTOR_REFERENCE: dhi/cert-manager-cainjector:1.21.2-debian13@sha256:c9ba2865292b71a5a31d796cf2c5d4818fc17bd6697f457d69aad9895b9b952e
  CERT_MANAGER_COMMIT_SHA: 922a06aa49ee4bb802db268ef72a174af70edd32
  CERT_MANAGER_CONTROLLER_REFERENCE: dhi/cert-manager-controller:1.21.2-debian13@sha256:bb855d64debfb462529cbea75dfeac67614997319352d12616e03547d39ebc93
  CERT_MANAGER_MAJOR_MINOR_VERSION: "1.21"
  CERT_MANAGER_STARTUPAPICHECK_REFERENCE: dhi/cert-manager-startupapicheck:1.21.2-debian13@sha256:12293d56af12d4531ee136335822c66fd0dfd849b2bf97f138d9e68ce2488edc
  CERT_MANAGER_VERSION: 1.21.2
  CERT_MANAGER_WEBHOOK_REFERENCE: dhi/cert-manager-webhook:1.21.2-debian13@sha256:2eaae2cd3857e48922099a7e394d527e17acfa93fe0c0b1c888a4e317935203f
  CHART_HELM_NAME: cert-manager-chart
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_VERSION: 4.1.4-2
contents:
  repositories:
    - deb [signed-by=/usr/share/keyrings/dhi-deb-main.gpg] http://dhi.io/deb/debian/main trixie main
  keyring:
    - https://dhi.io/keyring/dhi-deb-gpg.D46852F6925E9F71.key
  builds:
    - name: cert-manager
      contents:
        packages:
          - bash
          - ca-certificates
          - coreutils
          - make
          - curl
          - git
          - grep
          - gawk
          - findutils
          - helm=4.1.4-2
        files:
          - url: git+https://github.com/cert-manager/cert-manager.git#v1.21.2
            checksum: 922a06aa49ee4bb802db268ef72a174af70edd32
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/deploy/charts/cert-manager
          with:
            chart:
              appRef: cert-manager-controller
              chartVersion: 1.21.2
              description: Docker Hardened Images Helm chart for Cert-Manager
              images:
                - name: cert-manager-controller
                  ref: dhi/cert-manager-controller:1.21.2-debian13@sha256:bb855d64debfb462529cbea75dfeac67614997319352d12616e03547d39ebc93
                - name: cert-manager-cainjector
                  ref: dhi/cert-manager-cainjector:1.21.2-debian13@sha256:c9ba2865292b71a5a31d796cf2c5d4818fc17bd6697f457d69aad9895b9b952e
                - name: cert-manager-acmesolver
                  ref: dhi/cert-manager-acmesolver:1.21.2-debian13@sha256:e9c7b6c21cb51469598b07fdf933009596afaff5658e54513b03b65dadef8975
                - name: cert-manager-startupapicheck
                  ref: dhi/cert-manager-startupapicheck:1.21.2-debian13@sha256:12293d56af12d4531ee136335822c66fd0dfd849b2bf97f138d9e68ce2488edc
                - name: cert-manager-webhook
                  ref: dhi/cert-manager-webhook:1.21.2-debian13@sha256:2eaae2cd3857e48922099a7e394d527e17acfa93fe0c0b1c888a4e317935203f
              name: cert-manager-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/cert-manager/cert-manager
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/deploy/charts/cert-manager
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/deploy/charts/
          with:
            chart: cert-manager
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/deploy/charts
          with:
            chart: cert-manager
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/cert-manager/config
