# syntax=dhi.io/build:2-helm3

name: Cert-Manager Helm chart 1.21.x
image: dhi.io/cert-manager-chart
variant: helm
tags:
  - 1.21.1
platforms:
  - linux/amd64
vars:
  CERT_MANAGER_ACMESOLVER_REFERENCE: dhi/cert-manager-acmesolver:1.21.1-debian13@sha256:0cd45b361d51d70e07ec9ad7a3ba3bb5fbc0fbf2beb88634fbc6e837da3022cd
  CERT_MANAGER_CAINJECTOR_REFERENCE: dhi/cert-manager-cainjector:1.21.1-debian13@sha256:f2441c5fe35d4211f7ebda88fd6b9d2373bdd14112f971a8fbc08ee7f00b4a76
  CERT_MANAGER_COMMIT_SHA: 24e33194fb39488eff2bbf10c6dc640f407cad44
  CERT_MANAGER_CONTROLLER_REFERENCE: dhi/cert-manager-controller:1.21.1-debian13@sha256:7b5f374ea5b883419c37052059e15363c2a66b46956d216a5c11a793670e7606
  CERT_MANAGER_MAJOR_MINOR_VERSION: "1.21"
  CERT_MANAGER_STARTUPAPICHECK_REFERENCE: dhi/cert-manager-startupapicheck:1.21.1-debian13@sha256:51d77124722f09d1e3cd03d560260f9bced4ac6554ecf6af967efeb681016ba8
  CERT_MANAGER_VERSION: 1.21.1
  CERT_MANAGER_WEBHOOK_REFERENCE: dhi/cert-manager-webhook:1.21.1-debian13@sha256:4a27484201e539df595344adcc59a02eb7c9ff383c698c69e933f85335b2e75d
  CHART_HELM_NAME: cert-manager-chart
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_VERSION: 4.1.4-2
contents:
  repositories:
    - deb [signed-by=/usr/share/keyrings/dhi-deb-main.gpg] http://dhi.io/deb/debian/main trixie main
  keyring:
    - https://dhi.io/keyring/dhi-deb-gpg.D46852F6925E9F71.key
  builds:
    - name: cert-manager
      contents:
        packages:
          - bash
          - ca-certificates
          - coreutils
          - make
          - curl
          - git
          - grep
          - gawk
          - findutils
          - helm=4.1.4-2
        files:
          - url: git+https://github.com/cert-manager/cert-manager.git#v1.21.1
            checksum: 24e33194fb39488eff2bbf10c6dc640f407cad44
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/deploy/charts/cert-manager
          with:
            chart:
              appRef: cert-manager-controller
              chartVersion: 1.21.1
              description: Docker Hardened Images Helm chart for Cert-Manager
              images:
                - name: cert-manager-controller
                  ref: dhi/cert-manager-controller:1.21.1-debian13@sha256:7b5f374ea5b883419c37052059e15363c2a66b46956d216a5c11a793670e7606
                - name: cert-manager-cainjector
                  ref: dhi/cert-manager-cainjector:1.21.1-debian13@sha256:f2441c5fe35d4211f7ebda88fd6b9d2373bdd14112f971a8fbc08ee7f00b4a76
                - name: cert-manager-acmesolver
                  ref: dhi/cert-manager-acmesolver:1.21.1-debian13@sha256:0cd45b361d51d70e07ec9ad7a3ba3bb5fbc0fbf2beb88634fbc6e837da3022cd
                - name: cert-manager-startupapicheck
                  ref: dhi/cert-manager-startupapicheck:1.21.1-debian13@sha256:51d77124722f09d1e3cd03d560260f9bced4ac6554ecf6af967efeb681016ba8
                - name: cert-manager-webhook
                  ref: dhi/cert-manager-webhook:1.21.1-debian13@sha256:4a27484201e539df595344adcc59a02eb7c9ff383c698c69e933f85335b2e75d
              name: cert-manager-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/cert-manager/cert-manager
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/deploy/charts/cert-manager
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/deploy/charts/
          with:
            chart: cert-manager
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/deploy/charts
          with:
            chart: cert-manager
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/cert-manager/config
