# syntax=dhi.io/build:2-helm3

name: Cert-Manager Helm chart 1.x
image: dhi.io/cert-manager-chart
variant: helm
tags:
  - 1.19.4
platforms:
  - linux/amd64
vars:
  CERT_MANAGER_ACMESOLVER_REFERENCE: dhi/cert-manager-acmesolver:1.19.4-debian13@sha256:af9a962f2c862c75b46eba570949276311c133ba81ffcdea776b431123a9a886
  CERT_MANAGER_CAINJECTOR_REFERENCE: dhi/cert-manager-cainjector:1.19.4-debian13@sha256:56045ecb7ccb1b8d5d502b57f43d3b23e5cb5426c5dad78f9c5e210db4747710
  CERT_MANAGER_COMMIT_SHA: 83820a03ce3e6b8a1084fa765d77a6b5b98e6943
  CERT_MANAGER_CONTROLLER_REFERENCE: dhi/cert-manager-controller:1.19.4-debian13@sha256:f8d9480d03772a4258d9a0a3a18df24393e32bd324a559d73bdef9e4bedc73d4
  CERT_MANAGER_MAJOR_VERSION: "1"
  CERT_MANAGER_STARTUPAPICHECK_REFERENCE: dhi/cert-manager-startupapicheck:1.19.4-debian13@sha256:91ae4d2848f79b06d7c6203412f9c116bd4dd49f05e558971a85d925e5c61768
  CERT_MANAGER_VERSION: 1.19.4
  CERT_MANAGER_WEBHOOK_REFERENCE: dhi/cert-manager-webhook:1.19.4-debian13@sha256:c8c0b44e354f53d29f2a9da9712ead1545521336cd098ec63b094c4e034bf63a
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.20.2-debian13-dev@sha256:c7510bdef2d5afba3a1c80b20b836748adaab6991684962b98460d7a36dcdfa4
contents:
  builds:
    - name: cert-manager
      uses: dhi.io/helm:3.20.2-debian13-dev@sha256:c7510bdef2d5afba3a1c80b20b836748adaab6991684962b98460d7a36dcdfa4
      contents:
        packages:
          - make
          - curl
          - git
        files:
          - url: git+https://github.com/cert-manager/cert-manager.git#v1.19.4
            checksum: 83820a03ce3e6b8a1084fa765d77a6b5b98e6943
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: Make Chart from template
          work-dir: ${source.dir}/helm-charts/
          privileged: true
          runs: |
            set -eux -o pipefail

            make _bin/helm/cert-manager/Chart.yaml
            cp _bin/helm/cert-manager/Chart.yaml deploy/charts/cert-manager/Chart.yaml
            rm deploy/charts/cert-manager/Chart.template.yaml
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/deploy/charts/cert-manager
          with:
            chart:
              appRef: cert-manager-controller
              description: Docker Hardened Images Helm chart for Cert-Manager
              images:
                - name: cert-manager-controller
                  ref: dhi/cert-manager-controller:1.19.4-debian13@sha256:f8d9480d03772a4258d9a0a3a18df24393e32bd324a559d73bdef9e4bedc73d4
                - name: cert-manager-cainjector
                  ref: dhi/cert-manager-cainjector:1.19.4-debian13@sha256:56045ecb7ccb1b8d5d502b57f43d3b23e5cb5426c5dad78f9c5e210db4747710
                - name: cert-manager-acmesolver
                  ref: dhi/cert-manager-acmesolver:1.19.4-debian13@sha256:af9a962f2c862c75b46eba570949276311c133ba81ffcdea776b431123a9a886
                - name: cert-manager-startupapicheck
                  ref: dhi/cert-manager-startupapicheck:1.19.4-debian13@sha256:91ae4d2848f79b06d7c6203412f9c116bd4dd49f05e558971a85d925e5c61768
                - name: cert-manager-webhook
                  ref: dhi/cert-manager-webhook:1.19.4-debian13@sha256:c8c0b44e354f53d29f2a9da9712ead1545521336cd098ec63b094c4e034bf63a
              name: cert-manager-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/cert-manager/cert-manager
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/deploy/charts/cert-manager
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/deploy/charts/
          with:
            chart: cert-manager
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/deploy/charts
          with:
            chart: cert-manager
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/cert-manager/config
