# syntax=dhi.io/build:2-helm3

name: Cert-Manager Helm chart 1.x
image: dhi.io/cert-manager-chart
variant: helm
tags:
  - 1.19.4
platforms:
  - linux/amd64
vars:
  CERT_MANAGER_ACMESOLVER_REFERENCE: dhi/cert-manager-acmesolver:1.19.4-debian13@sha256:bb522fca80190463350f5bd85850845dcea7229c3d7aad05a7f2ef64a56551cb
  CERT_MANAGER_CAINJECTOR_REFERENCE: dhi/cert-manager-cainjector:1.19.4-debian13@sha256:3996303f413780fb1aae36537767ff2c5ee4004151cb08a1664d0c5a996d370d
  CERT_MANAGER_COMMIT_SHA: 83820a03ce3e6b8a1084fa765d77a6b5b98e6943
  CERT_MANAGER_CONTROLLER_REFERENCE: dhi/cert-manager-controller:1.19.4-debian13@sha256:713a143b5ed87d29ce0daea07bb51bcf2f6fddd88ffdb65d24f3127fde903fdc
  CERT_MANAGER_MAJOR_VERSION: "1"
  CERT_MANAGER_STARTUPAPICHECK_REFERENCE: dhi/cert-manager-startupapicheck:1.19.4-debian13@sha256:3f4dc6aa352e7d21c731f66ceade27926d7facce96754ca04c0e642b12a6e29c
  CERT_MANAGER_VERSION: 1.19.4
  CERT_MANAGER_WEBHOOK_REFERENCE: dhi/cert-manager-webhook:1.19.4-debian13@sha256:0f99e236e185e40ecdaad9be46285b0d6b5dda8cf360e2676178a70cd6106991
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.20.1-debian13-dev@sha256:92e43232140b33018c99c7b178d2f7302cfb0f0017267731b0512ac206cd8690
contents:
  builds:
    - name: cert-manager
      uses: dhi.io/helm:3.20.1-debian13-dev@sha256:92e43232140b33018c99c7b178d2f7302cfb0f0017267731b0512ac206cd8690
      contents:
        packages:
          - make
          - curl
          - git
        files:
          - url: git+https://github.com/cert-manager/cert-manager.git#v1.19.4
            checksum: 83820a03ce3e6b8a1084fa765d77a6b5b98e6943
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: Make Chart from template
          work-dir: ${source.dir}/helm-charts/
          privileged: true
          runs: |
            set -eux -o pipefail

            make _bin/helm/cert-manager/Chart.yaml
            cp _bin/helm/cert-manager/Chart.yaml deploy/charts/cert-manager/Chart.yaml
            rm deploy/charts/cert-manager/Chart.template.yaml
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/deploy/charts/cert-manager
          with:
            chart:
              appRef: cert-manager-controller
              description: Docker Hardened Images Helm chart for Cert-Manager
              images:
                - name: cert-manager-controller
                  ref: dhi/cert-manager-controller:1.19.4-debian13@sha256:713a143b5ed87d29ce0daea07bb51bcf2f6fddd88ffdb65d24f3127fde903fdc
                - name: cert-manager-cainjector
                  ref: dhi/cert-manager-cainjector:1.19.4-debian13@sha256:3996303f413780fb1aae36537767ff2c5ee4004151cb08a1664d0c5a996d370d
                - name: cert-manager-acmesolver
                  ref: dhi/cert-manager-acmesolver:1.19.4-debian13@sha256:bb522fca80190463350f5bd85850845dcea7229c3d7aad05a7f2ef64a56551cb
                - name: cert-manager-startupapicheck
                  ref: dhi/cert-manager-startupapicheck:1.19.4-debian13@sha256:3f4dc6aa352e7d21c731f66ceade27926d7facce96754ca04c0e642b12a6e29c
                - name: cert-manager-webhook
                  ref: dhi/cert-manager-webhook:1.19.4-debian13@sha256:0f99e236e185e40ecdaad9be46285b0d6b5dda8cf360e2676178a70cd6106991
              name: cert-manager-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/cert-manager/cert-manager
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/deploy/charts/cert-manager
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/deploy/charts/
          with:
            chart: cert-manager
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/deploy/charts
          with:
            chart: cert-manager
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/cert-manager/config
