# syntax=dhi.io/build:2-helm3

name: Cert-Manager Helm chart VERSION:^v?([0-9]+).*$.x
image: dhi.io/cert-manager-chart
variant: helm
tags:
  - 1.19.4
platforms:
  - linux/amd64
vars:
  CERT_MANAGER_ACMESOLVER_REFERENCE: dhi/cert-manager-acmesolver:1.19.4-debian13@sha256:d78861950b162cd98f53a5033a3f39ef3b6b5fb2686ca453c0ae9aadd9d25069
  CERT_MANAGER_CAINJECTOR_REFERENCE: dhi/cert-manager-cainjector:1.19.4-debian13@sha256:891d41370463f66756cd6e406b8c2df761b999c65eb3a946f29ff66504a5f01c
  CERT_MANAGER_COMMIT_SHA: 83820a03ce3e6b8a1084fa765d77a6b5b98e6943
  CERT_MANAGER_CONTROLLER_REFERENCE: dhi/cert-manager-controller:1.19.4-debian13@sha256:89e918b41980be9994778cc613c78e723983193b6e38da859e84b1ae000cba0b
  CERT_MANAGER_STARTUPAPICHECK_REFERENCE: dhi/cert-manager-startupapicheck:1.19.4-debian13@sha256:0d4212d72ed226a28b5810bf791657f82a57e2344aa5164af95781734db49992
  CERT_MANAGER_VERSION: 1.19.4
  CERT_MANAGER_WEBHOOK_REFERENCE: dhi/cert-manager-webhook:1.19.4-debian13@sha256:7f6ef130fc7e883443084bafd8ff42dde97bdf9350f2b979dd5e924f63cc9d15
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.20.1-debian13-dev@sha256:caa7223ddf8951e9bb159f921683e515361321ccf67c103981ffea2ae14a64eb
  SEMVER_MAJOR_MINOR_VERSION: ${VERSION:^v?([0-9]+\.[0-9]+).*$}
  SEMVER_MAJOR_VERSION: ${VERSION:^v?([0-9]+).*$}
  SEMVER_VERSION: ${VERSION:^v?([0-9]+\.[0-9]+\.[0-9]+).*$}
contents:
  builds:
    - name: cert-manager
      uses: dhi.io/helm:3.20.1-debian13-dev@sha256:caa7223ddf8951e9bb159f921683e515361321ccf67c103981ffea2ae14a64eb
      contents:
        packages:
          - make
          - curl
          - git
        files:
          - url: git+https://github.com/cert-manager/cert-manager.git#v1.19.4
            checksum: 83820a03ce3e6b8a1084fa765d77a6b5b98e6943
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: Make Chart from template
          work-dir: ${source.dir}/helm-charts/
          privileged: true
          runs: |
            set -eux -o pipefail

            make _bin/helm/cert-manager/Chart.yaml
            cp _bin/helm/cert-manager/Chart.yaml deploy/charts/cert-manager/Chart.yaml
            rm deploy/charts/cert-manager/Chart.template.yaml
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/deploy/charts/cert-manager
          with:
            chart:
              appRef: cert-manager-controller
              description: Docker Hardened Images Helm chart for Cert-Manager
              images:
                - name: cert-manager-controller
                  ref: dhi/cert-manager-controller:1.19.4-debian13@sha256:89e918b41980be9994778cc613c78e723983193b6e38da859e84b1ae000cba0b
                - name: cert-manager-cainjector
                  ref: dhi/cert-manager-cainjector:1.19.4-debian13@sha256:891d41370463f66756cd6e406b8c2df761b999c65eb3a946f29ff66504a5f01c
                - name: cert-manager-acmesolver
                  ref: dhi/cert-manager-acmesolver:1.19.4-debian13@sha256:d78861950b162cd98f53a5033a3f39ef3b6b5fb2686ca453c0ae9aadd9d25069
                - name: cert-manager-startupapicheck
                  ref: dhi/cert-manager-startupapicheck:1.19.4-debian13@sha256:0d4212d72ed226a28b5810bf791657f82a57e2344aa5164af95781734db49992
                - name: cert-manager-webhook
                  ref: dhi/cert-manager-webhook:1.19.4-debian13@sha256:7f6ef130fc7e883443084bafd8ff42dde97bdf9350f2b979dd5e924f63cc9d15
              name: cert-manager-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/cert-manager/cert-manager
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/deploy/charts/cert-manager
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/deploy/charts/
          with:
            chart: cert-manager
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/deploy/charts
          with:
            chart: cert-manager
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/cert-manager/config
