# syntax=dhi.io/build:2-helm3

name: NATS Helm chart 2.x
image: dhi.io/nats-chart
variant: helm
tags:
  - 2.15.0
platforms:
  - linux/amd64
vars:
  APPVERSION: 2.15.0
  CHART_COMMIT_SHA: e3075e17d4ccaaf61f5502b65c32c25dc12504f2
  CHART_HELM_NAME: nats-chart
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_VERSION: 4.1.4-2
  NATS_BOX_REFERENCE: dhi/nats-box:0.20.0-debian13-compat@sha256:b5171834b12fdce87074c52d026d29f549b1435f1d63d74047e25451991ddcbd
  NATS_REFERENCE: dhi/nats:2.15.0-debian13@sha256:0809f30100938f4dc0cee716a7031eaf665c1ebc6f3f744e7390892ef6e5e7ab
  NATS_SERVER_CONFIG_RELOADER_REFERENCE: dhi/nats-server-config-reloader:0.24.0-debian13@sha256:286ee2eb45153e60afde3f949286499cda32a2bd8aa827ba63d97a751bdd5dae
  PROMETHEUS_NATS_EXPORTER_REFERENCE: dhi/prometheus-nats-exporter:0.20.2-debian13@sha256:e225e2396f5d2f53cca6a2c0018d814c925592bbc6f5d5a0fa31d93e07c845fe
  SEMVER_MAJOR_MINOR_VERSION: "2.15"
  SEMVER_MAJOR_VERSION: "2"
  SEMVER_VERSION: 2.15.0
  VERSION: 2.15.0
contents:
  repositories:
    - deb [signed-by=/usr/share/keyrings/dhi-deb-main.gpg] http://dhi.io/deb/debian/main trixie main
  keyring:
    - https://dhi.io/keyring/dhi-deb-gpg.D46852F6925E9F71.key
  builds:
    - name: nats
      work-dir: ${source.dir}/helm-charts/helm/charts/nats
      contents:
        packages:
          - bash
          - ca-certificates
          - coreutils
          - helm=4.1.4-2
        files:
          - url: git+https://github.com/nats-io/k8s.git#nats-2.15.0
            checksum: e3075e17d4ccaaf61f5502b65c32c25dc12504f2
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          with:
            chart:
              appRef: nats
              description: Docker Hardened Images Helm chart for NATS
              images:
                - name: nats
                  ref: dhi/nats:2.15.0-debian13@sha256:0809f30100938f4dc0cee716a7031eaf665c1ebc6f3f744e7390892ef6e5e7ab
                - name: nats-server-config-reloader
                  ref: dhi/nats-server-config-reloader:0.24.0-debian13@sha256:286ee2eb45153e60afde3f949286499cda32a2bd8aa827ba63d97a751bdd5dae
                - name: prometheus-nats-exporter
                  ref: dhi/prometheus-nats-exporter:0.20.2-debian13@sha256:e225e2396f5d2f53cca6a2c0018d814c925592bbc6f5d5a0fa31d93e07c845fe
                - name: nats-box
                  ref: dhi/nats-box:0.20.0-debian13-compat@sha256:b5171834b12fdce87074c52d026d29f549b1435f1d63d74047e25451991ddcbd
              name: nats-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/nats-io/k8s
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          with:
            chart: .
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          with:
            chart: .
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: .
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/nats/config
