# syntax=dhi.io/build:2-helm3

name: Istio Egress Helm chart 1.x
image: dhi.io/istio-egress-chart
variant: helm
tags:
  - 1.29.2
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: 0c774325b938c4dbda4ea4ad4fb6156e80a12de8
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.20.2-debian13-dev@sha256:f9dd4a356298b0769dc4c2f718b9f564b631ddf37c19e061d61af9081bc7da13
  ISTIO_PROXYV2_REFERENCE: dhi/istio-proxyv2:1.29.2-debian13@sha256:27bc77b73484dfb6916c1b05fa6b3b66dd189352e4bdbb01e8573c17403d7586
  SEMVER_MAJOR_MINOR_VERSION: "1.29"
  SEMVER_MAJOR_VERSION: "1"
  SEMVER_VERSION: 1.29.2
  VERSION: 1.29.2
contents:
  builds:
    - name: istio-egress
      uses: dhi.io/helm:3.20.2-debian13-dev@sha256:f9dd4a356298b0769dc4c2f718b9f564b631ddf37c19e061d61af9081bc7da13
      work-dir: ${source.dir}/helm-charts/manifests/charts/gateways/istio-egress
      contents:
        files:
          - url: git+https://github.com/istio/istio.git#1.29.2
            checksum: 0c774325b938c4dbda4ea4ad4fb6156e80a12de8
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          with:
            chart:
              appRef: proxyv2
              description: Docker Hardened Images Helm chart for Istio Egress
              images:
                - name: proxyv2
                  ref: dhi/istio-proxyv2:1.29.2-debian13@sha256:27bc77b73484dfb6916c1b05fa6b3b66dd189352e4bdbb01e8573c17403d7586
              name: istio-egress-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/istio/istio
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          with:
            chart: .
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: .
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/istio-egress/config
