# syntax=dhi.io/build:2-helm3

name: Istio Egress Helm chart 1.30.x
image: dhi.io/istio-egress-chart
variant: helm
tags:
  - 1.30.1
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: 10229c76f2854420eeac94906ffff949b9aab746
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.21.0-debian13-dev@sha256:ece8efeb889adab72837b0042d8419283ac7fdf2b5c2c8fe09a34e4b8a34ae2e
  ISTIO_PROXYV2_REFERENCE: dhi/istio-proxyv2:1.30.0-debian13@sha256:b1f11eee29c2ae16a28a95777d95c17b0f951c021fe18987dd2fbc0a638f8d50
  SEMVER_MAJOR_MINOR_VERSION: "1.30"
  SEMVER_MAJOR_VERSION: "1"
  SEMVER_VERSION: 1.30.1
  VERSION: 1.30.1
contents:
  builds:
    - name: istio-egress
      uses: dhi.io/helm:3.21.0-debian13-dev@sha256:ece8efeb889adab72837b0042d8419283ac7fdf2b5c2c8fe09a34e4b8a34ae2e
      work-dir: ${source.dir}/helm-charts/manifests/charts/gateways/istio-egress
      contents:
        files:
          - url: git+https://github.com/istio/istio.git#1.30.1
            checksum: 10229c76f2854420eeac94906ffff949b9aab746
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          with:
            chart:
              appRef: proxyv2
              description: Docker Hardened Images Helm chart for Istio Egress
              images:
                - name: proxyv2
                  ref: dhi/istio-proxyv2:1.30.0-debian13@sha256:b1f11eee29c2ae16a28a95777d95c17b0f951c021fe18987dd2fbc0a638f8d50
              name: istio-egress-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/istio/istio
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          with:
            chart: .
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: .
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/istio-egress/config
