controller:
  image:
    repository: ${envoy-ai-gateway-controller.registry}/${envoy-ai-gateway-controller.repository}
    tag: ${envoy-ai-gateway-controller.tag}@${envoy-ai-gateway-controller.digest}
    pullPolicy: IfNotPresent
extProc:
  image:
    repository: ${envoy-ai-gateway-extproc.registry}/${envoy-ai-gateway-extproc.repository}
    tag: ${envoy-ai-gateway-extproc.tag}@${envoy-ai-gateway-extproc.digest}
