# syntax=dhi.io/build:2-helm3

name: Kured Helm chart 5.x
image: dhi.io/kured-chart
variant: helm
tags:
  - 5.12.1
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: 73ac791764d2b816af13c8c1c9ce048c021f04b7
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.21.0-debian13-dev@sha256:7c201a9174a2b56cb13136f19d87b23309d09eb2fc8a24e8c08a31ebd907a943
  KURED_IMAGE_REFERENCE: dhi/kured:1.22.1-debian13@sha256:66edeac54cd4fdf0f2e6940644e6a1c73991b28a390bed87b522dffd8f28469c
  SEMVER_MAJOR_MINOR_VERSION: "5.12"
  SEMVER_MAJOR_VERSION: "5"
  SEMVER_VERSION: 5.12.1
  VERSION: 5.12.1
contents:
  builds:
    - name: kured-chart
      uses: dhi.io/helm:3.21.0-debian13-dev@sha256:7c201a9174a2b56cb13136f19d87b23309d09eb2fc8a24e8c08a31ebd907a943
      work-dir: ${source.dir}/helm-charts/charts/kured
      contents:
        files:
          - url: git+https://github.com/kubereboot/charts.git#kured-5.12.1
            checksum: 73ac791764d2b816af13c8c1c9ce048c021f04b7
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          with:
            chart:
              appRef: kured
              description: Docker Hardened Images Helm chart for Kured
              images:
                - name: kured
                  ref: dhi/kured:1.22.1-debian13@sha256:66edeac54cd4fdf0f2e6940644e6a1c73991b28a390bed87b522dffd8f28469c
              name: kured-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/kubereboot/kured
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          with:
            chart: .
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: .
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/kured/config
