# syntax=dhi.io/build:2-helm3

name: Keycloak Helm chart 7.x
image: dhi.io/keycloak-chart
variant: helm
tags:
  - 7.2.0
platforms:
  - linux/amd64
vars:
  BUSYBOX_REFERENCE: dhi/busybox:1.37.0-debian13@sha256:e0cbe035dd7d7072e088172c5833bf756bfba3618567c0f5e73288e97e3a19bf
  CHART_COMMIT_SHA: 279061024a68a250bc6767737f3c1bf6e7539313
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.21.0-debian13-dev@sha256:7b9ee43cc77e81e2dcbb1b0f6e8ce376b71d63c90c81f2863e24aefff774a8da
  KEYCLOAK_REFERENCE: dhi/keycloak:26.6.3-debian13@sha256:4106a83fbca43f45de40260db12626a58ee350fc24feda2264b78dce79f4a19d
  SEMVER_MAJOR_MINOR_VERSION: "7.2"
  SEMVER_MAJOR_VERSION: "7"
  SEMVER_VERSION: 7.2.0
  VERSION: 7.2.0
contents:
  builds:
    - name: keycloak-chart
      uses: dhi.io/helm:3.21.0-debian13-dev@sha256:7b9ee43cc77e81e2dcbb1b0f6e8ce376b71d63c90c81f2863e24aefff774a8da
      contents:
        files:
          - url: git+https://github.com/codecentric/helm-charts.git#keycloakx-7.2.0
            checksum: 279061024a68a250bc6767737f3c1bf6e7539313
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/keycloakx
          with:
            chart:
              appRef: keycloak
              description: Docker Hardened Images Helm chart for Keycloak
              images:
                - name: keycloak
                  ref: dhi/keycloak:26.6.3-debian13@sha256:4106a83fbca43f45de40260db12626a58ee350fc24feda2264b78dce79f4a19d
                - name: busybox
                  ref: dhi/busybox:1.37.0-debian13@sha256:e0cbe035dd7d7072e088172c5833bf756bfba3618567c0f5e73288e97e3a19bf
              name: keycloak-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/codecentric/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/keycloakx
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          privileged: true
          with:
            chart: ${source.dir}/helm-charts/charts/keycloakx
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          with:
            chart: ${source.dir}/helm-charts/charts/keycloakx
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: ${source.dir}/helm-charts/charts/keycloakx
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/keycloak/config
