# syntax=dhi.io/build:2-helm3

name: Keycloak Helm chart 7.x
image: dhi.io/keycloak-chart
variant: helm
tags:
  - 7.1.11
platforms:
  - linux/amd64
vars:
  BUSYBOX_REFERENCE: dhi/busybox:1.37.0-debian13@sha256:a91d3f23f20f9ab231ebefa0acf1799dd7dbad424fa4dca099762790e900f4f7
  CHART_COMMIT_SHA: 15f09f31c8c4c23c4162d8d6e3b2b6f3669f7b43
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.20.2-debian13-dev@sha256:ce95680846fc18d3d179f82f9d633c8274f41cd0d0f8213cbfc4039fbe2cd112
  KEYCLOAK_REFERENCE: dhi/keycloak:26.6.1-debian13@sha256:af5fda28bf3719474748e5f4366e6ae78b4cc2c10d12b8dcdc0849e713fc4976
  SEMVER_MAJOR_MINOR_VERSION: "7.1"
  SEMVER_MAJOR_VERSION: "7"
  SEMVER_VERSION: 7.1.11
  VERSION: 7.1.11
contents:
  builds:
    - name: keycloak-chart
      uses: dhi.io/helm:3.20.2-debian13-dev@sha256:ce95680846fc18d3d179f82f9d633c8274f41cd0d0f8213cbfc4039fbe2cd112
      contents:
        files:
          - url: git+https://github.com/codecentric/helm-charts.git#keycloakx-7.1.11
            checksum: 15f09f31c8c4c23c4162d8d6e3b2b6f3669f7b43
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/keycloakx
          with:
            chart:
              appRef: keycloak
              description: Docker Hardened Images Helm chart for Keycloak
              images:
                - name: keycloak
                  ref: dhi/keycloak:26.6.1-debian13@sha256:af5fda28bf3719474748e5f4366e6ae78b4cc2c10d12b8dcdc0849e713fc4976
                - name: busybox
                  ref: dhi/busybox:1.37.0-debian13@sha256:a91d3f23f20f9ab231ebefa0acf1799dd7dbad424fa4dca099762790e900f4f7
              name: keycloak-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/codecentric/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/keycloakx
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          privileged: true
          with:
            chart: ${source.dir}/helm-charts/charts/keycloakx
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          with:
            chart: ${source.dir}/helm-charts/charts/keycloakx
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: ${source.dir}/helm-charts/charts/keycloakx
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/keycloak/config
