# syntax=dhi.io/build:2-helm3

name: Keycloak Helm chart 7.x
image: dhi.io/keycloak-chart
variant: helm
tags:
  - 7.2.0
platforms:
  - linux/amd64
vars:
  BUSYBOX_REFERENCE: dhi/busybox:1.37.0-alpine3.24@sha256:636d705b1516b95c89efb11ae77091f768a6aae4daf9cc6324ea32249dfcbbe9
  CHART_COMMIT_SHA: 279061024a68a250bc6767737f3c1bf6e7539313
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.21.1-debian13-dev@sha256:4a31f16f7a169beeda158b2db462a85c6767889a961726b04907bf4d0a6754f4
  KEYCLOAK_REFERENCE: dhi/keycloak:26.6.3-debian13@sha256:7b328d49a6d391d514dea44eebd4e31bb99f2481715a4480937ae5af418af304
  SEMVER_MAJOR_MINOR_VERSION: "7.2"
  SEMVER_MAJOR_VERSION: "7"
  SEMVER_VERSION: 7.2.0
  VERSION: 7.2.0
contents:
  builds:
    - name: keycloak-chart
      uses: dhi.io/helm:3.21.1-debian13-dev@sha256:4a31f16f7a169beeda158b2db462a85c6767889a961726b04907bf4d0a6754f4
      contents:
        files:
          - url: git+https://github.com/codecentric/helm-charts.git#keycloakx-7.2.0
            checksum: 279061024a68a250bc6767737f3c1bf6e7539313
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/keycloakx
          with:
            chart:
              appRef: keycloak
              description: Docker Hardened Images Helm chart for Keycloak
              images:
                - name: keycloak
                  ref: dhi/keycloak:26.6.3-debian13@sha256:7b328d49a6d391d514dea44eebd4e31bb99f2481715a4480937ae5af418af304
                - name: busybox
                  ref: dhi/busybox:1.37.0-alpine3.24@sha256:636d705b1516b95c89efb11ae77091f768a6aae4daf9cc6324ea32249dfcbbe9
              name: keycloak-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/codecentric/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/keycloakx
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          privileged: true
          with:
            chart: ${source.dir}/helm-charts/charts/keycloakx
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          with:
            chart: ${source.dir}/helm-charts/charts/keycloakx
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: ${source.dir}/helm-charts/charts/keycloakx
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/keycloak/config
