# syntax=dhi.io/build:2-helm3

name: Vault Helm chart 0.x
image: dhi.io/vault-chart
variant: helm
tags:
  - 0.33.0
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: 14492475a3af1bde536491a4d19c78f34b38ebf0
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.21.0-debian13-dev@sha256:7b9ee43cc77e81e2dcbb1b0f6e8ce376b71d63c90c81f2863e24aefff774a8da
  SEMVER_MAJOR_MINOR_VERSION: "0.33"
  SEMVER_MAJOR_VERSION: "0"
  SEMVER_VERSION: 0.33.0
  VAULT_CSI_PROVIDER_REFERENCE: dhi/vault-csi-provider:1.7.2-debian13@sha256:be413f294edc0347be0302bd9c40b3f9b19679720783234ac0395440d913261e
  VAULT_HELM_REFERENCE: dhi/vault:1.21.4-debian13-helm@sha256:d06c18f734dacbb695fee1c7d9d0be7d66ea2497b0a5b036ad1fc47252a6e834
  VAULT_K8S_REFERENCE: dhi/vault-k8s:1.7.4-debian13@sha256:559eec8e07abd8e6788c1127a1734bb4e3f4dd1d03c8d31798cd27457f049b82
  VAULT_REFERENCE: dhi/vault:1.21.4-debian13@sha256:76681c3b07dcd1cc7b49c151b842b55ae57d2ea209fd653631005c14dc5c7a81
  VERSION: 0.33.0
contents:
  builds:
    - name: vault
      uses: dhi.io/helm:3.21.0-debian13-dev@sha256:7b9ee43cc77e81e2dcbb1b0f6e8ce376b71d63c90c81f2863e24aefff774a8da
      contents:
        packages:
          - bash
          - build-essential
          - coreutils
          - grep
          - libc-bin
          - sed
        files:
          - url: git+https://github.com/hashicorp/vault-helm.git#v0.33.0
            checksum: 14492475a3af1bde536491a4d19c78f34b38ebf0
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts
          with:
            chart:
              appRef: vault
              description: Docker Hardened Images Helm chart for Vault
              images:
                - name: vault
                  ref: dhi/vault:1.21.4-debian13@sha256:76681c3b07dcd1cc7b49c151b842b55ae57d2ea209fd653631005c14dc5c7a81
                - name: vault-helm
                  ref: dhi/vault:1.21.4-debian13-helm@sha256:d06c18f734dacbb695fee1c7d9d0be7d66ea2497b0a5b036ad1fc47252a6e834
                - name: vault-k8s
                  ref: dhi/vault-k8s:1.7.4-debian13@sha256:559eec8e07abd8e6788c1127a1734bb4e3f4dd1d03c8d31798cd27457f049b82
                - name: vault-csi-provider
                  ref: dhi/vault-csi-provider:1.7.2-debian13@sha256:be413f294edc0347be0302bd9c40b3f9b19679720783234ac0395440d913261e
              name: vault-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/hashicorp/vault-helm
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          with:
            chart: ${source.dir}/helm-charts
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts
          with:
            chart: .
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: ${source.dir}/helm-charts
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/vault/config
