# syntax=dhi.io/build:2-helm3

name: Vault Helm chart 0.x
image: dhi.io/vault-chart
variant: helm
tags:
  - 0.32.0
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: 3e032ad7685f80fc2a021e282a52b6d2fbd37a07
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.21.0-debian13-dev@sha256:6506c914dff9353ce03ce64c8d30089cf14419d8d39f026c53917e1451fb8b21
  SEMVER_MAJOR_MINOR_VERSION: "0.32"
  SEMVER_MAJOR_VERSION: "0"
  SEMVER_VERSION: 0.32.0
  VAULT_CSI_PROVIDER_REFERENCE: dhi/vault-csi-provider:1.7.1-debian13@sha256:bb6a5a905731e366141b2cca6fcf82239de8ea1074a8167c0bad34cc99f33640
  VAULT_HELM_REFERENCE: dhi/vault:1.21.4-debian13-helm@sha256:62b3890c253dbd705b66a3909c61e9edcffc664550588c84e2b9f9bb948a864a
  VAULT_K8S_REFERENCE: dhi/vault-k8s:1.7.4-debian13@sha256:3c4dacbc2625d1f6cbc9bb455b419b357635a00bc78166d5871f248c9ed1e6e9
  VAULT_REFERENCE: dhi/vault:1.21.4-debian13@sha256:a0388bbaf8e979e7562a423d473e6492e4d708d8f7dc1e522e5b553aa9a0d7e6
  VERSION: 0.32.0
contents:
  builds:
    - name: vault
      uses: dhi.io/helm:3.21.0-debian13-dev@sha256:6506c914dff9353ce03ce64c8d30089cf14419d8d39f026c53917e1451fb8b21
      contents:
        packages:
          - bash
          - build-essential
          - coreutils
          - grep
          - libc-bin
          - sed
        files:
          - url: git+https://github.com/hashicorp/vault-helm.git#v0.32.0
            checksum: 3e032ad7685f80fc2a021e282a52b6d2fbd37a07
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts
          with:
            chart:
              appRef: vault
              description: Docker Hardened Images Helm chart for Vault
              images:
                - name: vault
                  ref: dhi/vault:1.21.4-debian13@sha256:a0388bbaf8e979e7562a423d473e6492e4d708d8f7dc1e522e5b553aa9a0d7e6
                - name: vault-helm
                  ref: dhi/vault:1.21.4-debian13-helm@sha256:62b3890c253dbd705b66a3909c61e9edcffc664550588c84e2b9f9bb948a864a
                - name: vault-k8s
                  ref: dhi/vault-k8s:1.7.4-debian13@sha256:3c4dacbc2625d1f6cbc9bb455b419b357635a00bc78166d5871f248c9ed1e6e9
                - name: vault-csi-provider
                  ref: dhi/vault-csi-provider:1.7.1-debian13@sha256:bb6a5a905731e366141b2cca6fcf82239de8ea1074a8167c0bad34cc99f33640
              name: vault-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/hashicorp/vault-helm
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          with:
            chart: ${source.dir}/helm-charts
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts
          with:
            chart: .
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: ${source.dir}/helm-charts
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/vault/config
