# syntax=dhi.io/build:2-helm3

name: Istio Discovery (istiod) Helm chart 1.x
image: dhi.io/istio-discovery-chart
variant: helm
tags:
  - 1.28.6
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: db606cedf03cac76d91a05a4a5628fa47bd537f3
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.20.2-debian13-dev@sha256:ce95680846fc18d3d179f82f9d633c8274f41cd0d0f8213cbfc4039fbe2cd112
  ISTIO_PILOT_REFERENCE: dhi/istio-pilot:1.28.6-debian13@sha256:2882333c029b29971f617f0608c10508c77b0546c33d377a9432c23789ef1d9a
  ISTIO_PROXYV2_REFERENCE: dhi/istio-proxyv2:1.28.6-debian13@sha256:ee71317ac1e62930e85c9f4ab86cc1a14ff02940069225607926b68389955c4d
  SEMVER_MAJOR_MINOR_VERSION: "1.28"
  SEMVER_MAJOR_VERSION: "1"
  SEMVER_VERSION: 1.28.6
  VERSION: 1.28.6
contents:
  builds:
    - name: istio-discovery
      uses: dhi.io/helm:3.20.2-debian13-dev@sha256:ce95680846fc18d3d179f82f9d633c8274f41cd0d0f8213cbfc4039fbe2cd112
      work-dir: /src/go/github.com/istio/istio/manifests/charts/istio-control/istio-discovery
      contents:
        files:
          - url: git+https://github.com/istio/istio.git#1.28.6
            checksum: db606cedf03cac76d91a05a4a5628fa47bd537f3
            path: /src/go/github.com/istio/istio
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          with:
            chart:
              appRef: pilot
              description: Docker Hardened Images Helm chart for Istio Discovery (istiod)
              images:
                - name: pilot
                  ref: dhi/istio-pilot:1.28.6-debian13@sha256:2882333c029b29971f617f0608c10508c77b0546c33d377a9432c23789ef1d9a
                - name: proxyv2
                  ref: dhi/istio-proxyv2:1.28.6-debian13@sha256:ee71317ac1e62930e85c9f4ab86cc1a14ff02940069225607926b68389955c4d
              name: istio-discovery-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/istio/istio
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          with:
            chart: .
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: .
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/istio-discovery/config
