# syntax=dhi.io/build:2-helm3

name: Istio Discovery (istiod) Helm chart 1.30.x
image: dhi.io/istio-discovery-chart
variant: helm
tags:
  - 1.30.2
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: f888ab4c8a0c3d0427bb0053fbebbe6b1f7e9a91
  CHART_HELM_NAME: istio-discovery-chart
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_VERSION: 4.1.4-2
  ISTIO_PILOT_REFERENCE: dhi/istio-pilot:1.30.2-debian13@sha256:194934a4854761fceb514d3136ee5e77ee2b30a5bbbc314eb1e3d5d6064bfa39
  ISTIO_PROXYV2_REFERENCE: dhi/istio-proxyv2:1.30.2-debian13@sha256:e785bb1203d432e7c2e9eba2d497a4c7219cec842fb77b9ba3e902524c0f8e6c
  SEMVER_MAJOR_MINOR_VERSION: "1.30"
  SEMVER_MAJOR_VERSION: "1"
  SEMVER_VERSION: 1.30.2
  VERSION: 1.30.2
contents:
  repositories:
    - deb [signed-by=/usr/share/keyrings/dhi-deb-main.gpg] http://dhi.io/deb/debian/main trixie main
  keyring:
    - https://dhi.io/keyring/dhi-deb-gpg.D46852F6925E9F71.key
  builds:
    - name: istio-discovery
      work-dir: /src/go/github.com/istio/istio/manifests/charts/istio-control/istio-discovery
      contents:
        packages:
          - bash
          - ca-certificates
          - coreutils
          - helm=4.1.4-2
        files:
          - url: git+https://github.com/istio/istio.git#1.30.2
            checksum: f888ab4c8a0c3d0427bb0053fbebbe6b1f7e9a91
            path: /src/go/github.com/istio/istio
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          with:
            chart:
              appRef: pilot
              description: Docker Hardened Images Helm chart for Istio Discovery (istiod)
              images:
                - name: pilot
                  ref: dhi/istio-pilot:1.30.2-debian13@sha256:194934a4854761fceb514d3136ee5e77ee2b30a5bbbc314eb1e3d5d6064bfa39
                - name: proxyv2
                  ref: dhi/istio-proxyv2:1.30.2-debian13@sha256:e785bb1203d432e7c2e9eba2d497a4c7219cec842fb77b9ba3e902524c0f8e6c
              name: istio-discovery-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/istio/istio
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          with:
            chart: .
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: .
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/istio-discovery/config
