# syntax=dhi.io/build:2-helm3

name: APISIX Helm chart 2.x
image: dhi.io/apisix-chart
variant: helm
tags:
  - 2.14.0
platforms:
  - linux/amd64
vars:
  APISIX_IMAGE_REFERENCE: dhi/apisix:3.16.0-debian13@sha256:64985926648c6e3738748b3d93f68aeadcd00e6ec73ca06cde29af7b4d3622e3
  APISIX_INGRESS_CONTROLLER_CHART_REFERENCE: dhi/apisix-ingress-controller-chart:1.1.2@sha256:2e9926f3f38a69abab30407886253e62de2504e92134acd14e8f4dbfe3f3d9e0
  BUSYBOX_IMAGE_REFERENCE: dhi/busybox:1.37.0-debian13@sha256:a91d3f23f20f9ab231ebefa0acf1799dd7dbad424fa4dca099762790e900f4f7
  CHART_COMMIT_SHA: 60c9cbbfe0c03aba53bdf9644f491c90204a43cd
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.20.2-debian13-dev@sha256:b72e12042810e0697eebb51a7862e7699f4df8eca02324029c220ccfd0bce4a4
  SEMVER_MAJOR_MINOR_VERSION: "2.14"
  SEMVER_MAJOR_VERSION: "2"
  SEMVER_VERSION: 2.14.0
  VERSION: 2.14.0
contents:
  builds:
    - name: apisix-chart
      uses: dhi.io/helm:3.20.2-debian13-dev@sha256:b72e12042810e0697eebb51a7862e7699f4df8eca02324029c220ccfd0bce4a4
      contents:
        files:
          - url: git+https://github.com/apache/apisix-helm-chart.git#apisix-2.14.0
            checksum: 60c9cbbfe0c03aba53bdf9644f491c90204a43cd
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/apisix
          with:
            chart:
              appRef: apisix
              dependencies:
                - alias: ingress-controller
                  condition: ingress-controller.enabled
                  name: apisix-ingress-controller-chart
                  ref: dhi/apisix-ingress-controller-chart:1.1.2@sha256:2e9926f3f38a69abab30407886253e62de2504e92134acd14e8f4dbfe3f3d9e0
              description: Docker Hardened Images Helm chart for APISIX
              images:
                - name: apisix
                  ref: dhi/apisix:3.16.0-debian13@sha256:64985926648c6e3738748b3d93f68aeadcd00e6ec73ca06cde29af7b4d3622e3
                - name: busybox
                  ref: dhi/busybox:1.37.0-debian13@sha256:a91d3f23f20f9ab231ebefa0acf1799dd7dbad424fa4dca099762790e900f4f7
              name: apisix-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/apache/apisix
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/apisix
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update values
          uses: yq/patch@v1
          work-dir: ${source.dir}/helm-charts/charts/apisix
          with:
            file: values.yaml
            patches:
              - del(.etcd.image)
              - del(.etcd.auth.rbac)
              - del(.etcd.containerSecurityContext)
              - del(.etcd.service)
              - del(.etcd.replicaCount)
              - del(.etcd.autoCompactionRetention)
              - del(.etcd.autoCompactionMode)
        - name: helm login
          uses: helm/login@v1
          with:
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          privileged: true
          with:
            chart: apisix
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: apisix
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: apisix
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/apisix/config
