# syntax=dhi.io/build:2-helm3

name: Grafana Tempo Helm chart 2.x
image: dhi.io/tempo-chart
variant: helm
tags:
  - 2.1.0
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: 94700eed451c4bd68456a4632310c63a07e41319
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.21.0-debian13-dev@sha256:dde1e16cc0ad3d2cdeebdb78f1e676b899e6f62a12c529dd620d045bd2fd334a
  SEMVER_MAJOR_MINOR_VERSION: "2.1"
  SEMVER_MAJOR_VERSION: "2"
  SEMVER_VERSION: 2.1.0
  TEMPO_QUERY_REFERENCE: dhi/tempo-query:2.10.5-debian13@sha256:e3904039ff562029e92a23d6083997db00d5ca68882dd5a91627cf85a9c697ff
  TEMPO_REFERENCE: dhi/tempo:2.10.5-debian13@sha256:d1983922abb81b651e410d2b12719fa940c17c1da2bf5aade7bd05c1fc21d7cc
  VERSION: 2.1.0
contents:
  builds:
    - name: grafana-tempo
      uses: dhi.io/helm:3.21.0-debian13-dev@sha256:dde1e16cc0ad3d2cdeebdb78f1e676b899e6f62a12c529dd620d045bd2fd334a
      work-dir: ${source.dir}/helm-charts/charts/tempo
      contents:
        files:
          - url: git+https://github.com/grafana-community/helm-charts.git#tempo-2.1.0
            checksum: 94700eed451c4bd68456a4632310c63a07e41319
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          with:
            chart:
              appRef: tempo
              description: Docker Hardened Images Helm chart for Grafana Tempo
              images:
                - name: tempo
                  ref: dhi/tempo:2.10.5-debian13@sha256:d1983922abb81b651e410d2b12719fa940c17c1da2bf5aade7bd05c1fc21d7cc
                - name: tempo-query
                  ref: dhi/tempo-query:2.10.5-debian13@sha256:e3904039ff562029e92a23d6083997db00d5ca68882dd5a91627cf85a9c697ff
              name: tempo-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/grafana-community/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          with:
            chart: .
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: .
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/grafana-tempo/config
