# syntax=dhi.io/build:2-helm3

name: Grafana Tempo Helm chart 2.x
image: dhi.io/tempo-chart
variant: helm
tags:
  - 2.2.0
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: 2a2621f73ad7ce902a9936941e5389243a419ef8
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.21.0-debian13-dev@sha256:27a89b8b9ac55c501c63c5ce01efab9b5e0915f98c220e54787816ff99c7abc2
  SEMVER_MAJOR_MINOR_VERSION: "2.2"
  SEMVER_MAJOR_VERSION: "2"
  SEMVER_VERSION: 2.2.0
  TEMPO_QUERY_REFERENCE: dhi/tempo-query:2.10.5-debian13@sha256:ee2a8a71b2288e036001655d3ea5b0e41386ee0983fd6cb496ff81d4761341c1
  TEMPO_REFERENCE: dhi/tempo:2.10.5-debian13@sha256:2a6b0e18809fa08c1d569b5632ca3a1d9fa1d855325085a28c6c38de438e5c90
  VERSION: 2.2.0
contents:
  builds:
    - name: grafana-tempo
      uses: dhi.io/helm:3.21.0-debian13-dev@sha256:27a89b8b9ac55c501c63c5ce01efab9b5e0915f98c220e54787816ff99c7abc2
      work-dir: ${source.dir}/helm-charts/charts/tempo
      contents:
        files:
          - url: git+https://github.com/grafana-community/helm-charts.git#tempo-2.2.0
            checksum: 2a2621f73ad7ce902a9936941e5389243a419ef8
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          with:
            chart:
              appRef: tempo
              description: Docker Hardened Images Helm chart for Grafana Tempo
              images:
                - name: tempo
                  ref: dhi/tempo:2.10.5-debian13@sha256:2a6b0e18809fa08c1d569b5632ca3a1d9fa1d855325085a28c6c38de438e5c90
                - name: tempo-query
                  ref: dhi/tempo-query:2.10.5-debian13@sha256:ee2a8a71b2288e036001655d3ea5b0e41386ee0983fd6cb496ff81d4761341c1
              name: tempo-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/grafana-community/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          with:
            chart: .
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: .
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/grafana-tempo/config
