# syntax=dhi.io/build:2-helm3

name: Grafana Tempo Helm chart 2.x
image: dhi.io/tempo-chart
variant: helm
tags:
  - 2.2.3
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: 6fd7692412eebaa8d4b1db9b71c5a747ac79ee13
  CHART_HELM_NAME: tempo-chart
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_VERSION: 4.1.4-2
  SEMVER_MAJOR_MINOR_VERSION: "2.2"
  SEMVER_MAJOR_VERSION: "2"
  SEMVER_VERSION: 2.2.3
  TEMPO_QUERY_REFERENCE: dhi/tempo-query:2.10.7-debian13@sha256:59ba19ce8587ae004a2ddfcc01e1d3197fd3458dfd76be196a9c18c2d6beddc1
  TEMPO_REFERENCE: dhi/tempo:2.10.7-debian13@sha256:958abf5f015e77aed9ca9a1178f30c7ea9a6030ac192b69297e4e47fb8afb1d8
  VERSION: 2.2.3
contents:
  repositories:
    - deb [signed-by=/usr/share/keyrings/dhi-deb-main.gpg] http://dhi.io/deb/debian/main trixie main
  keyring:
    - https://dhi.io/keyring/dhi-deb-gpg.D46852F6925E9F71.key
  builds:
    - name: grafana-tempo
      work-dir: ${source.dir}/helm-charts/charts/tempo
      contents:
        packages:
          - bash
          - ca-certificates
          - coreutils
          - helm=4.1.4-2
        files:
          - url: git+https://github.com/grafana-community/helm-charts.git#tempo-2.2.3
            checksum: 6fd7692412eebaa8d4b1db9b71c5a747ac79ee13
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          with:
            chart:
              appRef: tempo
              description: Docker Hardened Images Helm chart for Grafana Tempo
              images:
                - name: tempo
                  ref: dhi/tempo:2.10.7-debian13@sha256:958abf5f015e77aed9ca9a1178f30c7ea9a6030ac192b69297e4e47fb8afb1d8
                - name: tempo-query
                  ref: dhi/tempo-query:2.10.7-debian13@sha256:59ba19ce8587ae004a2ddfcc01e1d3197fd3458dfd76be196a9c18c2d6beddc1
              name: tempo-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/grafana-community/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          with:
            chart: .
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: .
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/grafana-tempo/config
