# syntax=dhi.io/build:2-helm3

name: KEDA Helm chart 2.x
image: dhi.io/keda-chart
variant: helm
tags:
  - 2.19.0
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: 86f514c2e28d70c8a0bf5ec1ad3cbec80b24ebf2
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.20.1-debian13-dev@sha256:5c85f22e85fe6e1299ff8fff613b5868320b157297a8b3ff08e5d0bbbbf6cbe9
  KEDA_ADMISSION_WEBHOOKS_REFERENCE: dhi/keda-admission-webhooks:2.19.0-debian13@sha256:574d4097d3d64d9a53e8088061d28154b6e032c015287f712069bdd0396644a9
  KEDA_METRICS_APISERVER_REFERENCE: dhi/keda-metrics-apiserver:2.19.0-debian13@sha256:7d33bbd638c1f6fcdbed84cfcdb4d1f19e1f6919188cfa41562cf4d393b20cba
  KEDA_REFERENCE: dhi/keda:2.19.0-debian13@sha256:386ef24b6ebecfde1824e8e29216ff678f6eb66d94eed268283ca0e771a8f241
  SEMVER_MAJOR_MINOR_VERSION: "2.19"
  SEMVER_MAJOR_VERSION: "2"
  SEMVER_VERSION: 2.19.0
  VERSION: 2.19.0
contents:
  builds:
    - name: keda-chart
      uses: dhi.io/helm:3.20.1-debian13-dev@sha256:5c85f22e85fe6e1299ff8fff613b5868320b157297a8b3ff08e5d0bbbbf6cbe9
      contents:
        files:
          - url: git+https://github.com/kedacore/charts.git#v2.19.0
            checksum: 86f514c2e28d70c8a0bf5ec1ad3cbec80b24ebf2
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/keda
          with:
            chart:
              appRef: keda
              description: Docker Hardened Images Helm chart for KEDA
              images:
                - name: keda
                  ref: dhi/keda:2.19.0-debian13@sha256:386ef24b6ebecfde1824e8e29216ff678f6eb66d94eed268283ca0e771a8f241
                - name: keda-admission-webhooks
                  ref: dhi/keda-admission-webhooks:2.19.0-debian13@sha256:574d4097d3d64d9a53e8088061d28154b6e032c015287f712069bdd0396644a9
                - name: keda-metrics-apiserver
                  ref: dhi/keda-metrics-apiserver:2.19.0-debian13@sha256:7d33bbd638c1f6fcdbed84cfcdb4d1f19e1f6919188cfa41562cf4d393b20cba
              name: keda-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/kedacore/charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/keda
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts
          privileged: true
          with:
            chart: keda
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts
          with:
            chart: keda
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts
          with:
            chart: keda
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/keda/config
