# syntax=dhi.io/build:2-helm3

name: KEDA Helm chart 2.x
image: dhi.io/keda-chart
variant: helm
tags:
  - 2.19.0
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: 86f514c2e28d70c8a0bf5ec1ad3cbec80b24ebf2
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.21.0-debian13-dev@sha256:dde1e16cc0ad3d2cdeebdb78f1e676b899e6f62a12c529dd620d045bd2fd334a
  KEDA_ADMISSION_WEBHOOKS_REFERENCE: dhi/keda-admission-webhooks:2.19.0-debian13@sha256:c62ed2f60b2abc34fb55ca8edfb7fd416696dd96ee91d14175e4abc06faafab2
  KEDA_METRICS_APISERVER_REFERENCE: dhi/keda-metrics-apiserver:2.19.0-debian13@sha256:7ecfbc1849f96a02ca367090210771b52e80a7164ee5d483b63009036230bd2e
  KEDA_REFERENCE: dhi/keda:2.19.0-debian13@sha256:9b4e5241049542da96869f58fe34f0b9aedea7f229c81b167c33678dee3b87b0
  SEMVER_MAJOR_MINOR_VERSION: "2.19"
  SEMVER_MAJOR_VERSION: "2"
  SEMVER_VERSION: 2.19.0
  VERSION: 2.19.0
contents:
  builds:
    - name: keda-chart
      uses: dhi.io/helm:3.21.0-debian13-dev@sha256:dde1e16cc0ad3d2cdeebdb78f1e676b899e6f62a12c529dd620d045bd2fd334a
      contents:
        files:
          - url: git+https://github.com/kedacore/charts.git#v2.19.0
            checksum: 86f514c2e28d70c8a0bf5ec1ad3cbec80b24ebf2
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/keda
          with:
            chart:
              appRef: keda
              description: Docker Hardened Images Helm chart for KEDA
              images:
                - name: keda
                  ref: dhi/keda:2.19.0-debian13@sha256:9b4e5241049542da96869f58fe34f0b9aedea7f229c81b167c33678dee3b87b0
                - name: keda-admission-webhooks
                  ref: dhi/keda-admission-webhooks:2.19.0-debian13@sha256:c62ed2f60b2abc34fb55ca8edfb7fd416696dd96ee91d14175e4abc06faafab2
                - name: keda-metrics-apiserver
                  ref: dhi/keda-metrics-apiserver:2.19.0-debian13@sha256:7ecfbc1849f96a02ca367090210771b52e80a7164ee5d483b63009036230bd2e
              name: keda-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/kedacore/charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/keda
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts
          privileged: true
          with:
            chart: keda
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts
          with:
            chart: keda
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts
          with:
            chart: keda
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/keda/config
