# syntax=dhi.io/build:2-helm3

name: Neo4j Helm chart 5.x
image: dhi.io/neo4j-chart
variant: helm
tags:
  - 5.26.26
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: e52826984a74339c48a12f0da9f23c29b65b0cf2
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.21.0-debian13-dev@sha256:dde1e16cc0ad3d2cdeebdb78f1e676b899e6f62a12c529dd620d045bd2fd334a
  KUBECTL_REFERENCE: dhi/kubectl:1.34.8-alpine3.22-dev@sha256:2a2ec222032ff24a4c4fb7f2bc1cf09397335028622e0abce1e0aca6f3097181
  NEO4J_REFERENCE: dhi/neo4j:5.26.25-debian13@sha256:1682349fcc5e1863aa79d722c2baed84a87ac01e55d3bb5c86473db2524ead0f
  SEMVER_MAJOR_MINOR_VERSION: "5.26"
  SEMVER_MAJOR_VERSION: "5"
  SEMVER_VERSION: 5.26.26
  VERSION: 5.26.26
contents:
  builds:
    - name: neo4j
      uses: dhi.io/helm:3.21.0-debian13-dev@sha256:dde1e16cc0ad3d2cdeebdb78f1e676b899e6f62a12c529dd620d045bd2fd334a
      contents:
        files:
          - url: git+https://github.com/neo4j/helm-charts.git#5.26.26
            checksum: e52826984a74339c48a12f0da9f23c29b65b0cf2
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/neo4j
          with:
            chart:
              appRef: neo4j
              description: Docker Hardened Images Helm chart for Neo4j
              images:
                - name: neo4j
                  ref: dhi/neo4j:5.26.25-debian13@sha256:1682349fcc5e1863aa79d722c2baed84a87ac01e55d3bb5c86473db2524ead0f
                - name: kubectl
                  ref: dhi/kubectl:1.34.8-alpine3.22-dev@sha256:2a2ec222032ff24a4c4fb7f2bc1cf09397335028622e0abce1e0aca6f3097181
              name: neo4j-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/neo4j/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: update chart values
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/neo4j
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          with:
            chart: ${source.dir}/helm-charts/neo4j
            cmd: dependency update
        - name: blank 3rd party images
          work-dir: ${source.dir}/helm-charts/neo4j
          runs: |
            set -eux -o pipefail

            # Blank out the 3rd party images for neo4j-operations
            sed -i '/- name: .*-operations/{n;s/^\([[:space:]]*image:\).*/\1 "" #THIS IMAGE IS NOT IN THE DHI CATALOG YET, PLEASE CONTACT THE DOCKER TEAM IF NEEDED/;}' ./templates/neo4j-operations.yaml
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts
          with:
            chart: neo4j
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: ${source.dir}/helm-charts/neo4j
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/neo4j/config
