hub:
  image:
    name: ${hub.registry}/${hub.repository}
    tag: ${hub.tag}@${hub.digest}
  podSecurityContext:
    fsGroup: 65532
  containerSecurityContext:
    runAsUser: 65532
    runAsGroup: 65532

proxy:
  chp:
    image:
      name: ${chp.registry}/${chp.repository}
      tag: ${chp.tag}@${chp.digest}
    containerSecurityContext:
      runAsUser: 65532
      runAsGroup: 65532
      runAsNonRoot: true
  secretSync:
    image:
      name: ${secret-sync.registry}/${secret-sync.repository}
      tag: ${secret-sync.tag}@${secret-sync.digest}
    containerSecurityContext:
      runAsUser: 65532
      runAsGroup: 65532
      runAsNonRoot: true
  traefik:
    image:
      name: ${traefik.registry}/${traefik.repository}
      tag: ${traefik.tag}@${traefik.digest}
    containerSecurityContext:
      runAsUser: 65532
      runAsGroup: 65532
      runAsNonRoot: true

singleuser:
  image:
    name: ${singleuser.registry}/${singleuser.repository}
    tag: ${singleuser.tag}@${singleuser.digest}
  networkTools:
    image:
      name: ${network-tools.registry}/${network-tools.repository}
      tag: ${network-tools.tag}@${network-tools.digest}
  uid: 65532
  fsGid: 65532

scheduling:
  userScheduler:
    image:
      name: ${kube-scheduler.registry}/${kube-scheduler.repository}
      tag: ${kube-scheduler.tag}@${kube-scheduler.digest}
    containerSecurityContext:
      runAsUser: 65532
      runAsGroup: 65532
      runAsNonRoot: true
  userPlaceholder:
    image:
      name: ${pause.registry}/${pause.repository}
      tag: ${pause.tag}@${pause.digest}
    containerSecurityContext:
      runAsUser: 65535
      runAsGroup: 65535
      runAsNonRoot: true

prePuller:
  hook:
    enabled: true
    image:
      name: ${image-awaiter.registry}/${image-awaiter.repository}
      tag: ${image-awaiter.tag}@${image-awaiter.digest}
  pause:
    image:
      name: ${pause.registry}/${pause.repository}
      tag: ${pause.tag}@${pause.digest}
    containerSecurityContext:
      runAsUser: 65535
      runAsGroup: 65535
      runAsNonRoot: true
