# syntax=dhi.io/build:2-helm3

name: Karpenter Helm chart 1.x
image: dhi.io/karpenter-chart
variant: helm
tags:
  - 1.13.0
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: 2be95547983a8948b7172aa66bf92c905fbbf001
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.21.0-debian13-dev@sha256:7c201a9174a2b56cb13136f19d87b23309d09eb2fc8a24e8c08a31ebd907a943
  KARPENTER_REFERENCE: dhi/karpenter:1.13.0-debian13@sha256:37ee04c1caa2579159de4f28aceb0606ce192ac72b5e08d71ec0344bad49c015
  SEMVER_MAJOR_MINOR_VERSION: "1.13"
  SEMVER_MAJOR_VERSION: "1"
  SEMVER_VERSION: 1.13.0
  VERSION: 1.13.0
contents:
  builds:
    - name: karpenter
      uses: dhi.io/helm:3.21.0-debian13-dev@sha256:7c201a9174a2b56cb13136f19d87b23309d09eb2fc8a24e8c08a31ebd907a943
      contents:
        files:
          - url: git+https://github.com/aws/karpenter-provider-aws.git#v1.13.0
            checksum: 2be95547983a8948b7172aa66bf92c905fbbf001
            path: ${source.dir}/karpenter-repo
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/karpenter-repo/charts/karpenter
          with:
            chart:
              appRef: karpenter
              description: Docker Hardened Images Helm chart for Karpenter
              images:
                - name: karpenter
                  ref: dhi/karpenter:1.13.0-debian13@sha256:37ee04c1caa2579159de4f28aceb0606ce192ac72b5e08d71ec0344bad49c015
              name: karpenter-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/aws/karpenter-provider-aws
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/karpenter-repo/charts/karpenter
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          privileged: true
          with:
            chart: ${source.dir}/karpenter-repo/charts/karpenter
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/karpenter-repo/charts
          with:
            chart: karpenter
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: ${source.dir}/karpenter-repo/charts/karpenter
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/karpenter/config
