# syntax=dhi.io/build:2-helm3

name: Karpenter Helm chart 1.x
image: dhi.io/karpenter-chart
variant: helm
tags:
  - 1.11.1
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: 77c161351fbad4f23fae329412de22f1045ccb42
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.20.2-debian13-dev@sha256:d3fce3e86c736f8a0d6006a879b3b3eb64074766065f62bcd67cef3c0fa6b848
  KARPENTER_REFERENCE: dhi/karpenter:1.9.0-debian13@sha256:2f95c59144500a1572f38d6da9651d3882f9a8df5c311205d7d92409222020aa
  SEMVER_MAJOR_MINOR_VERSION: "1.11"
  SEMVER_MAJOR_VERSION: "1"
  SEMVER_VERSION: 1.11.1
  VERSION: 1.11.1
contents:
  builds:
    - name: karpenter
      uses: dhi.io/helm:3.20.2-debian13-dev@sha256:d3fce3e86c736f8a0d6006a879b3b3eb64074766065f62bcd67cef3c0fa6b848
      contents:
        files:
          - url: git+https://github.com/aws/karpenter-provider-aws.git#v1.11.1
            checksum: 77c161351fbad4f23fae329412de22f1045ccb42
            path: ${source.dir}/karpenter-repo
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/karpenter-repo/charts/karpenter
          with:
            chart:
              appRef: karpenter
              description: Docker Hardened Images Helm chart for Karpenter
              images:
                - name: karpenter
                  ref: dhi/karpenter:1.9.0-debian13@sha256:2f95c59144500a1572f38d6da9651d3882f9a8df5c311205d7d92409222020aa
              name: karpenter-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/aws/karpenter-provider-aws
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/karpenter-repo/charts/karpenter
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          privileged: true
          with:
            chart: ${source.dir}/karpenter-repo/charts/karpenter
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/karpenter-repo/charts
          with:
            chart: karpenter
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: ${source.dir}/karpenter-repo/charts/karpenter
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/karpenter/config
