# syntax=dhi.io/build:2-helm3

name: Temporal Helm chart 0.x
image: dhi.io/temporalio-chart
variant: helm
tags:
  - 0.74.0
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: f45aaf0383978350e8fdb81d7de57f238e0e3e7f
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  GRAFANA_CHART_REFERENCE: dhi/grafana-chart:12.1.1@sha256:731e4a60524cd5adac6195ca433842e4f3cb4d778520d56055ad0756b697714d
  HELM_REFERENCE: dhi/helm:3.20.2-debian13-dev@sha256:f9dd4a356298b0769dc4c2f718b9f564b631ddf37c19e061d61af9081bc7da13
  PROMETHEUS_CHART_REFERENCE: dhi/prometheus-chart:28.16.0@sha256:7d93bf545a3699bd73e777d5a7a0d254a04717e573193c6fcad8156b483c5968
  SEMVER_MAJOR_MINOR_VERSION: "0.74"
  SEMVER_MAJOR_VERSION: "0"
  SEMVER_VERSION: 0.74.0
  TEMPORALIO_ADMIN_TOOLS_REFERENCE: dhi/temporalio-admin-tools:1.28.4-cli-1.6.2-debian13@sha256:790ff48915710bcc9f59ac1d4e1b6476ab2435c1ccc0dc5581d850c5d810a7de
  TEMPORALIO_SERVER_REFERENCE: dhi/temporalio-server:1.28.4-cli-1.6.2-debian13@sha256:a96350d00dca2177c2cb2fc966115e3cc726f5393664e279e75a7d63480d852c
  TEMPORALIO_UI_REFERENCE: dhi/temporalio-ui:2.48.4-debian13@sha256:3230a55577577d806839a93c676a6e001e022ce3761002f988c71124e33d4580
  VERSION: 0.74.0
contents:
  builds:
    - name: temporalio
      uses: dhi.io/helm:3.20.2-debian13-dev@sha256:f9dd4a356298b0769dc4c2f718b9f564b631ddf37c19e061d61af9081bc7da13
      work-dir: ${source.dir}/helm-charts/charts/temporal
      contents:
        files:
          - url: git+https://github.com/temporalio/helm-charts.git#temporal-0.74.0
            checksum: f45aaf0383978350e8fdb81d7de57f238e0e3e7f
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          with:
            chart:
              appRef: temporalio-server
              dependencies:
                - alias: prometheus
                  condition: prometheus.enabled
                  name: prometheus
                  ref: dhi/prometheus-chart:28.16.0@sha256:7d93bf545a3699bd73e777d5a7a0d254a04717e573193c6fcad8156b483c5968
                - alias: grafana
                  condition: grafana.enabled
                  name: grafana
                  ref: dhi/grafana-chart:12.1.1@sha256:731e4a60524cd5adac6195ca433842e4f3cb4d778520d56055ad0756b697714d
              description: Docker Hardened Images Helm chart for TemporalIO
              images:
                - name: temporalio-server
                  ref: dhi/temporalio-server:1.28.4-cli-1.6.2-debian13@sha256:a96350d00dca2177c2cb2fc966115e3cc726f5393664e279e75a7d63480d852c
                - name: temporalio-admin-tools
                  ref: dhi/temporalio-admin-tools:1.28.4-cli-1.6.2-debian13@sha256:790ff48915710bcc9f59ac1d4e1b6476ab2435c1ccc0dc5581d850c5d810a7de
                - name: temporalio-ui
                  ref: dhi/temporalio-ui:2.48.4-debian13@sha256:3230a55577577d806839a93c676a6e001e022ce3761002f988c71124e33d4580
              name: temporalio-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/temporalio/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: update values
          uses: yq/patch@v1
          with:
            file: values.yaml
            patches:
              - del(.cassandra)
              - del(.elasticsearch)
        - name: relocate chart
          uses: helm/rudder@v1
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: helm login
          uses: helm/login@v1
          with:
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          privileged: true
          with:
            chart: temporal
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          with:
            chart: .
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: .
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/temporalio/config
