# syntax=dhi.io/build:2-helm3

name: Temporal Helm chart 0.x
image: dhi.io/temporalio-chart
variant: helm
tags:
  - 0.74.0
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: f45aaf0383978350e8fdb81d7de57f238e0e3e7f
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  GRAFANA_CHART_REFERENCE: dhi/grafana-chart:12.4.2@sha256:29be0931fc326a1507e5001c5057ada23b9fe0cc422d68e74a2e625a55b9404f
  HELM_REFERENCE: dhi/helm:3.21.0-debian13-dev@sha256:ed0c764ca91c1084c850f3b00e7248f9127153bb3a5803058a337ac99ba6d479
  PROMETHEUS_CHART_REFERENCE: dhi/prometheus-chart:28.16.0@sha256:35bd6dc8958b714d8e44c3aa9e17d5c4430f8c87dea6d043b700e8ac10229c75
  SEMVER_MAJOR_MINOR_VERSION: "0.74"
  SEMVER_MAJOR_VERSION: "0"
  SEMVER_VERSION: 0.74.0
  TEMPORALIO_ADMIN_TOOLS_REFERENCE: dhi/temporalio-admin-tools:1.29.6-cli-1.7.1-debian13@sha256:467415ccf1f52829d50d62d956e09c645b179da492b88bec085c53954c0ed5c5
  TEMPORALIO_SERVER_REFERENCE: dhi/temporalio-server:1.29.6-cli-1.7.1-debian13@sha256:9c95165dd1992af26260c3e2d6fb3f84ad7cbe4349c51b9e7cfffa1c904b7458
  TEMPORALIO_UI_REFERENCE: dhi/temporalio-ui:2.50.0-debian13@sha256:b90f1464208981aa57b1f2877ca246f3f787196f24d3e1747a5e6b508404c35b
  VERSION: 0.74.0
contents:
  builds:
    - name: temporalio
      uses: dhi.io/helm:3.21.0-debian13-dev@sha256:ed0c764ca91c1084c850f3b00e7248f9127153bb3a5803058a337ac99ba6d479
      work-dir: ${source.dir}/helm-charts/charts/temporal
      contents:
        files:
          - url: git+https://github.com/temporalio/helm-charts.git#temporal-0.74.0
            checksum: f45aaf0383978350e8fdb81d7de57f238e0e3e7f
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          with:
            chart:
              appRef: temporalio-server
              dependencies:
                - alias: prometheus
                  condition: prometheus.enabled
                  name: prometheus
                  ref: dhi/prometheus-chart:28.16.0@sha256:35bd6dc8958b714d8e44c3aa9e17d5c4430f8c87dea6d043b700e8ac10229c75
                - alias: grafana
                  condition: grafana.enabled
                  name: grafana
                  ref: dhi/grafana-chart:12.4.2@sha256:29be0931fc326a1507e5001c5057ada23b9fe0cc422d68e74a2e625a55b9404f
              description: Docker Hardened Images Helm chart for TemporalIO
              images:
                - name: temporalio-server
                  ref: dhi/temporalio-server:1.29.6-cli-1.7.1-debian13@sha256:9c95165dd1992af26260c3e2d6fb3f84ad7cbe4349c51b9e7cfffa1c904b7458
                - name: temporalio-admin-tools
                  ref: dhi/temporalio-admin-tools:1.29.6-cli-1.7.1-debian13@sha256:467415ccf1f52829d50d62d956e09c645b179da492b88bec085c53954c0ed5c5
                - name: temporalio-ui
                  ref: dhi/temporalio-ui:2.50.0-debian13@sha256:b90f1464208981aa57b1f2877ca246f3f787196f24d3e1747a5e6b508404c35b
              name: temporalio-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/temporalio/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: update values
          uses: yq/patch@v1
          with:
            file: values.yaml
            patches:
              - del(.cassandra)
              - del(.elasticsearch)
        - name: patch chart values
          uses: helm/rudder@v1
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: helm login
          uses: helm/login@v1
          with:
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          privileged: true
          with:
            chart: .
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          with:
            chart: .
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: .
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/temporalio/config-0
