# syntax=dhi.io/build:2-helm3

name: Temporal Helm chart 0.x
image: dhi.io/temporalio-chart
variant: helm
tags:
  - 0.74.0
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: f45aaf0383978350e8fdb81d7de57f238e0e3e7f
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  GRAFANA_CHART_REFERENCE: dhi/grafana-chart:11.3.8@sha256:1eb946dc20edbd63460cd90a13c72157fc5a6ad4e339b716c8a20fdd69c3271c
  HELM_REFERENCE: dhi/helm:3.20.1-debian13-dev@sha256:7bee3e50c815757f78414dcd850621d0cca82d3660da2376f1111069073f3bd5
  PROMETHEUS_CHART_REFERENCE: dhi/prometheus-chart:28.16.0@sha256:36c252fb4f7f103fcfdb49e09f81f516e6c08c86cbb5bd2726f7b40f1bb2cce7
  SEMVER_MAJOR_MINOR_VERSION: "0.74"
  SEMVER_MAJOR_VERSION: "0"
  SEMVER_VERSION: 0.74.0
  TEMPORALIO_ADMIN_TOOLS_REFERENCE: dhi/temporalio-admin-tools:1.28.3-cli-1.6.2-debian13@sha256:12df48515e197640df1d466a2f0e3e292978b86c5abaf7e36ca59aa5304b4370
  TEMPORALIO_SERVER_REFERENCE: dhi/temporalio-server:1.28.3-cli-1.6.2-debian13@sha256:1d330aaa9f110246b27cd7b5e9a3cbcaf93db0f1d6d53048b66ce30cb7336716
  TEMPORALIO_UI_REFERENCE: dhi/temporalio-ui:2.48.1-debian13@sha256:ee79d164688101c28599516c921a9af2affca6be7c7bfddb32c17624787a1633
  VERSION: 0.74.0
contents:
  builds:
    - name: temporalio
      uses: dhi.io/helm:3.20.1-debian13-dev@sha256:7bee3e50c815757f78414dcd850621d0cca82d3660da2376f1111069073f3bd5
      work-dir: ${source.dir}/helm-charts/charts/temporal
      contents:
        files:
          - url: git+https://github.com/temporalio/helm-charts.git#temporal-0.74.0
            checksum: f45aaf0383978350e8fdb81d7de57f238e0e3e7f
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          with:
            chart:
              appRef: temporalio-server
              dependencies:
                - alias: prometheus
                  condition: prometheus.enabled
                  name: prometheus
                  ref: dhi/prometheus-chart:28.16.0@sha256:36c252fb4f7f103fcfdb49e09f81f516e6c08c86cbb5bd2726f7b40f1bb2cce7
                - alias: grafana
                  condition: grafana.enabled
                  name: grafana
                  ref: dhi/grafana-chart:11.3.8@sha256:1eb946dc20edbd63460cd90a13c72157fc5a6ad4e339b716c8a20fdd69c3271c
              description: Docker Hardened Images Helm chart for TemporalIO
              images:
                - name: temporalio-server
                  ref: dhi/temporalio-server:1.28.3-cli-1.6.2-debian13@sha256:1d330aaa9f110246b27cd7b5e9a3cbcaf93db0f1d6d53048b66ce30cb7336716
                - name: temporalio-admin-tools
                  ref: dhi/temporalio-admin-tools:1.28.3-cli-1.6.2-debian13@sha256:12df48515e197640df1d466a2f0e3e292978b86c5abaf7e36ca59aa5304b4370
                - name: temporalio-ui
                  ref: dhi/temporalio-ui:2.48.1-debian13@sha256:ee79d164688101c28599516c921a9af2affca6be7c7bfddb32c17624787a1633
              name: temporalio-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/temporalio/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: update values
          uses: yq/patch@v1
          with:
            file: values.yaml
            patches:
              - del(.cassandra)
              - del(.elasticsearch)
        - name: relocate chart
          uses: helm/rudder@v1
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: helm login
          uses: helm/login@v1
          with:
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          privileged: true
          with:
            chart: temporal
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          with:
            chart: .
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: .
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/temporalio/config
