# syntax=dhi.io/build:2-helm3

name: Temporal Helm chart 1.x
image: dhi.io/temporalio-chart
variant: helm
tags:
  - 1.2.0
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: 5721e9a3138dec93584ac231a8d57231234a6964
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.20.2-debian13-dev@sha256:b72e12042810e0697eebb51a7862e7699f4df8eca02324029c220ccfd0bce4a4
  SEMVER_MAJOR_MINOR_VERSION: "1.2"
  SEMVER_MAJOR_VERSION: "1"
  SEMVER_VERSION: 1.2.0
  TEMPORALIO_ADMIN_TOOLS_REFERENCE: dhi/temporalio-admin-tools:1.29.6-cli-1.6.2-debian13@sha256:f9561cdaa922bad978a69d2e3aa97b24d0ecbcdb2b09f8793b400cd9d1327349
  TEMPORALIO_SERVER_REFERENCE: dhi/temporalio-server:1.29.6-cli-1.7.0-debian13@sha256:4c04abc82a56c9cdba4805c7e8d3dbbeb22fc7b043b0efff97340866680d1271
  TEMPORALIO_UI_REFERENCE: dhi/temporalio-ui:2.49.1-debian13@sha256:527faa4c5186f394fd5abff2130741c83504d32a8ecea84f96f188a67c32e4f7
  VERSION: 1.2.0
contents:
  builds:
    - name: temporalio
      uses: dhi.io/helm:3.20.2-debian13-dev@sha256:b72e12042810e0697eebb51a7862e7699f4df8eca02324029c220ccfd0bce4a4
      work-dir: ${source.dir}/helm-charts/charts/temporal
      contents:
        files:
          - url: git+https://github.com/temporalio/helm-charts.git#temporal-1.2.0
            checksum: 5721e9a3138dec93584ac231a8d57231234a6964
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          with:
            chart:
              appRef: temporalio-server
              description: Docker Hardened Images Helm chart for TemporalIO
              images:
                - name: temporalio-server
                  ref: dhi/temporalio-server:1.29.6-cli-1.7.0-debian13@sha256:4c04abc82a56c9cdba4805c7e8d3dbbeb22fc7b043b0efff97340866680d1271
                - name: temporalio-admin-tools
                  ref: dhi/temporalio-admin-tools:1.29.6-cli-1.6.2-debian13@sha256:f9561cdaa922bad978a69d2e3aa97b24d0ecbcdb2b09f8793b400cd9d1327349
                - name: temporalio-ui
                  ref: dhi/temporalio-ui:2.49.1-debian13@sha256:527faa4c5186f394fd5abff2130741c83504d32a8ecea84f96f188a67c32e4f7
              name: temporalio-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/temporalio/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: patch chart values
          uses: helm/rudder@v1
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          with:
            chart: .
            cmd: lint . -f values/values.postgresql.yaml
        - name: package
          uses: helm/package@v1
          with:
            chart: .
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/temporalio/config-1
