# syntax=dhi.io/build:2-helm3

name: Temporal Helm chart 1.x
image: dhi.io/temporalio-chart
variant: helm
tags:
  - 1.2.0
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: 5721e9a3138dec93584ac231a8d57231234a6964
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.21.0-debian13-dev@sha256:7c201a9174a2b56cb13136f19d87b23309d09eb2fc8a24e8c08a31ebd907a943
  SEMVER_MAJOR_MINOR_VERSION: "1.2"
  SEMVER_MAJOR_VERSION: "1"
  SEMVER_VERSION: 1.2.0
  TEMPORALIO_ADMIN_TOOLS_REFERENCE: dhi/temporalio-admin-tools:1.31.1-cli-1.7.2-debian13@sha256:45c9f7320b0c4a826bf91ba59d4aa411e7619d88ea63045b1c323c40297f98e7
  TEMPORALIO_SERVER_REFERENCE: dhi/temporalio-server:1.31.0-debian13@sha256:36a1b164ac7cb8eba66decfce85d4dac73fd469646087bd059b4631921881531
  TEMPORALIO_UI_REFERENCE: dhi/temporalio-ui:2.51.0-debian13@sha256:adb10c4188328fa9a5ce94e8d93d5f4984821521ff8577a30b95571d88d90faf
  VERSION: 1.2.0
contents:
  builds:
    - name: temporalio
      uses: dhi.io/helm:3.21.0-debian13-dev@sha256:7c201a9174a2b56cb13136f19d87b23309d09eb2fc8a24e8c08a31ebd907a943
      work-dir: ${source.dir}/helm-charts/charts/temporal
      contents:
        files:
          - url: git+https://github.com/temporalio/helm-charts.git#temporal-1.2.0
            checksum: 5721e9a3138dec93584ac231a8d57231234a6964
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          with:
            chart:
              appRef: temporalio-server
              description: Docker Hardened Images Helm chart for TemporalIO
              images:
                - name: temporalio-server
                  ref: dhi/temporalio-server:1.31.0-debian13@sha256:36a1b164ac7cb8eba66decfce85d4dac73fd469646087bd059b4631921881531
                - name: temporalio-admin-tools
                  ref: dhi/temporalio-admin-tools:1.31.1-cli-1.7.2-debian13@sha256:45c9f7320b0c4a826bf91ba59d4aa411e7619d88ea63045b1c323c40297f98e7
                - name: temporalio-ui
                  ref: dhi/temporalio-ui:2.51.0-debian13@sha256:adb10c4188328fa9a5ce94e8d93d5f4984821521ff8577a30b95571d88d90faf
              name: temporalio-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/temporalio/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: patch chart values
          uses: helm/rudder@v1
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          with:
            chart: .
            cmd: lint . -f values/values.postgresql.yaml
        - name: package
          uses: helm/package@v1
          with:
            chart: .
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/temporalio/config-1
