# syntax=dhi.io/build:2-helm3

name: Temporal Helm chart 1.x
image: dhi.io/temporalio-chart
variant: helm
tags:
  - 1.2.0
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: 5721e9a3138dec93584ac231a8d57231234a6964
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.21.0-debian13-dev@sha256:e3d7fb6de37608485fd22d3dd04ed6b0f9cc68431cb21697c2383978e2847ed2
  SEMVER_MAJOR_MINOR_VERSION: "1.2"
  SEMVER_MAJOR_VERSION: "1"
  SEMVER_VERSION: 1.2.0
  TEMPORALIO_ADMIN_TOOLS_REFERENCE: dhi/temporalio-admin-tools:1.31.0-cli-1.7.0-debian13@sha256:cedbb552db99b93a42bfdaf96783f088b47aa5440a1056a7eaf6e67917cbb74b
  TEMPORALIO_SERVER_REFERENCE: dhi/temporalio-server:1.31.0-debian13@sha256:20319989dea49ae8cedd068ab9a3ecead18452a73925f8e9562dc26c03ab231d
  TEMPORALIO_UI_REFERENCE: dhi/temporalio-ui:2.50.0-debian13@sha256:649dc72654b6d659b862eb816408a78d4091a7d750e72e2d73d2c15b0579aaf7
  VERSION: 1.2.0
contents:
  builds:
    - name: temporalio
      uses: dhi.io/helm:3.21.0-debian13-dev@sha256:e3d7fb6de37608485fd22d3dd04ed6b0f9cc68431cb21697c2383978e2847ed2
      work-dir: ${source.dir}/helm-charts/charts/temporal
      contents:
        files:
          - url: git+https://github.com/temporalio/helm-charts.git#temporal-1.2.0
            checksum: 5721e9a3138dec93584ac231a8d57231234a6964
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          with:
            chart:
              appRef: temporalio-server
              description: Docker Hardened Images Helm chart for TemporalIO
              images:
                - name: temporalio-server
                  ref: dhi/temporalio-server:1.31.0-debian13@sha256:20319989dea49ae8cedd068ab9a3ecead18452a73925f8e9562dc26c03ab231d
                - name: temporalio-admin-tools
                  ref: dhi/temporalio-admin-tools:1.31.0-cli-1.7.0-debian13@sha256:cedbb552db99b93a42bfdaf96783f088b47aa5440a1056a7eaf6e67917cbb74b
                - name: temporalio-ui
                  ref: dhi/temporalio-ui:2.50.0-debian13@sha256:649dc72654b6d659b862eb816408a78d4091a7d750e72e2d73d2c15b0579aaf7
              name: temporalio-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/temporalio/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: patch chart values
          uses: helm/rudder@v1
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          with:
            chart: .
            cmd: lint . -f values/values.postgresql.yaml
        - name: package
          uses: helm/package@v1
          with:
            chart: .
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/temporalio/config-1
