# syntax=dhi.io/build:2-helm3

name: KGateway CRDs Helm chart 2.x
image: dhi.io/kgateway-crds-chart
variant: helm
tags:
  - 2.3.0
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: 4fcd28c459a7ab621d01f8aef72ff7ddacc91774
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.21.0-debian13-dev@sha256:462393863790e8d4b174f63f0da50798da095a059d4fab7692ae4fb7a58e99d3
  SEMVER_MAJOR_MINOR_VERSION: "2.3"
  SEMVER_MAJOR_VERSION: "2"
  SEMVER_VERSION: 2.3.0
  VERSION: 2.3.0
contents:
  builds:
    - name: kgateway-crds-chart
      uses: dhi.io/helm:3.21.0-debian13-dev@sha256:462393863790e8d4b174f63f0da50798da095a059d4fab7692ae4fb7a58e99d3
      contents:
        files:
          - url: git+https://github.com/kgateway-dev/kgateway.git#v2.3.0
            checksum: 4fcd28c459a7ab621d01f8aef72ff7ddacc91774
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/install/helm/kgateway-crds
          with:
            chart:
              appRef: kgateway-crds
              description: Docker Hardened Images Helm chart for KGateway CRDs
              images: []
              name: kgateway-crds-chart
              sourceUrl: https://github.com/kgateway-dev/kgateway
            cmd: prepare
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/install/helm
          with:
            chart: kgateway-crds
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/install/helm
          with:
            chart: kgateway-crds
