# syntax=dhi.io/build:2-helm3

name: Fairwinds VPA Helm chart 4.x
image: dhi.io/fairwinds-vpa-chart
variant: helm
tags:
  - 4.11.0
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: 668395099685a5057ec86f0df71c028c46487243
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.21.0-debian13-dev@sha256:ece8efeb889adab72837b0042d8419283ac7fdf2b5c2c8fe09a34e4b8a34ae2e
  KUBE_WEBHOOK_CERTGEN_REFERENCE: dhi/kube-webhook-certgen:1.8.3-debian13@sha256:4afe5086a3217becb4f9eb79ce1b62617f7c69ea0ac0e3ae11d470850e6840cf
  KUBECTL_REFERENCE: dhi/kubectl:1.35.5-debian13@sha256:7cd5ffd107f82ea7eb14182a005f20b01db1170bf6eab71b0bd9a5f667b6d607
  METRICS_SERVER_CHART_REFERENCE: dhi/metrics-server-chart:3.13.1@sha256:dd416e234b1cf1bd2bc8aa650f190b15359cc5d54a8932cd64489fd12c164b91
  SEMVER_MAJOR_MINOR_VERSION: "4.11"
  SEMVER_MAJOR_VERSION: "4"
  SEMVER_VERSION: 4.11.0
  VERSION: 4.11.0
  VPA_ADMISSION_CONTROLLER_REFERENCE: dhi/vpa-admission-controller:1.7.0-debian13@sha256:347ae9bc6e9f935e0d97a2b679a148b30cbdad1fef2d38d9ccf7b694bedf09ff
  VPA_RECOMMENDER_REFERENCE: dhi/vpa-recommender:1.7.0-debian13@sha256:f3926fd64dcb2e1be48373c3d3977513cb20d4c691169640f275d602d9b5db60
  VPA_UPDATER_REFERENCE: dhi/vpa-updater:1.7.0-debian13@sha256:165929bf79391ca7e70d34793577a362a89d0dceb26201095942fa589f63f047
contents:
  builds:
    - name: fairwinds-vpa-chart
      uses: dhi.io/helm:3.21.0-debian13-dev@sha256:ece8efeb889adab72837b0042d8419283ac7fdf2b5c2c8fe09a34e4b8a34ae2e
      contents:
        files:
          - url: git+https://github.com/FairwindsOps/charts.git#668395099685a5057ec86f0df71c028c46487243
            checksum: 668395099685a5057ec86f0df71c028c46487243
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/stable/vpa
          with:
            chart:
              appRef: vpa-admission-controller
              dependencies:
                - alias: metrics-server
                  condition: metrics-server.enabled
                  name: metrics-server
                  ref: dhi/metrics-server-chart:3.13.1@sha256:dd416e234b1cf1bd2bc8aa650f190b15359cc5d54a8932cd64489fd12c164b91
              description: Docker Hardened Images Helm chart for Fairwinds VPA
              images:
                - name: vpa-admission-controller
                  ref: dhi/vpa-admission-controller:1.7.0-debian13@sha256:347ae9bc6e9f935e0d97a2b679a148b30cbdad1fef2d38d9ccf7b694bedf09ff
                - name: vpa-recommender
                  ref: dhi/vpa-recommender:1.7.0-debian13@sha256:f3926fd64dcb2e1be48373c3d3977513cb20d4c691169640f275d602d9b5db60
                - name: vpa-updater
                  ref: dhi/vpa-updater:1.7.0-debian13@sha256:165929bf79391ca7e70d34793577a362a89d0dceb26201095942fa589f63f047
                - name: kube-webhook-certgen
                  ref: dhi/kube-webhook-certgen:1.8.3-debian13@sha256:4afe5086a3217becb4f9eb79ce1b62617f7c69ea0ac0e3ae11d470850e6840cf
                - name: kubectl
                  ref: dhi/kubectl:1.35.5-debian13@sha256:7cd5ffd107f82ea7eb14182a005f20b01db1170bf6eab71b0bd9a5f667b6d607
              name: fairwinds-vpa-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/FairwindsOps/charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/stable/vpa
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: helm login
          uses: helm/login@v1
          with:
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/stable
          privileged: true
          with:
            chart: vpa
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/stable
          with:
            chart: vpa
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/stable
          with:
            chart: vpa
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/fairwinds-vpa/config
