# syntax=dhi.io/build:2-helm3

name: Fairwinds VPA Helm chart 4.x
image: dhi.io/fairwinds-vpa-chart
variant: helm
tags:
  - 4.11.0
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: 668395099685a5057ec86f0df71c028c46487243
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.21.0-debian13-dev@sha256:7b9ee43cc77e81e2dcbb1b0f6e8ce376b71d63c90c81f2863e24aefff774a8da
  KUBE_WEBHOOK_CERTGEN_REFERENCE: dhi/kube-webhook-certgen:1.8.3-debian13@sha256:efa24b78ec465a09216ea840c83c6e7d0b8f62fa1f8b19783cf7bddb92dbce97
  KUBECTL_REFERENCE: dhi/kubectl:1.35.5-debian13@sha256:7cd5ffd107f82ea7eb14182a005f20b01db1170bf6eab71b0bd9a5f667b6d607
  METRICS_SERVER_CHART_REFERENCE: dhi/metrics-server-chart:3.13.1@sha256:3ccd73027da6551b68830ae7d2af95a9b29c516da151b59fa4dab399b71bdd98
  SEMVER_MAJOR_MINOR_VERSION: "4.11"
  SEMVER_MAJOR_VERSION: "4"
  SEMVER_VERSION: 4.11.0
  VERSION: 4.11.0
  VPA_ADMISSION_CONTROLLER_REFERENCE: dhi/vpa-admission-controller:1.7.0-debian13@sha256:6aae1770c6a1b13bd2b602289a659bb6dd9f4918a421a89bd5026b10ac448008
  VPA_RECOMMENDER_REFERENCE: dhi/vpa-recommender:1.7.0-debian13@sha256:b40b1fec7cf381e01c7c9e128c417a7a601dcc949161826ab349d35b394b1c4f
  VPA_UPDATER_REFERENCE: dhi/vpa-updater:1.7.0-debian13@sha256:f7f2a492f127aad53c073d5355a56226e067984217a48b3432b194800ce6b612
contents:
  builds:
    - name: fairwinds-vpa-chart
      uses: dhi.io/helm:3.21.0-debian13-dev@sha256:7b9ee43cc77e81e2dcbb1b0f6e8ce376b71d63c90c81f2863e24aefff774a8da
      contents:
        files:
          - url: git+https://github.com/FairwindsOps/charts.git#668395099685a5057ec86f0df71c028c46487243
            checksum: 668395099685a5057ec86f0df71c028c46487243
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/stable/vpa
          with:
            chart:
              appRef: vpa-admission-controller
              dependencies:
                - alias: metrics-server
                  condition: metrics-server.enabled
                  name: metrics-server
                  ref: dhi/metrics-server-chart:3.13.1@sha256:3ccd73027da6551b68830ae7d2af95a9b29c516da151b59fa4dab399b71bdd98
              description: Docker Hardened Images Helm chart for Fairwinds VPA
              images:
                - name: vpa-admission-controller
                  ref: dhi/vpa-admission-controller:1.7.0-debian13@sha256:6aae1770c6a1b13bd2b602289a659bb6dd9f4918a421a89bd5026b10ac448008
                - name: vpa-recommender
                  ref: dhi/vpa-recommender:1.7.0-debian13@sha256:b40b1fec7cf381e01c7c9e128c417a7a601dcc949161826ab349d35b394b1c4f
                - name: vpa-updater
                  ref: dhi/vpa-updater:1.7.0-debian13@sha256:f7f2a492f127aad53c073d5355a56226e067984217a48b3432b194800ce6b612
                - name: kube-webhook-certgen
                  ref: dhi/kube-webhook-certgen:1.8.3-debian13@sha256:efa24b78ec465a09216ea840c83c6e7d0b8f62fa1f8b19783cf7bddb92dbce97
                - name: kubectl
                  ref: dhi/kubectl:1.35.5-debian13@sha256:7cd5ffd107f82ea7eb14182a005f20b01db1170bf6eab71b0bd9a5f667b6d607
              name: fairwinds-vpa-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/FairwindsOps/charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/stable/vpa
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: helm login
          uses: helm/login@v1
          with:
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/stable
          privileged: true
          with:
            chart: vpa
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/stable
          with:
            chart: vpa
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/stable
          with:
            chart: vpa
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/fairwinds-vpa/config
