# syntax=dhi.io/build:2-helm3

name: Fairwinds VPA Helm chart 4.x
image: dhi.io/fairwinds-vpa-chart
variant: helm
tags:
  - 4.11.0
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: 668395099685a5057ec86f0df71c028c46487243
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.20.2-debian13-dev@sha256:ce95680846fc18d3d179f82f9d633c8274f41cd0d0f8213cbfc4039fbe2cd112
  KUBE_WEBHOOK_CERTGEN_REFERENCE: dhi/kube-webhook-certgen:1.8.2-debian13@sha256:2471915394649d9e4f3a28ffc6e95f073a469233528da4c1c97b002dd00f8ee8
  KUBECTL_REFERENCE: dhi/kubectl:1.35.4-debian13@sha256:664ebea9a9f57b02182afc649436075c6ca821296aa594c7e0f289b6a3cef0c3
  METRICS_SERVER_REFERENCE: dhi/metrics-server-chart:3.13.0@sha256:299178aa593ae569ac763406433d23685a7c6fb596ee286594b86d31ab83a8ca
  SEMVER_MAJOR_MINOR_VERSION: "4.11"
  SEMVER_MAJOR_VERSION: "4"
  SEMVER_VERSION: 4.11.0
  VERSION: 4.11.0
  VPA_ADMISSION_CONTROLLER_REFERENCE: dhi/vpa-admission-controller:1.6.0-debian13@sha256:cc006643e5670ec08b77dccaeb8b88a930ae147967f3776cfd785cdddcb29324
  VPA_RECOMMENDER_REFERENCE: dhi/vpa-recommender:1.6.0-debian13@sha256:041e14b8df5f1c6454cf8f008e701248792db83c91a64a8a2f4305e9eb941726
  VPA_UPDATER_REFERENCE: dhi/vpa-updater:1.6.0-debian13@sha256:8ddda4473b20a9bd1999e73b9b6c8eff420fe0a11f97380bffdcd4a0cf21995f
contents:
  builds:
    - name: fairwinds-vpa-chart
      uses: dhi.io/helm:3.20.2-debian13-dev@sha256:ce95680846fc18d3d179f82f9d633c8274f41cd0d0f8213cbfc4039fbe2cd112
      contents:
        files:
          - url: git+https://github.com/FairwindsOps/charts.git#668395099685a5057ec86f0df71c028c46487243
            checksum: 668395099685a5057ec86f0df71c028c46487243
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/stable/vpa
          with:
            chart:
              appRef: vpa-admission-controller
              dependencies:
                - alias: metrics-server
                  condition: metrics-server.enabled
                  name: metrics-server
                  ref: dhi/metrics-server-chart:3.13.0@sha256:299178aa593ae569ac763406433d23685a7c6fb596ee286594b86d31ab83a8ca
              description: Docker Hardened Images Helm chart for Fairwinds VPA
              images:
                - name: vpa-admission-controller
                  ref: dhi/vpa-admission-controller:1.6.0-debian13@sha256:cc006643e5670ec08b77dccaeb8b88a930ae147967f3776cfd785cdddcb29324
                - name: vpa-recommender
                  ref: dhi/vpa-recommender:1.6.0-debian13@sha256:041e14b8df5f1c6454cf8f008e701248792db83c91a64a8a2f4305e9eb941726
                - name: vpa-updater
                  ref: dhi/vpa-updater:1.6.0-debian13@sha256:8ddda4473b20a9bd1999e73b9b6c8eff420fe0a11f97380bffdcd4a0cf21995f
                - name: kube-webhook-certgen
                  ref: dhi/kube-webhook-certgen:1.8.2-debian13@sha256:2471915394649d9e4f3a28ffc6e95f073a469233528da4c1c97b002dd00f8ee8
                - name: kubectl
                  ref: dhi/kubectl:1.35.4-debian13@sha256:664ebea9a9f57b02182afc649436075c6ca821296aa594c7e0f289b6a3cef0c3
              name: fairwinds-vpa-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/FairwindsOps/charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/stable/vpa
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: helm login
          uses: helm/login@v1
          with:
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/stable
          privileged: true
          with:
            chart: vpa
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/stable
          with:
            chart: vpa
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/stable
          with:
            chart: vpa
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/fairwinds-vpa/config
